### ISSUE TITLE
Divide views dataset by domain

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1005]
Currently, all views across domain areas (Payments, GTFS Schedule, GTFS RT, Airtable) are included in the single `views` BigQuery dataset. This was done because Metabase did not support joins across BigQuery datasets and we wanted to ensure that data could be joined across domains. 

As of version 0.42, Metabase will support joins across datasets. As a result we can reconsider whether we want to make dedicated `views_<domain>` datasets rather than having everything combined in one -- as we create more views, it seems likely that the current combined `views` dataset will become unwieldy (if it hasn't already).

**Comment by j-meelah** [comment]
Obsolete by dbt
