### ISSUE TITLE
As a Data Assessments Manager I need structured data on vendor contracts, so that I can view this information when I am prepping for meetings with agencies

### ISSUE THREAD

**Issue by vykster** [cal-itp/data-infra#1019]
As a Data Assessments Manager I need structured data on vendor contracts.

Resources:

- Contracts - these are saved in an old worktask folder that Trillium led. 005D, see the documents repository folder. https://drive.google.com/drive/folders/1ctWiOaZkjWfq3w_31MdfrX4yt2hT4aEI?usp=sharing
- Create the list of fields for the "dataset." ie: agency name, agency id number, contract name, contract amount. (Olivia + Enza)

Todo:

- [x] Review existing data collection efforts (airtable)
- [x] Create data dictionary for contracts table
- [x] Data entry for all existing contracts into AirTable base [Transit Technology Stacks, contracts table](https://airtable.com/appeVUdmRBi3K9hTS/tblyuFnXNG7izMx8v/viwzpVycNnMgjnzw7?blocks=hide)
- [x] Import AirTable into Metabase see #774 
- [x] Create view of contracts data for data assessments manager in Metabase

**Comment by vykster** [comment]
This issue should be assigned to @ProvvidenzaC with support from @o-ram

**Comment by e-lo** [comment]
There are data structures available to input this information in the Transit Technology Stacks Airtable which would link it with the stack data we already have including organizations, products, services, etc.  

Suggest inputing the data into here.

![image](https://user-images.githubusercontent.com/794787/151904606-6b8eece7-462b-4736-901b-7cc41acab28d.png)

**Comment by o-ram** [comment]
Thanks, E! I haven't explored the Transit Stacks Airtable yet; that's a good idea.

**Comment by vykster** [comment]
Update @ProvvidenzaC will use this table for data entry, they are drafting a data dictionary this week.

**Comment by vykster** [comment]
Reviewing source data in metabase, it seems the contracts table might not already be mapped into Metabase

**Comment by vykster** [comment]
According to Holly -- Airtable ingestion schedule for mid-April

**Comment by AnthonyRollins** [comment]
@o-ram I believe this happened on April 12th, is that correct?
