### ISSUE TITLE
Explore using pyproject.toml and/or poetry

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#1025]
**Is your feature request related to a problem? Please describe.**
Inconsistency in project configuration. Linting exceptions, requirements, etc. are defined in different places. I've also hit at least one requirements version mismatch issue locally; specifically, the following code causes a version conflict exception when running in a fresh `venv` created from the Airflow requirements.

```python
>>> import calitp
>>> calitp.sql.get_engine()
```

**Describe the solution you'd like**
Experiment with using pyproject.toml and likely poetry.

**Describe alternatives you've considered**
n/a

**Additional context**
One potential issue this could introduce: the pyproject.toml is scoped to a directory, not a repository. This could create some discrepancies in scope; for example, two subfolders may contain different `requirements.txt` (for example, `scripts/` and `airflow/`) but still want to use the same global linting configurations for github workflows. Nothing major, but it could mean making some decisions around broadening the scope of requirements (`scripts/requirements.txt` could become dev dependencies, for example).

**Comment by holly-g** [comment]
Per discussion in thead: https://cal-itp.slack.com/archives/C02KH3DGZL7/p1647879967059329 

"We may want to consider switching to poetry for the shared_utils/jupyterhub requirements; its dependency resolver is better than pip" 
cc @charlie-costanzo

**Comment by holly-g** [comment]
Resolved by #1272
