### ISSUE TITLE
Research: Look into the spike in 'Route Z' values for MST in early January

### ISSUE THREAD

**Issue by mjumbewu** [cal-itp/data-infra#1029]
## Question

As can be seen on the [Payments Data Validation](https://metabase.k8s.calitp.jarv.us/dashboard/28-payments-data-validation) dashboard, during the first week of January 2022, MST had an unexpectedly large number of transactions coded with the route `'Route Z'`. Before that week and after that week the number of `'Route Z'` records has been fairly low. What happened?

According to LittlePay, they simply use the values that come from the device. According to SC Soft (the device manufacturer), they are always able to correlate a route with a transaction as long as the GTFS-RT feed for the agency is consistently available and valid. If (and only if?) the GTFS-RT feed is unavailable will they code a transaction as taking place on `'Route Z'`. So, is this a GTFS-RT issue for MST?

Check the GTFS-RT data around the time of the Route Z for MST.
* Are there vehicle IDs missing?
* Do the records exist or is there a chunk of time with no records for particular routes?
* Is there a schedule data change around the same time?

In case it is helpful, a summary of RT validation: https://docs.google.com/document/d/1Pab8lAeyx6FAur439wpQE-eSLWQuzoso3M6Np5__bDA/edit#

## Metrics

* Correlation between (1) missing data in the GTFS RT feed for MST and (2) transactions coded with `Route Z` in the LittlePay data.

## Data sources

* The `payments.stg_cleaned_device_transactions` table for which transactions are `Route Z`. Useful fields will be (at least): `route_id`, `transaction_date_time_pacific`.
* The `gtfs_rt.vehicle_positions` table for RT data.

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**:
  - Are the `Route Z` trips confined to specific routes (i.e., are there stretches of time where there are no transactions for one route, but there are transactions for other routes), or across all routes (i.e., are there stretches of time where the only transactions coming through are for `Route Z`)?
  - Do a large portion of the `Route Z`-coded LittlePay transactions for MST during the week of Jan 2-8 correspond to times when data in the GTFS-RT feed from MST was unavailable (either missing RT data overall, or missing specific fields, or missing fields for specific routes)?
* **View**:
  - `payments.stg_cleaned_device_transactions` or `views.payments_rides`
  - `gtfs_rt.vehicle_positions`
* **Research**:
  - The findings will be useful for us to explain to MST why there were a spike in `Route Z` trips during the first week of January, and may help us coordinate with partners to avoid such outages in the future. A notebook with the results could be an appropriate medium.

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by j-meelah** [comment]
Subsequent spikes of "Route Z" occurrences have been investigated and attributed to PAD issues.
