### ISSUE TITLE
Verify metabase configuration backups and pruning

### ISSUE THREAD

**Issue by themightychris** [cal-itp/data-infra#1038]
After #1021 has been live for a ~week connect to the storage bucket with a local `restic` client to verify:

- Snapshots have been getting created at the expected interval
- Pruning has been happening and conforms so far to the expected policy
- Dump a random sampling of new/old snapshots and spot check that the dumps contain complete schema and data

Add an article to the docs while you do this, leaving behind a step guide for verifying metabase metadata backups

**Comment by Nkdiaz** [comment]
Have verified that the metabase shapshots have been generated at the expected interval, have verified that the backups have not been corrupted in by loading a psql dump within a docker container that has postgres V13.5. Write up will follow shortly with the steps performed.
