### ISSUE TITLE
Handle all-blank rows in Airtable operator

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1043]
Per @e-lo in Slack: 

> it is quite common that extra records are created inadvertently

in Airtable, and so we should have a procedure to delete all-blank rows.

The challenge is that generally the rows will not actually be literally entirely null:
* The record ID will exist
* Any calculated fields (`# of feeds`, `static coverage`, etc.) will exist (they will all be `0` or the equivalent, but they will not literally be null) 

I can see three options:
* Add a condition to the `AirtableToWarehouseOperator` that checks that at least one of some subset of fields is not null (for example, organization name)
* Add a condition as above to the creation of the relevant `view` 
* Add an additional level of processing between `airtable_loader` and `airtable_views` that does this checking 

The first is cleaner if we have multiple fields of interest because checking lots of nulls in SQL is not ideal. But the second or third is preferable if we want to err on the side of caution and not risk dropping valid data in our snapshots.

I am not sure how urgent this is; right now, these rows will fail a SQL integrity check but that doesn't actually prevent the data being written to the warehouse. I believe it will send email notifications. If we think it's worth actually deleting these from the Airtable, this actually might be an acceptable end state? (Email notification alerting us to go delete the empty data; the data still does actually populate.)

**Comment by evansiroky** [comment]
For this particular item and other Airtable ingestion problems, let's try to fix things in the airtable data itself first and try to update the ingestion pipeline code sparingly. It's going to be a much larger effort to write code to adapt to ingestion problems, so we should try to avoid that if possible. Let's see if this particular problem occurs frequently enough that we seem to be spending more time fixing things than we would be creating automation to fix things.

**Comment by e-lo** [comment]
> Let's see if this particular problem occurs frequently enough that we seem to be spending more time fixing things than we would be creating automation to fix things.

I like this approach. 🤞

**Comment by lauriemerrell** [comment]
I don't think we've encountered issues with this recently (issue over a year old). Closing.
