### ISSUE TITLE
Come up with schema for data warehouse table

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/data-infra#1045]
This is a task related to #960.

We have some data from the Amplitude Export API.  Next, we need to decide what schema we want for the table going into the Cal-ITP data warehouse.

**Comment by thekaveman** [comment]
@angela-tran I think this was closed by #1209 right?

**Comment by angela-tran** [comment]
> @angela-tran I think this was closed by #1209 right?

This task is focused on the schema that ends up in Metabase, whereas #1209 was the intermediate external table. We could roll this into https://github.com/cal-itp/data-infra/issues/1188 if this seems too small to be its own ticket.

**Comment by thekaveman** [comment]
Ok... well whatever this one is, it's either too small or a duplicate and I think we can close it. #1188 seems like the place the views schema would be created/tracked so let's use that.
