### ISSUE TITLE
Implement `amplitude_to_df` function

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/data-infra#1046]
This is a task related to #960, and completes the **"Amplitude to Airflow"** task, as detailed below.

## Amplitude to Airflow task

1. [x] Create a module in [`airflow/plugins/operators`](https://github.com/cal-itp/data-infra/tree/main/airflow/plugins/operators) like `amplitude_to_flattened_json_operator.py`; see [`realtime_to_flattened_json_operator.py`](https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/operators/realtime_to_flattened_json_operator.py) as an example
2. [x] Create a function in the module like `amplitude_to_df()` to download Amplitude data and return it in a DataFrame. This function should take as parameters all API keys, querystrings, etc. needed to get at the data, perhaps reading from `os.env` if a value is not provided. See the [Amplitude Export API docs](https://developers.amplitude.com/docs/export-api)
3. [x] Create a class in the module inheriting from `airflow.models.BaseOperator` like `AmplitudeToFlattenedJSONOperator`

**Comment by thekaveman** [comment]
Closed in #1121
