### ISSUE TITLE
Docs request: what even is a transit agency and how can we answer questions that relate to their GTFS data? 

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1047]
A lot of times Caltrans staff will get asked various questions such as #984. When attempting to answer this question a lot of confusion can arise with how to quantify this answer due to our thorough dataset in the California Transit airtable. A quick how-to guide is needed to determine:

1. What organizations do we want to analyze depending on the research question?

There has been an effort (see the [Transit Provider Categorization](https://docs.google.com/document/d/1e0Z-aLKzNg7xnP0gSCCSWOuNPjTB8xN1G7vWVYQ8bYk/edit#heading=h.5taosqpsjhbq) doc) to classify organizations into various tracking, assistance or reporting categories. A shorter version of this should be documented such that analysts can quickly know what kind of filtering of organizations to use depending on the research ask.

2. How should an organization's services be aggregated when analyzing?

Typical research questions ask what seem to be fairly basic questions like #984. However, an organization can have multiple services that it manages and a service can be described in multiple GTFS datasets. Therefore, a situation can arise where it is unclear how the completeness of data should be counted. Is it when all services that an organization manages have a certain quality about them or when at least one, or a threshold? A clear plan of what aggregation strategy to use should be agreed upon and documented.

**Comment by e-lo** [comment]
Q: where is the final destination of this documentation such that it is accessible and front-of-mind to analysts when they need it?

**Comment by charlie-costanzo** [comment]
> Q: where is the final destination of this documentation such that it is accessible and front-of-mind to analysts when they need it?

Hey @e-lo! It will live here, underneath the `Analysts` chapter of the data services docs, likely somewhere under the `Introduction to the Warehouse` sub-section

**Comment by charlie-costanzo** [comment]
Hey @e-lo! so the timing of this issue is pretty swell since I'm also working on other metadata tasks this week and it makes a lot of sense to take care of these all in one feel swoop. Like I mentioned briefly at all-hands, I'd love to grab some of your time to try to answer this transit agency definition question if you don't mind! If that works, would the end of this week or early next week work for you perhaps?

**Comment by charlie-costanzo** [comment]
Meeting with Analysts Tuesday, March 29th to whiteboard a decision-tree for use in determining which definition of 'agency' to use in research requests

**Comment by charlie-costanzo** [comment]
Link to [doc with takeaways from analyst call](https://docs.google.com/document/d/11QLmwAnDQm0K7DwQIOyUQX5fU__nxoQhaLyIm6WJQ0w/edit?usp=sharing)

**Comment by charlie-costanzo** [comment]
This is nearly wrapped up - we're generating an additional view table to support the reference document in #1487, and cleaning up some of the language used in the document.
