### ISSUE TITLE
Deploy prometheus/grafana/loki stack into data-infra-apps cluster

### ISSUE THREAD

**Issue by lottspot** [cal-itp/data-infra#1050]
Our recent period of troubles with stability on the kubernetes cluster has brought us to the conclusion that we would like to get away from relying on GCP for storing and processing application logs. Deploying this standardized monitoring and logging stack, in addition to streamlining the management of problems, is also a foundational step in evolving other key aspects of our operations, such as identifying and routing alerts.

**Comment by evansiroky** [comment]
@lottspot, to clarify, you are recommending to use this stack as it pertains to reliability monitoring and not to ingestion of the logs for the purposes of analyzing feed availability in our business processes, right? 

I believe @Nkdiaz is still proceeding with ingesting the logs into BigQuery as part of the work to answer #1010.
