### ISSUE TITLE
Airflow stability issues - "state of this instance has been externally set to failed" and similar, Feb 2022

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1052]
Making a ticket to track information about and instances of the  "state of this instance has been externally set to failed" error that has been logged in production Airflow lately. 

For example, task `airtable_loader.fare_systems` failed with this message on the midnight 2/8 runs ([log link](https://o1d2fa0877cf3fb10p-tp.appspot.com/log?execution_date=2022-02-07T00%3A00%3A00%2B00%3A00&task_id=california_transit_fare_systems&dag_id=airtable_loader)).

**Comment by Nkdiaz** [comment]
Here is What I see in the logs:
Query I used: 
`textPayload:"state of this instance has been externally set to failed"`
Here is a picture of the logs: 
![image](https://user-images.githubusercontent.com/32888103/153060085-f748d6f8-c640-4482-884f-bb575736bc63.png)

**Comment by evansiroky** [comment]
Let's hold off on further investigation until this happens a few more times. Each time this has happened, it appears the resolution has been to clear the affected DAG tasks and then it just worked.

**Comment by evansiroky** [comment]
This exact error occurred in 1 DAG task today. However, there were a lot of other similar failures that occurred today and sometimes even after a whole DAG task completed successfully.

This error message was observed in one DAG task before the DAG task even started:

> Dependencies not met for <TaskInstance: airtable_loader.california_transit_funding_programs 2022-02-09T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state which is not a valid state for execution. The task must be cleared in order to be run.

This error message was observed in three DAG tasks after each DAG task completed execution without an error:

> Executor reports task instance finished (failed) although the task says its queued. (Info: None) Was the task killed externally?

**Comment by evansiroky** [comment]
Seems like [this StackOverflow question](https://stackoverflow.com/questions/65380492/why-are-my-airflow-tasks-being-externally-set-to-failed) is pretty relevant. Our airflow instance's `job_heartbeat_sec` and `scheduler_heartbeat_sec` are both set to `5`. Maybe we should increase these to 60?

**Comment by lauriemerrell** [comment]
[crosspost from Slack]

It might make sense to change this, but I am a bit confused -- my read of the SO post is that the issue was that the scheduler_health_check_threshold was set to a smaller number than the heartbeat setting. But in our case scheduler_health_check_threshold is set to 30, which is greater than our heartbeat settings. If anything, it seems like making heartbeat longer might actually make this worse...? Maybe I am misunderstanding something here. Maybe increasing heartbeat to 30 and scheduler_health_check_threshold to 60 makes sense if we think 5 is too often but based on my read of the post, if we set heartbeat to 60 and leave scheduler_health_check_threshold at 30 it would maybe get worse.

**Comment by evansiroky** [comment]
@holly-g can this be prioritized? It is causing a lot of problems.

**Comment by lauriemerrell** [comment]
A few other data points:

* The most common error message that I see in the Airflow logs is: 
```
*** Log file is not found: gs://us-west2-calitp-airflow2-pr-171e4e47-bucket/logs/rt_loader/external_calitp_validation_params/2022-03-24T00:00:00+00:00/1.log. The task might not have been executed or worker executing it might have finished abnormally (e.g. was evicted)
*** 404 GET https://storage.googleapis.com/download/storage/v1/b/us-west2-calitp-airflow2-pr-171e4e47-bucket/o/logs%2Frt_loader%2Fexternal_calitp_validation_params%2F2022-03-24T00%3A00%3A00%2B00%3A00%2F1.log?alt=media: No such object: us-west2-calitp-airflow2-pr-171e4e47-bucket/logs/rt_loader/external_calitp_validation_params/2022-03-24T00:00:00+00:00/1.log: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
```
* I have intermittently started seeing this yesterday and today -- it has always recovered on its own, but wanted to note
![image](https://user-images.githubusercontent.com/55149902/160135211-3dbc0b63-713d-4c13-9463-1d8ef544682b.png)

**Comment by lauriemerrell** [comment]
Briefly saw this in prod Airflow but it cleared itself: 

<img width="817" alt="image" src="https://user-images.githubusercontent.com/55149902/160139003-420ea3ec-0262-4941-bd72-cc02e7d356ef.png">

**Comment by lauriemerrell** [comment]
We are leaving this ticket open until we have 7 consecutive days with none of these failure (`404` log not found errors or the `state of instance externally set to failed`). First execution date with no errors was 4/5. If we make it to execution date 4/12 (assessed next Wednesday 4/13) with none of these errors, we will close the ticket. 

Issue has been addressed by #1281 and #1340

**Comment by lauriemerrell** [comment]
Womp womp, recurred again today after a respite. Example: https://o1d2fa0877cf3fb10p-tp.appspot.com/log?dag_id=gtfs_downloader&task_id=generate_provider_list&execution_date=2022-04-07T00%3A00%3A00%2B00%3A00

**Comment by lauriemerrell** [comment]
On Monday 4/11, @atvaccaro re-set our scheduler and job heartbeats back to 5sec, because we thought that some of the issues may have been caused by Airflow jobs essentially losing tracking information because of too-long pauses. Since then (Monday night and Tuesday night runs), we have not had any of these issues.

If we make it to next Tuesday morning 4/19 with no more instances of the issue, I will close this ticket.

**Comment by lauriemerrell** [comment]
We have gone a week without these issues! 🎉 I am closing this ticket. Future Airflow issues should be treated as a new situation.
