### ISSUE TITLE
gtfs-rt: calitp_filepath is populating with unnecessary temp filepath in RT JSON files

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1054]
**Describe the bug**
The `caltip_filepath` field (populated [here](https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/operators/realtime_to_flattened_json_operator.py#L42)) in the RT JSON files is populated with a meaningless temp filepath.

Example from 2022-02-7 for `itp_id` 278, `url` 0:
 `"calitp_filepath": "/tmp/tmpxgebfkqq/2022-02-07T23:59:45/278/0/gtfs_rt_vehicle_positions_url"`

**To Reproduce**
1. Go to any JSON file in `gtfs-data/rt_processed/` (in GCS)
2. Download & open the file
3. Observe the `calitp_filepath` field

**Expected behavior**
I don't think we need this field in the final JSON at all? Looking at `vehicle_positions_legacy`, we don't seem to have been tracking anything equivalent there. If we wanted to keep the last parts (with the scraping timestamp), maybe that's useful? But we should parse that out and only store that rather than storing the full temp filepath.

**Additional context**
I am not sure if there is some specific reason we added this field.

**Comment by atvaccaro** [comment]
Oh this is my doing; it was in the original PR I inherited and just left it there. It might be useful to keep the original GCS path, at least.

**Comment by lauriemerrell** [comment]
If we change the JSON generation in #1176, we could potentially address this.

**Comment by lauriemerrell** [comment]
This is fixed in v2 pipeline/no longer applicable
