### ISSUE TITLE
docs(airflow): retrieving logs for pods on a local airflow setup

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#1055]
Currently, we don't have available documentation on retrieving logs for pods on a local airflow setup to point team members towards.

from @themightychris:
> [it] might be a good snippet of know-how to capture in the docs somewhere... how to pull pod logs for a local airflow run from the GCP logs explorer

The following information should be added to the data services documentation:
in location [_digital services docs / airflow / local setup_](https://docs.calitp.org/data-infra/airflow/local-setup.html):
> **Pulling Pod Logs for a Local Airflow Run**
> To pull pod logs,
> 1.  Navigate to GCP > Operations > Logging > Logs Explorer > query field
> 2. Run the following query, substituting the name of the terminated pod with the pod whose logs you would like to retrieve:
> `resource.labels.pod_name="pod.name"`
> ex.
> `resource.labels.pod_name="gtfs-rt-validation.85d1bfec8223489d886be905ff234a03"`

**Additional context**
Still need to add additional information on how to retrieve the name of the pod that you are looking to find logs for

**Comment by charlie-costanzo** [comment]
With additional information on how to find the name of the pod:

**Pulling Pod Logs for a Local Airflow Run**
To pull pod logs,
1. Navigate to GCP > Operations > Logging > Logs Explorer > _query field_
2. Run the following query, substituting the name of the terminated pod with the pod whose logs you would like to retrieve:
`resource.labels.pod_name="pod.name"`
ex.
`resource.labels.pod_name="gtfs-rt-validation.85d1bfec8223489d886be905ff234a03"`

If you're unsure of the name of a pod, in your local Airflow UI:
1. Navigate to the "logs" section for PodOperators
2. Search for log messages similar to this, which will provide the name of the pod:
`Pod not yet started: gtfs-rt-validation.87a693a129d64ccdb3d9d21bf29c2f46`

**Comment by lauriemerrell** [comment]
Thanks for writing this up Charlie -- I would clarify in the header that pod logs will only exist for PodOperators (like, "pod logs" are not something that will exist for all local Airflow DAG task runs), and then for the second list change #1 to "Navigate to the logs section for an individual PodOperator DAG task"

**Comment by charlie-costanzo** [comment]
> Thanks for writing this up Charlie -- I would clarify in the header that pod logs will only exist for PodOperators (like, "pod logs" are not something that will exist for all local Airflow DAG task runs), and then for the second list change #1 to "Navigate to the logs section for an individual PodOperator DAG task"

awesome thank you so much for the feedback @lauriemerrell!!
