### ISSUE TITLE
GTFS-RT: support for dynamic schema detection / rare or experimental fields 

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1058]
Spinning this out from discussion on #1056 / #1051, to make sure we don't lose track of big-picture concerns raised by @e-lo regarding the need to support rare/experimental fields in GTFS RT. Specifically, is there a way that we can get rare / experimental fields into BigQuery?

Looking at [the docs](https://cloud.google.com/bigquery/docs/schema-detect), unfortunately I don't think there's a way to force BigQuery auto-detection to work for this -- the docs say

> Therefore, auto-detection should work as expected as long as there is at least one row of data that has values in every column/field.

^ I don't think that's going to happen, based on the initial experience. (BigQuery yelled about fields that were rarely used, and failed to load them).

That means we would have to (and maybe there are other options I'm not thinking of):

* Scrape the schema from another location like the [realtime proto spec](https://developers.google.com/transit/gtfs-realtime/gtfs-realtime.proto) - especially if this exists in another, more amenable format? But this would still restrict us only to "defined experimental" fields. 

* Extract the schema from each file individually and concatenate those into a combined schema of all fields at the end (perhaps we could extract the schema from just one instance from each feed, assuming that a given feed's schema is probably consistent?). I would wonder about performance impacts there but that might be a better bet... The thing I'm not sure about here is that this is not tabular data, so this is not as straightforward as it is for like CSVs. (Like, what if a nested field two levels deep is only present in one file, how can we integrate that into the full schema?) 

@atvaccaro, curious about your thoughts here. 

ETA @e-lo's original suggestions:
> Is there a reason why we would define this in a static .sql file rather than using something dynamically generated from the canonical .proto definitions? (or a [json-schema](https://json-schema.org/) middle-person?)

("this" referring to the external table schema for `vehicle_positions`)

**Comment by lauriemerrell** [comment]
A few clarifying questions for @e-lo (restating from #1056 to move the conversation here): 
* When you refer to experimental fields, does that mean "defined experimental" fields like `occupancyStatus`, or just any field that's present? Do you know of example fields (or planned fields) that some feeds might have that aren't in the spec but that we want to support? 
* Do you have this concern about GTFS schedule data as well? Right now, we only load a list of explicitly defined fields into the GTFS schedule pipeline. (See for example [routes](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_schedule_history/routes.yml)). If we want to revisit that too that would probably be a separate ticket.

I'm kind of wondering if there's an in between status where we track fields that are present that we don't load, and then we monitor that and add support for those that seem useful? Basically just want to be cognizant that some "custom" fields are likely to be in error, and that we might want to guard against that.

**Comment by atvaccaro** [comment]
> @atvaccaro, curious about your thoughts here.

Something like https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema could be interesting but I think the hard-coded schema is fine for the near/mid-term future.

**Comment by lauriemerrell** [comment]
One quirk that I want to document based on the reading I did yesterday (from the [BQ docs on loading a JSON schema](https://cloud.google.com/bigquery/docs/schemas#specifying_a_json_schema_file)):

> When you supply a JSON schema file, it must be stored in a locally readable location. You cannot specify a JSON schema file stored in Cloud Storage or Drive.
