### ISSUE TITLE
Bug: day transitions result in not-ready-yet data in GTFS Guidelines metabase dashboard

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1064]
**Describe the bug**

The GTFS Guidelines metabase dashboard has a date filter that points to yesterday. However, when the time changes to a new day this transition occurs at UTC time (which is 4pm during Pacific Standard Time, or 5pm during Pacific Daylight time) the date filter points to yesterday in UTC time. Since this is also when the daily DAGs begin to run, a lot of the data will not be ready yet and a lot of stuff may show up as blank.

**To Reproduce**

1. At 4:05pm Pacific Standard Time, go to https://dashboards.calitp.org/dashboard/26
2. Note blank entries for AC Transit URLs

**Expected behavior**

All of the metabase dashboard data should reflect the most recently available data and there shouldn't be any "downtime" of data.

**Additional context**

Maybe a way to resolve this is to set the internal timezone of the server that metabase is running on to be the America/Los_angeles timezone?

**Comment by evansiroky** [comment]
That's an interesting note, @lauriemerrell. I think that solution works well for dashboards that are only focused on the most-up-to-date data, but may not always work for other ones where users want to select a particular date to look at.

I have gone ahead and changed the timezone of metabase, so we'll see if that ends up working out.

**Comment by evansiroky** [comment]
Changing the metabase timezone did not resolve this.

**Comment by holly-g** [comment]
Checked in with Evan (10/3) -- we can close this ticket.
