### ISSUE TITLE
Investigate: Why are areas.txt errors blocking RT validation

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1067]
See #902; we are getting errors about areas.txt blocking RT validation, which doesn't make much sense, because it's not a required file and doesn't interact with the RT data.

We want to: 

- [x] Try to run [the latest docker image of the mobility-data/gtfs-realtime-validator project](https://github.com/mobilitydata/gtfs-realtime-validator/#setup) and see if we can reproduce the MTC 511 error
- [x] If we can reproduce, submit an issue to the validator 
- [x] ~If not, see if we need to update our validator version or similar~ N/A
- [x] Make a concrete plan for how we will address in our pipeline while we wait for a fix (consider suppressing areas.txt from being copied in our schedule feeds used for RT validation)

 Per Evan:

> That's unfortunate that the whole RT validator bails on a field missing within areas.txt. That file shouldn't even be needed to analyze the GTFS-RT with its current spec. Maybe we should remove that file from the static feed before validating. Or maybe better yet, @lauriemerrell, can you try to run [the latest docker image of the mobility-data/gtfs-realtime-validator project](https://github.com/mobilitydata/gtfs-realtime-validator/#setup) and see if you can reproduce the MTC 500 error? If you can, can you please submit an issue to that project?

_Originally posted by @evansiroky in https://github.com/cal-itp/data-infra/issues/902#issuecomment-1036383033_

**Comment by lauriemerrell** [comment]
On step 1, I get this -- "can't read content"
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/55149902/153954208-a612dda0-6103-40bc-8ee7-34341484ab32.png">

So, I cannot seem to run the validator in the docker image for the ITP ID 200 MTC feeds. I was able to run it successfully for Capitol Corridor (one of the MTC feeds, but which does not have `areas.txt` in its static feed). 

There is no detailed error, but perhaps this is `areas.txt` blocking somehow before validation even begins...? There is no detailed error exposed in the UI. 

The underlying issue with `areas.txt` seems to be that the `areas.txt` file for the MTC feed is missing the required `wkt` field. 

cc @evansiroky -- do you think this is worth raising to the MobilityData folks?

**Comment by lauriemerrell** [comment]
Also, step 4 (address temporarily) was handled in #902 -- @atvaccaro is simply deleting `areas.txt` from the list of files copied over for RT validation.

**Comment by evansiroky** [comment]
> cc @evansiroky -- do you think this is worth raising to the MobilityData folks?

@lauriemerrell Yes, definitely. Please create a bug report issue in https://github.com/MobilityData/gtfs-realtime-validator

**Comment by lauriemerrell** [comment]
Submitted as issue MobilityData/gtfs-realtime-validator/issues/92.

@evansiroky, do you think we should leave this issue open on our side...?

**Comment by evansiroky** [comment]
I'll go ahead and close. We can open another issue to update to the latest gtfs-rt-validator when a fix release has been published.
