### ISSUE TITLE
Docs request: Logging ecosystem 

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/data-infra#1071]
**Is your feature request related to a problem? Please describe.**

While we have general documentation about how we are using GCP logging system, it is RT-Archiver specific. We are going to expand the logging infrastructure to multiple areas of the code and thus should update the documentation accordingly.
It will also help analysts conduct queries on the infrastructure to help answer data efficiency questions 
 
**Describe the solution you'd like**

I imagine in being in 4 parts

general logging page
1- Prometheus/grafana
2- Google cloud/big query
    - should write out column descriptions to clarify which are calitp specific and which are generic GCP Logger (i.e 
      receivedTimestamp vs. timestamp)
3- airflow?
4- jupyterhub?

I also think we should create some graphs because some of the systems are quite convoluted 

**Describe alternatives you've considered**
I wouldn't mind some feedback on what areas are unnecessary to include in the documentation. Most of the logging systems require some sort of credentials to see information so I don't think there is a security concern but might want to double check

**Comment by Nkdiaz** [comment]
On hold after consolation with @lottspot , makes sense to do the documentation after we have the prometheus etc set up

**Comment by Nkdiaz** [comment]
We discussed in standup that this is currently blocked until we refactor the rt-archiver. I agreed that it doesn't make sense to build infrastructure for something that is quickly going to be obsolete

**Comment by holly-g** [comment]
Closing this ticket due to ongoing work with RT archiver v3.
