### ISSUE TITLE
Docs request: Updated Calitp-py and extraction packages 

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/data-infra#1072]
As part of this ticket [Calitp extraction packages](https://github.com/cal-itp/data-infra/issues/850#issuecomment-993936915), The last part of the handoff includes updating the documentation. During the handoff meeting, I informally wrote down notes that need to be added to the official documentation. 
I will work with @charlie-costanzo to add the polished notes to the calitp official documentation

**Comment by charlie-costanzo** [comment]
heyo @Nkdiaz! Let me know whenever you think is best for me to start helping out here!
