### ISSUE TITLE
GTFS RT: Reimplement San Diego MTS trip updates

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1091]
@chriscauley discovered that the San Diego MTS (ITP ID 278) RT feeds do not support simultaneous requests to the trip updates and vehicle positions feeds. Our requests to both vehicle positions and trip updates were failing when both URLs were enabled, but succeed if only one URL is listed.

We believe that the root cause is a bug on the feed provider side, but we likely need to implement a workaround of some kind so that we can download both data types. In the short term to unblock ongoing work with vehicle positions (#1086), we temporarily disabled trip updates collection in #1088. 

We see a few ways forward:
- ⭐ _current preferred approach_ Implement some way for the RT archiver to only make sequential requests to these URLs (i.e., add a configurable option to block simultaneous requests on these two specific URLs) 
- 🚫 _speculative, non-preferred_ Potentially request a different API key so that we aren't making simultaneous requests using the same API key across both vehicle positions and trip updates -- however we are not 100% sure that this would work

**Comment by atvaccaro** [comment]
This is blocked pending an RT Archiver refactor. Currently, the architecture doesn't support this sort of constraint.

**Comment by atvaccaro** [comment]
I'm unsure if we can achieve this in the new architecture either. I haven't seen 500s coming from San Diego so we might be OK now?

@lauriemerrell @holly-g I'd like to close and re-open if we see this again.

**Comment by atvaccaro** [comment]
Ah @lauriemerrell has pointed out it's currently disabled for pipeline use in Airtable, so this is still relevant.

**Comment by lauriemerrell** [comment]
As of today (8/24/23), we are still not scraping this data. May be worth revisiting at some point. Leaving issue open.

**Comment by evansiroky** [comment]
As of 2023-12-11 the Transit Data Quality team and Customer Success successfully got San Diego MTS to allow our systems to make the needed requests to obtain the data.
