### ISSUE TITLE
Define Quarterly Dashboard

### ISSUE THREAD

**Issue by e-lo** [cal-itp/data-infra#11]
Results from GTFS Grading scheme evaluations. 

cc: @amymapsmith @mcplanner

**Comment by hunterowens** [comment]
some questions we can probably answer with this  / should be able to answer w/ this, roughly paraphrasing  @mcplanner 

- what static validation issues were identified most recently for agency X?
- what static validation issues were identified for agencies that are clients of vendor Y?
- what agencies have validation issue Z?
- what percentage of agencies meet guideline A?
- track changes and give aggregate statistics.
- what is realtime uptime for agency X

**Comment by hunterowens** [comment]
Additional thing that is a crucial KPI: what is Δ between static and RT on any given day week hour etc

**Comment by mcplanner** [comment]
More specifically:

   - what % of trips in the static feed are showing up in real time? We're
   more likely to find failures to meet uptime requirements because of partial
   outages than full outages.
   - what trips are showing up in real time but not static? Are agencies
   having difficulty representing planned detours and service changes in the
   static feed?

**Comment by mcplanner** [comment]
I closed a duplicate ticket, which had the following suggestions:

The following outcomes are needed for tracking outcomes of the MSD program. 

[reference sheet](https://docs.google.com/spreadsheets/d/1uHqi-xbNioQBMfgVzC_-kN2B0LI-1e_a_FAWD72zhsE/edit#gid=0)

| Metric | Proposed Method |
| -------- | -------------------------- | 
| Transit Data Errors Identified | # of unique Validator errors found in the quater | 
| Transit Data Errors Resolved | # of validators errors that are not present that we are the start of the quarter | 
| Valid Schedules | # of valid schedules being scraped an put into the Data Warehouse | 
| Valid Realtime updates available in GTFS Realtime  | Number of Realtime Feeds  | 
| Alerts available in GTFS Alerts | # of agencies publishing GTFS alerts | 
| Fares available in GTFS Schedule | # of agencies publishing Fares V2 |

**Comment by mcplanner** [comment]
Next steps on this ticket: consolidate all these ideas into a document, vet with the team, and then publish them some place discoverable.

**Comment by mcplanner** [comment]
@machow and I discussed this today. There are lots of dashboards to build:
* quarterly metrics that Gillian et al care about
* less frequent metrics that track progress of specific and highly niche initiatives, like feed expiration dates
* more frequent metrics that are likely one-offs (whatever rabbit hole Ruth is in that day)

Of the three, the quarterly dashboard is the easiest to address and offers the greatest possible impact. Let's give Gillian something shiny she can use to show us off. Best of all, we already have a version in a [spreadsheet](https://docs.google.com/spreadsheets/d/1uHqi-xbNioQBMfgVzC_-kN2B0LI-1e_a_FAWD72zhsE/edit#gid=0) that we've been manually updating. Some of these can be generated programmatically now (transit data issues observed, based on the validators), some will be in the future (number of Improvement Strategies, once we build a place to store them), and others will always be manual (Fares v2 created).

@e-lo any issue with this being available on reports.calitp.org publicly?

**Comment by mcplanner** [comment]
There are likely other metrics we'd want to add, aggregating what's in the monthly reports, such as:
* % of feeds with pathways, fares, shapes, etc data 
* % of agencies with each flavor of real time data
* % of agencies with 20 seconds or shorter update frequencies

**Comment by mcplanner** [comment]
[I started a new list to edit here.](https://docs.google.com/document/d/13rRLy5Kd1OXsyB_hbUegIeARu45E6rwoc6H46_IS8rc/edit#)

**Comment by machow** [comment]
Going to leave here, in case useful context for data people: [California minimum GTFS guidelines](https://dot.ca.gov/cal-itp/california-minimum-general-transit-feed-specification-gtfs-guidelines). There are a lot of feed-level pieces people are looking to check (e.g. does it have a pathways file, less than X% added or removed route IDs, etc..).

**Comment by mcplanner** [comment]
A broad list of useful quarterly metrics has been defined [here](https://docs.google.com/document/d/13rRLy5Kd1OXsyB_hbUegIeARu45E6rwoc6H46_IS8rc/edit#). 

Linking to the new epic (#257) and closing this issue as complete.
