### ISSUE TITLE
Warehouse Views: Update semantic types in Metabase 

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1107]
Right now, a lot of our fields in Metabase in the `Warehouse Views` database do not have appropriate semantic types set: 
![image](https://user-images.githubusercontent.com/55149902/154732175-a7b754e9-9e7e-4237-8e5a-0b67213c6249.png)

This creates annoyance because Metabase will automatically bin numeric ID fields and such, which you then have to manually undo every single time you use the field:
![image](https://user-images.githubusercontent.com/55149902/154732384-866f6cb7-64d8-4191-96bb-e2d07b49815d.png)
 
Fixing this would be a pretty significant effort, especially for things like `calitp_itp_id` that might need to be set as foreign keys potentially across many tables (we may need to experiment with how exhaustive those designations need to be.)

**Comment by atvaccaro** [comment]
We can now use https://github.com/gouline/dbt-metabase#semantic-types to define these! In addition, dbt-metabase automatically converts dbt relationship tests into FK semantics, which would help a ton.
