### ISSUE TITLE
Consistency within new views tables (airflow and docs)

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1117]
**Is your feature request related to a problem? Please describe.**

I'm noticing that a number of newly-created airflow DAG tasks that create new BigQuery tables within the `views` dataset aren't always consistent. Also, the docs around creating new airflow DAG tasks and BigQuery tables could use an update to help guide data engineers. I noticed this while reviewing https://github.com/cal-itp/data-infra/pull/1114.

**Describe the solution you'd like**

* Any DAG task that creates a table within the `views` dataset should probably live within a `*_views` DAG. This can help better organize DAG tasks and make it clear where the data that gets produced ends up within the BigQuery datasets.
* DAG tasks that create a new table should have that table name as their DAG task name. For example, in #1114, there is a DAG task`rt_loader_files/rt_views_gtfs_rt_fact_files_wide_hourly.sql` however it creates a table called `views.gtfs_rt_fact_files_wide_hourly`. This DAG task name should be renamed `rt_views/gtfs_rt_fact_files_wide_hourly`.
* The docs pages https://docs.calitp.org/data-infra/warehouse/views.html and https://docs.calitp.org/data-infra/warehouse/table_naming.html could probably be consolidated and moved into the `airflow` section instead of their current location.

**Describe alternatives you've considered**

Not having any consistency at all.

**Additional context**

This should not block https://github.com/cal-itp/data-infra/pull/1114. It may be a good idea to add expectations to the PR template regarding these items.

**Comment by lauriemerrell** [comment]
Yeah, I called out in the PR that created `rt_fact_files` (#1106) that I was doing this because I suspected we will want to have the `rt_loader_files` DAG and its associated views run more often than daily, which is how often the `rt_views` DAG runs. (I know @atvaccaro has some opinions about the current coupling of data extraction frequency and warehouse operations.)

**Comment by lauriemerrell** [comment]
We can move it if we decide we are not going to do that, but that was the rationale.

**Comment by atvaccaro** [comment]
When/if we implement dbt, this convention won't be just a convention since dbt uses the filename as the table name by default; we'll actually have code as documentation. Plus datasets are driven primarily by folder structure with an explicit configuration, so it has a similar benefit.

**Comment by atvaccaro** [comment]
Closing as we've moved past this; I'm updating docs this week anyways
