### ISSUE TITLE
New Team Member - Blake Fleischer

### ISSUE THREAD

**Issue by holly-g** [cal-itp/data-infra#1124]
Name: Blake Fleischer
Role: Data Services Program Support Team Lead (Jarvus)
Reports to: @themightychris 

Google Workspace Email Address: blake.f@jarv.us
GitHub Username: blakeflei

Starts full-time on 3/1

**Set-up:**
- [ ] Technical Onboarding call scheduled

- [ ] Added to tools:
  - [x] Github
    - [x] Organization: Cal-ITP
    - [x] Team: jarvus
    - [x] Team: warehouse-users
  - [ ] JupyterLab
  - [x] Google Cloud Console
  - [x] Metabase
  - [x] Slack

- [ ] Added to meetings:
  - [ ] Daily Stand-ups
  - [x] Lunch n' Learn
  - [ ] Data Team All-Hands

- [x] Added to Slack channels:
  - [x] #data-analyses
  - [x] #data-infra
  - [x] #data-office-hours
  - [x] #lunch-n-learn

**Comment by evansiroky** [comment]
I took care of the Slack and GitHub invites.

**Comment by holly-g** [comment]
Day 1 ✅
