### ISSUE TITLE
New Team Member - Jameelah Young

### ISSUE THREAD

**Issue by holly-g** [cal-itp/data-infra#1125]
Name: Jameelah Young (Jarvus)
Role: Payments Data Architect 
Reports to: Blake Fleischer

Google Workspace Email Address: jameelah.y@jarv.us
GitHub Username: jameelahmyoung

**Set-up:**
- [x] Technical Onboarding call scheduled

- [x] Added to tools:
  - [x] Github
    - [x] Organization: Cal-ITP
    - [x] Team: jarvus
    - [x] Team: warehouse-users
  - [x] JupyterLab
  - [x] Google Cloud Console
  - [x] Metabase
  - [x] Slack

- [x] Added to meetings:
  - [x] Daily Stand-ups
  - [x] Lunch n' Learn
  - [x] Data Services All-Hands

- [x] Added to Slack channels:
  - [x] #data-analyses
  - [x] #data-infra
  - [x] #payments-data
  - [x] #data-office-hours
  - [x] #lunch-n-learn

**Comment by evansiroky** [comment]
I took care of the Slack and GitHub invites.

**Comment by holly-g** [comment]
Day 1 ✅
