### ISSUE TITLE
Should we move invalid SacRT data out of primary prod buckets?

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1128]
On approximately 2/9/22, SacRT (`calitp_itp_id 273`) changed their realtime URLs. The URLs that we were pointing to became HTML login pages, that we continued to download. The "proto" files that we were downloading from then until #1127 is merged are totally invalid (they are literally HTML). 

I am wondering if we want to move these files out of the primary production buckets. **They do fail parsing anyway so there's no bad data making it into the warehouse**, but they "look" like valid files in the GCS bucket. Just wondering if we want to do anything to get them out of there.

**Comment by evansiroky** [comment]
Seems like moving/deleting would be OK for the affected files.

**Comment by lauriemerrell** [comment]
Per data services stakeholder sync on 6/6/23, we are not planning to backfill RT data pre-September 2022. Closing since this data is just sitting archived.
