### ISSUE TITLE
Implement structured contextual logging for the RT archiver

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1129]
As we begin investigating RT feed reliability issues, we have run into challenges with insufficient detail and structure in the archiver logs (the logs that are actually generated by the archiver itself; not the log extraction process into BigQuery). @atvaccaro wants to implement structured contextual logs for the archiver so we can more effectively follow the trail of individual transactions.

**Comment by holly-g** [comment]
Iceboxing this issue

**Comment by atvaccaro** [comment]
this is done in the new merged code

**Comment by lauriemerrell** [comment]
Specifically this is in #1614
