### ISSUE TITLE
Log response headers in the RT archiver & alert on non-protobuf content types

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1130]
Related to #1129 

When investigating the issue that ultimately became #1127 / #1128, we realized that we were retrieving non-proto data in the archiver and storing that in GCS with no alerting. 

In the specific SacRT case the `content type` in the request response did identify the data as HTML (rather than protobuf), but we didn't do anything with that information on our ingestion side. We would like to begin logging response headers in the archiver and using this to generate alerts for non-proto response types.

**Comment by evansiroky** [comment]
This seems like perhaps it could lead to us being able to check [one of the GTFS-RT best practices](https://github.com/MobilityData/GTFS_Realtime_Best-Practices/blob/master/en/introduction.md#feed-publishing--general-practices) which states:

> The web-server hosting GTFS Realtime data should be configured to correctly report the file modification date (see HTTP/1.1 - Request for Comments 2616, under Section 14.29) so consumers can leverage the If-Modified-Since HTTP header. This saves producers and consumers bandwidth by avoiding transferring feed contents that haven't changed.

**Comment by atvaccaro** [comment]
this is done in the new code!

**Comment by lauriemerrell** [comment]
Specifically this is done in #1614
