### ISSUE TITLE
Make a helper to more easily examine individual proto files

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1142]
Checking the contents of GTFS RT proto files is difficult because you have to have the schema defined (can't just download & double click to open). 

We should make a helper (maybe in `calitp-py`?) that allows you to specify an ITP ID, URL number, feed type, and time (at different granularities: date, hour, minute) and print the proto contents.

**Comment by evansiroky** [comment]
There's already https://www.npmjs.com/package/print-gtfs-rt-cli which does a pretty good job of converting GTFS-RT files to JSON.

**Comment by chriscauley** [comment]
https://github.com/cal-itp/calitp-py/pull/37

**Comment by holly-g** [comment]
Closed by https://github.com/cal-itp/calitp-py/pull/37 -- thank you, Chris! 🎉
