### ISSUE TITLE
GTFS Data: Add GRaaS URL as GitHub secret.

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#1164]
Add GRaaS URL as a GitHub secret. Note that this isn't confidential (hence me pasting below), we are just making an effort to not put it out in the open, as the feeds are not yet live.

secret name: GRAAS_SERVER_URL
secret value: lat-long-prototype.wl.r.appspot.com

**Comment by hunterowens** [comment]
FWIW, I'm a little hesitant to start warehousing data that isn't "live" yet. Or at least, we would need to implement a procedure to not capture it with all the other RT data in the warehouse and discard it at some point. 

If it isn't live, does it at least cover some attempt to have the majority of the runs / buses etc?

**Comment by owades** [comment]
That's fair. We've gone back and forth recently on it, here's a [Slack thread](https://cal-itp.slack.com/archives/C01PE4NMH5G/p1645646978611049) with @evansiroky @atvaccaro and I discussing.

To your question: these agencies are all posting regular updates, which this feed captures, but none of these agencies are capturing the majority of runs/vehicles yet (at least I don't believe so).

We're trying to avoid repeat work of building out analytics on quality/uptime of our rt feeds, by taking advantage of data team resources, and I understand & share your concern of test data getting mixed in with everything else.

I know very little about what's downstream of agencies.yml so I'll default to you @hunterowens @evansiroky @atvaccaro on how to proceed with this issue and #1163

**Comment by hunterowens** [comment]
Ty! I'll defer to @atvaccaro and @evansiroky judgement on how best to include "testing" data in the warehouse. FWIW, this wouldn't be the only situation where I could see I wanted to see test data potentially as a feature.

**Comment by evansiroky** [comment]
I believe it makes sense to leverage our resources in this way to help the GRaaS team at this time. I've gone ahead and added the secrets.
