### ISSUE TITLE
Use calitp version 0.0.12 in JupyterHub

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1165]
I'd really love to be able to access the latest version of `calitp` in JupyterHub: https://github.com/cal-itp/calitp-py/releases/tag/v0.0.12 to get the random proto utility that @chriscauley added. I'm not sure exactly what needs to happen to pin the new version in the JupyterHub image but would love to get it on there if possible.

**Comment by holly-g** [comment]
@charlie-costanzo to bump new version of calitp in JupyterHub this week
