### ISSUE TITLE
Build summary reporting for GRaaS rt feeds

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#1166]
**Is your feature request related to a problem? Please describe.**
GRaaS publishes a vehicle-positions rt feed for each agency that uses our app. In ad-hoc testing the feeds have worked great but we'd like to establish some more robust testing. We'd mainly like to track, for each agency, how many updates are published per day, broken down by trip, route and by vehicle.

**Describe the solution you'd like**
Perhaps it could be a dashboard which allows you to select agency and date, and shows:
- table with position updates totals, broken down by trip, route vehicle
- line graph, showing updates per minute or hour. One line per trip, per route, or per vehicle.

**Describe alternatives you've considered**
We considered building something simple ourselves ([here](https://github.com/cal-itp/graas/issues/107)), until Evan pointed out that the data team has infrastructure that could support this.

**Additional context**
May depend on [this PR](https://github.com/cal-itp/data-infra/pull/1163), which depends on [this issue](https://github.com/cal-itp/data-infra/issues/1164).

**Comment by atvaccaro** [comment]
@owades can we close this? It's doable via Metabase now

**Comment by owades** [comment]
yes!
