### ISSUE TITLE
Add task for loading external table of "official list" spreadsheet

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#118]
See https://github.com/cal-itp/data-infra/pull/115. Should go into a transitstacks DAG, so we can reconstruct warehouse.

**Comment by thekaveman** [comment]
This is great, thank you @machow. Just a note there are 4 different sheets, each loaded as an external table, then joined together in a (broken) view.

**Comment by thekaveman** [comment]
Also, it sounds like from talking with @e-lo and Juliet yesterday - there are still some updates/changes to come to that spreadsheet. There may be another couple of sheets/tables needed, and some modifications to the columns.

**Comment by machow** [comment]
Ah, thanks for the heads up--I can have it tear down the old table daily and put up a new w/ the latest column setup

**Comment by hunterowens** [comment]
@thekaveman / @machow to work on this week

**Comment by machow** [comment]
@hunterowens @thekaveman, I'm not able to query the external tables. It looks like maybe the range that was set no longer works (maybe column names were changed?). Can one of provide some explanation of the range you set (or the correct range now)? Thanks!

![image](https://user-images.githubusercontent.com/2574498/119873996-2ad71080-bef3-11eb-89c1-b6b3a1533bfb.png)

**Comment by thekaveman** [comment]
@machow yeah all the sheet names changed, and some of the column names were cleaned up recently as well. We're just waiting on one more column rename in the *Fares* sheet, but the other four sheets have been re-mapped into BQ tables.

One note, I didn't recreate that view - it was failing anyway, and was just a lazy `LEFT JOIN` of all the external tables. Not sure if it's useful or not.

**Comment by machow** [comment]
Thanks! I'll look over the tables today while looking over the pipeline

**Comment by machow** [comment]
@thekaveman I can create the tables in the web UI, but there may be one small piece to add to load external tables in the pipeline: sharing any spreadsheet loaded with the pipeline's service account. I'm going to try giving the account view privileges on a sheet quickly to check.

**Comment by machow** [comment]
Hmm.. that wasn't it--but it's weird that the failing SQL command, and the web UI are using the same user (michael.c@jarv.us). Lemme look around a bit more!

**Comment by machow** [comment]
Ah, good discussion here--https://github.com/fishtown-analytics/dbt/issues/3040#issuecomment-789223055.

I'll likely need to add scope to looking credentials (and double check that the service account has access to drive)

**Comment by machow** [comment]
@thekaveman I've added transitstacks using an operator called CsvToWarehouse, which downloads the sheets from a URL, and loads into the warehouse.

We can add files like these to the warehouse to upload arbitrary sheets!:

https://github.com/cal-itp/data-infra/blob/main/airflow/dags/transitstacks_loader/fares.yml

**Comment by machow** [comment]
Note that I do the joins here:

https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/transitstacks.yml
