### ISSUE TITLE
Transit Provider Technology stacks

### ISSUE THREAD

**Issue by e-lo** [cal-itp/data-infra#12]
Need in queryable/joinable form so we can ask questions like:

"What was the average grade for transit providers using vendor B compared to others in their peer group"

**Comment by hunterowens** [comment]
@e-lo / I  talked about initial protype of gforms - sheet-> cleanedup read only data replica in BQ / DW?

**Comment by mcplanner** [comment]
The next step on this project is getting clearly defined by me.

**Comment by mcplanner** [comment]
Closing as a duplicate of #204
