### ISSUE TITLE
Bug: Architecture updates may have caused loss in RT data collection

### ISSUE THREAD

**Issue by blakeflei** [cal-itp/data-infra#1201]
**Describe the bug**
Updates to architecture may have caused brief downtime in RT data collection. Unintended consequence of [1198](https://github.com/cal-itp/data-infra/pull/1198). 

**To Reproduce**
Merge of https://github.com/cal-itp/data-infra/pull/1198, and any additional steps taken in the deployment.

**Expected behavior**
Updates to architecture don't cause interruptions in data collection.

**Comment by lauriemerrell** [comment]
@blakeflei can you clarify acceptance criteria / intended work here? I believe that PR #999 was intended to get us as far as we could w.r.t archiver uptime when handling updates to `agencies.yml`. In bug backlog conversation today we were wondering if this can be closed.

**Comment by atvaccaro** [comment]
no longer relevant in v3
