### ISSUE TITLE
Metabase question: Which GTFS Schedule feeds have failed to download?

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1205]
## User Story

**As a** research data analyst,
**I want to** know what agency GTFS Schedule URLs have failed to download and for how many consecutive days they have failed,
**so that** I can properly categorize which transit agencies are having problems with GTFS quality
**and so that** I can know which transit agencies I need to reach out to about failing URLs

For this user story, only the GTFS Schedule and not the GTFS Realtime URLs are considered.

## Acceptance Criteria

**Given** the results of historical GTFS Schedule download attempts in the nightly pipeline,
**When** the [Catastrophic GTFS Errors Dashboard](https://dashboards.calitp.org/dashboard/46-catastrophic-gtfs-errors-dashboard) is opened,
**Then** a table should be shown that lists out all GTFS Schedule URLs that failed to download and for how many consecutive days they have failed to download

**Example:**

Something like the following table should be shown:

|Agency|URL|Number of Days of Unsuccessful Downloads|Last Successful Download Date|
|--|--|--|--|
| Montebello Bus Lines | https://github.com/LACMTA/los-angeles-regional-gtfs/raw/main/montebello-ca-us/montebello-ca-us.zip | 40 | 2022-03-02 |

**Comment by lauriemerrell** [comment]
@evansiroky I believe this is complete (filter at top changed to last 30 days because nothing failed yesterday):

![image](https://user-images.githubusercontent.com/55149902/176248577-690c70af-84d0-451c-a722-ce98b9351580.png)

**Comment by evansiroky** [comment]
Looks great, thanks!
