### ISSUE TITLE
Upgrade data-infra-apps cluster to kubernetes 1.21

### ISSUE THREAD

**Issue by lottspot** [cal-itp/data-infra#1251]
Current version: v1.20.15

We currently have issues with redeploying jupyterhub via the CI/CD pipeline due to the fact that it attempts to utilize a [`PodDisruptionBudget`](https://kubernetes.io/docs/tasks/run-application/configure-pdb/), which requires Kubernetes 1.21 or newer. 

```bash
$ /bin/bash -c "RELEASE_CHANNEL=prod; source ci/vars/releases/prod-jupyterhub.env; source ci/steps/release-helm-changes.sh"
error: unable to recognize "/tmp/tmp.clxWTgC9Uy": no matches for kind "PodDisruptionBudget" in version "policy/v1"
skip: jupyterhub
```

**Comment by atvaccaro** [comment]
oh this is done
