### ISSUE TITLE
upgrading to composer with airflow version 2.0, python 3.6->3.8 

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#126]
Not urgent, but composer has a preview version with airflow version 2.0. The reason to upgrade is that they're going straight from python 3.6 to 3.8. In the meantime, numpy's [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) suggested dropping python 3.6 support in June 2020, so a number of libraries have shifted to require 3.7+ (including pandas 1.2, released Dec 2020).

**Comment by evansiroky** [comment]
This is somewhat more desirable at this point for 2 reasons.

1. [Airflow v1 has reached end-of-life state](https://github.com/apache/airflow#version-life-cycle) and is no longer supported by the software maintainers.
2. The webserver frequently crashes (see #652), so hopefully an update to v2 fixes this.

**Comment by machow** [comment]
Michael to add note giving lay of the land based on existing knowledge / research, stub out research issue before syncing with James on Weds.
