### ISSUE TITLE
Add line number as a column to all gtfs tables

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#127]
Something to investigate, but validator output often refers to the line number of entries where errors occurred. In order to connect these errors to the data, we'll need to explicitly capture line number (since SQL is unordered).

There are some complicating factors here. If we implement change capture, we will not want to keep this around. The line number could be used to fetch data from a specific GTFS schedule file in our external tables.

**Comment by hunterowens** [comment]
I think in this case we can refer back to the original CSVs on GCS, if
needed, and why we store them

**Comment by machow** [comment]
Ah yeah--that's fair. I was thinking it could be useful to be able to filter out all rows with specific validation errors across all agencies. But it seems a lot nicer to punt to looping over buckets and not worry about it
