### ISSUE TITLE
Bug: Foreign key violation not caught by GRaaS dashboard

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#1271]
**Describe the bug**
An foreign key violation appeared in County Express's [static feed](http://data.trilliumtransit.com/gtfs/sanbenitocounty-ca-us/sanbenitocounty-ca-us.zip) and it appears not to show up in the [GRaaS Static GTFS validation dashboard](https://dashboards.calitp.org/dashboard/45-graas-static-gtfs-requirements?feed_name=Unitrans%20(0)&feed_name=Tulare%20County%20Regional%20Transit%20Agency%20(0)&feed_name=Santa%20Ynez%20Valley%20Transit%20(0)&feed_name=Desert%20Roadrunner%20(0)&feed_name=Glendora%20Transportation%20Division%20(0)&feed_name=Glenn%20County%20Transit%20(0)&feed_name=County%20Express%20(0)).

The issue is that service_id c_23971_b_none_d_0 is present for several trips in trips.txt, and is not listed in calendar.txt.

**To Reproduce**
Navigate to the [dashboard](https://dashboards.calitp.org/dashboard/45-graas-static-gtfs-requirements?feed_name=Unitrans%20(0)&feed_name=Tulare%20County%20Regional%20Transit%20Agency%20(0)&feed_name=Santa%20Ynez%20Valley%20Transit%20(0)&feed_name=Desert%20Roadrunner%20(0)&feed_name=Glendora%20Transportation%20Division%20(0)&feed_name=Glenn%20County%20Transit%20(0)&feed_name=County%20Express%20(0)) and look for foreign key violations.

**Expected behavior**
We would expect to see this reported in the dashboard, and in an automated email, as per [this ticket](https://github.com/cal-itp/data-infra/issues/997).

**Additional context**
We discovered this via https://github.com/cal-itp/graas/issues/191

**Comment by evansiroky** [comment]
I looked at this feed and it appears valid. The quoted service ID of `c_23971_b_none_d_0` is present in the `calendar_dates.txt` file and has the appropriate `exception_type` value of `1` indicating added service for the specified date. As long as a service ID is present in the calendar_dates.txt file in this manner it technically does not need to be in the calendar.txt file (see [docs about the calendar_dates.txt file](https://gtfs.org/schedule/reference/#calendar_datestxt)).

**Comment by owades** [comment]
Thanks @evansiroky. My bad for reporting it as a data-infra bug - it is a bug on our end! We have yet to account for calendar_dates.txt, and I didn't realize that file also uses service_id as a unique identifier. We will accommodate on our end!
