### ISSUE TITLE
Vendor Onboarding: Payments Data Discussion Checklist

### ISSUE THREAD

**Issue by blakeflei** [cal-itp/data-infra#1274]
## Background
As vendors are being on-boarded, a list of early discussion points and checklist of questions or information needed can help in anticipating data structures that data infrastructure should be prepared for ingestion, governance, and serving. Ideally, this is in a form that is straightforward to reference and annotate as needed.

## Acceptance Criteria
A document shared to Rebel that has a checklist of items that can be used in on-boarding conversations that helps us anticipate vendor data and availability formats we will ingest, govern, and serve. Document should be shared with Rebel and our teams so  followup meetings with Rebel are relatively straightforward.

**Comment by mjumbewu** [comment]
Will be largely based on https://docs.google.com/document/d/1zs89Vmtu6JuYKwh107MOLC91M_w3xOPtaTfgKvm1-jA/edit?usp=sharing

**Comment by mjumbewu** [comment]
I've taken most of the document and transferred it into a Google form at https://docs.google.com/forms/d/1-Wxg_kUxZaPZBwc2rkr4Zd5SW4HMHVtwV2sl2q73cHk/edit. There are some internal notes that I've left off about RTBF laws and Fares v2. The original document is still useful as an internal discussion point.

**Comment by holly-g** [comment]
See above for latest doc.
