### ISSUE TITLE
process validation report to convert fieldValue2 to strings

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#128]
Recently, a feed added rows with duplicate values of  keys in its `trips.txt` and `stop_times.txt`, that raised a gtfs validator duplicate_key error for the first time. This error reports the field names and values that were duplicated. Because (stop_id, stop_sequence) in `stop_times.txt` should be unique, it uses the entries fieldName1, fieldName2, fieldValue1, fieldValue2, etc..

Note that fieldValue2 is often an integer, because that's how it's coded in this feed's stop_sequence column of `stop_times`.

```
{'code': 'duplicate_key',
 'severity': 'ERROR',
 'totalNotices': 19,
 'notices': [{'filename': 'trips.txt',
   'oldCsvRowNumber': 20,
   'newCsvRowNumber': 19,
   'fieldName1': 'trip_id',
   'fieldValue1': '1008'},
  {'filename': 'stop_times.txt',
   'oldCsvRowNumber': 958,
   'newCsvRowNumber': 996,
   'fieldName1': 'trip_id',
   'fieldValue1': '1008',
   'fieldName2': 'stop_sequence',
   'fieldValue2': 0},
  {'filename': 'stop_times.txt',
   'oldCsvRowNumber': 959,
   'newCsvRowNumber': 997,
   'fieldName1': 'trip_id',
   'fieldValue1': '1008',
   'fieldName2': 'stop_sequence',
   'fieldValue2': 1},
...
```

However, this raises an important issue--bigquery expects that the json data conforms to the schema given, but fieldValue might not return a specific type of value (it is coded as Object in the java tool). I think that as it turns out it will work out fine to say fieldValue2 is an integer, but wonder if different input data could cause this to break.

(Something to keep an eye on; may be better ways to do the JSON unnesting in bigquery; we would be okay converting everything reported to strings, and using the row numbers to connect to the original data)

**Comment by hunterowens** [comment]
fixed when #129 is merged
