### ISSUE TITLE
Grafana dashboard: GTFS-RT Archiver

### ISSUE THREAD

**Issue by lottspot** [cal-itp/data-infra#1283]
Prod and preprod should each have their own dashboard. This can be done either by creating separate dashboards or more ideally by creating a single dashboard which can toggle between the two environments via a dropdown (similarly to the way the [node exporter](https://monitoring.k8s.calitp.jarv.us/d/rYdddlPWk/node-exporter-full?orgId=1&refresh=1m) dashboard allows switching between hosts). At minimum, this dashboard should show:

- [ ] CPU Utilization
- [ ] Memory utilization

**Comment by Nkdiaz** [comment]
Dashboard is visible at this current link: 
https://monitoring.k8s.calitp.jarv.us/d/xPWY4jL7z/gtfs-rt-achiver?orgId=1&var-DS_PROMETHEUS=Prometheus&var-namespace=gtfs-rt&from=now-6h&to=now
