### ISSUE TITLE
Grafana Dashboard: Jupyterhub Users

### ISSUE THREAD

**Issue by lottspot** [cal-itp/data-infra#1284]
The graphs in this dashboard should display all users overlaying each other (not stacked) on a single axis. Should display at minimum:

- [ ] CPU utilization
- [ ] Memory utilization

This dashboard will enable us to complete #592 in an informed way

**Comment by atvaccaro** [comment]
I made this https://monitoring.k8s.calitp.jarv.us/d/967c0gU7k/jupyterhub-monitoring which I think covers things
