### ISSUE TITLE
Bug: Some shape_ids missing from gtfs_schedule_dim_shapes_geo (but present in gtfs_schedule_dim_shapes)

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#1289]
**Describe the bug**
While running RT analysis for AC Transit (4), I noticed that queries on `gtfs_schedule_dim_shapes_geo` failed to find a shape for about 20% of trips on 2022-03-23.

Looking at a few of the affected shape_ids, it seems like they are however present in `gtfs_schedule_dim_shapes`. Not sure why they aren't making it into `dim_shapes_geo` with their points ordered as arrays.

**To Reproduce**
Query on `gtfs_schedule_dim_shapes_geo` returning no data
```
SELECT *
FROM `cal-itp-data-infra.views.gtfs_schedule_dim_shapes_geo`
WHERE calitp_itp_id = 4 AND calitp_deleted_at > '2022-03-23' AND calitp_extracted_at <= '2022-03-23'
AND shape_id = 'shp-72R-12'
LIMIT 1000
```

Query showing data for same shape_id and date on `gtfs_schedule_dim_shapes`
```
SELECT *
FROM `cal-itp-data-infra.views.gtfs_schedule_dim_shapes`
WHERE calitp_itp_id = 4 AND calitp_deleted_at > '2022-03-23' AND calitp_extracted_at <= '2022-03-23'
AND shape_id = 'shp-72R-12'
LIMIT 1000
```
<img width="1074" alt="Screen Shot 2022-03-30 at 11 57 42 AM" src="https://user-images.githubusercontent.com/54728455/160910309-4416349c-a53e-4533-a542-6c688c1371f8.png">

**Expected behavior**
Records with ordered shape point arrays in `dim_shapes_geo` for all shapes in `dim_shapes`

**Additional context**
Query finding affected shapes for AC Transit
```
SELECT DISTINCT t1.shape_id, t1.calitp_itp_id, t1.calitp_deleted_at, t1.calitp_extracted_at
FROM `cal-itp-data-infra.views.gtfs_schedule_dim_shapes` AS t1
LEFT JOIN `cal-itp-data-infra.views.gtfs_schedule_dim_shapes_geo` AS t2 ON t2.shape_id = t1.shape_id
WHERE t2.shape_id IS NULL
AND t1.calitp_itp_id = 4 AND t1.calitp_deleted_at > '2022-03-23' AND t1.calitp_extracted_at <= '2022-03-23'
LIMIT 1000
```

Query finding number of dropped shape_ids by itp_id/extracted/deleted. Issue seems to affect about 7 feeds.
```
SELECT COUNT(DISTINCT t1.shape_id) AS num_shapes, t1.calitp_itp_id, t1.calitp_deleted_at, t1.calitp_extracted_at
FROM `cal-itp-data-infra.views.gtfs_schedule_dim_shapes` AS t1
LEFT JOIN `cal-itp-data-infra.views.gtfs_schedule_dim_shapes_geo` AS t2 ON t2.shape_id = t1.shape_id
WHERE t2.shape_id IS NULL
AND t1.calitp_deleted_at > '2022-03-23' AND t1.calitp_extracted_at <= '2022-03-23'
GROUP BY t1.calitp_itp_id, t1.calitp_deleted_at, t1.calitp_extracted_at
ORDER BY num_shapes DESC
LIMIT 1000
```

**Comment by lauriemerrell** [comment]
Ok, this is fun. Once again a versioning issue. This example shape: `shp-72R-12` was deleted on 3/26. My current logic doesn't handle finding out that a `shape_id` was deleted. In `dim_shapes`, all the points show up as deleted on 3/26 (correctly), but `dim_shapes_geo` thinks the shape is still active, so the merge doesn't combine them because `dim_shapes` says it's deleted and `dim_shapes_geo` thinks it's not. I can fix.
