### ISSUE TITLE
Update GCS keys for extracted payments data

### ISSUE THREAD

**Issue by j-meelah** [cal-itp/data-infra#1306]
## User stories

As a Data Engineer, I want to write extracted payments data to GCS using keys that follow a `year/month/day/hour/minute/second/<VENDOR>/<ENTITY>` convention, so that there is a logical framework for storing data extracted from payment processors other than just Littlepay.

### Summary

We currently perform our extraction of payments data via a bucket sync with Littlepay. As we look to integrate other payment processor vendors, it is likely that we'll need to incorporate other extraction methods such as scheduled API calls, SFTP transfers, etc. It is important for subsequent pipeline operations that we have a pattern for storing extracted data that is independent of its method of extraction.

### Acceptance Criteria

- A new GCS bucket for _all_ extracted data called `raw` (GTFS data will use this same bucket)
- Data is extracted at some recurring interval (determined per vendor) and written to `raw/payments/year/month/day/hour/minute/second/<VENDOR>/<ENTITY>` 
- Downstream processes are rewritten to read from the new bucket 

### Notes
- Only implement for Littlepay since it's the only available vendor at the moment.

**Comment by holly-g** [comment]
Moving to backlog, will want to first speak to vendors (e.g. Enghouse, INIT) before resuming

**Comment by j-meelah** [comment]
Additional vendor schemas were not available to inform key patterns, but generic updates to GCS for extraction of LP transaction data were made as part of v2.
