### ISSUE TITLE
Consider using output of `rt_loader_files.calitp_files_process` instead of globbing in all the `rt_loader.parse_*` jobs separately

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1308]
Idea came up in conversation between @atvaccaro and myself.

Right now, [we glob](https://github.com/cal-itp/data-infra/blob/main/jobs/gtfs-rt-parser/gtfs_rt_parser.py#L56) to get all the files to parse for a given day. We do this once each for `service alerts`, `trip updates`, and `vehicle positions`.

However, we **also** do this in [`calitp_files_process.py`](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/rt_loader_files/calitp_files_process.py), and in that case we write out a parsed version to GCS.

We might want to consider using the GCS output from `calitp_files_process.py` instead of globbing separately for each RT file type. 

Risks:
* The GCS output may be subject to write delay issues from the archiver. (See #1123)
* The GCS output is already parsed; is there a risk in re-constituting raw paths from that parsed content? (We could potentially add the raw paths in the GCS output from `calitp_files_process.py` if we're concerned about this)

Benefits:
* Stop repeating an expensive glob operation when we already have the results of that operation saved out elsewhere.
* If we decide we like the existing parsing, we could speed things up by using a lookup on ITP ID / URL number from the CSV.

**Comment by atvaccaro** [comment]
see https://github.com/cal-itp/data-infra/issues/1309 related

**Comment by lauriemerrell** [comment]
Closing as obsolete in v2
