### ISSUE TITLE
GTFS RT: Have we missed protobuf files in our `rt_loader.parse_*` jobs due to globbing too close to midnight?

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1309]
Realized today that we did not assess whether #1123 also affected the globbing in the `rt_loader.parse_*` jobs. 

The problem is that the RT archiver takes some time to write its files. If the globbing in `rt_loader` is done promptly at midnight, its list of files to parse may be missing files from the 2300 hour UTC that haven't finished writing yet. 

Unless the job is re-run later, those files will not be picked up.

I propose a few actions to resolve this:

- [ ] Investigate prevalence: we can compare all the timestamps from `views.gtfs_rt_fact_files` with timestamps in the actual external tables (would have to impute them from `calitp_filepath`) to see what files are missing
- [ ] Address the actual issue: short to medium term. A few options:
   * Delay running the `parse` jobs until 30 minutes or an hour after midnight, to give time for the archiver to finish (not necessarily preferred; see [this comment](https://github.com/cal-itp/data-infra/pull/1307#pullrequestreview-929315268))
   * Have the `parse` jobs process the prior, rather than the current, day -- this is what we did for `rt_loader_files.calitp_files_process`, but see [this comment ](https://github.com/cal-itp/data-infra/pull/1307#issuecomment-1086249859) for potential concerns
- [ ] Address the actual issue: long term -- worth considering @j-meelah's suggestions around streaming. Can we process this data **as it comes in**?

**Comment by atvaccaro** [comment]
As discussed in a huddle, processing hourly can help with this.
