### ISSUE TITLE
Bug: pybigquery to sqlalchemy-bigquery

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#1313]
**Describe the bug**

This [GH issue was opened in siuba](https://github.com/machow/siuba/issues/407), and Michael has identified that upgrading from `pybigquery==0.10.2` to another pinned version of [sqlalchemy-bigquery](https://pypi.org/project/sqlalchemy-bigquery/) for the Hub should fix the `isin` situation.

**To Reproduce**

**Expected behavior**

Able to use `isin` or `in` conditions when querying from our BQ tables using `siuba` 

**Additional context**

**Comment by charlie-costanzo** [comment]
nice thank you for spinning this up @tiffanychu90! I'll get a new version of the Jupyter image taken care of soon, and that'll include this bump and the other packages we talked about recently

**Comment by lauriemerrell** [comment]
Just for awareness, [this comment](https://github.com/machow/siuba/issues/407#issuecomment-1082460991) from @machow explains the situation in detail

**Comment by charlie-costanzo** [comment]
first step of this is updating the calitp-py package as done in [this PR in calitp-py](https://github.com/cal-itp/calitp-py/pull/49), second step is updating Jupyter image

**Comment by holly-g** [comment]
Closed by https://github.com/cal-itp/calitp-py/pull/49
