### ISSUE TITLE
Create plan for isolated data-infra-apps environments

### ISSUE THREAD

**Issue by j-meelah** [cal-itp/data-infra#1324]
## User story
As a DevOps engineer, I want to audit the existing design of our project's environments, so that I can propose improved designs such that environments are better mirrored and isolated.

### Summary
As the Cal-ITP platform gets more end users and developers, there is a need to improve the delineation of infrastructure resources. This is especially important for maximizing production uptime, minimizing deployment risks, and improving development/testing workflows. The motivation here is to create a basis that the team can make iterative decisions from that is informed by common pain points and project risks, with the hope of avoiding premature commitments to any specific strategies or implementations.

### Work Involved
- Audit challenges in development and deployment cycles as it pertains to infrastructure
- Propose high level options to address the identified challenges 
- Document overall and proposal-specific considerations, both technical and administrative.

### Acceptance Criteria
A document capturing the tasks in "Work Involved" to be reviewed by the team.

### Notes
This issue is scoped to services within the _data-infra-apps_ cluster

**Comment by holly-g** [comment]
Moving to icebox.
