### ISSUE TITLE
Change airtable_loader Airflow execution schedule

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1325]
To attempt to mitigate Airflow performance issues, and because the Airtable pipeline is quite separate from other data pipelines, we would like to change the execution time to be a few hours after midnight UTC.

This also seems appropriate because capturing it anytime overnight Pacific makes sense as a snapshot at times that it's unlikely to be actively edited.

AC: move `airtable_loader` execution time to 2 or 3 AM UTC

**Comment by evansiroky** [comment]
Would it make sense to do this for more DAGs than just the `airtable_loader` DAG?

**Comment by holly-g** [comment]
@evansiroky We considered this, but we're going to keep the scope of this ticket very narrow and stick with just `airtable_loader` for the pupose of the sprint components.
