### ISSUE TITLE
Docs request: Add documentation about transform_warehouse

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1328]
**Is your feature request related to a problem? Please describe.**

Documentation should be added about the new `transform_warehouse` DAG.

**Describe the solution you'd like**

The page https://docs.calitp.org/data-infra/airflow/production-maintenance.html needs to include a new row in the table list of DAGs with information about this new DAG. Perhaps it doesn't need to be in the dependency diagram since it doesn't run on the daily schedule, but some notes around what the expectations are for maintaining this should be added.

**Describe alternatives you've considered**

Looking at the code to figure it out.

**Additional context**

Depends on #1327 being merged so that the docs get updated. Until then, the `Describe the solution you'd like` section won't make sense.

It may be a good idea to update the pull request template to be more specific about documentation expectations around DAGs and dbt.

**Comment by lauriemerrell** [comment]
This was fixed by #1478, somehow I missed connecting it at the time
