### ISSUE TITLE
GTFS Schedule: Remove mislabeled Lassen Transit Service Agency data

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1344]
Per PR #1342, we have erroneously been downloading data from `http://data.trilliumtransit.com/gtfs/tehama-ca-us/tehama-ca-us.zip` and assigning it to `Lassen Transit Service Agency` (ITP ID `162`). Based on the Git history it looks like it has been incorrect for all of history up to PR #1342.

We should remove this mislabeled data. (Related to #1138)

AC:
- [ ] data from `http://data.trilliumtransit.com/gtfs/tehama-ca-us/tehama-ca-us.zip` is no longer associated with `ITP ID 162` in the warehouse

**Comment by atvaccaro** [comment]
We no longer need to do this as the backfill was performed by labeling data with actual URLs present in status.csv files.
