### ISSUE TITLE
Change RT validation to output raw (or minimally transformed) data

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#1345]
somewhat related to https://github.com/cal-itp/data-infra/issues/1083

The RT validator already outputs JSON which BigQuery should be able to read. Currently, the validator pipeline transforms the JSON into pre-aggregated tabular data and serializes as parquet. This has a number of downsides, including (I think) empty parquet files breaking external tables (https://github.com/cal-itp/data-infra/issues/1180) and the loss of granularity inherent in aggregation.

**Comment by lauriemerrell** [comment]
cc @holly-g - I think we should try to get to this next sprint. See https://github.com/cal-itp/gtfs-rt-validator-api/pull/7#issuecomment-1092015491

**Comment by holly-g** [comment]
👍  queued up. thanks for flagging, @lauriemerrell !
