### ISSUE TITLE
Clean up very old erroneous ITP IDs

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1353]
In #988 @edasmalchi identified a bunch of `ITP ID`s that contained data from a mix of agencies in `GTFS Schedule Feeds Latest`. That dataset's issue has been resolved by #1320, but there is still a larger matter of cleaning up the ITP IDs that had incorrect data in them. Eric identified these in particular: 

> 1, 8, 2, 3 (there may be more?)

We should clean up the data in these as part of #1138.

AC:
- [ ] ITP IDs contain only correct data (will require checking what was in `agencies.yml` on the dates the data was scraped and assessing what was intended) -- presumably much of this data should have different ITP IDs assigned

**Comment by atvaccaro** [comment]
We no longer need to do this as the backfill was performed by labeling data with actual URLs present in status.csv files.

**Comment by atvaccaro** [comment]
Actually this may affect RT
