### ISSUE TITLE
User Story: Relabel mislabeled GTFS data (wrong ITP ID / URL number)

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1354]
## User stories

As a data scientist, I want to be able to relabel mislabeled data that is downloaded with the wrong `itp id` / `url number` (in both the RT and schedule pipelines) so that we can correct data in the warehouse even if the original download had mislabeled data. 

Some considerations that must be decided:

- [ ] Timing: given #1149 (#1013, #1352) -- do we want to move data in the current bucket / metadata structure, or wait for a larger re-key copy job and then make edits based on that? 
- [ ] Method: Related to timing -- do we want to copy current data into corrected locations (and make all attendant metadata updates, which may require rerunning most of the Airflow history for GTFS schedule), or do we want to create some after-the-fact annotations table, which applies labeling corrections within the warehouse but does not change the locations of raw data?

### Acceptance Criteria

To resolve this ticket we should,

- [ ] Define a process that can be used to relabel GTFS schedule and RT data
- [ ] Record that process in a central location (likely docs.calitp.org)
- [ ] Ensure that the process allows us to resolve all of the following issues (which can then be resolved one by one outside this ticket based on the new process)
   * #1344
   * #1353 
   * #521 
   * #1018 
   * #1118 

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

Note: on 5/3/22, I split out #1470 to be a separate ticket because we have determined that that data is in a different situation than the case listed here

**Comment by lauriemerrell** [comment]
cc @holly-g and @j-meelah -- per discussion earlier, I am marking this high priority even though, based on considerations outlined in ticket body, it may not be addressed immediately pending what we decide re: bucket refactor

**Comment by atvaccaro** [comment]
We no longer need to do this as the backfill was performed by labeling data with actual URLs present in status.csv files.

**Comment by atvaccaro** [comment]
Some of this may be RT

**Comment by lauriemerrell** [comment]
Per data services stakeholder sync on 6/6/23, we are not planning to backfill RT data pre-September 2022. Closing. As Andrew noted, issue is fixed for schedule.
