### ISSUE TITLE
reports | fix docker implementation

### ISSUE THREAD

**Issue by blakeflei** [cal-itp/data-infra#1362]
## Background
The reports website has been difficult/unstable to maintain and hard to scale across the team, and running the building of the reports website locally isn't common for most of the team. Additionally, installing the requirements.txt locally on recent Jarvus hardware requires changes to the libraries in requirements.txt. To streamline this process, allow for others to easily prepare a build environment, and prepare for building the reports website remotely, updating the build process in docker is an important first step.

**As a** maintainer of the reports website, **I want** to be able run a few commands outlined in the repo readme to build the reports website _without debugging_ **so that** the building of the reports website can be much more easily maintained by a few folks and can more easily be transferred to remote execution.

## Acceptance criteria
**Given**

- The instructions in the repo readme
- Less than 30 minutes of guidance via a call or slack

**Then**
Anyone on the team with a local docker installation and access to GCP BigQuery will be able build the reports without debugging.

**Comment by blakeflei** [comment]
WIP here: https://github.com/cal-itp/reports/tree/docker-fix

**Comment by blakeflei** [comment]
[Docker fix cal-itp/reports#114](https://github.com/cal-itp/reports/pull/114) only addresses the reports generation, not the website hosting. 

The goal is to have everything containerized so a hybrid container/host environment isn't needed for generation.

**Comment by holly-g** [comment]
Closed by https://github.com/cal-itp/reports/pull/146
