### ISSUE TITLE
User Story: Additional macros in dbt

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1366]
## Summary

(Based on [this comment](https://github.com/cal-itp/data-infra/pull/1364#discussion_r848487151) from @atvaccaro)

As a data scientist, I want to leverage dbt macros to lower the risk of typos or mistakes in copy-pasted code and ensure consistency in the codebase. I also want to limit changes in the initial dbt migration to reduce risk of introducing bugs. 

Therefore, I would us to take a second pass over the dbt warehouse after the initial GTFS schedule migration is complete and add additional macros.

## Acceptance Criteria

- [ ] Add a macro for the generation of `*_key` columns in `gtfs_schedule_views_staging` to replace repetitive code like: `FARM_FINGERPRINT(CONCAT(CAST(calitp_hash AS STRING), "___", CAST(calitp_extracted_at AS STRING)))
            AS calendar_key`

## Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by atvaccaro** [comment]
I think this is done, we use `dbt_utils.generate_surrogate_key` for this type of work
