### ISSUE TITLE
Switch Jupyter/calitp-py to using google oauth instead of service account

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#1376]
Currently, there's an env var set in the JupyterHub values.yaml `CALITP_SERVICE_KEY_PATH`. This is eventually used in calitp-py's `get_engine()` function. We are looking to add some new Jupyter users who should not have access to BigQuery by default, so we should remove this key from Jupyter, or at least have a custom spawner check by user for access.

In addition, we may want to consider re-configuring "warehouse-users" in the Cal-ITP github org, as that is the group that grants access to Jupyter right now. The name is misleading if it's no longer aligned with BigQuery access.

**Comment by holly-g** [comment]
cc @hunterowens  
If we'll be opening up the Hub to more caltrans users and they shouldn't be granted access to BigQuery, thoughts on "jupyterhub-users" in the Cal-ITP github org?
