### ISSUE TITLE
Payments: Clean up unused sbmtd_transactions table

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1377]
See #1372 for context -- the `payments_views.sbmtd_transactions` table is no longer being updated, but it also contains some bad data due to bugs introduced by #1233. 

Per @mjumbewu, the rows we should throw away are these:
```sql
select
    *,
    count(*) over (partition by micropayment_id) as duplicates,
    rank() over (partition by micropayment_id order by length(all_route_ids)) as priority
from `cal-itp-data-infra.views.sbmtd_transactions`
qualify duplicates > 1 and priority > 1
```

AC:
- [ ] ^ delete those rows from the `payments_views.sbmtd_transactions` table

_Originally posted by @mjumbewu in https://github.com/cal-itp/data-infra/issues/1372#issuecomment-1098431069_

**Comment by lauriemerrell** [comment]
Closing as NA, this table has been deprecated.

**Comment by lauriemerrell** [comment]
Ope never mind, @charlie-costanzo says this still needs to be done

**Comment by charlie-costanzo** [comment]
Wait I'm sorry, I misunderstood this. This table has been deprecated so cleaning up those rows isn't necessary.  I am closing again as this is NA
