### ISSUE TITLE
Dashboard modification request: filter out gtfs datasets based on deprecated data in agencies.yml vs airtable dashboard

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1387]
## User Story

*As a* transit data quality analyst using the [agencies.yml URLs vs airtable URIs dashboard](https://dashboards.calitp.org/dashboard/58-agencies-yml-urls-vs-airtable-uris),
*I want to* know which gtfs datasets in airtable have been deprecated,
*so that* I can make sure the agencies.yml file is up-to-date

## Acceptance criteria

*Given* data from the airtable gtfs datasets table
  *and* data of the agencies.yml file
*When* data is compared to determine what URIs exist in airtable that are missing in the agencies.ym file
*Then* only those records from the gtfs datasets that are not marked as deprecated should be considered

### Context

In the [agencies.yml URLs vs airtable URIs dashboard](https://dashboards.calitp.org/dashboard/58-agencies-yml-urls-vs-airtable-uris), all questions in the section `URIs in airtable gtfs datasets table that are not in agencies.yml` should be edited to filter out gtfs dataset records that are marked as deprecated.

This issue depends on #1343.

**Comment by lauriemerrell** [comment]
Reopening until Metabase connection for this data is restored

**Comment by lauriemerrell** [comment]
Re-closing now that v2 dashboard is once again available.
