### ISSUE TITLE
Move RT parsing to run hourly in smaller batches, and implement hive keys

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#1410]
Also make any other necessary adjustments to the overall architecture to achieve below AC. One thing to note is that globbing is going to be rough here; we'll be doing it 24 times a day instead of 1.

See https://github.com/cal-itp/data-infra/issues/1112 as potentially related.

AC:
1. External tables readable by dbt; one table per RT type
2. These tables must sit on top of hive partitioned GCS JSONL files.
3. A specific RT parsing DAG exists that runs hourly.
4. One output file is written per input file, rather than the current aggregated files.
5. https://github.com/cal-itp/data-infra/issues/1309 is closeable

Optional:
1. Consider flagging DecodeErrors more loudly.

**Comment by lauriemerrell** [comment]
Would this include backfilling to re-process old data?

**Comment by atvaccaro** [comment]
> Would this include backfilling to re-process old data?

Backfilling parsed data, yes. I think the easiest way will be an actual backfill in Airflow vs. writing a migration script.

**Comment by atvaccaro** [comment]
this is done and backfill is running! making a new ticket for decoderrors
