### ISSUE TITLE
Update Amplitude Benefits events schema with new event properties

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-infra#1432]
**Is your feature request related to a problem? Please describe.**

In cal-itp/benefits#452 we added some new events and properties related to the authentication provider and sign in process.

**Describe the solution you'd like**

- [ ] Update the [`event_properties` struct](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/amplitude_benefits/jsonl_bigquery.sql#L36) in the `amplitude.benefits_events` external table
- [ ] Update [`bigquery_to_views`](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/amplitude_benefits/bigquery_to_views.sql) to add the new `event_properties` field

**Additional context**

Following on from https://github.com/cal-itp/data-infra/issues/960

**Comment by afeld** [comment]
Per @thekaveman, this is just a matter of making the data visible in Metabase… the data exists in Amplitude.
