### ISSUE TITLE
Add Google Analytics to DBT docs site

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-infra#1464]
**Is your feature request related to a problem? Please describe.**

We should get Analytics configured on the new https://dbt-docs.calitp.org

**Describe the solution you'd like**

I created a new property in the Cal-ITP GA account. Here is the code:

```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-G5TSW4348C"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-G5TSW4348C');
</script>
```

**Comment by atvaccaro** [comment]
@thekaveman would you be OK with closing this? dbt still doesn't have an easy way to inject a GA ID (the issue has been stale for forever https://github.com/dbt-labs/dbt-docs/issues/63) so it would involve modifying the index JS
