### ISSUE TITLE
Grafana Dashboard | Metabase

### ISSUE THREAD

**Issue by holly-g** [cal-itp/data-infra#1466]
## User story

As an engineer, I want to know how to scale Metabase so that it can run smoothly in prod as we continue to add more users and data sources.

### Acceptance Criteria

Grafana dashboard displaying: 

- [x] CPU utilization
- [x] Memory utilization

### Notes

Out-of-scope: 

Knowing the number of questions being asked. Some of these features are available in the `Pro` version, and a future research ticket will address some of these asks.

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by Nkdiaz** [comment]
https://monitoring.k8s.calitp.jarv.us/d/i23JFN_nk/metabase?orgId=1&from=now-6h&to=now

**Comment by 7onn** [comment]
@Nkdiaz would you mind sharing the dashboard? I'd love not having to build one from scratch =p
