### ISSUE TITLE
Define location for data assessors to send completed Assessments and Improvement Strategies

### ISSUE THREAD

**Issue by mcplanner-zz** [cal-itp/data-infra#147]
The Data Assessment team within DRMT is developing its Standard Operating Procedures for producing and managing GTFS Data Assessments and Transit Data Improvement Strategies. So far, this work has been handled by Cal-ITP and stored in Google Drive. Eventually, these reports should be viewable by the public (similar to reports.calitp.org). This issue flags the data-infra team to recommend/create a place to store these documents in the long term that will support publication on a public-facing website.

**Comment by mcplanner** [comment]
Task for the next assigned sprint: Ruth to define what this looks like (including copy), where it lives, and how that affects other resources at that location.

This is slated for reports.calitp.org unless opposition exists. cc @hunterowens

**Comment by edasmalchi** [comment]
closed pending new SOPs
