### ISSUE TITLE
User Story: Relabel mislabeled GTFS RT data (wrong RT type)

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1470]
## User stories

As a data scientist, I want to be able to relabel mislabeled data in the RT pipeline where data has been assigned the wrong RT type (for example, `trip updates` data has been downloaded under the `vehicle positions` label).

Based on ongoing work on the RT pipeline, it has become clear that this will need to be corrected by a one-off copy operation and can't be handled in the warehouse, because this data is being assigned the wrong data *type*, not just an incorrect *label*. 

Therefore, I am splitting this out from #1354 to be worked on separately. 

## Acceptance Criteria

To resolve this ticket we should,

- [ ] Define a process that can be used to copy/rename RT data that has been downloaded under the wrong type: what backups do we need? How do we run the copy? How do we re-run parsing? 

- [ ] Record that process in a central location (likely docs.calitp.org)
- [ ] Ensure that the process allows us to resolve all of the following issues (which can then be resolved one by one outside this ticket based on the new process)
  - [x] https://github.com/cal-itp/data-infra/issues/386
  - [ ] https://github.com/cal-itp/data-infra/issues/1181

Sprint Ready Checklist

1.  [ ] Acceptance criteria defined
2.  [ ] Team understands acceptance criteria
3.  [ ] Team has defined solution / steps to satisfy acceptance criteria
4.  [ ] Acceptance criteria is verifiable / testable
5.  [ ] External / 3rd Party dependencies identified

**Comment by j-meelah** [comment]
Addressed in https://github.com/cal-itp/data-infra/issues/386

**Comment by atvaccaro** [comment]
This is still relevant since this is RT data.
