### ISSUE TITLE
Deal with two-row feed_info.txt

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1471]
The current Foothill Transit (ITP ID `112`) feed's `feed_info.txt` has two rows with two sets of active dates (both have the same start date) and the same feed version identifier. 
![image](https://user-images.githubusercontent.com/55149902/166695042-e0d8d9be-7bc1-49ba-b059-be7ca182f134.png)

This causes fanout in the warehouse, because we have two copies of the same feed in `gtfs_schedule_dim_feeds`. Specifically, a test is failing on `gtfs_schedule_fact_daily_trips` because we have two copies of the same trip. 

While this is clearly a bug in their feed, I am not entirely sure how to address this in the warehouse. I am inclined to put in a hacky condition in `gtfs_schedule_dim_feeds` or `feed_info_clean` to filter out one of these rows specifically because this should be rare and putting in logic that tries to programmatically address this kind of situation is unlikely to be robust.

AC:
- [ ] Only one row in `gtfs_schedule_dim_feeds` for the Foothill Transit feed from `2022-05-03`. 
- [ ] The unique combination of columns test on `gtfs_schedule_fact_daily_trips` should pass.

**Comment by holly-g** [comment]
Slack thread here: https://cal-itp.slack.com/archives/C02JFS4LAMU/p1651671937502189 
Let's revisit 5/31 after receiving clarification in the GTFS spec.

**Comment by lauriemerrell** [comment]
whoops this was not supposed to be closed by #1712, reopening
