### ISSUE TITLE
New airtable view: organizations + gtfs_service_data

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#1487]
### **Is your feature request related to a problem? Please describe.**
To compliment the `GTFS Agency-Use Reference` document in progress, I think a new airtable view should be created to compliment that resource and allow analysts to easily access data supporting that definition use-case.

### **Describe the solution you'd like**
A new view from airtable called something like `views.airtable_california_transit_organizations_x_gtfs_service_data_`, which includes a join of the following from airtable:

**table**: `gtfs_service_data`
* services (rename = 'mobility_service')
* agency_id
* network_id
* route_id
* category
* dataset_type
* gtfs_dataset

**table**: `organzations`
* name (rename = 'organization_name')
* mobility_services_managed (rename = 'mobility_service')
  * **This needs to be unnested**

### **Describe alternatives you've considered**
Describing in the docs how analysts can isolate that data themselves. But seeing as that would still require changes to the codebase to complete I believe it is worthwhile to just spin up a new view.

### Additional context
**Direction provided by E:**
> Provider’s service represented in GTFS = sum of “primary” gtfs-service relationships where service is managed by that provider

**Destination table preview (with changed column names)**:
<img width="850" alt="Screen Shot 2022-05-09 at 1 21 23 PM" src="https://user-images.githubusercontent.com/25835059/167463525-cc3e9318-ab72-444f-8d62-466b8541b4df.png">

**Preview agency-use reference docs [DRAFT]**:
[What is an agency?](https://data-infra-1430--cal-itp-previews.netlify.app/warehouse/what_is_agency.html) preview document

**Comment by lauriemerrell** [comment]
Working on this alongside #1159
