### ISSUE TITLE
Create payments dashboard from synthetic data

### ISSUE THREAD

**Issue by j-meelah** [cal-itp/data-infra#1493]
**User Story**
As a payments product owner, I'd like to have a payments metrics dashboard sourced from synthetic data, so that I can securely demo the features of the dashboard to external parties.

**Describe the solution you'd like**
I want a version of the [Payments Metrics Dashboard](https://dashboards.calitp.org/dashboard/29-payments-metrics) that is sourced from entirely synthetic data modeled after production data.

**Acceptance Criteria**
- A version of the Payments Metrics Dashboard that does not consist of any production data.
- Documentation of the process so we can replicate or modify accordingly (i.e., new columns)

**Comment by j-meelah** [comment]
https://www.activestate.com/blog/top-10-python-packages-for-creating-synthetic-data/

**Comment by j-meelah** [comment]
Data has been successfuly generated using _independent attribute mode_ from` DataSynthesizer` as a CSV. Currently generating an alternative set using _correlated attribute mode_. CSVs need to be staged in warehouse next to be made available to Metabase.

**Comment by j-meelah** [comment]
@charlie-costanzo to generate corresponding Metabase dashboard per data staged in `uploaded_data.synthetic_payments_rides`

**Comment by holly-g** [comment]
[Dashboard](https://dashboards.calitp.org/dashboard/89-payments-metrics-synthetic-data?time_window=past3months~)
