### ISSUE TITLE
docs: replacing defunt analytics tools URLS in docs with new URLS

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#1502]
**Is your feature request related to a problem? Please describe.**
We recently migrated the URLs of some of our analytics tools to new, more official URLs - but in some places the data services analytics docs contain our old and possibly now defunct URLs.

**Describe the solution you'd like**
Review the current links in the [Data Services Analytics Documentation](https://docs.calitp.org/data-infra/analytics_welcome/overview.html#analysts-welcome) and making sure that any external links that point to analytics tools are directing to the newer, appropriate URLs, such as:
* notebooks.calitp.org
* analysis.calitp.org
* dbt-docs.calitp.org
* dashboards.calitp.org

**Comment by thekaveman** [comment]
Hi @charlie-costanzo - can you please provide a little more detail here?

What is the new analytics tool with more official URLs? And which docs site are we talking about?

* https://docs.calitp.org/data-infra
* https://dbt-docs.calitp.org
* something else?

I had previously submitted #1464, is this related?

**Comment by thekaveman** [comment]
Gotcha!! Thanks for the clarification 🙏
