### ISSUE TITLE
Investigate performance indicators associated with RT file creation issues 

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1515]
We now have historical RT archiver performance data in Grafana that we can cross-reference against the RT file creation dashboard. We want to use that to see whether we can find leading performance indicators that could alert us to issues sooner than the current file-driven monitoring. 

AC for this ticket:
- [ ] Laurie and James to work together to look at Grafana data covering time periods where file creation went down and see whether we can find any performance indicators that seem reliably associated with these outages
- [ ] If we find anything promising, write a ticket or other plan for future work to set up alerting based on that finding (i.e., creating alerting is explicitly **out of scope** for this initial investigation)

**Comment by lottspot** [comment]
I went rogue and made some graphs which appear to be pretty reliable indicators of problems afoot:

* https://monitoring.k8s.calitp.jarv.us/d/xPWY4jL7z/gtfs-rt-achiver?viewPanel=27
* https://monitoring.k8s.calitp.jarv.us/d/xPWY4jL7z/gtfs-rt-achiver?viewPanel=26
* https://monitoring.k8s.calitp.jarv.us/d/xPWY4jL7z/gtfs-rt-achiver?viewPanel=8

Please review and freely offer suggestions/questions/issues @lauriemerrell. We could as a next step dig into historical data to determine whether these indicators are reliable enough to alert on once they are tweaked to satisfaction.

**Comment by lauriemerrell** [comment]
@lottspot if you would like to close the issue based on the alerting you set up last week, that is ok with me!

**Comment by holly-g** [comment]
Graphs/alerting are all set up! Closing.
