### ISSUE TITLE
RT Archiver / K8s:  Insufficient quota warning

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1519]
When looking at the [RT archiver node pool](https://console.cloud.google.com/kubernetes/nodepool/us-west1/data-infra-apps/gtfsrt-v1?project=cal-itp-data-infra) for unrelated troubleshooting, we noticed this warning:

`us-west1-a: Insufficient quota to satisfy the request: waiting on IG: instance https://www.googleapis.com/compute/v1/projects/cal-itp-data-infra/zones/us-west1-a/instances/gke-data-infra-apps-gtfsrt-v1-2d12659c-0h57 is still CREATING. Last attempt error: [QUOTA_EXCEEDED] Instance 'gke-data-infra-apps-gtfsrt-v1-2d12659c-0h57' creation failed: Quota 'N2_CPUS' exceeded. Limit: 24.0 in region us-west1. - . `

![image](https://user-images.githubusercontent.com/55149902/170060358-e7790d36-27a3-470b-95ce-5b1994eeecda.png)

@lottspot indicated that this is potentially concerning so I am submitting this ticket to record / get this in the queue to investigate.

**Comment by atvaccaro** [comment]
We can ignore, this node pool no longer exists and the new one is fine
