### ISSUE TITLE
GTFS Schedule Pipeline: Proto-Airtable extract

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1527]
Given that Airtable work is happening in parallel to pipeline updates, we need a very rough Airtable extract mockup that we can use for testing the non-agencies.yml based download process.

Questions:
* Do we download from Airtable, save that output, then have a separate step that dedupes before reading into the downloader?
* Where in process to assign UUID while Airtable work is pending?
* Where in process to fill in API keys

AC:
- [ ] Data from the `gtfs datasets` Airtable table is exported into a JSON containing list of URLs to scrape 
- [ ] JSON is saved in GCS in hive-partitioned fashion

**Comment by atvaccaro** [comment]
all credit to @lauriemerrell this is done!
