### ISSUE TITLE
GTFS Schedule pipeline: `gtfs_downloader` validation updates

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1529]
In concert with #1528, make a new validation DAG task that (AC):

- [ ] Validates a zipfile (output by #1527) 
- [ ] Saves validation results in a hive-partitioned GCS bucket
- [ ] Hive partition path is based on:
   - [ ] The date and time that the code actually runs, not the Airtable execution date
   - [ ] UUID (not ITP ID & URL number)

**Comment by j-meelah** [comment]
Closed by #1648
