### ISSUE TITLE
GTFS Schedule Pipeline: RT archiver core work

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1531]
The RT archiver must be updated to (AC):

- [x] Ingest the Airtable-extracted data (example generated in #1527) instead of `agencies.yml`
- [x] Write data out to locations that are:
   - [x] Hive-partitioned
   - [x] Based on UUID instead of ITP ID and URL number 
   - [x] added 6/16: consider naming raw data bucket to `gtfs-rt-raw`

**Comment by atvaccaro** [comment]
this is done and deployed; we still need to backfill old data (potentially, we could also just union in dbt) but the core changes are deployed

**Comment by lauriemerrell** [comment]
For paper trail: This was closed by https://github.com/cal-itp/data-infra/pull/1614
