### ISSUE TITLE
GTFS Schedule Pipeline: Warehouse updates

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1536]
Epic containing tasks related to item [#6 Warehouse updates from the GTFS Schedule Pipeline Proposal - May 2022 project](https://docs.google.com/document/d/1tPPpZMgPfRNviarF2BrSrwZYtSGnPzGcT75erHo-UZ0/edit#heading=h.a0ttns92ee8o).

**Comment by atvaccaro** [comment]
Going to close, there's two outstanding issues but the vast majority is done!
