### ISSUE TITLE
Evaluate AlloyDB vs Python-based transforms in our dbt pipeline

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#1564]
At some point we will want to be doing more GEOGRAPHY stuff that BigQuery cannot support. We can do more via PostGIS in AlloyDB, or Python/Geopandas/that whole stack. I want to do some exploratory work to see how multi-backend dbt feels, and how we can pipe data between the databases easily.

**Comment by j-meelah** [comment]
Recommended time for research/evaluation is ~3-5 hours.

**Comment by holly-g** [comment]
Will be replaced by dbt Python models
