### ISSUE TITLE
Define User Stories for Statements Dashboard End Users

### ISSUE THREAD

**Issue by j-meelah** [cal-itp/data-infra#1569]
## User stories

As a statement dashboard product stakeholder, I want to write user stories for end user personas so that I can assess product value and determine work allocation accordingly.

### Summary
As part of the scoping efforts for a new dashboard for statements data, we want to contextualize our exploration around potential end users and their use cases. Rebel Group has existing manual processes that exhibit some of the potential features of this product concept. We've also explored data integration prospects together that would facilitate automated, daily ingestions of funded transaction data.

### Acceptance Criteria

Document outlining several user stories for a payments statement dashboard.

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
5. - [x] External / 3rd Party dependencies identified

**Comment by j-meelah** [comment]
User stories developed in collaboration with Rebel Group, and have been presented to Cal-ITP stakeholders.

**Comment by holly-g** [comment]
Doc: https://docs.google.com/document/d/1pSZgcdD-bfGCvU0rBnJGMhq691fF8eAJBx_FI06mjn4/edit#
