### ISSUE TITLE
Update dbt overview page documentation 

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/data-infra#1572]
**Is your feature request related to a problem? Please describe.**
Currently the dbt page contains an overview landing page when you click on the following link 

[Overview](https://dbt-docs.calitp.org/#!/overview)

**Describe the solution you'd like**
We should update the text to have CalITP specific information/ more information on what the purpose of the dbt docs are.

**Additional context**
We might want to move some of the documentation from https://docs.calitp.org/data-infra/intro.html over to this page

**Comment by j-meelah** [comment]
Let's leverage [this](https://docs.calitp.org/data-infra/datasets_and_tables/navigating_dbt_docs.html?highlight=dbt) as a reference for dbt's role in the Cal-ITP project.
