### ISSUE TITLE
Requesting each Swiftly client to give us API access individually

### ISSUE THREAD

**Issue by mcplanner-zz** [cal-itp/data-infra#159]
Swiftly has one API for all of its clients, and regulates access at their admin level. To see all RT data for their CA clients, we need to ask each Swiftly client to ask Swiftly to add us to each of their accounts.

Swiftly clients are (MTC feeds have a *):

- Avalon Transit
- City of Banning
- City of Santa Monica (Big Blue Bus)
- City of Turlock
- Eastern Sierra Transit Authority
- Gold Country Stage
- Humboldt Transit Authority
- Lake Transit Authority
- Madera County Connection
- Napa Valley Transportation Authority*
- North County Transportation District
- Orange County Transportation Authority
- Redding Area Bus Authority
- San Joaquin Regional Transit District
- Santa Clara Valley Transportation Authority (VTA)*
- Santa Maria Area Transit
- Sonoma-Marin Area Rail Transit (SMART)*

**Comment by mcplanner** [comment]
@hunterowens, were you able to ingest Gold Coast Transit's? They're the only one that has added us so far. Let me know if that is working for us and I can start adding these asks in our ongoing discussions.

**Comment by thekaveman** [comment]
@mcplanner Big Blue Bus caught my eye - they make GTFS-RT data available without an API key at http://gtfs.bigbluebus.com/ (e.g. http://gtfs.bigbluebus.com/tripupdates.bin), by consuming the Swiftly API with their key and republishing. Do we necessarily need the direct Swiftly connection for all of these?

**Comment by hunterowens** [comment]
My guiding principle is defer to the agency official feed

so secondard feeds, whether upstream or downstream, should be considered,
well secondary. IDK if we need to measure change in the same way we do with
511 agencies (Which is modification not a mirror of feeds)

**Comment by mcplanner** [comment]
Perhaps really the ask is two part:
1) checking to see which ones we still need
2) understanding how if more than one agency comes to us through Swiftly,
what we need to support it.

**Comment by mcplanner** [comment]
Have we ingested Gold Coast yet to see if we can work with Swiftly?

**Comment by machow** [comment]
Anything needed here? It looks like there is no RT url for Gold Coast in agencies.yml.

**Comment by holly-g** [comment]
Closing! These agencies got tracked in Teamwork.
