### ISSUE TITLE
Add human readable validator errors to DW

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#162]
@mcplanner has prepped a [spreadsheet of human readable](https://docs.google.com/spreadsheets/d/1GDDaDlsBPCYn3dtYPSABnce9ns3ekJ8Jzfgyy56lZz4/edit#gid=0) validator errors. 

In order to do cal-itp/notebooks#20 and make improvements to the reports, we should store these human readable strings alongside the validator errors in the notebook. 

Proposed method

1. save the mapping as a yml or csv in the repo
2. Update the view pipeline (cc @machow) 

Then do the notebooks issue 20 and work with @e-lo to figure out which vendors have the same errors and do errors over time.

**Comment by machow** [comment]
requires: #161

**Comment by machow** [comment]
I'm pulling in the human reader validator spreadsheet, and noticing that...

* The spreadsheet puts the codes as camel case (e.g. DuplicateKeyNotice)
* The validator output uses snakecase (e.g. duplicate_key)
* From the example above, there are sometimes small differences (like putting the word Notice on the end).

I'm guessing the camelcase likely is what the java code itself uses as variable names, and maybe that made its way into the docs somewhere? @mcplanner do you mind linking to where you grab code names from? I think we'll need a strategy to go from the camelcase to what's in the data (hopefully there is a resource in https://github.com/mobilityData/gtfs-validator; or we could do quickly by hand).

https://metabase.k8s.calitp.jarv.us/question/3/notebook

**Comment by machow** [comment]
For posterity--here are the relevant links in their docs

* [docs where they convert from camel to snake case](https://github.com/MobilityData/gtfs-validator/blob/master/docs/NOTICES.md)
* [the code where it happens](https://github.com/MobilityData/gtfs-validator/blob/52434454b747bb4085038f27563e98fee6018ca5/core/src/main/java/org/mobilitydata/gtfsvalidator/notice/Notice.java#L52-L54)

**Comment by hunterowens** [comment]
@machow checking in on this?

**Comment by machow** [comment]
view is deployed here!: https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/validation_code_descriptions.py
