### ISSUE TITLE
Turn RT Archiver V2 ticker and consumer prototype into production-ready code

### ISSUE THREAD

**Issue by j-meelah** [cal-itp/data-infra#1627]
### User Story
As a Data Engineer, I want to turn the RT Archiver V2 ticker and consumer experimental code into a production-grade MVP

### Acceptance Criteria

- RT Archiver V2 is deployed in parallel with RT Archiver V1
- Deployed application is able to service the full catalog of URLs 
- MVP does not have to meet SLOs, but should be within reasonable "reach" given immediately subsequent optimizations and feature work

### Notes

Working branch: https://github.com/cal-itp/data-infra/pull/1614

The deployed application does not have to be fully optimized, but conceptually sound enough that we can make incremental improvements that will allow us to confidently fulfill SLOs. **The work here is to essentially take the learnings from the prototype and implement a comparable version that is _at least_ minimally viable for supporting the full RT URL scraping workload.**

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by atvaccaro** [comment]
this is merged!
