### ISSUE TITLE
Deploy RT Archiver V2 MVP

### ISSUE THREAD

**Issue by j-meelah** [cal-itp/data-infra#1628]
### User story

As a DevOps Engineer, I want to deploy the RT Archiver V2 MVP, so that we can observe its performance and make changes accordingly.

### Summary

In #1627, we are developing a MVP for RT Archiver V2. **The work here is to configure and execute the deployment of the resulting application code.**

### Acceptance Criteria

- There is a running instance of RT Archiver V2 in GCP

### Notes

Discuss sub-prod environment considerations with tech stakeholders and design accordingly

### Tester [Stakeholder]

1. @atvaccaro 
2. @lauriemerrell 

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
3. - [ ] Team understands acceptance criteria
4. - [ ] Team has defined solution / steps to satisfy acceptance criteria
5. - [ ] Acceptance criteria is verifiable / testable
6. - [ ] External / 3rd Party dependencies identified

**Comment by holly-g** [comment]
Completed
