### ISSUE TITLE
Enhancement: Ensure same timestamp across Airtable extracts

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1629]
This is something that we wanted to do as part of #1625 but realized that it would be harder than we thought, so deferring until it becomes higher priority.

Currently, Airtable extracts are timestamped based on the time that each individual DAG task runs ([see here](https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/operators/airtable_to_gcs.py#L75)). This means that we don't have a shared timestamp identifier across multiple extracts that are part of the same overall DAG run. (We still think this is absolutely preferable to timestamping based on DAG task execution date in a way that risks overwriting data if a DAG is re-run.)

Our current solution will be that we enforce a daily granularity for extracts on the warehouse side. 

This should be fine for the short term, but long-term we may want to explore whether we can force all extracts to have the same timestamp to facilitate joins.

Ideas:
* Refactor the operator to extract an entire base (or bases) rather than having one DAG task per table -- this obviously has downsides but would give everything the same timestamp
* Try to extract an actual DAG runtime from the Airflow *DAG* context (this may be difficult again because there are separate tasks) 
* Perhaps experiment with something like task groups that could facilitate the above 
* Perform backfill accordingly

**Comment by atvaccaro** [comment]
We should also do this for GTFS schedule if we don't have another ticket.

**Comment by lauriemerrell** [comment]
This has been working without this for a long time, don't think this is necessary at this point.
