### ISSUE TITLE
New Team Member - Katrina Kaiser

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#1644]
Name: Katrina Kaiser
Role: Research Data Specialist III
Reports to: Hunter Owens

Google Workspace Email Address: katrina@calitp.org
GitHub Username:
Slack Username: @Katrina Kaiser

**Set-up:**
- [x] Technical Onboarding call scheduled

- [x] Added to tools:
  - [x] Github
    - [x] Organization: Cal-ITP
    - [x] Team: warehouse-users
  - [x] JupyterLab
  - [x] Google Cloud Console
  - [x] Metabase
  - [x] Slack

- [x] Added to meetings:
  - [x] Daily Stand-ups
  - [x] Lunch n' Learn

- [x] Added to Slack channels:
  - [x] #data-analyses
  - [x] #data-office-hours
  - [x] #lunch-n-learn

**Comment by hunterowens** [comment]
start date is 8/2

**Comment by charlie-costanzo** [comment]
Hey @hunterowens! Do you know if we've gotten any of these yet?

> Google Workspace Email Address:
> GitHub Username:
> Slack Username:

**Comment by hunterowens** [comment]
I'll ask tomorrow!

**Comment by hunterowens** [comment]
@charlie-costanzo username is @KatrinaMKaiser!
