### ISSUE TITLE
New Team Member - Alyssa Medina

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1659]
Name: Alyssa Medina
Role: Research Data Analyst I
Reports to: @evansiroky 

Google Workspace Email Address: alyssa@calitp.org
GitHub Username:
Slack Username: Alyssa Medina

**Set-up:**
- [x] Technical Onboarding call scheduled

- [x] Added to tools:
  - [x] Github
    - [ ] Organization: Cal-ITP
    - [ ] Team: warehouse-users
  - [x] JupyterLab
  - [ ] Google Cloud Console
  - [x] Metabase
  - [x] Slack

- [x] Added to meetings:
  - [x] Lunch n' Learn

- [x] Added to Slack channels:
  - [x] #data-analyses
  - [x] #data-office-hours
  - [x] #lunch-n-learn

**Comment by holly-g** [comment]
GitHub username created: `aly-medina`
