### ISSUE TITLE
User Story: Run the Fares v2 validator for each agency

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#1664]
### Summary

As a Cal-ITP team member, I want to understand whether a given agency provides complete fares info according to the draft GTFS Guidelines v3, so that I can understand whether they are ready to implement contactless payments.

Specifically, I'd like to see whether the agency provides the appropriate fares-related files in their static feed: fare_leg_rules, rider_categories, fare_containers, fare_products, and if they provide those files, whether they pass the [fares v2 validator](https://github.com/TransitApp/gtfs-fares-v2-validator) without errors.

This roughly duplicates https://github.com/cal-itp/data-infra/issues/558.

We are making an effort to automatically measure as much of the GTFS Guidelines as possible, so we can understand very easily where a given agency stands, and what support they need.

### Acceptance Criteria

I can check, for any given agency, whether they've provided fare files in their static GTFS feed.
I can check, for any given agency, whether yesterday/today's static feed passed the fares v2 validator error-free.

### Tester [Stakeholder]

1. Scott Owades

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by owades** [comment]
@evansiroky mentioned that since gtfs-validator will include fares validation, it might not make sense to prioritize this. I'm going to seek a better understanding of that work.

**Comment by owades** [comment]
Draft MD PR [#1228](https://github.com/MobilityData/gtfs-validator/pull/1228) would address this - I hear Kevin is going to offer Brian some support in reviewing

**Comment by holly-g** [comment]
Closed by https://github.com/MobilityData/gtfs-validator/pull/1228
