### ISSUE TITLE
User Story: Check whether agency feeds are linked in transit.land

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#1666]
### Summary

As a Cal-ITP team member, I want to understand whether a given agency's static and RT feeds are linked on aggregator transit.land, so that I can understand whether they comply with the draft GTFS Guidelines v3.

This roughly duplicates https://github.com/cal-itp/data-infra/issues/574.

We are making an effort to automatically measure as much of the GTFS Guidelines as possible, so we can understand very easily where a given agency stands, and what support they need.

---

### Acceptance Criteria

1. For each agency, I'd like to see a true/false value, in dbt or metabase, for whether their feeds (according out our source of truth, likely Airtable) are listed on transit.land.
2. In implementing #1688, an analyst/engineer should be able to use the output of this ticket to create the "check" defined as: "This service provider's feed is represented on transit.land".

### Tester [Stakeholder]

1. Scott Owades

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
3. - [ ] Team understands acceptance criteria
4. - [ ] Team has defined solution / steps to satisfy acceptance criteria
5. - [ ] Acceptance criteria is verifiable / testable
6. - [ ] External / 3rd Party dependencies identified

**Comment by owades** [comment]
Blocked by: https://github.com/cal-itp/data-infra/pull/1585

**Comment by owades** [comment]
Consider checking transitfeeds.com as well, until it is deprecated

**Comment by owades** [comment]
@charlie-costanzo @holly-g would it be possible to include the transit.land uniqueID ("Onestop ID") in this work? For agencies that **are** linked in transit.land, you could report the OnestopID value, and for agencies that are not linked in transit.land, you could report a null value.

**Comment by charlie-costanzo** [comment]
> would it be possible to include the transit.land uniqueI D ("Onestop ID") in this work? For agencies that **are** linked in transit.land, you could report the OnestopID value, and for agencies that are not linked in transit.land, you could report a null value.
> 
> The reason for wanting this is that, as a part of the manual assessment process, Cal-ITP staff will view the transit.land page of the transit provider, as an easy way to inspect shapes.txt. We can save them a step by providing this link directly.

@holly-g I believe this is work that would need to be done on the scraper itself? Not sure who would be most appropriate for that. I could look into it, but I'm about to be out of town for 2 weeks so it wouldn't be until after then 

cc @owades
