### ISSUE TITLE
Amplitude Benefits: 404 causing DAG failure

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/data-infra#1682]
Starting around August 5, we have been seeing this error in the `amplitude_benefits.api_to_jsonl` DAG task:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://amplitude.com/api/2/export?start=20220805T00&end=20220805T23`

[Logs](https://o1d2fa0877cf3fb10p-tp.appspot.com/log?execution_date=2022-08-05T00%3A00%3A00%2B00%3A00&task_id=api_to_jsonl&dag_id=amplitude_benefits)

**Comment by lauriemerrell** [comment]
FYI @angela-tran @machikoyasuda @thekaveman -- this seemingly did not happen today, after happening every day for several days 👀 Possible they fixed it on their side?

<img width="819" alt="image" src="https://user-images.githubusercontent.com/55149902/184364810-694725fb-eeac-4e2f-b819-6d02c4d6eae3.png">

**Comment by angela-tran** [comment]
I think we should update our operator to be ok with a 404 response code.

From https://www.docs.developers.amplitude.com/analytics/apis/export-api/#status-codes,

>  404    |  No data available for the time range requested.
