### ISSUE TITLE
User Story: Ingest WeHo RT URLs & define process for storing authorization information in v3 archiver 

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1684]
### Summary

1. **As an** analytics engineer OR a Cal-ITP data manager 
2. **I want** to be able to add new URLs and associated secrets (API keys and headers) to the v3 RT archiver
3. **So that** new data is downloaded by the v3 archiver

Specifically, we need to document where to add new API keys or header secrets to be ingested by the new v3 archiver. This issue is prompted by #1683 where we are adding new WeHo RT URLs for the v2 archiver but I do not know how to add the necessarily authorization information for the v3 archiver too. 

### Acceptance Criteria

1. Most urgent: Get WeHo credentials from #1683 stored in the appropriate place(s).
2. I currently see API keys stored as Airflow environment variables **and** in Google Cloud Secrets Manager (and I see in the v3 archiver that it [seems to reference Secrets Manager](https://github.com/cal-itp/data-infra/blob/main/services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/consumer.py#L31-L41)). In the [authorization proposal doc](https://docs.google.com/document/d/15x0RLZkQg8LCTVmXTLxOFeNfKg_lm0mW5EQe1H9oGfg/edit), we had proposed entry in just the Airflow UI. If we need to enter also in Google Cloud Secrets Manager, that should be documented very clearly somewhere. Perhaps we will need to develop a dedicated docs page, I am not sure if this would belong in the Airtable Operating Procedures doc because it involves a workflow that spans both Airtable and not-Airtable.
3. If we are using Google Cloud Secrets Manager, all the relevant people (at the very least, me and Evan) should presumably have permissions to add secrets there. I currently do not have permissions to add a secret:
![image](https://user-images.githubusercontent.com/55149902/183925538-5d8c6856-1766-4601-a966-ba08ecba69cd.png)
4. We should consider whether / where we would recommend people storing the API key in a way that's retrievable for developers to use for testing. That's slightly outside the core scope but if we have data managers enter directly in Google Cloud Secrets and Airflow environment variables, we should make sure there's a way for developers to test locally if needed. 

### Tester [Stakeholder]

1. Me (Laurie)
2. @evansiroky and anyone else he proposes who needs to be able to do this workflow

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
4. - [ ] Team understands acceptance criteria
5. - [ ] Team has defined solution / steps to satisfy acceptance criteria
6. - [ ] Acceptance criteria is verifiable / testable
7. - [ ] External / 3rd Party dependencies identified

**Comment by atvaccaro** [comment]
I think we can close this, WeHo secret is in secrets manager and it's ingested by the archiver

Only relevant follow-up is https://github.com/cal-itp/data-infra/issues/1938

cc @lauriemerrell
