### ISSUE TITLE
User Story: Data structure and/or dashboard to support GTFS Guideline check-level reporting

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#1688]
### Summary
As a Cal-ITP team member, I want an easy way to understand transit service providers' GTFS Guideline compliance, so I can quickly understand a provider's current GTFS needs in order to provide the support they need.

My goal is to have a single dashboard that summarizes, for a given day, the result of a series of about 30 GTFS checks for a given agency. ![Here's a prototype](https://user-images.githubusercontent.com/3301353/184032340-5d2252f0-91e3-4dad-b607-e68f69a99a91.png).

The checks are listed [here](https://docs.google.com/spreadsheets/d/1v5nPowMi0EzQpfDd9d0ZluWnKX8JKm8E2nGMmuUvDRE/edit#gid=1120242357) I'll describe the solution that I have in mind below, and I am open to other ways of solving this.

**An option for how to solve:**
Build a new fact table, containing one row per day, per agency, per check. Since each check is very different, relying on a combination of schedule, RT,  airtable data and more, much custom logic would need to live in the table-creation process. [Here's how I think the table would look](https://docs.google.com/spreadsheets/d/1v5nPowMi0EzQpfDd9d0ZluWnKX8JKm8E2nGMmuUvDRE/edit#gid=1164332414).

Once we have this fact table, dashboard creation in Metabase or another tool will be straightforward - and could be broken out into a separate task. An elegant part of this solution is that, when a new check is added to the fact table, it can flow directly into reporting without needing to push any reporting updates.

### Acceptance Criteria

**Example:**

1. An analyst is able to reproduce [this dashboard](https://user-images.githubusercontent.com/3301353/184032340-5d2252f0-91e3-4dad-b607-e68f69a99a91.png), including for yesterday's gtfs data, relying entirely on the output of this issue.

### Notes

Considering resource constraints, and the huge amount of checks involved, I'm open to being a very active developer on this task. As one option, (assuming you agree with my solution proposed above) perhaps Jarvus could design a fact table, including a single very simple check, and leave it up to me to add the remaining checks.

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by lauriemerrell** [comment]
Thanks @owades -- this proposal sounds good. A few heads up items about how this might interact with the rewrite:
1. For the "date" index, two things:
   1. The way that the pipeline currently works, we have validations (from the validator) for each date in a way that's actually fairly separate from the "feed version". In the future it will be more closely aligned. But for now, validations that come directly from the validator have date handling that might be fairly different than date handling for validations we have to implement manually/ourselves. 
   2. The index structure itself: I just wanted to confirm that in general the underlying data that is being evaluated likely wouldn't change from day to day. For example, if a feed is uploaded on January 1 and then not updated at all until August 18, we are not actually bringing hundreds of copies of that identical data into the warehouse -- we would just update the "expiration date" for the January 1 data once it expires. It's totally fine to construct a daily index for this table, but I just wanted to flag that regarding the mechanics of the actual checks themselves. 
2. How will such a table be "keyed" -- this is likely something that will need to be reevaluated in the rewrite (for now it would presumably be keyed on ITP ID, which is the current standard, but post-rewrite something like service as defined via Airtable might be better). This isn't a huge deal, mostly just an FYI that if we make a table now we may have to refactor slightly to align with the new pipeline.

**Comment by owades** [comment]
Thank you, @lauriemerrell!

1. These are really helpful points, and my response to both is "let's do whatever Laurie says". Having a row for every date isn't necessary, as long as the structure we land on is one that interfaces well with reporting.

2. I think that makes sense, starting with ITP ID and then refactoring when the new pipeline is complete. In general I want to limit the amount of re-work I'm asking for, and this is hopefully my only ask where the business value of doing it sooner outweighs the cost.
