### ISSUE TITLE
Deploy Hosted Grading Scheme

### ISSUE THREAD

**Issue by e-lo** [cal-itp/data-infra#17]
**Source**: https://github.com/wesleyi23/gtfs_grading_application

**Timing**: By Spring!

**Dependencies**: This is a dependency for the following 2021 MSD milestones:
1. 2021 Q2 Launch DIY GTFS Assessment Toolkit

**Priority**: Fairly high

**Interested Parties**: MSD Team @mcplanner @e-lo @wesleyi23

**Comment by mcplanner** [comment]
Next steps: determine how schedule accuracy fits into the next version of the GTFS Guidelines, and how this will be part of the DRMT assessment process.

**Comment by mcplanner** [comment]
Moving to Teamwork
