### ISSUE TITLE
Bug: Airtable organizations table pipeline broken because of field data type change

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1731]
**Describe the bug**
A few weeks ago, we changed the `fare_systems` column in the `organizations` table in Airtable -- it used to be a linked record field, but we deleted the link and the field was converted to a string. This data type change has broken our Airtable data ingest for all tables that rely on `organizations`. 

**To Reproduce**
Check production Airflow, `transform_warehouse` DAG has failed since ~8/18.

**Expected behavior (AC to fix)**

- [x] Short term fix: suppress this field so the tables can run again (completed in #1734)
- [ ] Medium term fix: Update data entry in Airtable & backfill (if needed, depending on plans for long term fix)
- [ ] Long term fix: #1724?

**Comment by thekaveman** [comment]
Somewhat related to getting the schema in the pipeline... just wanted to put this question on your radar (which I also linked to from Slack earlier): https://github.com/cal-itp/crm-helpdesk/issues/116#issuecomment-1233276823

**Comment by lauriemerrell** [comment]
"short term" fix has been in effect for a ~year now and is working fine, no further action planned AFAIK
