### ISSUE TITLE
Schedule: Update downloader to use new Airtable fields (authentication & `pipeline_URL`)

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1736]
Since we originally implemented the provisional v2 pipeline, the new authentication information has been added to Airtable. To ingest it, we need to do the following **for only the new schedule pipeline:**

- [ ] Use `pipeline_URL` instead of the original `URI` field (`pipeline_URL` has had the auth URL params removed where applicable)
   * _Note that this will change the base64 encoding of the URLs_ 
- [ ] Use only the **structured** authorization information in Airtable (`authorization_URL_parameter_name`, `URL_secret_key_name`, `authorization_header_parameter_name`, `header_secret_key_name`) to retrieve auth info (i.e., remove any hacky interim we code to work around this until it was populated)

**Comment by lauriemerrell** [comment]
@atvaccaro I think we concluded that it didn't actually change the base64 encoding of the URLs?

**Comment by atvaccaro** [comment]
Correct, we were parsing out the auth param templating in the old code.
