### ISSUE TITLE
Checking what entries in views.agency_names are not in the data

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#176]
from pairing w/ @Nkdiaz -- we should check which agencies have 0 notices in our data. The potential problem is that when there are 0 notices, then an agency will not even show up. This is because if you unnest something with 0 entries, it returns 0 rows of data:

```sql
SELECT 1, t1 FROM UNNEST([]) t1
```

It's useful to add these agencies, even if they have metric values that are 0 (so people can see that explicitly). Let's check against our list of agencies (we can just use the most current ones, `views.agency_names`). Which entries are in agency_names that aren't in validation_code metrics?

* validation_code_metrics (t1) right join with agency_names (t1)
* check where t1.calitp_itp_id IS NULL

**TODO**: 

* report here which agencies aren't included
* (to pair on): including agencies with 0 rows in metrics.

**Comment by Nkdiaz** [comment]
Will be addressed by https://github.com/cal-itp/data-infra/pull/175
