### ISSUE TITLE
GTFS schedule warehouse refactor: Initial reports website tables 

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1762]
Based on feedback from our [model storming conversation with Eric and Aaron](https://docs.google.com/document/d/1khAd6VpKHIZKpIUFNmdMMFGkSqHt1tdB6t-BMXC_sMA), create the following tables (naming subject to change) in v2 of the warehouse:

- [x] Replicate existing table `reports_daily_service_routes_stops`
- [ ] Replicate existing `reports_gtfs_schedule_index` -- will need to discuss re-keying (re: ITP ID / url number); add vendor information

**Comment by edasmalchi** [comment]
Thoughts on selecting which dataset: Let's pick the one that matches RT if RT present, otherwise retain current report choice

**Comment by lauriemerrell** [comment]
Closing in favor of updated / better scoped #2098
