### ISSUE TITLE
GTFS backfill: RT & RT validations

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1772]
We need to backfill the GTFS RT data scraped between July 8, 2021 and September ??, 2022 (move data from `gtfs-data/rt/` to `calitp-gtfs-rt-raw`.

The exact implementation is TBD, but we need to consider the following:

- [ ] Copy raw protos to new location 
- [ ] Should we copy parsed data to new location?
- [ ] Should we copy v1 (validator 1.1.0 from CUTR S3) validations into new locations / decide on what date validator MD 1.0.0 is the only version available?

**Comment by atvaccaro** [comment]
We're going to backfill from v1 up to 2022-09-15 to mirror schedule and preserve response headers.
