### ISSUE TITLE
User Story: Include manual GTFS check data from Airtable in the warehouse

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#1773]
### Summary

As a Cal-ITP team member interfacing with agencies, I want to understand where they stand on a series of manually-performed GTFS checks, so that I can be completely up to date on the status of their GTFS feed and provide support accordingly.

While we are automating every check possible, there remain ~14 checks which can only be performed manually (listed below). These checks mostly already are occurring, and are tracked in Airtable. We need to get these checks into the warehouse, so they can be added to fact_daily_guideline_checks.

I believe the two options are:
A) Connect the existing tables to the warehouse
B) Create a better Airtable data structure, and connect this to the warehouse.

As addition context for option A, the checks are listed in 3 separate tables (I may be using incorrect Airtable lingo): `gtfs-dataset check data`, `gtfs-service check data`, and `provider check data`. It seems straightforward to consolidate these 3 tables to one, if that were deemed necessary. There's also a table called `gtfs checks` which provides info about each check. As I understand, these tables are linked to the source of truth transit-provider table in Airtable, so hopefully clean joins are possible.

List of needed manual checks, just for extra context:
- Static feed ingested by Google Maps and/or a combination of Apple Maps, Transit App, Bing Maps, Moovit or local Open Trip Planner services.
- Realtime feed ingested by Google Maps and/or a combination of Apple Maps, Transit App, Bing Maps, Moovit or local Open Trip Planner services.
- Static and RT feeds are representative of all fixed-route transit services under the transit providers' purview;
- Static and RT feeds are representative of all deviated-fixed route transit services under the transit providers' purview
- Shapes in shapes.txt are precise enough to show the right-of-way that the vehicle uses and not inaccurately exit the right-of-way.
- Include tts_stop_name entries in stops.txt for stop names that are pronounced incorrectly in most mobile applications.
- Passes Grading Scheme v1
- Follow all GTFS Schedule Best Practices (version 1.0 or later) and "Should" statements in specification.
- Consistent with GTFS Realtime Best Practices and "Should" statements in specification.
- GTFS Schedule link is posted on website
- GTFS Realtime link is posted on website
- Authentication process follows guidelines
- Includes an open license that allows commercial use
- Technical contact is listed on website

### Acceptance Criteria

I am able to added addition GTFS checks based off of the Airtable data tables listed above. Data remains up to date.

### Tester [Stakeholder]

1. Scott Owades

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by owades** [comment]
Just flagging that we are discussing changing the location of where in Airtable these checks are stored. I'll keep this ticket/Holly posted on (small) changes to requirements.

**Comment by evansiroky** [comment]
Here are the columns I ended up creating:

- `organizations.Manual Check: Contact on Website`
- `services.Manual Check: GTFS Realtime Data Ingested in Trip Planner`
- `services.Manual Check: GTFS Schedule Data Ingested in Trip Planner`
- `gtfs service data.Manual Check: fixed-route completeness`
- `gtfs service data.Manual Check: demand-response completeness`
- `gtfs datasets.Manual Check: Link to dataset on website`
- `gtfs datasets.Manual Check: Stable URL`
- `gtfs datasets.Manual Check: Accurate Shapes`
- `gtfs datasets.Manual Check: Grading Scheme v1`
- `gtfs datasets.Manual Check: Data License`
- `gtfs datasets.Manual Check: Authentication Acceptable`

**Comment by atvaccaro** [comment]
is this done now? @lauriemerrell @owades

**Comment by atvaccaro** [comment]
@owades says yes!
