### ISSUE TITLE
Follow up steps: new GTFS download config type

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1774]
This is a ticket to enumerate non-code steps that need to be taken after PR #1754 and PR #1786 merge.

- [ ] Backfill metadata on raw GCS artifacts (schedule & RT) to use the new config & extract schemas -- RT will probably need an Airflow job
- [ ] Backfill outcomes to conform to new schema (subject to TBD call on how to impute extracted at)
- [ ] Copy files in prod to have base64 URL at the end (final partition instead of TS)

**Comment by atvaccaro** [comment]
I don't think we need this anymore, closing
