### ISSUE TITLE
Request to Add Airtable Column to Data Warehouse

### ISSUE THREAD

**Issue by aly-medina** [cal-itp/data-infra#1782]
## User stories

Would like to add column `GTFS Schedule Quality` into the data warehouse (Metabase) for data analysis.

---

### Summary

1. As a Research Data Analyst
2. I want to add  `GTFS Schedule Quality` from the `Services` table in Airtable to the data warehouse 
3. So that an analysis can be conducted pertaining to GTFS & Vendor relationship, providing accurate stats for accountability purposes

### Acceptance Criteria

1. If I search for `GTFS Schedule Quality` in Metabase
1. It should populate

**Comment by lauriemerrell** [comment]
Hi @aly-medina -- thanks for your patience while we've looked into this!

I would want to defer to @evansiroky on whether it is appropriate to bring this field into the warehouse as-is, for two reasons:

1. I am a little concerned about the fact that this is a field that is being manually entered, when we have ways to assess GTFS quality within the warehouse (for example, @owades's in-progress GTFS guidelines fact table, or the raw validations data itself) that might be more robust/up to date. It's hard for me to tell if this field is up to date, and looking in Airtable it is definitely missing in some cases. 
2. I am confused about why this field is being entered in the `services` table, when it is a determination about GTFS dataset quality. It seems like it would be more appropriate to have determinations of GTFS dataset quality on a table of GTFS datasets and then assess how they relate to services via a join or similar, as opposed to setting & maintaining this attribute on the `services` table directly.

I think these questions are related to some of the concerns that @evansiroky has voiced about Airtable data model maintenance.

We can explore adding this field to the warehouse temporarily, perhaps with some notes explaining its possible limitations, as has been discussed in Slack, but I wanted to check with @evansiroky and his thoughts about the future direction of this type of data before just adding it.
