### ISSUE TITLE
record GTFS on a daily schedule

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#18]
[this code](https://gitlab.com/cutr-at-usf/transi/core/record-gtfs/-/blob/master/record.py) from CUTR will help us download GTFS. 

The question remains: where do we want to the list of GTFS urls to live? a version controlled catalog.yml? trillium gsheet?

**Comment by e-lo** [comment]
Yes to something on GitHub.
Perhaps:

https://specs.frictionlessdata.io/data-resource/#language

Or stick with same format as GBFS list:

https://raw.githubusercontent.com/NABSA/gbfs/master/systems.csv

Eventually should be available using a regular pull from mobility database

**Comment by hunterowens** [comment]
the frictionless data resource spec looks similar to [Intake](https://intake.readthedocs.io/en/latest/quickstart.html).. One thought is to have something similar to the gbfs list in github and then parse into frictionless/ intake /etc

**Comment by hunterowens** [comment]
but "can be changed with a PR" seems the right level of difficultly given how often URLs might change

**Comment by hunterowens** [comment]
One issue that keeps popping up with the `GTFS` field in the existing database - these are often note the `.zip` download URLs 

In my ideal world, each url on that list should be a download url, that is, it returns the gtfs zip file. Unfortunately, some urls (ie, `https://gitlab.com/LACMTA/gtfs_bus, https://gitlab.com/LACMTA/gtfs_rail`) aren't zip files. 

Given that keeping that URL at a consistent location is a performance metric, we could use git history or do an append only file to track how often agencies are changing the url

**Comment by e-lo** [comment]
Does this work: https://gitlab.com/LACMTA/gtfs_rail/-/archive/master/gtfs_rail-master.zip

**Comment by hunterowens** [comment]
Yup!

**Comment by hunterowens** [comment]
with #20 merged, this is now scheduled. Now just need to fix #21 before this issue is closed out.

**Comment by hunterowens** [comment]
def fixed!
