### ISSUE TITLE
Re-run validator across time / investigate missing calitp_extracted_at in some validation.json

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#180]
cf https://github.com/cal-itp/notebooks/issues/20#issuecomment-866044511

I think that after implementing adding calitp_extracted_at to validator reports, some of the processing tasks may not have been re-run over our history.

**Comment by machow** [comment]
Okay--this is a pretty weird one. It seems that at some point validation files were saved with `//` in their path. E.g. "{path_to_agency}/91_0//validation.json". In this case, it is treated is sometimes treated as a separate file from "{path_to_agency}/91_0/validation.json". I'm not sure when this happens, or whether it's intended behavior.

tl;dr we should rename the `//` files to use `/`.



```python
import json
import gcsfs

# two separate files-- the one with // is the correct one
json.load(fs.open("gs://gtfs-data/schedule/2021-04-16T00:00:00+00:00/91_0/validation.json"))
json.load(fs.open("gs://gtfs-data/schedule/2021-04-16T00:00:00+00:00/91_0//validation.json"))
```

Here's code to look up when calitp_extracted_at is none.

```python
import gcsfs
import json
import re

re_month_day = re.compile("2021-([0-9]+-[0-9]+)_")

fs = gcsfs.GCSFileSystem(project="cal-itp-data-infra")
reports = {k: json.load(fs.open(k)) for k in fs.glob("gs://gtfs-data/schedule/processed/*/validation*")}

bad_reports = {k: v for k, v in reports.items() if v.get("calitp_extracted_at") is None}
len(bad_reports)

# set of days to re-run validator on
{re_month_day.search(k).groups[0] for k in bad_reports}
```

## Fix

It seems like we could...

*  search for and move files with `//` to be their `/` counterparts. 
* re-run file processing for every day (or just the ones affected)
* re-run gtfs_schedule_history2 DAG, `validation_notices_load` task

**Comment by machow** [comment]
Failed all non-running tasks / dagruns, and it is updating again. I think I needed to clear fewer at a time 🙄

**Comment by mcplanner** [comment]
Possibly will be resolved when we upgrade Airflow.

**Comment by machow** [comment]
This should be resolved in airflow v2, which refactored the scheduler. See also https://github.com/cal-itp/data-infra/issues/249
