### ISSUE TITLE
Allow filtering by agency name in gtfs report metabase  dashboard

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#181]
cc @mcplanner @hunterowens @Nkdiaz

See [this convo in slack](https://cal-itp.slack.com/archives/C01FNDG1ZPA/p1624394465086100). Currently [the gtfs report dashboard](https://metabase.k8s.calitp.jarv.us/dashboard/6) can filter by calitp_itp_id, but not agency name. There should be a way to include by using a linked filter to views.gtfs_agency_names.

![image](https://user-images.githubusercontent.com/2574498/123003735-a5c00980-d381-11eb-8c70-bf7074ad8e22.png)

Here is a relevant doc:

https://www.metabase.com/learn/building-analytics/dashboards/linking-filters

**Comment by machow** [comment]
TODO: 

for this question which is on the GTFS schedule dashboard...

* add a parameter also  (it's hardcoded to filter a specific calitp id)
* add the files being reported in the first part gtfs report table (shown below)

![image](https://user-images.githubusercontent.com/2574498/123129817-3b0edc80-d41a-11eb-97ed-0dd884e4077c.png)


https://metabase.k8s.calitp.jarv.us/question/26

**Comment by machow** [comment]
One thing for us to figure out down the road--we currently plot what files an agency has on a given day, but the plot won't show files that are never added. For example, in the plot below we can't tell that transfers.txt doesn't exist in this feed. 

![image](https://user-images.githubusercontent.com/2574498/123849756-2bded180-d8e7-11eb-9cbb-6e06daa8bfec.png)

It seems like reproducing the table above is tricky in metabase / SQL..!

**Comment by Nkdiaz** [comment]
Is completed and updated in metabase
https://metabase.k8s.calitp.jarv.us/dashboard/6?start_date=2021-05-01&end_date=2021-07-31
