### ISSUE TITLE
Assess feasibility of using masked PANs as a proxy for unique riders

### ISSUE THREAD

**Issue by j-meelah** [cal-itp/data-infra#1813]
## User stories

As a payments metrics dashboard user, I want to know if `masked_pan` is a feasible attribute to use for unique rider metrics, so that I can analyze ridership trends.

### Acceptance Criteria

Analysis comparing entity relationships between `funding_source_vault_id`, `customer_id`, `principal_customer_id`, and **`masked_pan`**

### Notes

We've removed charts that represent unique rider counts because of entity resolution concerns about the corresponding attribute(s) being used to determine distinct ridership. We'll want to compare candidate attributes and make a recommendation for the best proxy for unique rider identifiers, starting with `masked_pan` so that we can re-introduce ridership charts to the dashboard with increased confidence in the underlying data.

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by charlie-costanzo** [comment]
Analysis notebook:

https://github.com/cal-itp/data-analyses/blob/main/payments/payments_attribute_analysis.ipynb
