### ISSUE TITLE
Migrate feed aggregator checker to pull URLs from Airtable rather than agencies.yml

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1826]
As part of ultimately turning off agencies.yml, we will need to migrate the feed aggregator checker (https://github.com/cal-itp/gtfs-aggregator-checker) to pull URLs from Airtable instead of agencies.yml. 

Acceptance criteria:

- [ ] Aggregator checker reads in an Airtable extract for the list of URLs to scrape, instead of using agencies.yml
- [ ] Results of aggregator checks are saved in a new, dedicated bucket
- [ ] New external table is created OR existing external table (https://github.com/cal-itp/data-infra/blob/main/airflow/dags/create_external_tables/feed_aggregator_checks.yml) is adapted to point at this new bucket 
- [ ] As part of this fix, we will render #1825 obsolete. We should make a decision as part of this ticket as to whether we need to backfill that old data into the new format.

**Comment by lauriemerrell** [comment]
https://github.com/cal-itp/data-infra/issues/2015

**Comment by atvaccaro** [comment]
made unnecessary by https://github.com/cal-itp/data-infra/pull/2144
