### ISSUE TITLE
Setting up cal-itp-data-infra-staging project

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#183]
@thekaveman (cc @hunterowens), can we set up a new cloud project called `cal-itp-data-infra-staging`? This will allow us to make a copy of our SQL tables on bigquery when developing. For other parts of the pipeline--e.g. GCS--we just change the name, so this is mainly for bigquery.

Do you mind setting up the new project? (I'm happy to take a stab at it, but think someone from compiler might be needed!)

**Comment by thekaveman** [comment]
@machow I will take a look! I haven't set up a new project before but it can't be too bad.

**Comment by thekaveman** [comment]
I imagine this new project will incur some additional costs? @machow @hunterowens do we have sign-off from Jeremy et. al on the additional spend?

**Comment by machow** [comment]
Right now the tables our duplicated into our current project, so the costs should stay the same! (Right now, we're not exceeding the free resources BigQuery provides per project :)

**Comment by thekaveman** [comment]
Oh I understand now 👍 Moving those `staging` tables into a separate project.

**Comment by thekaveman** [comment]
@machow Created the project and added you as an Owner. You should have received an email notification:

![image](https://user-images.githubusercontent.com/1783439/123331000-8f39bf80-d4f3-11eb-89d5-1fd0ae560bff.png)

/cc @hunterowens

**Comment by machow** [comment]
Thanks! Can we add the same billing account to the new project? It looks like transferring datasets is disabled for free projects.

I think we should still be able to keep an eye on it from the same billing page as cal-itp-data-infra, but will double check to make sure!

**Comment by thekaveman** [comment]
Done @machow

**Comment by machow** [comment]
Looks like copying datasets across project works--so we're all squared away, thanks!
