### ISSUE TITLE
Investigate failing dbt tests (GTFS & Airtable)

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1831]
We have several tests that are failing for GTFS schedule, RT, & Airtable data in dbt right now. The purpose of this ticket is to capture an **investigation** task that we need to do to identify the root cause and propose next steps. If the fixes for any of these will take more than ~30 min to implement, they can be deferred to a follow-up ticket.

**Acceptance criteria**:

Proposed resolution (demote to warn; change test if test is wrong; fix actual underlying data) for each of the following failing tests:
- [ ] table: `gtfs_schedule_fact_daily_feed_stops` / failing check: `dbt_utils_unique_combination_of_columns_gtfs_schedule_fact_daily_feed_stops_feed_key__stop_key__date`
- [ ] table: `stops_clean` / failing check: `unique_stops_clean_stop_key`
- [ ] table: `stg_transit_database__gtfs_service_data` / failing check: `dbt_utils_unique_combination_of_columns_stg_transit_database__gtfs_service_data_key__calitp_extracted_at`
- [ ] table: `dim_contract_attachments` / failing check: `unique_dim_contract_attachments_key`
- [ ] table: `stg_rt__vehicle_positions` / failing check: `unique_stg_rt__vehicle_positions_key`

**Comment by atvaccaro** [comment]
https://github.com/cal-itp/data-infra/pull/2222 solves the GTFS dim errors; I've put the Airtable tests on our Friday agenda.

**Comment by lauriemerrell** [comment]
`unique_dim_contract_attachments_key` issue remains but is documented in #2909
