### ISSUE TITLE
Failing Payments data models - September 2022

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1847]
Recording a few different Payments data models that are currently failing, for investigation:

* In dbt: `unique_stg_cleaned_device_transaction_types_littlepay_transaction_id` -- message: `Got 2 results, configured to fail if != 0`
* Also dbt: `validate_cleaned_device_transaction_pairs_common_fields` -- message: `Got 1658 results, configured to fail if != 0`
* Also dbt: `validate_cleaned_micropayment_device_transactions` -- message: `Got 4 results, configured to fail if != 0`
* In `payments_views.mst_ridership`, the `littlepay_transaction_id.check_unique` test failed ([link](https://o1d2fa0877cf3fb10p-tp.appspot.com/log?dag_id=payments_views&task_id=mst_ridership&execution_date=2022-09-23T00%3A00%3A00%2B00%3A00))

**Comment by charlie-costanzo** [comment]
dbt: `validate_cleaned_device_transaction_pairs_common_fields` 
message: `Got 1658 results, configured to fail if != 0`
* `has_mismatched_customer_id` = 578 results
* `has_mismatched_device_id` = 1091 results
* `has_mismatched_route_id` = 5 results
* `has_mismatched_direction` = 2 results

**Comment by lauriemerrell** [comment]
Closing as won't do, rewrite is commencing soon and we won't be revisiting this
