### ISSUE TITLE
User Story: alerts for improperly coded airtable records in GTFS dataset table

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1877]
### Summary

**As a** airtable data manager or airtable data editor
**I want** know if any records in airtable are improperly coded
**So that** I can go fix those records

### Acceptance Criteria

1. This particular ticket applies only to the GTFS Dataset table
1. The `gtfs datasets`.`QC: Has minimum required fields` should be made available in metabase
2. A metabase question should be made that shows all rows where the value of `gtfs datasets`.`QC: Has minimum required fields` is not "OK"
3. The metabase question should send off an email to all data owners and data editors responsible for the table.

### Tester [Stakeholder]

1. @evansiroky 
 
# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
5. - [ ] Team has defined solution / steps to satisfy acceptance criteria
6. - [ ] Acceptance criteria is verifiable / testable
7. - [ ] External / 3rd Party dependencies identified

**Comment by j-meelah** [comment]
When take on this issue we will also explore alternative monitoring/alerting solutions, such as configuring [notifications within Airtable](https://support.airtable.com/docs/create-custom-notifications-for-your-base ) itself or leveraging a dedicated monitoring service such as [Sentry](https://sentry.io/welcome/).

**Comment by evansiroky** [comment]
This has been resolved using Airtable automations
