### ISSUE TITLE
User Story: Create monitoring dashboards for actual data availability for v2 archiver

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1895]
### Summary

**As an** analytics engineer,  **I want** a Metabase dashboard showing RT file availability for the v3 archiver analogous to what we have for v2 (old) **so that** I get an get a more holistic picture of actual data availability than what Sentry alerts offer.

Sentry is helpful for identifying when outages start, but given the transient nature of most RT outages, it would be helpful to create a dashboard that shows overall file availability over time. This would also help show when new feeds are added. This would also help catch if there are failures that are causing issues in data creation that are not yet being caught in Sentry, which I suspect may have happened with SunLine (URL: https://infopoint.sunline.org/InfoPoint/GTFS-Realtime.ashx?Type=VehiclePosition) which had an expired certificate. I don't see any issues in Sentry related to the expired cert from the v3 archiver even though the v2 (old) archiver shows no data for a period and then the return of data. 

I think @atvaccaro might disagree with this request or think that at least part of it could be handled by improved Sentry settings, which may also be true.

### Acceptance Criteria
1. Tables that show:
   1.  overall file counts by day per URL, perhaps ideally also showing the first day that a URL appeared in our data to help troubleshoot 
   2. file counts by hour like our current wide by hour table?
3. A Metabase dashboard that consumes this table to visualize data availability similar to what we have for the current archiver

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
3. - [ ] Team understands acceptance criteria
5. - [ ] Team has defined solution / steps to satisfy acceptance criteria
6. - [ ] Acceptance criteria is verifiable / testable
7. - [ ] External / 3rd Party dependencies identified

**Comment by atvaccaro** [comment]
> I think @atvaccaro might disagree with this request or think that at least part of it could be handled by improved Sentry settings, which may also be true.

Nope I think this makes total sense; for me, Sentry is about operations/alerting and tracking a backlog of issues to solve/investigate. Metabase makes total sense for a general data availability dashboard.
