### ISSUE TITLE
Enable analysts to add / debug pipeline tasks in vscode

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#190]
@thekaveman @themightychris (cc @hunterowens). It'd be helpful to create a simple vscode setup for analysts with...

* calitp and some pinned pipeline dependencies
* ability to open jupyter notebooks

Any thoughts / articles on how to set this up? Is setting it up as `.devcontainer` in the calitp-py repo the move?

**Comment by thekaveman** [comment]
> Is setting it up as `.devcontainer` ... the move?

This sounds like a really nice approach! I'm a big fan of VS Code + devcontainers.

The [Docker Compose](https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose) setup is a nice way to get multiple services running if that helps. [benefits/.devcontainer](https://github.com/cal-itp/benefits/blob/dev/.devcontainer.json) is an example of this.

The standard VS Code Docker images also work for single-container situations. [cal-itp.github.io/.devcontainer](https://github.com/cal-itp/cal-itp.github.io/tree/main/.devcontainer) is an example of this.

**Comment by machow** [comment]
Ah, cool--thanks! I'll take a stab at it based on the examples, and then if it works maybe ping y'all to kick the tires!

**Comment by thekaveman** [comment]
Please do! 👍
