### ISSUE TITLE
Bug: Dask cluster dashboard does not load, probably due to DNS/port issues?

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#1913]
**Describe the bug**
I installed https://github.com/dask/dask-labextension per request by @edasmalchi but dashboards don't load data. I think this may be due to how the Helm chart sets up ports/services. I will do some digging.

**To Reproduce**
The provided dashboard URL such as `http://dask-scheduler.dask.svc.cluster.local:8787/status` does not work in Jupyter; using port 80 does work to load the list of available pages, but the pages themselves do not work.

**Expected behavior**
n/a

**Additional context**
n/a

**Comment by tiffanychu90** [comment]
I was able to load some of the pages....I think by opening the link that opens in the cell after you run the `client = ....` and call `client`, rather than from the side panel. But of the pages that load, not all of them show stuff

**Comment by atvaccaro** [comment]
closing, this is minor
