### ISSUE TITLE
Answer questions in Ruth's "Questions for Juniper doc"

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#192]
https://docs.google.com/document/d/1uu_CxSEoV5sUxSGFSGu2iuunMEHVY5mPlBzeogOIxWE/edit

It seems like a good way to carve this doc up is...

* Answer questions first in a jupyter notebook, commit to http://github.com/cal-itp/data-analyses
* Review w/ Ruth, determine which dashboards they might go in
* Put up metric views for them into the warehouse
* Add to metabase dashboards

**Comment by mcplanner** [comment]
First round complete! On to Ruth to define follow up questions.

https://nbviewer.jupyter.org/github/cal-itp/data-analyses/blob/96487901cd3d8727a0639136b3a2223ee8258462/juniper_report_questions/juniper_gtfs_schedule.ipynb

**Comment by machow** [comment]
Note that the current version of the report is viewable here in github:

https://github.com/cal-itp/data-analyses/blob/main/juniper_report_questions/juniper_gtfs_schedule.md
