### ISSUE TITLE
GTFS Data: update Torrance Transit RT feeds

### ISSUE THREAD

**Issue by o-ram** [cal-itp/data-infra#1925]
Update `agencies.yml` in order to update our RT feeds for Torrance. Torrance uses our Cal-ITP API key like other Swiftly feeds.

Update the following gtfs datsets:

- https://api.goswift.ly/real-time/torrance/gtfs-rt-alerts
- https://api.goswift.ly/real-time/torrance/gtfs-rt-trip-updates
- https://api.goswift.ly/real-time/torrance/gtfs-rt-vehicle-positions

## Checklist

- [ ] Manually made sure any new feeds have `itp_id`s that are not duplicative
- [ ] Mannually confirmed URIs are valid (to be automated in future per #908)
- [ ] Made sure the Airtable database has consistent information

**Comment by evansiroky** [comment]
I have asked @aly-medina to work on this, so she may be publishing a PR soon.

**Comment by evansiroky** [comment]
See https://github.com/cal-itp/data-infra/pull/1920
