### ISSUE TITLE
Add file row number to GTFS Schedule CSV to JSONL conversion

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#1927]
**Is your feature request related to a problem? Please describe.**
Right now, we do not have the ability to deterministically flag duplicates in GTFS Schedule data. For example, if we have a given trip record with a duplicate ID, we can assume that the "order" of records in BigQuery is the same as the original file but we don't actually have a column that indicates the order in the original CSV.

**Describe the solution you'd like**
Add a `_FILE_ROW_NUMBER` in the unzip/convert job, to mirror the `_FILENAME` provided by BigQuery.

**Describe alternatives you've considered**
No alternatives are provided natively, as best I can tell.

**Additional context**
I think this is important for data lineage as well as cleaning/testing in dbt.

**Comment by atvaccaro** [comment]
This was deployed in https://github.com/cal-itp/data-infra/pull/2121 but no backfill has been run.

**Comment by j-meelah** [comment]
This has been addressed
