### ISSUE TITLE
Planning out GTFS RT loading / end products

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#197]
@hunterowens, @lottspot has extracted several hours of GTFS RT data to `gs://gtfs-data/rt`. I figured this issue could be a good place to bubble back up current planning docs for GTFS RT data outcomes, and planning how to get there.

Existing issues:

* https://github.com/cal-itp/data-infra/issues/38
* https://github.com/cal-itp/data-infra/issues/16
* https://github.com/cal-itp/data-infra/issues/145:one is number of realtime feeds.
* https://github.com/cal-itp/data-infra/issues/11: what is realtime uptime for a given GTFS RT feed?

Main questions I have:

* Is the first deliverable here a metabase dashboard? Can we spec a list of questions that would be useful for it to answer? [Ruth's Juniper questions doc](https://docs.google.com/document/d/1uu_CxSEoV5sUxSGFSGu2iuunMEHVY5mPlBzeogOIxWE/edit?ouid=104768584258452876474&usp=docs_home&ths=true) is a good example of questions for a dashboard to answer.

**Comment by hunterowens** [comment]
Hey! 

Let me know if you have any questions but the next steps in my mind are

1) Unpack the proto files into parquet, which then can be used as an external table in bigquery for analysis 
2) run the validator in batch mode adn store the validator results for GTFS GT 
3) New Issue: Add GTFS-RT data to reports 

I'm sure @mcplanner will have a bunch of ideas here when she is back!

**Comment by mcplanner** [comment]
I do have ideas! Is this the same as defining what goes into the Juniper reports (reports.calitp.org)? Or something broader? Or something experimental to make sure it works?

**Comment by machow** [comment]
I think the big remaining piece was addressed by your list of questions:

https://github.com/cal-itp/data-infra/issues/205

We can make sure that everything is loaded in a way that facilitates answering them / explicitly discuss when the size of the data might make answering some harder than others.

**Comment by machow** [comment]
@hunterowens can you say a bit about the most CALITP is looking paying monthly for storing RT data?

**Comment by hunterowens** [comment]
my hope is that we can process all the files and the cost of storing the observations long term in either parquet or BQ isn't that high? I did some back of hand math somewhere but cannot find it at the moment.

**Comment by cvc5185** [comment]
@machow and the rest of the team - dropping some GTFS-RT resources that I found below!

### GTFS-RT Resources
- [Google Realtime Overview](https://developers.google.com/transit/gtfs-realtime/guides/feed-entities)
- [Google GTFS-RT Feed Examples](https://developers.google.com/transit/gtfs-realtime/examples)
- [Google Realtime Reference](https://developers.google.com/transit/gtfs-realtime/reference)
- [MobilityData GTFS Realtime Resource Center](https://gtfs.mobilitydata.org/spec/gtfs-realtime)
- [MobilityData GTFS Realtime Best Practices](https://gtfs.mobilitydata.org/best-practices/gtfs-realtime)

### Transit Feeds
- [Open Mobility Data aka Transit Feeds - GTFS/GTFS-RT feed aggregator](https://transitfeeds.com/)

### CUTR GTFS-RT Validator Resources
- [Introducing the GTFS-Realtime Validator (CUTR Medium Article)](https://barbeau.medium.com/introducing-the-gtfs-realtime-validator-e1aae3185439)
- [CUTR RT Validator Webapp Readme](https://github.com/CUTR-at-USF/gtfs-realtime-validator)
- [CUTR Batch RT Validator Readme](https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/gtfs-realtime-validator-lib/README.md#batch-processing)
- [CUTR - Transit Feed Quality Calculator](https://github.com/CUTR-at-USF/transit-feed-quality-calculator)
- [CUTR GTFS Realtime Validator - Implemented Rules](https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/RULES.md)

### GTFS-RT Libraries & Software
- [GTFSR_kit - python library for processing GTFS-RT data](https://github.com/mrcagney/gtfsr_kit)
- [TheTransitClock - Open source real-time transit arrival prediction software](https://thetransitclock.github.io/)

**Comment by machow** [comment]
Thanks @cvc5185--this is super helpful!

@hunterowens I'm anticipating a combination of...

* one of the vehicle positions feeds is ~200 kb. So ~200kb * 5,000 captures / day = 1 Gb / day. (for this 1 feed)
* whatever we use (e.g. parquet) will need to be a table for BQ, so may be larger than the protobuf file
* standard cloud storage is about $0.02 a Gb / month. Say we go 3x this feed, at 3 terabytes a year. After a year, it will cost $60 month to host. At 10 terabytes a year, it's about $200 / month after a year. Could archive data, etc.. to cut costs by an order of 10.

Note that this means a strategy for [not re-downloading composite feeds like GovCBus](https://github.com/cal-itp/data-infra/pull/173#issuecomment-862571006) is especially important.

I'll dig deeper and write up a breakdown of potential costs / strategies, but want to get a rough sense for constraints.

**Comment by hunterowens** [comment]
the largest GTFS-RT feed is probably Muni? 

[This notebook](https://nbviewer.jupyter.org/github/CityOfLosAngeles/atsac-etl-analysis/blob/master/notebooks/costs.ipynb) was done at my old job to estimate the cost of storing 40K sensors at 5 second frequnecies using parquet compression. Let's chat on monday about best long term storage ideas. But 200$ a month after a year doesn't scare me)

**Comment by evansiroky** [comment]
Closing as GTFS-RT data is being collected.
