### ISSUE TITLE
Bug: Metrolink download failing in both v1 and v2 pipelines even though it works in browser

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1989]
**Describe the bug**
We are getting `403` in both the v1  and v2 pipelines for Metrolink: `https://www.metrolinktrains.com/globalassets/about/gtfs/gtfs.zip`. However I am able to access the file via browser. 

I think it's an issue with `User-Agent`, but I can't figure out exactly what is happening. 

If I do this: 

```
r = requests.get(URL, headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4)"
            "AppleWebKit/537.36 (KHTML, like Gecko)"
            "Chrome/83.0.4103.97 Safari/537.36"
        )
    })
```

In Jupyter, it succeeds (these header values are [what we specify in v1 prod](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_downloader/download_data.py#L44-L50)). 

But when I run the [`download_url` function](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_downloader/download_data.py#L38) with a breakpoint, verifying that this header is set, I still get a `403`. 😢 

I can't figure out why. 

Here's `r.request.headers` from my successful request: `{'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4)AppleWebKit/537.36 (KHTML, like Gecko)Chrome/83.0.4103.97 Safari/537.36', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive'}`.

Here's the request headers for the unsuccessful request using `download_url`: `{'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4)AppleWebKit/537.36 (KHTML, like Gecko)Chrome/83.0.4103.97 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}`

I checked using `Accept-Encoding` = `'gzip, deflate'` locally and that still worked, and that's the only difference I see between the successful and unsuccessful requests.

**Comment by atvaccaro** [comment]
The 403 is coming from Cloudflare blocking non-browsers from accessing the file. We might be able to use selenium with some headless driver ([example](https://stackoverflow.com/questions/46920243/how-to-configure-chromedriver-to-initiate-chrome-browser-in-headless-mode-throug)) but I'm not sure what's easily doable in pod operators.

**Comment by atvaccaro** [comment]
I've flagged this to @evansiroky who is going to see if we have any contacts with the agency.

**Comment by lauriemerrell** [comment]
Issue stopped happening in January.
