### ISSUE TITLE
User Story: schedule & RT feed presence in Mobility Database

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#1999]
## User stories
---

### Summary

As a Cal-ITP team member, I want to understand whether a given transit provider's GTFS schedule and RT feeds are present in the [Mobility Database](https://github.com/MobilityData/mobility-database-catalogs), so that I can help them get the data added if not.

### Acceptance Criteria

I'm able to add checks for presence in the Mobility Database to the v2 guideline data models. I will default to Laurie and Andrew on the proper index table to use for this.
### Notes

I'm hoping this can be delivered by the end of January 2023.

### Tester [Stakeholder]

1. Scott

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by holly-g** [comment]
Closed by https://github.com/cal-itp/data-infra/pull/2177 and https://github.com/cal-itp/data-infra/pull/2177
