### ISSUE TITLE
Remove outdated Tulare feed from agencies.yml

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2006]
Tulare County (ITP ID 346)’s https://data.trilliumtransit.com/gtfs/tcat-flex-ca-us/tcat-ca-us.zip feed is listed as historic in Airtable, but is still present in agencies.yml. Per conversation, we can remove it from agencies.yml.

**Comment by atvaccaro** [comment]
No longer relevant, agencies.yml is frozen/deprecated
