### ISSUE TITLE
GTFS-RT implement deployment / re-deployment process

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#202]
@lottspot, do you mind filling in with next steps? Seems like the keys are...

* handling updates to RT extraction script
* handling updates to agencies.yml
* describing steps for automating through GH actions

**Comment by lottspot** [comment]
Any changes to the archiver script (gtfs-rt-archive.py) need to be followed by a typical 2 stage build/deploy process. #226 includes resources and documentation to build and deploy the archiver script onto the kubernetes cluster. The steps captured in this documentation next need to be implemented as GH actions.

**Comment by lottspot** [comment]
Before we can really automate the deployment of changes, we have to settle on a release flow. I've sketchd one out below which I think would work well for this case, which is essentially broken into a 2 stage process:

### 1. builds

1. Push a tag (probably best delineated by gtfs-rt-archive/${VERSION})
2. Perform an image build from the tagged commit
3. Create a request for a release into prod

### 2. releases

1. Approve release of a specific build into the release environment
2. Update release environment configuration to point to approved build
3. Apply release environment config changes back to main branch
4. Rollout approved build into release environment

**Comment by machow** [comment]
The build process LGTM. For release, does this make sense?:

* data updates: agencies.yml file changes. Because this is loaded by the container at run time, it **requires a restart, but not a rebuild**.
* logic updates: the extraction script changes.  **Requires a build and release**.

I think any approach for releasing logic updates makes sense (e.g. committing a config, etc..). Will this separation work? I'm not sure if it's what you already had in mind, so wanted to double check!

**Comment by machow** [comment]
re-opening as this does not appear completed. There is no automation for restarting when agencies.yml is updated, so we have not updated the GTFS RT process for who knows how many months?

**Comment by lottspot** [comment]
Released in #425
