### ISSUE TITLE
Define Scope of TransitStacks Database

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#204]
From talking w/ @e-lo and @cvc5185 . [Doc with 3 categories of questions here](https://docs.google.com/document/d/1e0KQ3kmNt8zJvjUhSmuRIuy0h4tEFwPz0kfqQWZjBkQ/edit?usp=sharing).

Here's a plot from Charlie counting compnents leading to human transactions:

![image](https://user-images.githubusercontent.com/2574498/126192514-cd77613c-aa15-4bed-8f3c-99fd141722f2.png)

**Comment by mcplanner** [comment]
Next steps: define scope of the Transit Stacks database.
* what are we storing
* for whom
* where/how
* what will we want to query?
* where do we want the results of those queries to live (accessible to who from where)?
