### ISSUE TITLE
User Story: mart tables for base schedule tables for analysts

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#2043]
## User stories

A user story is implemented as well as it is communicated.
If the context and the goals are made clear, it will be easier for everyone to implement it, test it, refer to it.

---

### Summary

A user story should typically have a summary structured this way:

As an analyst, I want a pre-joined table for GTFS schedule data for the most common tables so I have an easy way to access assembled tables in a standardized way (rename these mart tables if needed): 
- [ ] `feed_key` to `organization name`: new under v2 warehouse
- [x] `trips`
- [x] `shapes`
- [x] `stops`
- [ ] `stop_times`...maybe..?

### Acceptance Criteria

This is something that can be verified to show that this user story is satisfied.

**Example:**

* [gtfs_utils for v2](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/gtfs_utils_v2.py)
* [Sample dbt SQL](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/dbt_for_gtfs_utils_v2.sql) -- I tried writing this similar to what I saw in `dbt-docs`, so hopefully it's mostly there? @lauriemerrell 

Also, here are a few points that need to be addressed:

### Notes

* could these incrementally updated everyday?
* https://github.com/cal-itp/data-analyses/pull/570

### Tester [Stakeholder]

1. @tiffanychu90 

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by holly-g** [comment]
Hi @tiffanychu90 , thanks for submitting this ticket! We'll tee this up for our next sprint (12/13 - 12/23). 
@lauriemerrell / @charlie-costanzo will reach out for a brief call with you to ask some clarifying questions before this gets picked up in the next sprint.

**Comment by lauriemerrell** [comment]
Notes from scoping conversation with @tiffanychu90 and @charlie-costanzo : https://docs.google.com/document/d/1DJpRpvnCPXhwwDHbFuVtckRBI1TeUvQ7SinaeySGKlM/edit#

**Comment by charlie-costanzo** [comment]
Closed in favor of continuing the remaining table in #2145
