### ISSUE TITLE
Bug: spurious frequency entries

### ISSUE THREAD

**Issue by ansoncfit** [cal-itp/data-infra#2054]
**Describe the bug**
The frequencies table at https://data.ca.gov/dataset/cal-itp-gtfs-ingest-pipeline-dataset/resource/48542c8f-8ce1-43e3-a965-6c68771d6fe5 has frequency entries for `cal_itp_id`s 14 (anaheim-regional) and 154 (laguna-beach-municipal-transit). But feeds at the corresponding `gtfs_schedule_urls` do not have frequency entries.

**Expected behavior**
Entries for these agencies should not appear in https://data.ca.gov/dataset/cal-itp-gtfs-ingest-pipeline-dataset/resource/48542c8f-8ce1-43e3-a965-6c68771d6fe5.

**Comment by lauriemerrell** [comment]
Pretty sure that this is caused by #1184. Best fix will be to migrate open data publishing to v2 warehouse (#1940).

**Comment by SorenSpicknall** [comment]
The cumulative changes in #988, #1280, #2156, etc. that resulted in updated V2 publishing resolved this issue. The `_is_current` field correctly marks these spurious entries, which are not making it into publication anymore.
