### ISSUE TITLE
User Story: Create trip ID coverage analysis tables 

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2063]
### Summary

A user story should typically have a summary structured this way:

1. **As a** data analyst or data quality assessor
2. **I want** to be able to see information about which trip IDs appeared in schedule vs RT data
3. **So that** I can understand trip ID discrepancies between RT and schedule and perhaps show agencies detailed information about their coverage 

### Acceptance Criteria

- [ ] Incremental tables that summarize a trip ID's presence in each type of RT data by day:
   - [ ] For vehicle positions, first and last message times / count of messages
   - [ ] For service alerts, distinct message text?, distinct cause/effect?, count of messages?
   - [ ] For trip updates, schedule relationship, perhaps max delay?, number of cancelled stops?, count of messages?

### Tester [Stakeholder]

1. @natam1 
2. Maybe @owades for the trip ID alignment guideline check

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
3. - [ ] Team understands acceptance criteria
4. - [ ] Team has defined solution / steps to satisfy acceptance criteria
5. - [ ] Acceptance criteria is verifiable / testable
6. - [ ] External / 3rd Party dependencies identified

**Comment by owades** [comment]
Yes please!

**Comment by lauriemerrell** [comment]
I'm going to call this completed based on `fct_observed_trips`, which doesn't do the comparison with schedule but has a key to enable that join. There is also separate issue #2685 for the comparison functionality
