### ISSUE TITLE
Recreate payments_rides Metabase questions with new warehouse tables

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#2074]
In #1876 we moved some payments dashboard queries from Metabase into the warehouse as tables, but have yet to recreate the questions in Metabase with those new tables.

* Recreate payments_rides questions in Metabase with new warehouse tables

**Comment by atvaccaro** [comment]
I think specifically we want to implement on top of the new v2 tables

**Comment by charlie-costanzo** [comment]
Closing as this has been completed in metabase
