### ISSUE TITLE
Dashboard to compare between v2 and v3 archivers 

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#2075]
Most of #1895 was completed in #2057 except for the final requirement, which involved creating a dashboard to compare between the v2 and v3 archivers 

* Create a new Metabase dashboard to compare between the v2 and v3 archivers, only focusing on file presence, not creating new tables for v2 archiver for comparison

**Comment by atvaccaro** [comment]
I don't think we need this anymore now that we're fully migrated, but willing to re-open if it proves relevant to backfill discussions.
