### ISSUE TITLE
add "Fare Type" to each payment record in payments

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#208]
Currently, we don't have what type of fare was paid for each trip. We should add that 

For each row in `mst_ridership_materialized`, we should add whether the trip was of the following types 

`single_fare` = a single, 2 tap full fare 
`penalty_fare` = fare charge when tap off was not performed
`daily_cap` = a trip that was daily capped or part of a series of trips that had a daily cap
`monthly_cap`= the same as above, but for the monthly cap~!

**Comment by machow** [comment]
Let's close and add to the current batch of payments issues if needed.
