### ISSUE TITLE
Enable two factor authentication for Sentry

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2142]
Currently two factor authentication is not enabled for Sentry. We should enable it.

**Comment by atvaccaro** [comment]
We may just want to switch over to OAuth via GitHub and avoid any password-based auth.

**Comment by atvaccaro** [comment]
This is done; 2FA is available in Sentry but we already have forced 2FA on GitHub and OAuth via GitHub is now enabled for everyone on Sentry.
