### ISSUE TITLE
Run GTFS Schedule validator on LAX FlyAway (downloaded .zip)

### ISSUE THREAD

**Issue by mcplanner-zz** [cal-itp/data-infra#220]
We're talking with the managers of the LAX FlyAway shuttle. They produce GTFS, but it's not easy to automatically download. It lives here in [Box](https://cloud1lawa.app.box.com/s/oldkeg2ykj6c9pxj3ysq15ndngmsdw55).

1) Can we download this and make it part of our automated reports?
2) If not, can we create a one-off report on the attached version to send to the data provider? [LAX Flyaway.zip](https://github.com/cal-itp/data-infra/files/6865672/LAX.Flyaway.zip)

**Comment by hunterowens** [comment]
I think there has got to be a way  to find the true download URL / stable URL with Box. If not, we can put somewhere and generate but less preferable.

**Comment by hunterowens** [comment]
I will dig into this today!
