### ISSUE TITLE
Create fact validation outcomes

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#2214]
**Is your feature request related to a problem? Please describe.**
Right now there's only a daily validation notices table, which I am modifying to exclude errored validations per @lauriemerrell's request.

**Describe the solution you'd like**
We should have an "outcomes" fact separate from the underlying notices and should be based on actual executions and no interpolation.

**Describe alternatives you've considered**

**Additional context**

**Comment by j-meelah** [comment]
Not aware of a current need, can reopen if necessary
