### ISSUE TITLE
User Story: aggregated GTFS schedule service hours by month-day_type-time_of_day

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#2234]
## User stories
---

### Summary

As an analyst, I want to be able to grab aggregated GTFS schedule service hours for a month.  I want to be able to calculate metrics like `average PM peak service hours` for operator X in January 2023.

### Table Schema
* Grain: `feed_key-shape_id-month-year-day_type-time_of_day`
* Timeframe for table: `Dec 2022`
* Day Type: `weekday`, `saturday`, `sunday` 
* Time-of-Day: `owl`, `early am`, `am peak`, `midday`, `pm peak`, `evening` 
* Calculations needed: sort `trips` into time_of_day bins based on trip's first departure time.
* Identifier columns: `feed_key`, `name`, `shape_id`, `route_id` + `route_short_name` or `route_long_name`
* Date columns: `month`, `year`, `day_type`, `time_of_day`
* Metric columns: `service_hours`, `n_trips`, `n_days`
* Notes: 
   * keep `shape_id` for flexibility to merge in geometry -- though, we brainstorm whether having it at `route`-level would limit our flexibility   
   * skip holiday categorization for now...may need Saturday vs Sunday breakdown, and storing `n_holidays` across all these is extraneous - holiday consideration can sit better in `data-analyses`
   * leave off summing up `all_day` and `peak` - maybe that sits better in `data-analyses`

Initial context: https://github.com/cal-itp/data-analyses/issues/512

### Tester [Stakeholder]

1. @tiffanychu90 

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by lauriemerrell** [comment]
Closed in #2275

**Comment by tiffanychu90** [comment]
**Changes to `ad_hoc` table**

## New table schema
* Grain: **(edits, drop shape_id)** `source_record_id/gtfs_dataset_name-route_id-month-year-day_type-time_of_day`
* Timeframe for table: Dec 2022
* Day Type: **(keep as is)**, with `day_type` for each day of week is fine for analysts to aggregate to weekday/sat/sun, and might be better left more granular
* Time-of-Day: **(keep as is)** owl, early am, am peak, midday, pm peak, evening
* Calculations needed: **(keep as is)** sort trips into time_of_day bins based on trip's first departure time.
* Identifier columns: **(edits, drop shape_id)** `source_record_id, name, route_id + route_short_name `
* Date columns: **(keep as is)** month, year, day_type, time_of_day
* Metric columns: **(edits, add service hours summation)** `service_hours`, `n_trips`

Summary of changes:
* `shape_id` was hard to use at an aggregated level to reattach with onto a selected day's `feed_key-shape_id-pt_array`
* Decide that summary of aggregated service hours can happen at the route-level
* Will request new table for the monthly equivalent of `fct_daily_scheduled_shapes`. If an analyst wants to use monthly `service_hours`, they still need to find a way to narrow down all the possible `shape_ids` to represent that line geometry. It would make sense to probably just select the `shape_id` that was valid for the most days that month.
