### ISSUE TITLE
Update Metabase dim_ntd_agency_info NTD Data to 2021

### ISSUE THREAD

**Issue by juliama0780** [cal-itp/data-infra#2235]
Update `dim_ntd_agency_info` to 2021 data. The NTD dataset is this [dataset](https://dashboards.calitp.org/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjI0NTJ9fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) in Metabase.

We will be demo-ing the GTFS Features dashboard mid-February and would appreciate an update from the 2018 data to 2021 data, from [this file.](https://www.transit.dot.gov/ntd/data-product/2021-annual-database-agency-information)

**Comment by atvaccaro** [comment]
Discussed this during sprint planning. Going to implement a very minimal loader, save a few years of data to GCS, and make available in the warehouse via external tables. Not going to automate anything or load other datasets yet, but should provide a pattern for future work.
