### ISSUE TITLE
SMTP for Metabase

### ISSUE THREAD

**Issue by themightychris** [cal-itp/data-infra#225]
Metabase needs to be configured with an SMTP server in order to be able to send new account invitations and password reset emails (and to use its pulses / dashboard notification features)

This article appears to confirm that GCP does not offer any managed SMTP service we could use, and points at a number of 3rd-party managed SMTP providers: https://cloud.google.com/compute/docs/tutorials/sending-mail#choosing_an_email_service_to_use

We tend to recommend using [Postmark](https://postmarkapp.com/) for this -- should we go ahead and set up an isolated account that could be handed off later?

@hunterowens @thekaveman -- is there a preference or existing resource for a different solution at DOT or one of the other teams we should use instead?

**Comment by hunterowens** [comment]
Postmark sounds good! would we exceed the free tier?

**Comment by themightychris** [comment]
probably not, but we'll need *someone's* card on file and it'll be an operational dependence

**Comment by hunterowens** [comment]
great. Can you work with @thekaveman here to setup

**Comment by thekaveman** [comment]
Hi @themightychris - I think I'm waiting on your word for the next steps. LMK what I can do!

**Comment by themightychris** [comment]
@thekaveman I provided a couple options for moving forward in the original issue description, it's not clear to me who's call this is to make. 

I can go ahead and set up an isolated Postmark account under a Jarvus card and deal with transferring ownership later if that's the call

**Comment by thekaveman** [comment]
My bad @themightychris, I thought @hunterowens said to go ahead with Postmark and you needed our CC. Happy to deal with a transfer later if you want to set it up now.

**Comment by themightychris** [comment]
@machow @hunterowens @thekaveman I've set up a postmark account, it's ready to log in to and integrate with, but it is in "test mode" pending human review of the application I submitted

**Comment by machow** [comment]
Thanks! Is this issue completed?!

**Comment by themightychris** [comment]
oh yeah this is all done! The postmark login is in our shared BitWarden vault, emails come from `metabase@dashboards.calitp.org`
