### ISSUE TITLE
July Reports

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#227]
Creating a tracking issue for the July reports, once july has ended (in 4 days? Time flies)

**Comment by machow** [comment]
Read my mind--thanks! When do we want to send the reports out? Does the 6th (or even 9th) work? If so, I can...

* check @ryon's capacity to do some small style updates
* collect / review / write-up some of the improvements that have been proposed into one place
* estimate which pieces we could fit in by then (e.g. using feed_info to calculate whether a feed is expired is not in the warehouse, but was calculated for #192, so could be slotted in fairly quickly).

**Comment by mcplanner** [comment]
Would August 2 be feasible? (The first workday of the month).

This is the only bug I see with the current reports that I know to be
blocking. What else?

https://github.com/cal-itp/data-infra/issues/219

**Comment by machow** [comment]
Some of these can be handled async. My main goal in listing here is to check whether it's worth collecting these kinds of issues / addressing some before next release.

* reports do not get generated if an agency does not have a feed_info.txt
* you and Hunter prefer different metrics for the service hours plot (switched to sum-total of hours across running trips at his request)
* days feed expired calculation is currently this: sum days where service hours are 0
* may be useful to review this [human readable validator error spreadsheet](https://docs.google.com/spreadsheets/d/1GDDaDlsBPCYn3dtYPSABnce9ns3ekJ8Jzfgyy56lZz4/edit#gid=0) to ensure we summarize in the way you want. For example, are you okay with these 200 details being individually reported?

![image](https://user-images.githubusercontent.com/2574498/127189853-05065737-0da6-4b42-a241-2dcb76a2e6d0.png)

**Comment by mcplanner** [comment]
- I was not aware that reports weren't getting generated if there's no
   feed_info.txt. Thank you for flagging that. Should that be a separate issue
   we can track?
   - I defer to Hunter's metric for service hours. If that's the only issue
   on this one, we can close this one.
   - What can I do to help clarify the "days feed expired" item? A short
   term fix would be to change the name to accurately reflect what's being
   shown, but longer term it should reflect days when there wasn't a valid
   feed based on start/end date. Also, would this be helpful to track with its
   own ticket?
   - I don't think I understand this last point. What 200 details? Is there
   one that looks especially unwieldy?

Thanks,

**Comment by machow** [comment]
Ah, I'm not sure if it came through on email, but I linked an image of validation errors in this report: https://reports.calitp.org/gtfs_schedule/2021/06/269

It sounds like the pieces I listed should be okay w/ quick fixes, so August 2nd should work! Can we push it back a day to August 3rd? That'll let me make sure everything generates with the new data.

**Comment by machow** [comment]
Here's the issue for feed_info not generating reports, and a new one for expired days:

* https://github.com/cal-itp/reports/issues/26
* https://github.com/cal-itp/reports/issues/27

I can use this current issue to track the quick fixes and deploying new reports!

**Comment by hunterowens** [comment]
@hunterowens to close once it has been emailed. 

otherwise, July reports are up!
