### ISSUE TITLE
New Team Member - Samantha Lewis

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#2273]
Name: Samantha Lewis
Role: Research Data Analyst II (temporary assignment)
Reports to: Evan Siroky

Google Workspace Email Address: samantha@calitp.org
GitHub Username: @SLewis1120
Slack Username: Samantha

**Set-up:**
- [ ] Technical Onboarding call scheduled

- [x] Added to tools:
  - [x] Github
    - [x] Organization: Cal-ITP
    - [x] Team: warehouse-users
  - [x] JupyterLab
  - [x] Google Cloud Console
  - [x] Metabase
  - [x] Slack

- [ ] Added to meetings:
  - [ ] Analyst Round Tables (Tuesday & Thursday)
  - [x] Lunch n' Learn
  - [ ] All-hands

- [x] Added to Slack channels:
  - [x] #data-analyses
  - [x] #data-office-hours
  - [x] #lunch-n-learn
  - [x] #data

**Comment by thekaveman** [comment]
I created the calitp.org account, and added the DOT account to Slack.

**Comment by holly-g** [comment]
Added samantha@calitp.org to GCP
