### ISSUE TITLE
Research Question: Importance of GTFS-Flex

### ISSUE THREAD

**Issue by e-lo** [cal-itp/data-infra#228]
Journey-planning applications have asked for some data points to help prioritize GTFS-Flex capabilities.  Some data points which would help demonstrate the importance of demand-responsive transit:

1. Number of transit services which have demand-responsive transit
2. % of California (by area, pop, employment) not served by fixed-route transit service
3. % of California served by demand-responsive transit
4. Total ridership of demand-responsive transit services

## Priority
Med-high: This will feed into [unnamed journey planning application]'s prioritization process.  There isn't a specific deadline so much as "as soon as we provide the data, they can start the process that will then start a process.

## Data Sources

- Population: [census] 
- Employment: [LODES](https://lehd.ces.census.gov/data/#lodes)
  - [Data dictionary ](https://lehd.ces.census.gov/data/lodes/LODES7/LODESTechDoc7.5.pdf) 
    - total jobs is S000_JT00 but could want to split up later and look at minority jobs
  - [Metadata to reference in analysis](https://lehd.ces.census.gov/data/lodes/LODES7/ca/version.txt)
  - [dataset](https://lehd.ces.census.gov/data/lodes/LODES7/ca/wac/ca_wac_S000_JT01_2018.csv.gz) for workplace location for all jobs in 2018
  - [geography crosswalk](https://lehd.ces.census.gov/data/lodes/LODES7/ca/ca_xwalk.csv.gz)
- demand-responsive and fixed-route operators: 
  -   Transit Provider db with NTD data linked
  -   Hunter's previous research? 
- Geographic areas: combo of stops.txt from all GTFS files with 1/4 or 1/3 mile buffers
- Ridership:
  -   Transit Provider db with NTD data linked
  -   Hunter's previous research?

**Comment by hunterowens** [comment]
[previous report and research](https://github.com/cal-itp/paratransit-eligibility-reports)

**Comment by machow** [comment]
@hunterowens and @Nkdiaz to pair. Key questions:

* where does the data for this question live right now?
* where will we put the results?
* can we produce snippets on the following...
  - calculating % of california
  - calculating whether a service has demand-responsive transit
  - e.g. X from this data, Y from that data, combined in this way

**Comment by hunterowens** [comment]
to do this, we'll need a final dataset that looks something like this 

| census_tract_geoid | has_demand_responsive | has_fixed_route | population | jobs | area |
| - | - | - | - | - | - | 
| xxx | True | False | 10 | 1 | 10M2 |

this will require 3ish datasets. 

1. Census Tract Population  / Jobs Numbers for all of CA 
2. A list of tract with fixed route service - join the stops dataset to tract geometeries, assume all that have a stop have fixed route service 
3. A list of tracts with DR service. TAke the City / County fields from the Transitstacks / NTD HQ data, assume the DR provider services the entirity of that geog. join to the state geoportal dataset, simplify into a single geometry, take the centroid of the tract, point in polygon insersect that to the tracts dataset to get "has_DR"

**Comment by hunterowens** [comment]
@hunterowens to link census datasets here for @Nkdiaz

**Comment by hunterowens** [comment]
[data](https://data.census.gov/cedsci/) - you'll want 3 year ACS tract level population estimates. 

@e-lo linked to the LODES employment statistics by tract in the issue description

**Comment by machow** [comment]
For data team meeting (from pairing w/ @Nkdiaz):

* Is this the data we want? (ACS 5 year demographic and housing info): https://data.census.gov/cedsci/table?q=United%20States&tid=ACSDP5Y2019.DP05
* here's an [api link for that data](https://api.census.gov/data/2019/acs/acs1?get=NAME,B01001_001E%22)

Intermediate next step:

* calculate population per geoid using census data
* fetch lodes data linked up top, calculate jobs per geoid

Final piece:

* Join census with stops (so we have a geoid associated per stop)
* Sync w/ Michael to check
* (Natalya TODO): Layout how to finish `has_demand_responsiveness`, `has_fixed_route`

**Comment by machow** [comment]
From pairing w/ @Nkdiaz, I just remembered that R has a very nice census library called `tidycensus` (as I recall, python's census lib is a bit more low level). Here is an R script for pulling out the data in the format @hunterowens listed above.

May need to tweak the variables we grab (I just grabbed a couple to fill in)

```R
library(tidycensus)
library(tidyverse)

census_api_key("<API_KEY_HERE>")

# uncomment this to see possible variables to load
load_variables(2019, "acs5", cache = TRUE) %>% View()

# get ACS data. modify variables argument to get additional measures
# we'll transform them to wide format so each variable will be its own column
tracts <- get_acs(
  geography="tract",
  state = "CA",
  year = 2019,
  variables = c(ttl_population = "B01003_001", ttl_jobs = "B24011_001")
)

wide_tracts <- tracts %>% select(-moe) %>% spread(variable, estimate)

wide_tracts %>% write_csv("calitp_acs5_tracts.csv")
```

**Comment by machow** [comment]
In order to calculate `has_fixed_route` that Hunter lists above. We need to do the following...

* get data from this google sheet https://docs.google.com/spreadsheets/d/105oar4q_Z3yihDeUlP-VnYpJ0N9Mfs7-q4TnribqYLU/edit#gid=471807468
* Use the `Modes` column to figure out if they have "DR" (for now, just check that DR is one of the modes listed)
* Use the `City` and `County` columns to map back to census data.

**Comment by machow** [comment]
@e-lo for this piece...

> Total ridership of demand-responsive transit services

Where do total ridership numbers come from? Is it somewhere in transitstacks?

**Comment by machow** [comment]
Blocked until the data source for demand responsive provider info is provided. See [this slack thread](https://cal-itp.slack.com/archives/C01FNDG1ZPA/p1632321514071200).

**Comment by machow** [comment]
Here is the notebook Natalya worked on for this: https://github.com/cal-itp/data-analyses/blob/main/gtfs_flex_research_questions/calitp_flex_research_demand_responsive.ipynb

**Comment by machow** [comment]
The draft of this analysis is completed--let's wait until other needs to re-open

**Comment by tiffanychu90** [comment]
@Nkdiaz: With the notebook, I see a couple of datasets that could be documented in `intake`:
- [ ] CA census tracts (we have some versions of this with population), so let's decide on a version and stick with it
- [ ] CA cities
- [ ] CA counties
- [ ] LODES/LEHD (with this version and one from the bus_service_increase analysis, let's pick a version and document it)

The demand responsive data is fairly analysis-specific....but it comes from a Google Sheet and not our warehouse? If It's not elsewhere in the warehouse and this is a canonical source, then maybe it should either live in the warehouse or a GCS bucket and documented in `intake`
