### ISSUE TITLE
Feature Request: Add Vendor Name Column from Airtable's Product Tab to Dim_Products

### ISSUE THREAD

**Issue by natam1** [cal-itp/data-infra#2294]
**Is your feature request related to a problem? Please describe.**
In the current warehouse, to get the vendor name that a transit service is using, we have to go through `dim_contracts` instead of `dim_service_components` to get the information which is causing us to miss some of the vendors that are being used by services. Even when we do use `dim_service_components`, we have to go through `dim_contracts` to get the Vendor Name/ID. We would like to show the Vendor Name instead of the different products vendors offer to transit services. 

**Describe the solution you'd like**
Add in Vendor Name to Dim_Products from the same source Airtable Products Tab to map the vendor name easier 

**Describe alternatives you've considered**
A bridge with vendor component and vendor name 

**Additional context**

**Comment by lauriemerrell** [comment]
Just for reference, it looks like only 270/309 (87%) products have a vendor specified:

![image](https://user-images.githubusercontent.com/55149902/220758698-3f4aca28-f7b6-48a3-9afe-d1a9bc552da9.png)
