### ISSUE TITLE
Create service-level guidelines check for has RT/schedule

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2311]
Per discussion on #2304, we need to make sure that organizations and services without GTFS data have some discrete check that they fail that makes it obvious that they don't have GTFS data. 

We should add four new service-level checks for:

- Has schedule
- Has VP
- Has TU
- Has SA

**Comment by owades** [comment]
We have this at the feed level for the RT feeds, in int_gtfs_quality__rt_feeds_present. Can this just roll up to the service level?

**Comment by lauriemerrell** [comment]
I think that check is slightly different, at least as currently implemented -- right now it's checking against the universe of RT URLs, and checking whether there were **files** present from the URL (so, given a URL, did we get any data). 

The proposal here would be whether a URL even exists (given a service, does it have an RT URL).

**Comment by owades** [comment]
Cool cool cool, got it!

**Comment by owades** [comment]
@lauriemerrell I can take this on tomorrow if you'd like.

**Comment by lauriemerrell** [comment]
@owades that would be great thank you! I got caught up in a bug investigation yesterday, I am still focused on #2327
