### ISSUE TITLE
Bug: automatically fetched dbt-bigquery version in precommit config causes errors

### ISSUE THREAD

**Issue by SorenSpicknall** [cal-itp/data-infra#2316]
**Describe the bug**
Version 1.4.0 of [dbt-bigquery](https://pypi.org/project/dbt-bigquery/) introduced breaking changes to various error classes referenced under dbt.exceptions, [including `CompilationException`](https://github.com/dbt-labs/dbt-bigquery/pull/460/files). Currently, our precommit config [brings in the latest release of that package by default](https://github.com/cal-itp/data-infra/blob/main/.pre-commit-config.yaml#L37) for use by sqlfluff 1.4.1, but the recent changes to dbt-bigquery break functionality. We need to reconcile the versions of sqlfluff and dbt-bigquery being used here, and possibly check elsewhere in the repo to futureproof against unsupported exception references.

**To Reproduce**
1. Make a change to a SQL file covered by the sqlfluff-linter precommit step.
2. Attempt to generate a commit.

**Expected behavior**
The precommit steps should be able to complete without internally erroring.

**Comment by atvaccaro** [comment]
fixed in https://github.com/cal-itp/data-infra/pull/2422
