### ISSUE TITLE
Data Quality Reports: add support for realtime data

### ISSUE THREAD

**Issue by mcplanner-zz** [cal-itp/data-infra#232]
[New queries are now in the Juniper mockup for real time data.](https://docs.google.com/document/d/1-iXNdl4f2EbYayKg3e7jkTALAcNzht9yGQuyIOtPLc4/edit?pli=1#)

Key metrics:
* Trip ID consistency between GTFS Schedule and Real time sources. Of all the trip IDs that appear in the GTFS Realtime feed(s), how many appear in the GTFS Schedule data? Note that mismatched IDs decrease the availability of updates for transit riders in trip planning applications.
* Feed availability. Is there a vehicle position, trip update, and service alerts feed?
* Average update frequency. Does it get updated every 20 seconds? More or less? 
* Fleet coverage. The guideline this references is evolving in the new version of the guidelines, so this is still being defined. It's something like "for all the trips that we expect to see in the GTFS-Realtime feed, how many are actually in the feed?". The open question is around "for all the trips that we expect", though it's likely just "what's in the GTFS Schedule" minus "what's been dropped in the Alerts feed".

**Comment by evansiroky** [comment]
Fixed in https://github.com/cal-itp/reports/issues/302
