### ISSUE TITLE
Sentry audit / bug bash

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2324]
Based on #2306, we realized we should get a better handle on the issues in Sentry & design a process for ongoing monitoring & maintenance. This ticket is for an initial investigation to:

- [ ] Review all open issues in Sentry and assess:
   - [ ] Number of tickets by type (RT Fetch exceptions vs. dbt failures vs. others)
   - [ ] Avg. volume of new vs. repeated issues over time (by week and longer term trend)
   - [ ]  Any open issues that seem concerning or unusual that merit specific attention
- [ ]  Based on review:
   - [ ]  Report back to the team on findings & turn any concerning issues into GitHub issues
   - [ ]  Make a recommendation on whether any alerting updates needed ex. are there issues that should alert more noisily or more frequently?
   - [ ]  Estimate how many hours per week it might take someone to monitor Sentry on an ongoing basis going forward
   - [ ]  Recommend a workflow for monitoring ex. when/why a Sentry issue gets turned into a GitHub issue

**Comment by atvaccaro** [comment]
https://docs.google.com/document/d/17GLW9b2PfOvTIukYl84zpaPbq1y6xCHmcK5kWO0jBO8/edit?usp=sharing

**Comment by atvaccaro** [comment]
I think this is done?
