### ISSUE TITLE
Payments: Create user guide for agency-facing dashboard

### ISSUE THREAD

**Issue by holly-g** [cal-itp/data-infra#2331]
### User Story

1. **As a** transportation planner at a transit agency
2. **I want** a user guide for the payments Metabase dashboard 
3. **So that** I will know how to effectively navigate and utilize the dashboard to get the information I need. 

### Acceptance Criteria

1. Uses [Cal-ITP branded slide deck template](https://docs.google.com/presentation/d/10J_VVuUv8QaQWI8d6QZhb2AgRVOhC0Jv/edit#slide=id.p3) 
2. Dashboard content/composition/utilization 
  a) Dashboard Metrics
3. Downloading Data from Metabase  
  a) Agencies have the option to download the raw data for applied uses in other data analytics platforms (e.g. Arc GIS / Tableau) 
4. Help Desk/Troubleshooting 
  a) Resetting password 
  b) Email contact: hello@calitp.org 

### Reviewer 

1. Ali Attari 
2. @jenro1 

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
6. - [x] External / 3rd Party dependencies identified

**Comment by charlie-costanzo** [comment]
draft slides available at:

[https://docs.google.com/presentation/d/1QjzzhcrWCrDTLkMnpr8sItpAswRMIXLq/edit?usp=sharing&ouid=110626321749510220581&rtpof=true&sd=true](https://docs.google.com/presentation/d/1QjzzhcrWCrDTLkMnpr8sItpAswRMIXLq/edit?usp=sharing&ouid=110626321749510220581&rtpof=true&sd=true)
