### ISSUE TITLE
Write better documentation for what dbt commands to run when setting up the project

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2333]
Right now [this section](https://github.com/cal-itp/data-infra/tree/main/warehouse#running-the-project-locally) does not give clear guidance on how best to initialize the dbt project for the first time. We should update this section to:
- [ ] Give a specific command that people should run when getting started 
   - [ ] This command should include `dbt seed`, which is not currently mentioned but which is now required for many models
- [ ] Link to resources about incremental tables to explain considerations if running for the first time in a long time.

**Comment by atvaccaro** [comment]
I think we can close this now; see https://github.com/cal-itp/data-infra/tree/main/warehouse#running-the-project-locally for updated language

**Comment by atvaccaro** [comment]
Actually we probably still need incremental docs.

**Comment by atvaccaro** [comment]
I think this is covered now but new docs
