### ISSUE TITLE
User Story: please remove GTFS Data Issue Template

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#2349]
### Summary

1. **As a** airtable data analyst
2. **I want** have a good set of options for feature template that make sense
3. **So that** I don't pick a issue template that is no longer relevant

### Acceptance Criteria

**Example:**

1. If I look at the issue templates
1. I should not see the GTFS Data Issue Template anymore

### Notes

I, @evansiroky created this issue to demonstrate to @SLewis1120 how to create a GitHub issue.

### Tester [Stakeholder]

1. @evansiroky 

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by lauriemerrell** [comment]
This was fixed by #2445
