### ISSUE TITLE
Bug: issue in new version of int_gtfs_quality__scheduled_trips_in_tu_feed

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#2373]
**Describe the bug**
I started looking at examples where my version of the scheduled_trips_in_tu_feed passed and Laurie's new version failed, and here's the first fruit of that investigation.

I think the counting and aggregation logic is causing some double-counting of observed trips.

When I look at the new version of `int_gtfs_quality__scheduled_trips_in_tu_feed`, for Commerce Municipal Bus Lines for 2023-02-04, I see the check failed because schedule has 112 trips while observed/tripupdates has 154 trips.

Logically this shouldn't be possible, since the query is left joining observed onto schedule - if they aren't equal, observed should be less, not greater.

I think the issue is that the aggregation logic is aggregating some duplicate rows, which double-counts trips. Admittedly I could go deeper into why there are duplicate rows, but I feel like Laurie can understand and/or explain this intuitively without an example. Let me know though, and I can go deeper.

An idea that I have to improve the `compare_trips` subquery is that, instead of the line:
`COUNTIF(observed_trips.trip_id IS NOT NULL) AS observed_trips,`
we could have the line:
`COUNTIF(observed_trips.trip_id IS null) AS missing_observed_trips,`

The check would pass if missing_observed_trips = 0, and fail if missing_observed_trips > 0

Here are the queries I used to confirm that both the schedule and trip updates feed showed 112 trip_id's on the given day:

```
SELECT count(distinct trip_id)  FROM `cal-itp-data-infra.mart_gtfs.fct_daily_scheduled_trips` t
LEFT JOIN `cal-itp-data-infra.mart_transit_database.dim_gtfs_datasets` d
ON t.gtfs_dataset_key = d.key
  AND CAST(t.service_date AS TIMESTAMP) BETWEEN d._valid_from AND d._valid_to
WHERE t.service_date = "2023-02-04"
AND d.base64_url = 'aHR0cHM6Ly9jaXR5Y29tbWJ1cy5jb20vZ3Rmcw=='
```
```
SELECT count(distinct trip_id) FROM `cal-itp-data-infra.mart_gtfs.fct_observed_trips` t
LEFT JOIN `cal-itp-data-infra.mart_transit_database.dim_gtfs_datasets` d
ON t.tu_gtfs_dataset_key = d.key
  AND CAST(t.dt AS TIMESTAMP) BETWEEN d._valid_from AND d._valid_to
WHERE t.dt = "2023-02-04"
    AND t.tu_base64_url IS NOT NULL
AND d.base64_url = 'aHR0cHM6Ly9jaXR5Y29tbWJ1cy5jb20vZ3Rmcy1ydC90cmlwdXBkYXRlcw=='
```

I did a spot-check and believe the 112 trips in each are the same trips.

**Comment by lauriemerrell** [comment]
Closed by #2375 (This issue does not exist in main)
