### ISSUE TITLE
missing AVTA GTFS

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#244]
From Cuong Trihn in D7 who is looping at the stops file for the purposes of the District 7 Active Transportation Plan.  Cuong is asking AVTA for their GTFS, I'll update this thread if he responds

the `agencies.yml` doesn't have AVTA (Antelope Valley Transit Authority). AVTA should have a GTFS / GTFS-RT file according to [this doc](https://www.avta.com/userfiles/files/Strategic_Plan_for_Integrated_Transportation_in_the_Antelope_Valley_120820.pdf)

From Cuong: 

I requested our student assistant to plot out the bus stops on a map and clip it for District 7 boundaries. From her analysis, it appears that there is a lack of complete data in areas served by Antelope Valley Transit Authority, which operates service in several cities and communities in northeast LA County.
 
![image](https://user-images.githubusercontent.com/1735650/128214858-60770837-a81a-46c6-b8a6-97c06fb7b4c1.png)

 

Nonetheless I’ve reached out to the transit agency to see if they can provide me such information. If I receive something, I can provide it to you to make updates.

**Comment by hunterowens** [comment]
thanks for the hot tip?  I guess we'll be in touch with them via the
assessment process.

**Comment by machow** [comment]
I'm going to close, since it sounds like the assessment process has a handle on this (feel free to reopen)
