### ISSUE TITLE
refactor payments ETL

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#245]
we need to refactor the payments ETL. 

Currently, each of the littlepay data feed daily exports are loaded into a bucket (`littlepay-data-extract-prod`) that has the following folders 

![image](https://user-images.githubusercontent.com/1735650/128222169-0f425f9d-e8e1-4770-9d9e-87ccba35bfd4.png)

each of these folders contains daily dumps that are updated daily when they are copied over from S3 to GCS. Currently they are loaded in as an external table. 

We should have this materialize and utilize a script that runs (python or other) that makes sure we are catching type conversion erorrs, etc. 

I've pushed a working branch to document these changes as `littlepay-etl-fix`

**Comment by machow** [comment]
This should be largely resolved by the new DAG setup. It still uses external tables, but does pre-processing to only keep columns specified in their schemas. Once an external table is used in a payments_views DAG view, it should indicate to us daily that the external table is in good shape.

https://docs.calitp.org/data-infra/datasets/mst_payments/#dags-overview
