### ISSUE TITLE
Handle tab-delimited data

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2484]
In #2465 and #2468 I suppressed tests on an Auburn feed that had some tab- (rather than comma-) delimited files. Ideally we should implement a more substantive fix for these files. Per [this Google doc](https://docs.google.com/document/d/15VwaDbp72hP69TWKM7LL3b31vxtrD5S_wsf_2-_PL34/edit#) we are evenly divided on whether it's preferable to try to just parse the tab-delimited files in the pipeline or whether we should suppress the null rows that result. 

We should assess the level of effort associated with each approach and pick one based on what is feasible right now.

**Comment by lauriemerrell** [comment]
Reopening because of #2567; initial fix approach did not work

**Comment by atvaccaro** [comment]
Re-opening until the backfill is performed.

**Comment by lauriemerrell** [comment]
This has been backfilled
