### ISSUE TITLE
Missing monthly report for Unitrans

### ISSUE THREAD

**Issue by mcplanner** [cal-itp/data-infra#250]
They're in the agencies.yml file, but not on reports.calitp.org.

**Comment by machow** [comment]
see https://github.com/cal-itp/reports/issues/26. Can you check whether it's the same for them?

**Comment by mcplanner** [comment]
Strangely, no it's not the same. Unitrans' feed_info has an email address.

**Comment by machow** [comment]
I downloaded and opened their data based on our current agencies.yml (`http://iportal.sacrt.com/GTFS/Unitrans/google_transit.zip`), and there is no feed_info file. Where are you seeing the feed_info file? (Different url?)

**Comment by machow** [comment]
Ah nice, thanks--because the data warehouse uses data as it existed at the time of publishing reports, it will not have a feed info file for last month. We should be able to generate reports for them once we resolve the issue of creating reports for feeds without a feed info file

**Comment by mcplanner** [comment]
Sweet
