### ISSUE TITLE
dbt test failures Sentry issue triage April/May 2023: Payments

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2500]
To resolve this ticket, inspect [all currently-failing dbt tests ](https://sentry.calitp.org/organizations/sentry/issues/?environment=cal-itp-data-infra&project=2&query=is%3Aunresolved+dbttestfail&referrer=issue-list&statsPeriod=14d)for *Payments data* and do one of the failing:

* Determine that the test is in some way erroneous and change its settings (ex. turn off, update test logic, downgrade to warning)
 * Determine that the test does represent a genuine problem or requires further investigation and make a ticket to fix the actual data/modeling issue (don't have to fix the issue itself to close this ticket but must make a ticket to prioritize and track its resolution)

**Comment by charlie-costanzo** [comment]
[tracking spreadsheet](https://docs.google.com/spreadsheets/d/16tNX56CgG2gXAMEQiVftFo3ldF3Ggn1TmwgcqSwTQjc/edit?usp=sharing)

Recommendations tl;dr:
* reduce alert thresholds for 10/12 alerts (all of which have bad rows that represent less than .05% of their total tows)(issue tk)
* The other two alerts are the same, just for the v1 and v2 pipeline, and should be investigated (issue tk)
  * `test_device_transaction_pairs_common_fields`
  * `validate_cleaned_device_transaction_pairs_common_fields`

**Comment by lauriemerrell** [comment]
Closing since investigation was performed, though there are still open failing tests from Payments data.
