### ISSUE TITLE
investigate `dim_organizations` versioning?

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#2508]
Placeholder issue to note that we may wish to investigate how often organizations are added/deleted/modified, or implement some sort of historical versioning for service components.

from @lauriemerrell about reports vendor info: https://github.com/cal-itp/data-infra/pull/2374

> I do think we might want a follow-up ticket to figure out the organization versioning here (probably low priority, I don't think that organization records get deleted often, but if a vendor changes names I think this logic would show the updated name.... That could maybe be desirable? But basically it just might be worth exploring further to confirm)

### Notes
I do think showing the updated name in the reports context would be desirable. Perhaps we can just see how it goes incorporating this info into the reports and only revisit if/when it becomes an issue

**Comment by lauriemerrell** [comment]
I don't think we've observed any issues from this, recommend closing @edasmalchi unless someone wants to look into it.
