### ISSUE TITLE
Create a gtfs schedule feed snapshot table (based on agencies.yml)

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#252]
Currently, we turn agencies.yml into a table (`gtfs_schedule_history.calitp_feeds`). It'd be useful to create a history table of changes to gtfs schedule feeds.

This will let us answer questions like...

* When do changes to gtfs_schedule_url occur?
* When is a new feed added? (i.e. new (calitp_itp_id, calitp_url_number) AND gtfs_schedule_url is not NULL ).
* When is a feed removed? (gtfs_schedule_url is NULL)
* Which feeds are the latest. E.g. currently in agencies.yml

## Proposal

**See [gtfs_schedule_history.calitp_files_updates](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_loader/calitp_files_updates_load.yml), for a place where we track changes. It calculates for each day a md5 hash, then compares it with the previous day (grouping by  itp_id, url_number, and file) to see when a file has changed in a feed.**

* tablename: gtfs_schedule_type2.calitp_feeds. One row per update of calitp_itp_id, calitp_url_number, gtfs_schedule_url
* columns:
  - calitp_itp_id, calitp_url_number, gtfs_schedule_url
  - calitp_extracted_at - date downloaded, calculated from _FILE_NAME
  - calitp_hash (of above columns)
  - calitp_extracted_at - marking when data was created
  - calitp_deleted_at - marking when data was removed (e.g. because it changed or was deleted)
* similar to other type2 tables, mark additions and deletions using a calitp_extracted_at, and calitp_deleted_at column.

The gist is that this table has entries for each URL we downloaded data from every day:

```SQL
SELECT 
   -- THESE ARE THE COLUMNS WE WANT TO CHANGE TRACK
   itp_id, url_number, gtfs_schedule_url,
   -- This is a weird, special bigquery column that tells us the file name. We need to parse calitp_extracted_at from it
   _FILE_NAME as fn
FROM `cal-itp-data-infra.gtfs_schedule_history.calitp_feeds`
```

![image](https://user-images.githubusercontent.com/2574498/128378012-3c14e68a-15f4-4c1b-8646-7dd8281a9197.png)

Note that the _FILE_NAME column has the DATE we need in it.

**Comment by machow** [comment]
Create columns

* is_latest - when `calitp_deleted_at` IS NULL
* exists_in_latest - calitp_itp_id and calitp_url_number exist in the latest data

TODO: 

Check [agencies.yml](https://github.com/cal-itp/data-infra/blob/main/airflow/data/agencies.yml)

* look up where a record was removed, and just double check that its exists_in_data is FALSE (e.g. [removed etran](https://github.com/cal-itp/data-infra/commit/b63f9ea3708ccc57a9c2566f77313d3d94a8a5fe#diff-504fdf3d4b2c7b3ed2d908d6440733807cf977552333d6140bae36cf5488924e))

Do some sanity checks in metabase

* barchart of counts for calitp_extracted_at
* barchart showing when a record was totally removed from agencies.yml (e.g. the max calitp_deleted_at for records that don't exist in latest).
* for each feed (itp_id and url number) how many modifications have been made? e.g. group by itp id and url number and count number of records.

Bonus: write a SQL query of how many feeds exist on each day

* either [fetch data for each day](https://docs.calitp.org/data-infra/warehouse/04_sql_snippets/#fetching-historical-data-for-specific-dates)
* OR use cumulative count summary in metabase (group by calitp_extracted_at)

**Comment by cvc5185** [comment]
- Verified: exists_in_data is FALSE for etran

<img width="734" alt="Screen Shot 2021-08-18 at 12 47 49 PM" src="https://user-images.githubusercontent.com/25835059/129939067-00294abe-748a-4ed5-9504-310e613a32f3.png">

Created Metabase views for each: [dashboard here](https://metabase.k8s.calitp.jarv.us/dashboard/13)

- "**Count by Cal Itp Extracted At**" - barchart of counts for calitp_extracted_at
- "**Records Totally Removed from agencies.yml**" - barchart showing when a record was totally removed from agencies.yml (e.g. the max calitp_deleted_at for records that don't exist in latest).
- "**Modifications by Feed**" - for each feed (itp_id and url number) how many modifications have been made? e.g. group by itp id and url number and count number of records.
- "**Number of Feeds Existing on Each Day**" (Bonus) - write a SQL query of how many feeds exist on each day using either [~~fetch data for each day~~](https://docs.calitp.org/data-infra/warehouse/04_sql_snippets/#fetching-historical-data-for-specific-dates) OR use cumulative count summary in metabase (group by calitp_extracted_at)

**Comment by machow** [comment]
Looks great--thanks! (Used while refactoring)
