### ISSUE TITLE
Define Quarterly Dashboard MVP

### ISSUE THREAD

**Issue by mcplanner** [cal-itp/data-infra#258]
Many of the queries in V1 [here](https://docs.google.com/document/d/13rRLy5Kd1OXsyB_hbUegIeARu45E6rwoc6H46_IS8rc/edit#) require databases that don't currently exist. Others may require additional effort.
To do: define the bounds of an MVP for a quarterly dashboard.

Part of #257 Quarterly Dashboard Epic

**Comment by machow** [comment]
Going to close, as it seems like the doc is the definition. Let's definitely sync if more is planned here
