### ISSUE TITLE
Store manually entered data for quarterly dashboard

### ISSUE THREAD

**Issue by mcplanner-zz** [cal-itp/data-infra#259]
The quarterly dashboard needs to track several datapoints that don't live in a database currently. For example, number of vendors with whom we're discussing GTFS-RT, or number of GRaaS implementations complete.

Many of these currently live in [spreadsheets](https://docs.google.com/spreadsheets/d/1uHqi-xbNioQBMfgVzC_-kN2B0LI-1e_a_FAWD72zhsE/edit#gid=0), where they're maintained by Cal-ITP staff. Determine if either these are appropriate for use with the quarterly dashboard, or if a new home is needed, build it.

Part of #257 Quarterly Dashboard Epic.

**Comment by machow** [comment]
One potentially useful note on the warehouse side. We can pretty quickly set it to download spreadsheets and make them into tables in the database daily.

So if a big challenge is avoiding fractionating, e.g. 

* metabase dashboard lacks manual calculations
* spreadsheet lacks automated ones,

we could include ingesting the manual spreadsheet and displaying some / all of its metrics in metabase

**Comment by machow** [comment]
See second tranche of planning for this work: https://github.com/cal-itp/data-infra/milestone/15
