### ISSUE TITLE
Bug: dim_stop_times_latest is failing in the publish script

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#2596]
**Describe the bug**
Publishing to CKAN has failed despite retries this week, specifically on `dim_stop_times_latest`. My assumption is that our data has grown to the point that the pod is getting killed because of memory consumption.

**To Reproduce**
See [these logs](https://o1d2fa0877cf3fb10p-tp.appspot.com/log?execution_date=2023-05-08T00%3A00%3A00%2B00%3A00&task_id=publish_california_open_data&dag_id=publish_open_data&map_index=-1)

**Expected behavior**
Since we already upload large CSVs in multi-part uploads, we should also be able to chunk the reads from BigQuery.

**Additional context**
![image](https://github.com/cal-itp/data-infra/assets/4305366/5b5fc5cb-dc13-4be4-8049-d54a191d3921)

**Comment by lauriemerrell** [comment]
@atvaccaro perhaps this ticket can also include #2617? 😅
