### ISSUE TITLE
Search for additional GTFS-RT feeds for `agencies.yml`

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#26]
The best source I have been able to identify for this for now is gonna be the [transitland-atlas](https://github.com/transitland/transitland-atlas), there might also be something buried inside one of the WT spreadsheets. 

I'll take point on this one

**Comment by hunterowens** [comment]
reached out to Maxime at MobilityData

**Comment by hunterowens** [comment]
first pass in #50

**Comment by mcplanner** [comment]
Investigating if this is something we can delegate to Trillium.

**Comment by mcplanner** [comment]
Thank you Juliet (Trillium) for confirming that we have everything in Transit.Land. Closing until we discover new feeds in the wild.
