### ISSUE TITLE
SBMTD | Notification for when null IDs surpass given threshold

### ISSUE THREAD

**Issue by Indiajar** [cal-itp/data-infra#2619]
@charlie-costanzo ## User story / feature request

As a demonstration partner for the payments dashboard, the agency would like to receive a notification when null IDs surpass given threshold. This measure will alert agencies if/when the number of missing route ids exceeds the typical amount. It also helps  to identify hardware connection issues. 

### Acceptance Criteria

SBMTD typically expects an absolute count of 20-45 unlabeled routes. 10% has been identified as a satisfactory threshold for metabase alerts. These alerts can be weekly so as to not overwhelm the agency.  

### Notes
_Please enter any additional information that will facilitate the completion of this ticket. For example: Are there any constraints not mentioned above? Are there any alternatives you have considered?_

**Comment by charlie-costanzo** [comment]
hey @Indiajar do we know what email address(es) we want this alert to go to?
