### ISSUE TITLE
Investigate parquet for storing rectangled GTFS RT files

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#266]
We need to load each new RT file into the warehouse. We can use an external table that points to rectangled versions of RT feed date. Let's start by trying to...

* rectangle vehicle positions
* store it as as parquet file

What we need to understand is...

* how much larger / smaller is the parquet file than the protobuf file?
* how much larger / smaller is it than a CSV file?
* what do we need to do to use the parquet format here?

**Comment by ccjarvus** [comment]
Some notes from yesterday:

- On headers
    - Headers are standard across all three pb files (positions, alerts, and updates) 
    - gtfsRealtimeVersion in the header is generally 2.0. We should learn more about realtime versions and how to handle unexpected versions if there are big differences between versions.
   - The header timestamp is worth having in the rectangle we make
- On entities
   - Positions
      - Pretty predictable - trip id, vehicle id, lat, long
       - Some entries (e.g. current status) are present only sometimes.
   - Alerts
       - There is possibility for unexpected results that we should program defensively around (e.g. a list with multiple translations of alert text, when we might only want the english translation)
      - Side note - would be interesting to capture all translations provided, even if we only rectangle the english text
Concept of "Informed Entity" - e.g. an agency can be notified of an alert, or a route can be informed of an alert. Unsure of the significance here yet. I have yet to see multiple entities alerted in the same json block, but I haven't really mapped over the files en masse yet.
   - Updates
      - I have seen a few variations of the json. I think based on how its configured, its a different kind of update, e.g. sometimes the update tells you when a bus plans to leave on station and arrive at another, sometimes the update tells you when the bus plans to arrive and depart from the same station.
- Big considerations
   - Programming for our explicit needs now can be a short term benefit, but could slow us down later on, e.g:
If we only rectangle 4 fields from Positions today, what do we do when we want a 5th field tomorrow? How do we migrate historical data? (I'm sure there's a solution. We just have to talk through it.)
- Next Steps
   - I am going to work on a general set of functions to:
      - Parse .pb
      - Convert each parsed .pb into a rectangle
    - I am going to research how to best leverage parquet for storing our rectangles

**Comment by ccjarvus** [comment]
[Here is our approach for rectangle'ing](https://github.com/cal-itp/gtfs-rt-api/blob/main/rectangle_vehicles.py)
