### ISSUE TITLE
Re-implement high level architecture diagram in mermaid.js in the repo

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#2672]
Also, add some subgraphs (inspired by @lauriemerrell's onboarding deck) breaking down some of the specifics of data flow. Enumerate tools necessary to deploy changes to each step of the process.

**Comment by lauriemerrell** [comment]
There is already a mermaid.js here: https://github.com/cal-itp/data-infra/blob/main/docs/architecture/architecture_overview.md, it's probably obsolete and perhaps should be redirected to whatever you create here
