### ISSUE TITLE
Epic: platform for creating manual reports

### ISSUE THREAD

**Issue by mcplanner** [cal-itp/data-infra#270]
An interface that allows DRMT staff to generate both Data Assessments and Transit Data Improvement Strategies, producing publicly retrievable reports, and storing the manually entered data in a queryable database.

Could be in Airtable?

**Comment by hunterowens** [comment]
I flagged this in the doc but I don't know if this is should be in GH  as a backlog item / shouldn't be an action item for Jarvus folks in August for sure and quite possibly at all, tbh, this feels like a process they need to manage using their existing tools. Can we close out this and leave in teamwork for now

**Comment by mcplanner** [comment]
This epic belongs in Teamwork. Closing!
