### ISSUE TITLE
Epic: Hosted version of the RT validator

### ISSUE THREAD

**Issue by mcplanner** [cal-itp/data-infra#273]
A deployment of the GTFS Validator that can be run easily on either an uploaded version of a feed or on one in the California database.

**Comment by hunterowens** [comment]
I think this is a dupe of #16 #253 #7

**Comment by mcplanner** [comment]
Only of 16, which I closed. 7 is about running the validator ourselves.
This is about letting anyone drop a link and see results.

**Comment by hunterowens** [comment]
ok!  this feels out of scope for this repo / this team /  resourcing as is.

**Comment by mcplanner** [comment]
This epic belongs in Teamwork. Closing!
