### ISSUE TITLE
Epic: Hosted version of the Grading Scheme UI

### ISSUE THREAD

**Issue by mcplanner** [cal-itp/data-infra#274]
A deployment of the Sequoia UI that can be run easily on either an uploaded version of a feed or on one in the California database.

**Comment by hunterowens** [comment]
Flagged in doc as well but before it is an issue we need to determine right way to resource. What was the result of the conversations around the app w/ Services team?

**Comment by hunterowens** [comment]
// dupe of #17

**Comment by mcplanner** [comment]
This epic belongs in Teamwork. Closing!
