### ISSUE TITLE
Move payments views into a DAG named payments_views

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#275]
Currently, views for payments live in the `gtfs_views` DAG. Let's...

* move them to a new DAG named payments_views
* keep everything else the same (e.g. they can still live in the `views` dataset)

This will make it a little bit easier for someone to drop in a work on payments domain specific data.

**Comment by machow** [comment]
@cvc5185 can you tackle this if you have time? The steps are basically...

* create a new folder in dags called payments_views
* copy gtfs_views/METADATA.yml to payments_views
* copy payments .sql files in the gtfs_views folder over
* run in airflow to double check that it works

**Comment by cvc5185** [comment]
hey @machow which payments .sql files in the gtfs_views folder were you referencing? screenshot of the list below
<img width="376" alt="Screen Shot 2021-08-17 at 11 09 29 AM" src="https://user-images.githubusercontent.com/25835059/129752136-b077cb8c-e53b-489a-8a40-ceba27e35c79.png">

**Comment by machow** [comment]
Ah good question--it looks like they're named `mst_*.sql`.

**Comment by cvc5185** [comment]
Great thanks for that! 

So I was trying to diagnose the reason that the payment DAGs were currently failing, would love to get your take @machow :

### This is the error that was coming up, related to DATETIME and Strings:
<img width="1144" alt="Screen Shot 2021-08-17 at 4 28 33 PM" src="https://user-images.githubusercontent.com/25835059/129797764-b3cf7275-f32a-4f46-be5c-7ecf31a583ff.png">

### From this code block (row 9):
<img width="911" alt="Screen Shot 2021-08-17 at 4 28 08 PM" src="https://user-images.githubusercontent.com/25835059/129797845-0be73832-89b7-4dde-8d71-9d22d07d9225.png">

### Looking at the original table, that is a string:

<img width="605" alt="Screen Shot 2021-08-17 at 4 29 20 PM" src="https://user-images.githubusercontent.com/25835059/129797884-94b5c4c3-46e8-4a95-9af5-be36d6eebb1a.png">

### So I tried adding this TIMESTAMP conversion, and it started working:

<img width="855" alt="Screen Shot 2021-08-17 at 4 41 08 PM" src="https://user-images.githubusercontent.com/25835059/129797979-6e80268f-8c2e-48d8-9117-0d7430dc67a7.png">

<img width="721" alt="Screen Shot 2021-08-17 at 4 45 29 PM" src="https://user-images.githubusercontent.com/25835059/129798078-508186d3-3369-476c-9a39-2b1a2cf9d630.png">

Does this make sense to you? Or am I off base

**Comment by machow** [comment]
Hey--I glanced at some rows of the source table, and that looks right to me... (cc @hunterowens )
