### ISSUE TITLE
Explore plotting GTFS schedule stops on a map in metabase

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#279]
It looks like metabase supports plotting on maps. Let's do a quick exploration...

* Can we plot `gtfs_schedule.stops` onto a **pin map** (using the lattitude and longitude columns)?
* How does drill-through work? Could we color the points?
* Can you add a filter to the map (may have to put the map on a dashboard)? E.g. by calitp_itp_id for now. How about filtering by hour of the day? (e.g. join stop_times to stops).

Note: for now, you can copy whatever tables you need to use into cal-itp-data-infra-staging views, which is accessible from metabase.

**Comment by cvc5185** [comment]
Heyo! So I was able to plot `gtfs_schedule.stops` onto a pin map (below)

<img width="819" alt="Screen Shot 2021-08-18 at 11 56 04 AM" src="https://user-images.githubusercontent.com/25835059/129931291-e88aa0fb-de04-4da8-99c9-591c1a89f965.png">

- It does seem like there is pretty limited functionality in maps, especially when it comes to drilling down. I haven't been able to modify the color of the points, etc

- You can add filters to the map, but I am having issues with the data in `gtfs_schedule.stops`. It doesn't seems to have a unique identifier to join on `gtfs_schedule.stop_times` with (the calitp_id fields are empty, and the stop_id field doesn't seem to be consistent across the tables)

**Comment by machow** [comment]
This is great, thanks! May be useful for #205 , I'll put up an issue, for us to query the giant "golden view" to get stops active on a specific day, between a specific time interval.
