### ISSUE TITLE
Issue downloading Marguerite Shuttle schedule data

### ISSUE THREAD

**Issue by mcplanner** [cal-itp/data-infra#280]
This link works when pasted into a browser, but fails in the pipeline.

https://transportation-forms.stanford.edu/google/google_transit.zip

**Comment by machow** [comment]
@mcplanner this link is not in agencies.yml? https://github.com/cal-itp/data-infra/blob/main/airflow/data/agencies.yml

**Comment by machow** [comment]
Looks like it succeeded today--going to close for now, but let me know if it errors again..!
