### ISSUE TITLE
Enable RBAC in metabase

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#281]
This is a useful piece of tech debt to pay down after delivering a a quarterly dashboard:

* can be done purely in metabase (by an admin)
* create groups for data workers, and data consumers
* prevent data consumers from accidentally saving change to dashboards
* create collections that are read only for data consumers

**Comment by ccjarvus** [comment]
Data Consumer and Data Worker roles have been created, and existing users have been assigned to one of those two groups.

Next steps would be for us to migrate any existing work to proper sub-collections under `Our Analytics` (#282) and limit access to the Metabase-mandatory All Users group.
