### ISSUE TITLE
Set up metabase dashboard folder structure

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#282]
* calitp dashboards collection
  - subcollection per dashboard

* Cal ITP Dashboards
    - Error Explorer Dashboard
    - Quarterly Report Dashboard
    - Error Explorer Dashboard Questions (...)
    - Quarterly Report Dashboard Questions (...)

**Comment by ccjarvus** [comment]
Structure is in place. Next steps will be to migrate existing work into these collections before restricting access with RBAC (#281)
