### ISSUE TITLE
Add a file with agency names, calitp ids to CKAN

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#284]
Currently, we upload our GTFS Schedule data, but not metadata with the names of agencies in our data. This means that people with see columns like `calitp_itp_id`, `calitp_url_number`, but will likely not know what agencies they represent.

**Comment by Nkdiaz** [comment]
Just checking the CKAN portal and an Agency file was uploaded on October 21, 2021 that contains a CSV with the following columns - Calitp_itp_id, url number, agency id, agency_name, and agency_url, calitp_extracted_at. For the purposes of this ticket, a file has been uploaded. Is the request for a more updated file?
