### ISSUE TITLE
Bug: dbt-metabase is failing due to mismatching YAML

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#2865]
**Describe the bug**
We have some models that lack appropriate YAML.

**To Reproduce**
See [logs](https://o1d2fa0877cf3fb10p-tp.appspot.com/log?execution_date=2023-07-31T15%3A37%3A17.032948%2B00%3A00&task_id=sync_dbt_docs_to_metabase&dag_id=deploy_dbt_docs&map_index=-1)

**Expected behavior**
YAML needs to be updated, most likely by adding missing columns.

**Additional context**
n/a

**Comment by SorenSpicknall** [comment]
Resolved by #2873
