### ISSUE TITLE
Handle duplicates in raw trips data

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#287]
Generally, the GTFS feeds we ingest are good about not including duplicate IDs.

However, two feeds have duplicate rows in their trips.txt files:

* Commerce Municipal Bus Lines: trip_id 1008 (e.g. on 2021-05-13)
* Burbank Bus: trip_id 301-2 (e.g. on 2021-07-31)

The bottom line is that this will screw up analyses, because it will erroneously create 2 copies of the trips data when we join it with other tables. For example, this means that trip 1008 gets counted twice when calculating service hours.

The most reliable way to deal with this is to **take out duplicates from our processed data (e.g. the one living in views)**. We will still have the validator errors run on the original source data to indicate the duplicates were there. I would also exclude it from the CKAN upload, along with a note of that as a processing step.

**Example code for fetching some duplicates**

```python
from calitp.tables import tbl

from siuba.sql import LazyTbl
from siuba import *
from siuba.dply.vector import n

tbl_trips = LazyTbl("bigquery://cal-itp-data-infra/gtfs_schedule_history", "trips")
tbl_trips >> filter(
    _.calitp_itp_id == 75,
    _.calitp_url_number == 0,
    _.route_id == "1693",
    _.service_id == "0",
    _.trip_id == "1008",
) >> arrange(_.calitp_extracted_at) >> collect()

tbl.gtfs_schedule_type2.trips() >> group_by(_.trip_key) >> filter(n(_) > 1)
```

**Comment by machow** [comment]
Related to #317 -- the tests flagged these duplicates. Let's remove the tests for now, and re-insert as part of fixing this issue.

TODO: discuss w/ team on Tues how they want to handle duplicates. We could remove duplicates (since they will e.g. affect the service hours count), or we can mark them (e.g. duplicate_number), or we can ignore them (since they only occur a few times).

**Comment by hunterowens** [comment]
pro removing dupes and pointing out in the validator errors.

**Comment by machow** [comment]
merged and it looks like dim trips tests are passing!

![image](https://user-images.githubusercontent.com/2574498/132748493-b950024d-b3dc-43a9-a600-a4a810d1a9a7.png)
