### ISSUE TITLE
Create Issue template / warehouse docs for research questions using QuVR MD

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#293]
QVR MD is an acronym to help with data research question intake. It stands for...

* question
* view
* research

* metric
* dashboard

Let's plan on working this into an issue template, and/or our warehouse docs

**Comment by machow** [comment]
@ccjarvus I put up a quick template here. Let's discuss quickly Thurs!

I've been thinking about how we can help askers answer these questions...

* How will the data science team respond to my request?
* When will they respond by?

Curious what you would add / change!

**Comment by ccjarvus** [comment]
Thanks @machow. Looks swell.

My only early thought (but in no way the hill I want to die on) is that a requester oughtn't request a report or a metric. Those steps are arguably for the discretion of the data worker. Wanted to write here before I forgot the thought. Looking forward to discussing tomorrow.

**Comment by machow** [comment]
Edited to be a bit more user friendly--let's close the issue, try it out and refine as needed!

![image](https://user-images.githubusercontent.com/2574498/132727359-0f7b0a44-8338-48f1-8c48-3cc41d2d9445.png)
