### ISSUE TITLE
Payments: Updates to fct_payments_rides_v2

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#2976]
The following modifications are suggested:

- [x] add agency_id from routes.txt or ageny_name from agencies.txt
- [x] add a description for earliest_tap:
  `The earliest transaction associated with a customer_id.`
- [x] remove extra lat/long geometry in table
- [x]  add `on_` to on tap fields?

**Comment by lauriemerrell** [comment]
Blocked by #3159

**Comment by charlie-costanzo** [comment]
Great, moved to done 👍🏼
