### ISSUE TITLE
Payments: Ensure refunds are being captured correctly Littlepay/Elavon data

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#2978]
And update the corresponding questions in Metabase

**Comment by lauriemerrell** [comment]
Make `int_payments__refunds` that brings together both credit refunds and post-settlement refunds from the refunds table. See the [refunds investigation Google doc](https://docs.google.com/document/d/1ijgAcY2Wc07kIaW16yos6bYIv_eEFji_e1ZTtgWU1R8/edit#heading=h.e8bf7f664yi1) for more
