### ISSUE TITLE
Handle two or more feeds inside the "gtfs_schedule_url" key

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#30]
Currently, the downloader is failing for Metro Los Angeles, b/c there are two urls in the download URL

we should have the path actually be something like `{run_time}/{agency_id}/{url}/[pileofiles.txt]`

**Comment by hunterowens** [comment]
@machow can you take a look at this? would like to get Metro Los Angeles handled.

**Comment by machow** [comment]
I think this was worked out in https://github.com/cal-itp/data-infra/pull/25. The url entries are now saved using the path `{itp_id}/{url_number}`, where url_number is the index of the url entry.

![image](https://user-images.githubusercontent.com/2574498/113318422-7350c400-92de-11eb-9b7a-00d2b147863b.png)

**Comment by hunterowens** [comment]
:+1: Let's close.
