### ISSUE TITLE
Benefits: extract additional fact tables from Amplitude event data for Metabase usage

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-infra#3045]
This ticket is a continuation of the work from:

* #2514 
* #2525

Those tickets brought Amplitude data into the warehouse under the new DBT structure. However much of the interesting event data is stuck inside one or more JSON columns in the view created by the above PRs, `Fct Benefits Events`.

This view is available in Metabase, but is currently mostly unusable for certain charting and querying; e.g. aggregations on data inside the JSON columns.

## User story / feature request

As a Metabase data consumer and chart builder, I want simple and straightforward access to Benefits enrollment and related events derived from Amplitude data already in the warehouse.

### Acceptance Criteria

- [x] #3046
- [x] #3048 
- [x] #3049
- [x] #3050
- [x] The new tables should be available for use within Metabase

**Comment by thekaveman** [comment]
We decided to implement these additional views in Metabase directly now that we have the expanded JSON data.

Keeping this is blocked until we have the Warehouse to Metabase sync fully working for production data.

**Comment by machikoyasuda** [comment]
These can now all be found in: `Cal-ITP Commons` / `Benefits` - 
<img width="1512" alt="image" src="https://github.com/cal-itp/data-infra/assets/3673236/dd76980e-f908-415a-81fd-3bff227eba58">

**Comment by thekaveman** [comment]
All production data is now available in Metabase! 🎉
