### ISSUE TITLE
Benefits: fact table by event phase - Enrollment

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-infra#3050]
Building on the work in #3046, this table should be filtered by the listed event types. 

## Acceptance criteria

Columns that aren't relevant for that event type (e.g. from the expanded `event_properties`) should be omitted.

Matching event types:

- [x] `started payment connection`
- [x] `closed payment connection`
- [x] `returned enrollment`

**Comment by machikoyasuda** [comment]
Done: https://dashboards.calitp.org/question/1967-benefits-fact-table-filtered-by-enrollment-event-phase

**Comment by thekaveman** [comment]
Looks great thank you @machikoyasuda!
