### ISSUE TITLE
Update Sentry runbook to describe Kafka offset failure recovery steps for Sentry outages

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#3064]
As a Cal-ITP data engineer, I want to have the recovery steps for common outages documented so I can manage a recovery quickly in the future. Specifically we should document how to handle when the Kafka offset gets out of sync as happened on October 26th.

Recovery steps are documented in [this Slack post](https://cal-itp.slack.com/archives/C0332307HKM/p1698350562026489?thread_ts=1698344410.240819&cid=C0332307HKM) and should be transferred to the Sentry recovery runbook.

**Comment by SorenSpicknall** [comment]
Resolved by #3069
