### ISSUE TITLE
Evaluate whether we can use soda-sql (either by updating dependencies) or another framework

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#307]
We often want to do

* all values are distinct
* no nulls
* contains only specific values

Ping me once updated dependencies are running, and I can make sure they build in our prod composer instance.

**Comment by ccjarvus** [comment]
Soda SQL has a [minimum Python version requirement of 3.7](https://github.com/sodadata/soda-sql/blob/1afb220959584257aca239aa60ae85da4afa6ee5/core/setup.py#L6-L9).

Until we upgrade Airflow, we will have to implement our own testing methodologies.

**Comment by machow** [comment]
Blocked by #126
