### ISSUE TITLE
Payments: Investigate broken question in Metabase `Journeys with Unlabeled Routes`

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#3074]
After reviewing the Metabase dashboards for payments agencies, it appears the question `Journeys with Unlabeled Routes` isn't working as expected (there appear to be more journeys with unlabeled routes than total journeys at times). We should investigate and rectify this error.

**Comment by lauriemerrell** [comment]
This was happening because the chart had two y-axes for most agencies and the two axes had different scales. This was confusing so I turned off that setting for all agencies and now unlabeled route journeys is always less than total journeys
