### ISSUE TITLE
Update pipeline to use GTFS Schedule Validator v4.2.0

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#3152]
## User story / feature request

Mobility Data has just released the [GTFS Schedule Validator v4.2.0](https://github.com/MobilityData/gtfs-validator/discussions/1614). This version includes important updates to be able to validator more fares v2 data. It also has a number of bug fixes.

### Acceptance Criteria

The data pipeline is updated to be able to use the GTFS Schedule Validator v4.2.0.

**Comment by lauriemerrell** [comment]
@evansiroky let us know if you would like Jarvus help with this. Here are two recent PRs that previously upgraded the validator version:
 - [#2893](https://github.com/cal-itp/data-infra/pull/2893)
 - [#2935](https://github.com/cal-itp/data-infra/pull/2935)

**Comment by lauriemerrell** [comment]
(Per conversation in Slack, Jarvus will queue for next sprint.)
