### ISSUE TITLE
dbt docs Netlify deploy is failing

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#3160]
As a Cal-ITP data user, I want the dbt docs site to always be up to date & not to fail when deployed in the daily job so that I know that the docs are fresh and contain the latest information.

We're [getting a Netlify failure ](https://o1d2fa0877cf3fb10p-tp.appspot.com/dags/transform_warehouse/grid?dag_run_id=manual__2023-12-01T18%3A46%3A38%2B00%3A00&task_id=dbt_run_and_upload_artifacts) in our dbt job runs. 

`[2023-12-01, 18:49:04 UTC] {pod_manager.py:237} INFO -  ›   Error: Site not found. Please rerun "netlify link"`

Seems to be the same issue as #2947, or at least the same symptoms

**Comment by SorenSpicknall** [comment]
Resolved via rotation of the cred involved in the deploy
