### ISSUE TITLE
New Airflow DAG for NTD downloading

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#3164]
## User story / feature request

As an analyst,
I would love to be able to query NTD data
and be able to join the NTD data with other data from our warehouse,
So that I can do various analyses to classify transit agencies according to revenue, ridership, etc.

### Acceptance Criteria

1. There is a DAG that has a task that can be manually ran to download NTD data to Google Cloud
2. There is a DAG that has a task that runs monthly that downloads monthly ridership data
3. Maybe a separate ticket? There is documentation on how to do various dbt modeling to enable the exposure of NTD data in various mart tables that metabase can read.

### Notes

Laurie will be creating a document that discusses some of this.

**Comment by vevetron** [comment]
I would want to be able to see NTD ridership in the mart.
