### ISSUE TITLE
Benefits: fill in missing event properties for historical events

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-infra#3168]
This is a follow up to the work done in #3046 / #3081 on the `mart_benefits.fct_benefits_events` table.

As the Benefits analytics scheme has evolved over the years, we have introduced new event attributes to better support analysis, filtering, etc. This means that historical events do not always contain information in these newer attributes, since they were generated prior to the attribute being introduced.

Fortunately the historical events all correspond to a single user flow: Senior eligibility for MST.

For this task, we want to fill in (i.e. hardcode) the missing data for these historical events to align them with other, newer Senior/MST events.

## Acceptance Criteria

The following columns should have no blank values in `mart_benefits.fct_benefits_events`:

### Auth phase events

See #3049

- [ ] `event_properties_eligibility_types`
- [ ] `event_properties_transit_agency`
- [ ] `user_properties_eligibility_types`
- [ ] `user_properties_transit_agency`

### Eligibility phase events

See #3048 

- [ ] `event_properties_eligibility_types`
- [ ] `event_properties_transit_agency`
- [ ] `user_properties_eligibility_types`
- [ ] `user_properties_transit_agency`

### Enrollment phase events

See #3050

- [ ] `event_properties_eligibility_types`
- [ ] `event_properties_transit_agency`
- [ ] `event_properties_payment_group`
- [ ] `user_properties_transit_agency`
- [ ] `user_properties_eligibility_types`

## Notes

Some related work on the Benefits side:

- https://github.com/cal-itp/benefits/pull/891
- https://github.com/cal-itp/benefits/pull/897
- https://github.com/cal-itp/benefits/pull/901
- https://github.com/cal-itp/benefits/pull/1057
- https://github.com/cal-itp/benefits/pull/1229

**Comment by machikoyasuda** [comment]
@lauriemerrell Do you have any guidance on how we should go about this?

**Comment by thekaveman** [comment]
In discussion with @indexing, we decided that this missing data isn't causing a problem for analytics or reporting at this time. We can revisit this clean up if this does become an issue in the future.
