### ISSUE TITLE
Add tests for facts and dimensions in gtfs_views

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#317]
We recently added the ability to test our SQL tables. Let's add tests to the tables in gtfs_views to start.

[Here is an example](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/validation_fact_daily_feed_codes.sql#L5-L13). Here are the [view docs](https://docs.calitp.org/data-infra/warehouse/02_views/).

* Check that surrogate keys do not have nulls and are unique (columns ending in _key).
* For tables that cross by date, ensure that the keys x date are composite unique
* Run on development airflow, and report back any failing tests

If you open the log for the task in airflow, you should see an output like...

![image](https://user-images.githubusercontent.com/2574498/131138954-3b73a27b-87fb-4387-a16a-97b8b76dcaea.png)

**Comment by cvc5185** [comment]
Hey @machow, update here:
Was able to get the tests for many tables up and running locally in airflow, pushed them and submitted a pull request. I can't remember if you also wanted me to push the tests that still weren't working?
Either way, these are the views whose tests still aren't working that we should pair on to review when you're able:

- Gtfs_schedule_fact_daily_trips (still not recognizing trip_key, like we suspected it might)
- Gtfs_schedule_fact_daily_service (still not recognizing feed_key, like we suspected it might)
- Gtfs_schedule_fact_daily_feed_files (many duplicates of the composite unique test that we identified)
- Gtfs_schedule_dim_trips (3 duplicate trip keys)
- Gtfs_schedule_dim_files (frequencies.txt is duplicated)
