### ISSUE TITLE
Bug: `payments.device_transactions` table is currently empty

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#318]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1735650/131153336-560bbbb2-4695-467a-88a9-1e715c25817c.png)

Currently, nothing in the device transactions table.

**Comment by machow** [comment]
Resolved, needed to use underscores (the processed folder name was set to be the same as the table, but the mst folder uses hyphens)
