### ISSUE TITLE
Bug: CKAN uploader downloads the stop times file twice

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#335]
**Describe the bug**
[here's a link to the code](https://github.com/cal-itp/data-infra/blob/041010fb9008cf1302fc77a5197024e1c124de16/services/gtfs-ckan-uploader/calitp_data_ca_exporter.py#L50)
**To Reproduce**

**Expected behavior**

only download hte large stop times file once
**Additional context**

**Comment by machow** [comment]
sorry--removed the line
