### ISSUE TITLE
Upgrade jupyterhub-singleuser custom image deps so it can build w/ Python 3.11

### ISSUE THREAD

**Issue by themightychris** [cal-itp/data-infra#3352]
After upgrading JupyterHub, we need to upgrade our custom docker image to incorporate the latest jupyterhub library. It appears that this dependency comes is as part of the `jupyter/datascience-notebook` base image we use. In #3350 I upgraded it from `:python-3.9` to the latest `:python-3.11.6` since the `:python-3.9` tag hasn't been updated in over 2 years, but now the image fails to build:

```console
 => [15/23] COPY ./pyproject.toml /reqs/pyproject.toml                                                                                                                                                                                 0.2s
 => [16/23] COPY ./poetry.lock /reqs/poetry.lock                                                                                                                                                                                       0.0s
 => [17/23] RUN poetry config virtualenvs.create false                                                                                                                                                                                 0.7s
 => ERROR [18/23] RUN cd /reqs && poetry install --with=shared_utils --with=portfolio                                                                                                                                                  0.8s
------
 > [18/23] RUN cd /reqs && poetry install --with=shared_utils --with=portfolio:
0.600 The currently activated Python version 3.11.6 is not supported by the project (~3.9).
0.600 Trying to find and use a compatible version. 
0.691 
0.691 Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
------
Dockerfile:45
--------------------
  43 |     COPY ./poetry.lock /reqs/poetry.lock
  44 |     RUN poetry config virtualenvs.create false
  45 | >>> RUN cd /reqs && poetry install --with=shared_utils --with=portfolio
  46 |     RUN poetry config virtualenvs.create true
  47 |     
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c cd /reqs && poetry install --with=shared_utils --with=portfolio" did not complete successfully: exit code: 1
```

To reproduce locally, check out the latest `main` branch and:

```bash
cd images/jupyter-singleuser/Dockerfile
docker build .
```

It appears that some poetry work will need to be done to upgrade dependencies to be compatible with Python 3.11

**Comment by mjumbewu** [comment]
@themightychris have you tried updating [the Python version in the pyproject.toml file](https://github.com/cal-itp/data-infra/blob/a5e2e4cbaf680705c6db05329975bd60ef9394f4/images/jupyter-singleuser/pyproject.toml#L8)? That _might_ be enough to fix, but there may also be additional package version changes needed with the Python upgrade.

**Comment by themightychris** [comment]
@mjumbewu good catch, after changing that line to `python = "~3.11"` I get:

![Screenshot 2024-05-23 at 5 43 11 PM](https://github.com/cal-itp/data-infra/assets/458494/dd76ca2c-d004-4b67-8cf7-90028e7d42ec)

**Comment by mjumbewu** [comment]
@themightychris Ooh, looks like the `calitp-map-utils` package is pinned to Python 3.9.x. Will have to take a look at that.

**Comment by mjumbewu** [comment]
Yep, it's [pinned](https://github.com/cal-itp/data-infra/blob/a5e2e4cbaf680705c6db05329975bd60ef9394f4/apps/maps/pyproject.toml#L9). That will have to be updated and [pushed up to PyPI](https://pypi.org/project/calitp-map-utils/).

**Comment by themightychris** [comment]
@mjumbewu I might have fixed it in #3354

**Comment by mjumbewu** [comment]
We'll run into the same issue for [`calitp-data-analysis`](https://github.com/cal-itp/data-infra/tree/a5e2e4cbaf680705c6db05329975bd60ef9394f4/packages/calitp-data-analysis).

**Comment by themightychris** [comment]
@mjumbewu yep just spotted that, already on it :-)

**Comment by themightychris** [comment]
Now we're deeper into the deps failing:

![Screenshot 2024-05-24 at 6 13 44 PM](https://github.com/cal-itp/data-infra/assets/458494/a5b550d9-f79c-44dc-a5b7-68a4e98c1a49)

This repo is also full of dependabot PRs relating to this and the `calitp-*` packages, so a more thorough sweep of dependencies might be needed @mjumbewu

**Comment by vevetron** [comment]
Yea i'm testing out different combos - building it on my local mac using docker.

Right now i'm running into a dask 2022 not working with python 3.11.  Also dask seems to be both in the calitp-data-analysis package as well as the base jupyter-single-user-image.  I'm not sure why.

I was thinking i'd remove it from the caltip-data-analysis package and just trying to have the requirements in the jupyter-single-user-image

**Comment by vevetron** [comment]
OOf except calitp-data-analysis doesn't like that:
https://github.com/cal-itp/data-infra/actions/runs/9230746834/job/25399500299?pr=3359#step:6:176
