### ISSUE TITLE
Alerts related to Gatus to know when analysis sites are down

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#3377]
## User story / feature request

_Please describe your need, outlining the key users, the feature being requested, and the goal that that the feature will facilitate._
As a data analyst, I want to know when the individual sites on the analysis.calitp.org are down. Jarvus set up https://gatus.jarv.us/ to help monitor various sites, but I would like an alert to show up in a Slack channel when something is down.

### Acceptance Criteria

Some type of alert is sent to Slack (or other method) when a site becomes broken.

**Comment by charlie-costanzo** [comment]
Following up with Chris about this

**Comment by charlie-costanzo** [comment]
Hey there @evansiroky, to get this set we need someone with admin in the Cal-ITP slack to generate a webhook URL to the desired channel for us. Would you be able to help with that?

**Comment by evansiroky** [comment]
@charlie-costanzo is there a way we can do email? We may not have slack forever.

**Comment by charlie-costanzo** [comment]
> [@charlie-costanzo](https://github.com/charlie-costanzo) is there a way we can do email? We may not have slack forever.

Yep @evansiroky that's no problem – I'll send a message on Slack to you and @tiffanychu90 now to figure out what email(s) they should go to

**Comment by charlie-costanzo** [comment]
Hey @tiffanychu90 and @evansiroky, your emails should now receive Gatus alerts for the analysis sites

**Comment by evansiroky** [comment]
I got some emails!
