### ISSUE TITLE
Upcoming changes to support for the files.upload API method in Slack

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-infra#3384]
## User story / feature request

This issue is to track changes coming to the Cal-ITP Slack Workspace, shared via an email announcement to Slack admins:

> A workspace that you administer contains apps or integrations that recently used the [files.upload web API method](https://api.slack.com/methods/files.upload). We want to inform you about two important changes coming to support for the files.upload API.
>
> **May 8, 2024**
> Newly created Slack apps will no longer be able to access the files.upload API. Existing applications will be able to continue
> using files.upload until support is discontinued. 
>
> **March 11, 2025**
> Support for the files.upload API for all apps will be discontinued.
>
> To prepare for this change, we recommend that app owners migrate away from files.upload and instead use the combination of [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal) and [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal). You can also leverage Slack's SDKs to help transition to this new way of uploading files by visiting our [api.slack page](https://api.slack.com/messaging/files#uploading_files).
>
> If the apps using the files.upload API do not update to the method above, file uploads from those apps in your workspace or organization will no longer work beginning on March 11, 2025. To view a list of apps in your workspace impacted by this change, click below:  [See list of affected apps](https://click.email.slackhq.com/?qs=a3f2f1a628de39ab2b5be9c68ded154276c1fc257c0422d0149b88316d439b9613c9f1e5f73650d379fe5e7bb96f85c6ceabd1f152c2fbef07f5a1473a76f286)
>
> More information about this change can be found in our [developer changelog](https://api.slack.com/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay).

Following the link to check the list of affected apps, it looks like the `Metabase` app uses this API to upload images of charts as part of the notification / scheduled post feature.

### Acceptance Criteria

- [ ] _Placeholder: Metabase updates their API_
- [ ] _Placeholder: We update our Metabase app to the latest version_

**Comment by evansiroky** [comment]
May be resolved by #3461
