### ISSUE TITLE
Jupyter Google OAuth failing with `Error 400: invalid_request`

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#3387]
**Describe the bug**
When seeking to authenticate with Google OAuth in JupyterLab using Google SDK/gcloud and `gcloud auth login`, users receive `Error 400: Invalid Request` (screenshot below)

**To Reproduce**
- Begin a new JupyterLab session
- Navigate to the terminal
- run `gcloud auth login`
- copy/paste the URL output into a browser window

**Expected behavior**
When you copy/paste the URL displayed into a browser, you should be successfully taken through the Google authentication flow to then be able to run operations like `bq load` in order to perform tasks like [Adding Ad-Hoc Data to the Warehouse](https://docs.calitp.org/data-infra/warehouse/adding_oneoff_data.html)

<img width="1019" alt="Screenshot 2024-07-01 at 4 19 11 PM" src="https://github.com/cal-itp/data-infra/assets/25835059/31da73c7-490b-4db3-8a0a-531edbad8d88">
<img width="407" alt="Screenshot 2024-07-01 at 4 24 38 PM" src="https://github.com/cal-itp/data-infra/assets/25835059/5a8193b1-c2e5-4c2c-9458-67ace9d2a907">

**Comment by vevetron** [comment]
Can you document the steps to recreate this error?

**Comment by charlie-costanzo** [comment]
> Can you document the steps to recreate this error?

Sorry about that @vevetron, I put this up quickly to come back to it later but won't publish them without more detail in the future. I just added more info above, let me know if you have any more questions

**Comment by charlie-costanzo** [comment]
@HaroldBooker this was just an issue on my side – it seems like a config that I added in my personal hub somewhere (probably ~3 years ago when setting up the hub) was causing a problem. I deleted my google sdk/supporting configs and re-installed and had no issue initializing
