### ISSUE TITLE
Use year-agency or year-agency-mode-tos grain for `mart_ntd.dim_annual_ntd_agency_service`

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#3396]
## User story / feature request

_Please describe your need, outlining the key users, the feature being requested, and the goal that that the feature will facilitate.**_

As a data scientist, I want to traverse the NTD tables in the warehouse in the same consistent way / similar design philosophy as our GTFS warehouse tables. I would like the grains to be clear in the dimensional tables. (I'm not sure if NTD annual data warrants the need for setting up fact tables). Starting with this [dim_annual_ntd_agency_service](https://dbt-docs.calitp.org/#!/model/model.calitp_warehouse.dim_annual_ntd_agency_service), we should set up our naming pattern in the warehouse for NTD annual / monthly data.

This builds off of earlier work:
* #3345 
* #3373 
* #3378

### Acceptance Criteria

- [ ] clear grain based on the name of the mart table - `mart_ntd.dim_annual_ntd_agency_service` implies that it's an annual service table for each agency (although we may want to include mode and type of service (TOS) here), but the column `time_period` means that we have rows showing annual totals as well as subtotals by weekday/weekend/time-of-day. 
- [ ] do not want the current NTD agency service table to be accidentally aggregated over all the rows for an agency and double, triple count the upt, voms, etc
- [ ] potential new tables at the additional grains we do want (weekday/weekend/time-of-day) is desired! come up with table name that makes clear the grain though
- [ ] dbt uniqueness tests / keys 
- [ ] document column descriptions in yaml - `time_period` here is not filled in, and you would not be clued in on the possible values of `time_period`
### Notes

Let's adhere to what we've already documented in the last round of warehouse work: https://docs.calitp.org/data-infra/warehouse/developing_dbt_models.html#what-is-the-grain-of-your-model

**Comment by vevetron** [comment]
Questions about the data that should be answered:
Average Weekday - AM Peak
Average Weekday - Midday
Average Weekday - PM Peak
Average Weekday - Other
Sum out to the same as 
Average Typical Weekday?


Does 
Average Typical Weekday
Average Typical Saturday
Average Typical Sunday
Sum out to 
Annual Total/52?

**Comment by vevetron** [comment]
Sounds like @evansiroky intends to roll this into other NTD ingestion work projects in the next coming block.

**Comment by erikamov** [comment]
There is a page with information about [2022 NTD Annual Data - Service (by Mode and Time Period)](https://data.transportation.gov/Public-Transit/2022-NTD-Annual-Data-Service-by-Mode-and-Time-Peri/wwdp-t4re/about_data) in case it helps.

**Comment by tiffanychu90** [comment]
Relevant discussion in [Slack](https://cal-itp.slack.com/archives/C02H6JUSS9L/p1728514216560289?thread_ts=1727283806.820109&cid=C02H6JUSS9L)

**Comment by erikamov** [comment]
Models created on `cal-itp-data-infra`:
* mart_ntd.dim_annual_service_agencies
* mart_ntd.dim_annual_service_mode_time_periods
* mart_ntd.fct_annual_service_modes

And the `mart_ntd.dim_annual_ntd_agency_service` was deleted from `cal-itp-data-infra`.

**Comment by erikamov** [comment]
@tiffanychu90 and @vevetron, Did you have a chance to look at the new tables? Can we close this ticket?

**Comment by vevetron** [comment]
Hey @Tiffany Ku did you have a strong opinion on this ticket? Erika broke out the data into two groups, [fct_annual_service_modes](https://dbt-docs.calitp.org/#!/model/model.calitp_warehouse.fct_annual_service_modes) for the annual data and [dim_annual_service_mode_time_periods](https://dbt-docs.calitp.org/#!/model/model.calitp_warehouse.dim_annual_service_mode_time_periods ) the different time periods.

This is implemented correctly - but I think your intention was to break out all the different modes? Probably have 
Average Typical Weekday
Average Typical Saturday
Average Typical Sunday in one fct table 

and 

Average Weekday - AM Peak
Average Weekday - Midday
Average Weekday - PM Peak
Average Weekday - Other

In another

**Comment by tiffanychu90** [comment]
@erikamov: Thanks for working on this! Was waiting for Christian to get some use out of the NTD tables before I made any calls on it, but I think it's definitely fine to close.
@vevetron: We can always tweak ourselves down the line
