### ISSUE TITLE
Mart table request: bus stops on the state highway network

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#3397]
This issue has been created on behalf of Uriel Fojas.

## User story / feature request

As an analyst from the Mobility Data Standards branch investigating bus stop shelters and amenities,
I would like to have a list of bus stops on the California State Highway Network,
So that I can have an up-to-date list of bus stops on the state highway network.

### Acceptance Criteria

A mart table is created that lists the bus stops on the California State Highway Network. This issue can use a simple buffer on the SHN shapefile to create a list of stops as was done in the notebook that Eric linked to below. Uriel may have additional methodology to improve the algorithm for finding items stops on the SHN, but that will should be created as follow-up issues.

### Notes

There was a notebook created for this [here](https://github.com/cal-itp/data-analyses/pull/1160).

**Comment by edasmalchi** [comment]
I added a few missing operators via https://github.com/cal-itp/data-analyses/pull/1217, but kept Tiffany's methodology otherwise

**Comment by edasmalchi** [comment]
Per Teams discussion with @evansiroky and Uriel, this dataset should probably only include stops with any service defined in their current GTFS Schedule feed.

**Comment by ohrite** [comment]
[Relevant Slack conversation](https://cal-itp.slack.com/archives/C02H6JUSS9L/p1728671948860059?thread_ts=1727903055.205829&cid=C02H6JUSS9L) as discussed in project planning

**Comment by ohrite** [comment]
From conversation with @evansiroky, there is a meeting coming up regarding stops
