### ISSUE TITLE
NTD Modeling – Mart – Remaining Tables in Dataset

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#3405]
## User story / feature request

Part of #3401 

As a data engineer, I would like to make mart tables for the NTD dataset incorporating the remaining tables that have been made available as part of this epic, and extending the work found in `warehouse/models/mart/ntd` (found below).

To do this, I will need to hold more interviews with stakeholders and understand business needs to develop mart tables (aside from `mart_ntd.dim_annual_ntd_agency_service` which has already been identified as a need by analysts, and documented in #3396 listed below).

Building upon the work completed in #3345

Existing patterns:
- [warehouse/models/mart/ntd](https://github.com/cal-itp/data-infra/tree/main/warehouse/models/mart/ntd)

### Acceptance Criteria

I can successfully access the data for the following tables in the warehouse as mart tables:
- `mart_ntd.dim_annual_ntd_agency_service` found in #3396 
- `mart_ntd.dim_annual_ntd_funding_source` [PR 3495](https://github.com/cal-itp/data-infra/pull/3495)

### Notes
---

**Comment by erikamov** [comment]
Creating new table `dim_annual_ntd_funding_source ` based on conversation with @tiffanychu90 on slack: [3405-new-ntd-tables](https://github.com/cal-itp/data-infra/compare/3405-new-ntd-tables)

**Comment by erikamov** [comment]
`dim_annual_ntd_funding_source` successfully created.

**Comment by erikamov** [comment]
Working on #3396 according with Slack conversation with @tiffanychu90 :
* Table naming pattern: [dim/fct]_[time grain: annual/monthly]_[grain: agency/agency_mode]_[some other descriptor]
* 3396 is referencing the changes to...stg_ntd_annual_data 2022 service_by_mode_and_time_period
dim_annual_ntd_agency_service -> renamed in mart_ntd with a name like dim_annual_agency_mode_timeofday_service.
 The dim_annual_agency_service name would belong to the stg_ntd_annual_data_2022_service_by_agncy entry in the pdf.

**Comment by evansiroky** [comment]
Perhaps we can make another issue for this, but there are a lot of additional mart tables that could be created. A good starting point for seeing what data questions could be answered would be to compare what is in some [NTD Transit Agency Profile Reports](https://www.transit.dot.gov/ntd/transit-agency-profiles). See [Santa Cruz Metro example](https://www.transit.dot.gov/sites/fta.dot.gov/files/transit_agency_profile_doc/2023/90014.pdf).

I'm making a list of additional questions that could be asked too.

**Comment by evansiroky** [comment]
In speaking with data engineers, my comment was converted to a new issue - #3540
