### ISSUE TITLE
Bug: Schedule validation errors missing from monthly reports

### ISSUE THREAD

**Issue by mcplanner-zz** [cal-itp/data-infra#341]
**Describe the bug**
Schedule validation errors aren't showing up in the monthly reports. Also the dates for the Guideline Consistency section are all for May.

**To Reproduce**
1. Go to https://reports.calitp.org/gtfs_schedule/2021/07/226/index.html
2. Scroll down to Consistency with GTFS Minimum Guidelines

**Expected behavior**
* I expect validation results for this report, specifically. It has errors in Metabase, but not here.
* I also expect dates for the file/field to be for July.
* I also question why the report says no feed end date, when I see end dates in the calendar.txt file. 

**Additional context**
Photo attached.
<img width="1378" alt="Screen Shot 2021-09-01 at 6 19 51 PM" src="https://user-images.githubusercontent.com/830005/131766508-537b6c00-a426-4cb9-b412-718a8b890f3a.png">

**Comment by machow** [comment]
Thanks for raising--I just flagged in this issue as well https://github.com/cal-itp/reports/issues/31

**Comment by holly-g** [comment]
Resolved
