### ISSUE TITLE
SBMTD Cap Riders

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#3410]
SBMTD has a question about Metabase data:

When I look at the number of unique riders receiving adjusted price rides, grouped by month, I know the time based cap is the 60 minute transfer, the daily cap is our $6 day pass cap and the multi-day cap should be the 30 day fare cap. (Also what does FIXED mean here?)

 

But about the multi-day cap (should top out at $52)--When I download and look at the actual transaction data for those that are marked as hitting this cap, there’s a column called “Charge Amount” and all of those amounts are between 0 and $1.25 (full fare is $1.75). So is that segment of data “taps where someone either first hit the cap and/or taps after they hit said cap”?

 

Ultimately what I’m trying to find is: I want to see how many unique riders are hitting the 30 day $52 fare cap, and those that do, how many rides do they end up taking in their 30 day window?

 

Also wondering what the difference between the unique riders receiving adjusted price rides and “product codes associated with adjusted price journeys” is.

**Comment by erikamov** [comment]
Reports created on metabase for Hillary Blackerby (SBMTD):
* Count of unique Riders that reached the Multi-Day Cap and the date will be based on the date of the first Multi-Day Cap record of each range: `2904-sbmtd-multi-day-cap-riders-this-year`
* List of riders that reached the Multi-Day Cap for validation: `3043-multi-day-cap-riders-all-records-filtered-by-rider`
* List of how many taps each rider who reached the Multi-Day Cap has: `3074-multi-day-cap-riders-taps`

**Comment by erikamov** [comment]
Reports are done, Hillary asked for sorting on her report. I can sort on my end, so Charlie and I added on (SBMTD) Contactless Payments Metrics Dashboard to see if she is able to sort from there with her current permissions.

Waiting for her confirmation.

**Comment by erikamov** [comment]
Reports were added to SBMTD Dashboard and Hillary was able to view and sort as she requested.

@evansiroky This task can be closed.
