### ISSUE TITLE
Stop Registry Discovery Effort

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#3412]
# Entur Stop Registry

This effort consists of three work areas:

1. Supporting Uriel during initial exploration
2. Supporting any data needs for the Stop Registry
3. Supporting infrastructure and operations needs for the Stop Registry

**Comment by ohrite** [comment]
Update as of 8/23: follow-up scheduled with Entur on Monday 8/26 to discover data and infrastructure needs.

**Comment by ohrite** [comment]
Update as of 8/26: followed up with Johan from Entur with Uriel, received non-technical overview of the National StopPlace Registry.

Outstanding areas of investigation:
* NSR has Parent/StopPlace/Quay hierarchy, whereas GTFS has no hierarchy, how do we reconcile this?
* What kinds of reporting would provide value to transit agencies, and what is possible in NSR?
* NSR speaks NeTEx, we do not, how much work to translate statewide GTFS->NeTEx->GTFS to complete the loop?
* Johan mentioned that deploying NSR has been attempted twice so far, but teams are still working on success, and SSO is not GCloud/AzureAD. We should meet with one of those teams, and Entur technical staff, to find out level of effort and approach.

**Comment by evansiroky** [comment]
GTFS does have a hierarchy for stops using `location_type` and `parent_station`. Whether all feeds publish this info is of course another issue.

**Comment by ohrite** [comment]
> GTFS does have a hierarchy for stops using `location_type` and `parent_station`. Whether all feeds publish this info is of course another issue.

True, `location_type`/`parent_station` allows grouping in `stops.txt`. NeTEx's hierarchy has more robust conventions, more discovery is needed to see if that maps 1:1.

**Comment by ohrite** [comment]
From conversation with Evan:

1. What would be required from the data side to produce data for a stop registry?
2. Recording shelter/signage for a stop: why do we need a stop registry

**Comment by evansiroky** [comment]
Thanks for delivering!
