### ISSUE TITLE
Littlepay Issuer / Card Scheme Questions

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#3413]
i.                I’m getting blanks in ‘card scheme’ within ‘FCT Payments Rides V2’– see below. Is this test data? There isn’t a specific time for the blanks – which are scattered throughout the data.

ii.               I can see that an issuer with a distinctly Polish name is showing as ‘United States’ – is this right? Or should I be checking with LittlePay?

**Comment by charlie-costanzo** [comment]
Closing this ticket - responded via email. This was a question that we received from Rebel regarding fields in the `fct_payments_rides_v2` tables. We don't create or manipulate any of these fields ourselves (or add any test data), simply ingest them from Littlepay, so we recommended that they reach out to Littlepay with these questions. It appears to be a data quality issue from Littlepay or another vendor.

**Comment by evansiroky** [comment]
Reopening at request of @akosmatzon who wants to review

**Comment by erikamov** [comment]
This issue is probably the same as [#3429](https://github.com/orgs/cal-itp/projects/24/views/1?pane=issue&itemId=77773288)

**Comment by akosmatzon** [comment]
Closing this ticket as it has to do with LittlePay. Some `funding source vault ID` values in **Micropayments** table are not present in the **Customer Funding Source** table, therefore information such as issuer, scheme, etc. cannot be looked up.

Georgia & myself will raise this to LittlePay on our Wednesday (9/18) call.
