### ISSUE TITLE
Enable public/non-public URL field

### ISSUE THREAD

**Issue by fsalemi** [cal-itp/data-infra#3416]
## User story / feature request

Requesting the addition of a new column to [`dim_gtfs_datasets`](https://console.cloud.google.com/bigquery?project=cal-itp-data-infra&pli=1&ws=!1m5!1m4!4m3!1scal-itp-data-infra!2smart_transit_database!3sdim_gtfs_datasets), that marks non-public feeds that we don't want to be published to the [open data pipeline](https://data.ca.gov/dataset/cal-itp-gtfs-ingest-pipeline-dataset/resource/e4ca5bd4-e9ce-40aa-a58a-3a6d78b042bd).

### Acceptance Criteria
The URL that we don't want to be published to the [open data pipeline](https://data.ca.gov/dataset/cal-itp-gtfs-ingest-pipeline-dataset/resource/e4ca5bd4-e9ce-40aa-a58a-3a6d78b042bd) can be filtered out.

### Notes

This would be a categorical dichotomous filed (BOOLEAN) by the name of `private_dataset` that can be `true` or `false`.

**Comment by vevetron** [comment]
True or Null?  That's probably okay?

**Comment by fsalemi** [comment]
> True or Null? That's probably okay?

@vevetron  Yes, it is OK. I will check NULL not False. So I do not need to have False and True or NULL will suffice.
