### ISSUE TITLE
Analyst sees an upgraded version of Metabase

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#3451]
## User story / feature request

As an slack admin,
I would like metabase to be updated to the latest version,
So that it uses the latest slack API to send messages to various slack channels.

### Acceptance Criteria

Metabase is updated to the latest version.

### Notes

From @thekaveman's research:

It looks like this Slack integration API was fixed in v0.48.13: [https://github.com/metabase/metabase/releases/tag/v0.48.13](https://urldefense.com/v3/__https:/github.com/metabase/metabase/releases/tag/v0.48.13__;!!LWi6xHDyrA!4LwIbR9I_UbBWWP-uDODMajzKDOh7aNoIxQYuu3PLFjkK2JtahkW84tUUD_9797Bkx2yCv9UX9Xzp-jxVLKVlg$)

So at a minimum, we would need to upgrade to v0.48.13 to fix the Slack integration issue. (The current version of Metabase is v0.50.25: [https://github.com/metabase/metabase/releases/latest](https://urldefense.com/v3/__https:/github.com/metabase/metabase/releases/latest__;!!LWi6xHDyrA!4LwIbR9I_UbBWWP-uDODMajzKDOh7aNoIxQYuu3PLFjkK2JtahkW84tUUD_9797Bkx2yCv9UX9Xzp-iVIJ9pGg$)

**Comment by ohrite** [comment]
@evansiroky This can be accepted in the following steps:

Visit https://dashboards.calitp.org/
Click on the Gear icon in the top right of the screen
Click About Metabase
Verify that the displayed version in v0.50.26.1
Verify that dashboards work as expected

**Comment by evansiroky** [comment]
It works! For a moment the custom maps didn't work, but looks there was a requirement for a specific response header in order for it to work, but I was able to change that in Google Cloud.
