### ISSUE TITLE
Maintenance Schedule

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#3460]
## User story / feature request

As a data pipeline maintainer,
I want to know when our tools and keys need maintenance,
So I can properly plan for maintenance before things go expire.

### Acceptance Criteria

Caltrans is delivered a spreadsheet listing out all tools and keys. Each of these tools and keys should note how often maintenance is expected and when the next maintenance task should probably occur.

### Notes

Some things that should be in there:

- Metabase
- LittlePay API key rotations
- Composer
- Airflow
- Sentry

**Comment by ohrite** [comment]
@evansiroky for clarity, is this meant to be a living document or a point-in-time report?

**Comment by evansiroky** [comment]
It should be a living document.

**Comment by ohrite** [comment]
Here's a draft schedule: https://docs.google.com/spreadsheets/d/1EdNCbN_hpcTCnog1c0PK1LsYeoXr29zF5Q0jSwtTxqI/edit

@themightychris Could you add some frequencies here?

**Comment by themightychris** [comment]
@ohrite done

**Comment by evansiroky** [comment]
Thanks for creating this initial list. @vevetron and I will begin creating monthly data maintenance GitHub issues noting what parts of the pipeline should probably receive some maintenance.
