### ISSUE TITLE
Bug: MST Taps table view bug

### ISSUE THREAD

**Issue by baudje** [cal-itp/data-infra#358]
**Describe the bug**
MST Tabs table does not load. 

**To Reproduce**
Warehouse views --> MST Tabs --> Error
Warehouse views --> MST Tabs --> Details --> See raw data for MST Tabs --> Error
`MST Tabs table does not load. Name customer_id not found inside t1; failed to parse view 'views.mst_taps' at [24:7]`

**Expected behavior**
A table with data

**Comment by hunterowens** [comment]
Hey @baudje  - I should have deleted that table, I was testing things out but the official table for reference should be `mst_ridership`.
