### ISSUE TITLE
Cleaning out copy of this repo from the bucket holding dags folder

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#37]
Currently, the bucket holding DAG files also has a copy of this repo from some time around Feb 19-24th (see image below). If seems like we remove everything that is not the dags folder, but cc @hunterowens in case it is used in some way. I'm not super familiar with cloud composer, so could be totally wrong here!

![image](https://user-images.githubusercontent.com/2574498/112180768-d8633600-8bc9-11eb-9fb8-363bec7e5fca.png)

**Comment by machow** [comment]
Noticed in this [google cloud doc](https://cloud.google.com/composer/docs/how-to/using/using-kubernetes-pod-operator#troubleshoot)

> Output of the Airflow scheduler and workers:
>   1. Go to the Cloud Composer environment's Cloud Storage bucket. This is bucket where the DAGs are located.
>  2. Review the logs at logs/DAG_NAME/TASK_ID/EXECUTION_DATE.

**Comment by hunterowens** [comment]
I think this is probably from my testing and futzing around w/ gcloud and gh actions

**Comment by machow** [comment]
I finally stumbled on a list of folders composer adds to the bucket (dags, data, logs, plugins)--

https://cloud.google.com/composer/docs/concepts/cloud-storage#folders_in_the_bucket

This made me wonder when things like our data folder is uploaded. Since it seems like the airflow server is only updated when requirements.txt changes. I wonder if that's when the data folder is also synced? I tried re-running the deploy job, but it failed because the requirements.txt file hadn't actually changed..

**Comment by hunterowens** [comment]
the main [deploy](https://github.com/cal-itp/data-infra/blob/main/.github/workflows/push_to_gcloud.yml) job should sync everything in `dags` on the repo to `dags`. hence why `data/agencies.yml` needs to live inside `dags`

The secondary job is run the update requirements.txt command. might be good to change names

**Comment by machow** [comment]
This is what I'm a bit surprised about--`agencies.yml` lives in `airflow/data`. We can sync that to the data folder in the bucket, and it seems like it will be mounted alongside dags (in the `$AIRFLOW_HOME` directory) for worker nodes (screenshot from worker via gcloud shell below). Or maybe it syncs when re-deploying airflow?

![image](https://user-images.githubusercontent.com/2574498/112346362-e2ea0200-8c93-11eb-9265-dd5c9cf83758.png)

In any event, I'll dig a bit deeper to get a feel for how these pieces fit together..

**Comment by machow** [comment]
Okay--the `gcloud composer storage` [CLI docs](https://cloud.google.com/sdk/gcloud/reference/composer/environments/storage) have been pretty helpful here. It looks like it has commands to store dags, plugins, and data, so maybe a good strategy is to sync them in the gh action that uploads the dags.

The kind of funny twist is that the "import" command adds, but doesn't remove old files.

It seems like for now...

* sync `dags`, `plugins`, `data` (including removing old files) in the github action

I'm onboard with having data in the DAGs directory, too--once I get everything synced with the repo, or as the pipeline grows, can definitely move things around.

**Comment by machow** [comment]
Okay--going to pull this thread a bit more. Right now our local setup has AIRFLOW_HOME as the folder holding dags, plugins, and data. But on composer it's set to the airflow user (`/home/airflow`), and a subdirectory has folders like dags, etc.. (`/home/airflow/gcs`). 

Commands run from an operator:

* `os.listdir()`: ['.bash_logout', '.profile', '.bashrc', 'gcsfuse', '.sudo_as_admin_successful', '.config', 'composer_kube_config', 'gcs']
* `os.getcwd()`: /home/airflow

This is causing opening files to work in the local setup, but not composer. Going to try manually setting the AIRFLOW_HOME variable in the composer UI...

**Comment by hunterowens** [comment]
this will be solved in #43

**Comment by hunterowens** [comment]
@machow should we close this issue?

**Comment by machow** [comment]
yeah, seems pretty clear / worked out now
