### ISSUE TITLE
Payments Research: How much revenue from fareboxes

### ISSUE THREAD

**Issue by mjumbewu** [cal-itp/data-infra#370]
## Goal(s)

* Program adoption for open loop payments

## Question

How much revenue comes from Littlepay vs existing farebox?

## Metrics

* Revenue from existing farebox (daily)
* Revenue from existing Littlepay (daily) 

## Data source(s)

* MST Farebox data **(Where does this come from? When can we get it? And at what granularity?)**
* Littlepay (device transactions)

**Comment by machow** [comment]
Related question: how many is it costing on average for a route (e.g. MST variable fare routes), vs the fixed fare for those routes
