### ISSUE TITLE
Payments Research: Discount fare payment methods

### ISSUE THREAD

**Issue by mjumbewu** [cal-itp/data-infra#371]
## Program Goal(s)

* Reduce burden on riders
* Increase equity

## Question

For people who are using a discount, how are they paying for their trip? 

## Metrics

* Discount ride payments by payment method (WEEKLY)

## Data sources

* MST Farebox report **(How automatable is access to this? Is it in a format easy to work with?)**
* Littlepay (micropayments) which shows fare type

**Comment by machow** [comment]
From pairing w/ @mjumbewu, this appears to depend on product_data, and not customer_funding_source, so we should be able to do it? (let's double check to be sure)

**Comment by mjumbewu** [comment]
One part of this is answered on the [dashboard](https://metabase.k8s.calitp.jarv.us/dashboard/29-payments-metrics) already (i.e., the types of fare products being used when one is used). The other interpretation of this question (are people paying with cards or phones) is dependent on customer funding source data (i.e., issue #704).

**Comment by jenro1** [comment]
Note: Data source for "how" riders are paying for their trip is in _customer funding source_ table under "form_factor" (Card, Digital Wallet, Wrist Worn, Non Card)

**Comment by mjumbewu** [comment]
This is implemented on the dashboard by the https://metabase.k8s.calitp.jarv.us/question/259-number-of-adjusted-price-rides-per-week-grouped-by-payment-method chart. Note though that for any chart using `form_factor`, we may have a lot of missing data right now. [From Terry in slack](https://jarvus.slack.com/archives/C0187ATNAG4/p1642674532000400?thread_ts=1642091326.004700&cid=C0187ATNAG4):

> We have an issue where the form factor is not appearing as a value we can interpret. In the data feed, if we see a value we can't interpret we set it to `null`. Most of your null values are due to this. The raw data looks like below. Once the issue is resolved you should see only a few `null` values, which will probably be due the card issuer not providing the `form_factor`.
> <img width="409" alt="Screenshot 2022-01-20 at 10 27 30" src="https://user-images.githubusercontent.com/146749/151594599-175c9dbd-2080-4c02-a43c-9adb318baf8c.png">

It's an issue that LittlePay is working on on their side.
