### ISSUE TITLE
Payments Research: Prevalence of riders hitting fare caps

### ISSUE THREAD

**Issue by mjumbewu** [cal-itp/data-infra#372]
## Goal(s)

* Reduce burden on riders
* Increase equity

## Question

For people using contactless, how many people are being auto-fare capped?

## Metrics

* % of unique customers who (1) are using contactless payment, and (2) hit the fare capping limit **(daily? weekly? should those be considered separately? together?)** compared to total unique customers (MONTHLY) 

## Data sources

* Littlepay (micropayments) which shows fare type
* Littlepay (micropayment adjustments) which shows fare caps
* Littlepay (device transactions) which shows route/bus
* **No source for total _unique_ riders at the moment?**

## Presentation(s)/Visualization(s) needed

**Comment by machow** [comment]
Because this is % of unique riders, this requires customer funding source

**Comment by mjumbewu** [comment]
This is now available in the https://metabase.k8s.calitp.jarv.us/question/260-percent-of-riders-with-adjustments-per-week-grouped-by-adjustment-type chart on the dashboard.
