### ISSUE TITLE
Move calitp_feed_name, calitp_feed_id to the far left of dim feeds 

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#376]
We should keep the most commonly used columns as far left as possible. Let's order the table as...

* feed_key (always keep the keys first)
* calitp_feed_name, calitp_feed_id
* remaining table columns

**Comment by lauriemerrell** [comment]
I am going to close this, not clear to me that `feed_id` or `feed_name` are more commonly used than `itp_id` and `url_number` (current first two columns). Don't think we need to do this.
