### ISSUE TITLE
Allow users on jupyterhub cloud to publish their analyses as e.g. voila dashboards

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#387]
TODO: is there a quick way for us to implement this? This doesn't need to happen right away, but let's keep an eye on it as a next step after deployment.

**Comment by atvaccaro** [comment]
Will this be resolved by https://github.com/cal-itp/data-analyses/pull/103?

**Comment by holly-g** [comment]
Yes!

**Comment by atvaccaro** [comment]
closing! analysis.calitp.org is up
