### ISSUE TITLE
Bug: littlepay data sync needs to remove files from destination, copy to subfolder

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#394]
**Describe the bug**

Currently, when we sync littlepay data for MST via a [data transfer job](https://console.cloud.google.com/transfer/cloud/jobs/transferJobs%2F14397376673459736076/configuration?authuser=0&project=cal-itp-data-infra). However, this job currently does not delete files from the destination that are not in source. This means causes issues with us keeping data that no longer exists (or was shuffled into a different file).

@hunterowens can you change delete "never", to remove unmatched files in destination? I don't think we have the keys for it (or if you send to me I can update the job).

![image](https://user-images.githubusercontent.com/2574498/134537629-f7a2fabd-28cd-40e6-a764-116740e03180.png)

**Comment by hunterowens** [comment]
also gave michael credentials

**Comment by machow** [comment]
@mjumbewu when you get the chance, can you make a new job that transfers littlepay MST data to a subfolder of littlepay-data-extract-prod, and then delete the original job?
