### ISSUE TITLE
Bug: Some rail routes appear missing from gtfs_schedule_dim_routes

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#396]
LA Metro and BART both operate heavy rail service, and describe it with `route_type == 1` in their [routes.txt](http://transitfeeds.com/p/la-metro/677/latest/file/routes.txt), however these routes don't seem to appear in gtfs_schedule_dim_routes. Additionally, I can't seem to locate LA Metro light rail service (`route_type == 0`), although other light rail operators do appear.

**To Reproduce**
1. View gtfs_schedule_dim_routes on Metabase; filter or show distribution of route_type
2. No routes appear with `route_type == 1`
3. Filter gtfs_schedule_dim_routes by `route_type == 0`
4. See distribution of agency names, LA Metro does not appear

**Expected behavior**
Several routes with `route_type == 1` corresponding to BART and LA Metro heavy rail routes
LA Metro light rail routes appearing when filtering by `route_type == 0`

**Comment by hunterowens** [comment]
Possible thought: since LA Metro has 2 GTFS feeds, we only load the bus schedule data (unlike every other agency that has multiple feeds, Metro has different service in each feed

**Comment by hunterowens** [comment]
cc @machow @charlie-costanzo @chriscardillo

**Comment by machow** [comment]
Thanks for raising--dim routes joins in agency information, but was improperly handling when an agency didn't provide agency data. I merged a PR to resolve a few days ago.

The pipeline has been having some intermittent failures over the last few days, so hasn't caught up to the changes. I'll clear and re-run everything now to get things up to date..

**Comment by machow** [comment]
Should be resolved now. @edasmalchi do you mind double checking on your end?

Here's a count of metro route types in our load of the latest raw data (note there are two route type == 1 rows)...

![image](https://user-images.githubusercontent.com/2574498/134711789-07db59c7-f9d7-4cb0-953d-114a20e5af84.png)

And here's filtering for route type 1 on metabase...

![image](https://user-images.githubusercontent.com/2574498/134711917-f5141c3d-6c65-4f53-8882-25c802d303f4.png)

**Comment by edasmalchi** [comment]
@machow Looks good to me, thanks!

Also I think I figured out why BART ended up with route type 2 not 1-- we must be loading MTC's regional GTFS feed? That has route type 2 for BART; BART's own feed has 1. Interesting to know, but probably not pressing.
