### ISSUE TITLE
Ensure payments demo agencies have GTFS RT urls in agencies.yml

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#400]
While we resolve questions about the payments data, let's make sure we have RT feed urls for the demo payments agencies. 

TODO: document the agencies

**Comment by hunterowens** [comment]
1) MST - monterrey salinas transit 
2) SBMTD - Santa Barbara Municipal Transit District 
3) Clean Air Express 
4) SacRT - Sacramento

**Comment by machow** [comment]
Thanks! I coded 4 that I could find with itp ids in this PR, and we can add any missing there..

https://github.com/cal-itp/data-infra/pull/401/files#diff-9636b37b7a066aea89bf0fd4331fec67112844dbc690f8c6db4cf3d211253999
