### ISSUE TITLE
Remove amtrak and tulare from views.reports_gtfs_schedule_index

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#402]
This view holds a row per report we'll generate (e.g. report for X feed in may is a row). If Amtrak and Tulare aren't supposed to have reports generated, then we'll need to filter them from here.

https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/reports_gtfs_schedule_index.sql

**Comment by evansiroky** [comment]
Fixed by https://github.com/cal-itp/data-infra/pull/781
