### ISSUE TITLE
Plan structure of datasets documentation / complete gtfs schedule datasets doc

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#404]
Now that @charlie-costanzo is wrapping up a tutorial page, let's be sure to plan exactly what users should see on https://docs.calitp.org/data-infra/datasets/gtfs_schedule/.

Key factors:

* We're using kimball style data modeling, so they'll need to understand what a dimension is (doesn't necessarily need to be on that page, but could be)
* need to know how to look up facts
* need to know key dimension tables
* maybe a graph of a fact table and the dimension tables it links to, to give a feel for a star schema

Misc:

* Listing out kicking tires on gtfs schedule dashboards
* Chasing me down for GTFS Schedule DAG docs (TODO: link to GTFS Schedule DAG run through issue, which lays out some of its key dynamics)

**Comment by tiffanychu90** [comment]
I can help out with as a good intro to the GTFS datasets in BigQuery, as it's just Markdown and doesn't require too much setup while I'm waiting for my state laptop!

**Comment by machow** [comment]
closed in favor of #660
