### ISSUE TITLE
Disable user scheduler in Jupyterhub

### ISSUE THREAD

**Issue by lottspot** [cal-itp/data-infra#410]
The "[user scheduler](https://alan-turing-institute.github.io/hub23-deploy/advanced/optimising-jupyterhub.html#using-available-nodes-efficiently-user-scheduler)" in Jupyterhub is a feature which schedules user pods on the most utilized node in the cluster. While this plays well in environments which have node autoscaling enabled, we do not have such autoscaling configured. This consequently causes node over-utilization and an eventual failure to schedule altogether once the node becomes full.

**Comment by ccjarvus** [comment]
Done!
