### ISSUE TITLE
Jupyterlab v2 release - improve security, easier google auth

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#419]
Once we merge @ccjarvus's jupyterlab service, we should have a working MVP. However, it will have two challenges:

* Users will need a service key to access the warehouse. Not ideal, since our logs will show every query as coming from the service user. We should use google auth instead.
* Our app secrets will have to be set by inf manually before deploying. We should use something like sealed secrets instead.

**Comment by machow** [comment]
@lottspot quick check--is sealed secrets implemented in the cluster? (Also, feel free to close this is it's a low priority / seems okay using the current variable setting approach).

Note that google auth was improved by just using gcloud on the hub

**Comment by lottspot** [comment]
We have #423 concerning sealed secrets; closing this issue since it has been otherwise addressed.
