### ISSUE TITLE
Exploring Current Reporting Process

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#456]
Getting familiar with existing process, credentials work, play around with existing reports, etc

**Comment by machow** [comment]
@charlie-costanzo I'm not sure what the acceptance criteria / outcome is here. Can this be closed, or is more needed?

**Comment by charlie-costanzo** [comment]
@machow yes it can be closed - sorry, this was a very vague issue. I think this can be closed in favor of [this issue tracking a reports hand-off call](https://github.com/cal-itp/data-infra/issues/463).
