### ISSUE TITLE
Explore expanding the reporting process to include more of the information that we're already publishing

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#457]
Hunter has mentioned adding charts to our reporting related to what's already being published in NTD, fares, etc. We should take time to explore what information we currently have available and whether it should be included in the reports we produce. 

This should likely be accomplished in a meeting between Tiffany, Hunter, and Michael.

**Comment by holly-g** [comment]
This appears to be good to close out !
