### ISSUE TITLE
Feature: join product data into ~~sbmtd~~ *full data* view

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#477]
From Jennie [via slack](https://cal-itp.slack.com/archives/C02CYPQKHH8/p1634083710037700), it would be useful to have product information in `views.sbmtd_transactions`.

AFAICT this could either happen through `device_transaction_purchase` OR `micropayments_adjustments`. Once we have some example questions to answer, we should be able to try the joins!

**edit:** let's also join it in to views.mst_transactions

**Comment by machow** [comment]
Question to answer:

* Employees register through magic link
* Littlepay manually adds to a concession group (tracked in productdata)
* All of them have a product applied to them
* Want to tell SBCAG Which are unique each week ($150 rolling cap, charging these people $75)

**Comment by machow** [comment]
@mjumbewu was this addressed by https://github.com/cal-itp/data-infra/pull/673? :)

**Comment by mjumbewu** [comment]
@machow Not entirely. This is in the new `payments_rides` view but not the `sbmtd_transactions` view. The SBMTD view has a best guess of which route each transaction was on, for those transactions without route data. We could pretty easily add the product data into the `sbmtd_transactions`, if the `payments_rides` table isn't good enough.

**Comment by mjumbewu** [comment]
I'm going to close this as a won't-do issue for now. The data that we're sending to MTD is [now from the rides table](https://cal-itp.slack.com/archives/C02CYPQKHH8/p1645746300143189?thread_ts=1645739864.232739&cid=C02CYPQKHH8), which already includes product information. If we ever need to go back and provide data for the other table, we can easily join it in manually.
