### ISSUE TITLE
Improving the Infra Docs Homepage

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#478]
The welcome page is a placeholder. Since it's the first page people see, it's a big opportunity to improve the content of the docs.

https://docs.calitp.org/data-infra/

Currently inaccurate - it doesn't reflect our current views data structure with dim/fact tables, etc.

**Comment by Nkdiaz** [comment]
On hold, until we decide when we want to fully redo the documentation per @charlie-costanzo  design/instruction into a separate section for analysis and infrastructure. The homepage will be part of that larger documentation overhall

**Comment by machow** [comment]
@charlie-costanzo assigning to you, but feel free to close if this is covered by other issues, etc..!

**Comment by holly-g** [comment]
It looks like there have since been some changes made to the homepage. I'm in favor of closing this issue now and revisiting any design changes/discussion during the next technical doc review call.
