### ISSUE TITLE
Automatically drop issues with 'new team member' into this board (with workflows?)

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#488]
from @thekaveman

> are you working on an Actions workflow to do this project assignment? I'd be interested in that too for a couple other repos...
> 
> We have the cal-itp/.github repo, where common workflow templates can be stored and more easily re-used across other projects. Want to put it in there?

**Comment by machow** [comment]
Looping back to what I think Kegan suggested at one point--this action looks like it should do it...

https://github.com/marketplace/actions/automate-projects

**Comment by machow** [comment]
Addressed in #501 -- @charlie-costanzo WDYT, are there other github events you want to move things onto the board? It's pretty quick to add.

**Comment by machow** [comment]
Pushed some changes and tested--it looks like it works with "new team member" and "analytics research"!
