### ISSUE TITLE
analyze feeds that fail to download

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#49]
Now that @mcplanner is back, we should try and analyze why the following feeds are failing. @machow can also pull some downloader log stats to help inform this. 

The follow agencies failed to have GTFS a GTFS feed atthe URL or the Zip File Failed to extract:['e-Tran', 'Foothill Transit', 'Manteca Transit', 'Menlo Park Shuttles', 'Paso Express', 'San Luis Obispo Regional Transit Authority', 'South County Area Transit', 'Tri Delta Transit', 'Tri-Valley Wheels']{{ ds }}

**Comment by machow** [comment]
Hey--dumping a more complete table for feeds that failed to download, so we can reference. Happy to investigate any rows :)

|                                             | agency_name                                 | status           | gtfs_schedule_url                                                                                                                            |   itp_id |
|:--------------------------------------------|:--------------------------------------------|:-----------------|:---------------------------------------------------------------------------------------------------------------------------------------------|---------:|
| ac-transit                                  | AC Transit                                  | HTTP error: 401  | https://api.actransit.org/transit/gtfs/current?token=2512B8179D2DC44895CDDC6D42                                                              |        4 |
| b-line                                      | B-Line                                      | HTTP error: 404  | http://www.blinetransit.com/documents/google_transit.zip                                                                                     |       48 |
| clean-air-express                           | Clean Air Express                           | HTTP error: 404  | http://www.cleanairexpress.com/GTFS7.24%COVID-19%CAE%GTFS.zip                                                                                |      nan |
| culver-citybus                              | Culver CityBus                              | HTTP error: 404  | https://www.culvercity.org/home/showdocument?id=169                                                                                          |       87 |
| dinuba-area-regional-transit-               | Dinuba Area Regional Transit                | HTTP error: 404  | https://tularecog.org/tcag/data-gis-modeling/gis-project-and-data/gtfs-data-as-of-june-19-/dart-dinuba-area-regional-transit-gtfs/           |       93 |
| grapeline                                   | Grapeline                                   | HTTP error: 404  | http://www.mjcaction.com/MJC_GTFS_Public/lodi_google_transit.zip                                                                             |      168 |
| long-beach-transit                          | Long Beach Transit                          | HTTP error: 404  | https://lbtransit.box.com/shared/static/aoyeskwmsa9g7pyg78q3xuiolgqe4f.zip                                                                   |        1 |
| manteca-transit                             | Manteca Transit                             | HTTP error: 404  | https://www.ci.manteca.ca.us/mantecatransit/googletransit/google_transit.zip                                                                 |      192 |
| menlo-park-shuttles                         | Menlo Park Shuttles                         | HTTP error: 404  | https://www.menlopark.org/DocumentCenter/View/73/google_transitzip                                                                           |      199 |
| paso-express                                | Paso Express                                | HTTP error: 404  | http://app.mecatran.com/urb/ws/feed/c2ZT1zbGcmFuc2O2NsaWVudD1zZWxmO2V4cGlyZ7dHlwZT1ndGZzO2tlezZTMwMzM1OTRiMTE2NzN2IxNjQwNjZjQwMGMzMzdiM2E1MT |      244 |
| slo-transit                                 | SLO Transit                                 | HTTP error: 404  | http://app.mecatran.com/urb/ws/feed/c2ZT1zbGcmFuc2O2NsaWVudD1zZWxmO2V4cGlyZ7dHlwZT1ndGZzO2tlezZTMwMzM1OTRiMTE2NzN2IxNjQwNjZjQwMGMzMzdiM2E1MT |      287 |
| san-luis-obispo-regional-transit-authority  | San Luis Obispo Regional Transit Authority  | HTTP error: 404  | http://app.mecatran.com/urb/ws/feed/c2ZT1zbGcmFuc2O2NsaWVudD1zZWxmO2V4cGlyZ7dHlwZT1ndGZzO2tlezZTMwMzM1OTRiMTE2NzN2IxNjQwNjZjQwMGMzMzdiM2E1MT |      289 |
| santa-clara-valley-transportation-authority | Santa Clara Valley Transportation Authority | HTTP error: 404  | http://www.vta.org/sfc/servlet.shepherd/document/download6901NUea                                                                            |      294 |
| south-county-area-transit                   | South County Area Transit                   | HTTP error: 404  | http://app.mecatran.com/urb/ws/feed/c2ZT1zbGcmFuc2O2NsaWVudD1zZWxmO2V4cGlyZ7dHlwZT1ndGZzO2tlezZTMwMzM1OTRiMTE2NzN2IxNjQwNjZjQwMGMzMzdiM2E1MT |      388 |
| tri-delta-transit                           | Tri Delta Transit                           | Misformatted url | http://.232.147.132/rtt/public/utility/gtfs.aspx                                                                                             |      336 |
| foothill-transit                            | Foothill Transit                            | failed to unzip  | http://foothilltransit.org/about/developer-resources/gtfs/                                                                                   |      112 |
| gold-country-stage                          | Gold Country Stage                          | failed to unzip  | http://data.trilliumtransit.com/gtfs/goldcountrystage-ca-us                                                                                  |      221 |
| metro                                       | Metro                                       | failed to unzip  | https://gitlab.com/LACMTA/gtfs_bus                                                                                                           |      182 |
| metro                                       | Metro                                       | failed to unzip  | https://gitlab.com/LACMTA/gtfs_rail                                                                                                          |      182 |
| tri-valley-wheels                           | Tri-Valley Wheels                           | failed to unzip  | https://www.wheelsbus.com/about/developers/                                                                                                  |      167 |
| tulare-county-area-transit                  | Tulare County Area Transit                  | failed to unzip  | http://data.trilliumtransit.com/gtfs/tcat-flex-ca-us                                                                                         |      346 |
| e-tran                                      | e-Tran                                      | failed to unzip  | https://share.elkgrovecity.org/messages/tpLyuetXMvzjM8oongDM5C/attachments/LbeTBVJuC2Eh3QPKIH6k7R/download/ETRAN_GTFS_15.zip                 |        5 |

**Comment by mcplanner** [comment]
- Foothill should be: http://foothilltransit.org/gtfs/foothilltransit-ca-us.zip
- The three Mectran agencies have similar issues. I'll try to reach out to them through one of the above agencies.
- Tri Delta and Wheels both have versions of their feed through MTC's API. Perhaps we should use those in addition?
- E-Tran's is behind a login, but I believe Sacramento is taking over it.
- I couldn't find Manteca and Menlo Park's.

**Comment by mcplanner** [comment]
Manteca: https://www.ci.manteca.ca.us/CommunityDevelopment/MantecaTransit/googletransit/google_transit.zip

**Comment by mcplanner** [comment]
I emailed a contact Aaron provided with SLORTA to find the others.

**Comment by mcplanner** [comment]
In PR #214 
* Updated Foothill, Manteca
* Removed E-Tran (they're part of SacRT now)
* Tri Delta and Wheels were already resolved
* South County and Paso Express are part of SLORTA, so I removed those entries as duplicates

**Comment by mcplanner** [comment]
Next steps: update with new daily report

**Comment by mcplanner** [comment]
We're down to four:
<img width="672" alt="Screen Shot 2021-07-28 at 11 59 39 AM" src="https://user-images.githubusercontent.com/830005/127380615-ea14c49a-74a1-4c34-aeb9-fdfb98cbb130.png">

I attempted to resolve three with PR #230 and contacted the agency about the fourth.
