### ISSUE TITLE
Bug: Sacramento RT does not appear in gtfs_schedule_fact_daily_service

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#498]
**Describe the bug**
Sacramento RT does not appear in gtfs_schedule_fact_daily_service

**To Reproduce**
1. Filter gtfs_schedule_fact_daily_service to itp_id == 273
2. No records appear

**Expected behavior**
Sacramento RT service data appearing.

**Comment by Nkdiaz** [comment]
Associated with https://github.com/cal-itp/data-infra/issues/914
