### ISSUE TITLE
Ingest LAX Flyaway GTFS feed in agencies.yml

### ISSUE THREAD

**Issue by mcplanner** [cal-itp/data-infra#499]
This isn't a clean URL so I'm not sure how to paste it in. It's a Box link, and the Download button has to be clicked to tigger the download.

https://cloud1lawa.app.box.com/s/oldkeg2ykj6c9pxj3ysq15ndngmsdw55

**Comment by holly-g** [comment]
@Nkdiaz, can you take on this ticket?

**Comment by holly-g** [comment]
`itp_id: 165` 

(according to[ this](https://calitp.teamwork.com/crm/companies/28832))

**Comment by holly-g** [comment]
@hunterowens any updates on #220?

**Comment by o-ram** [comment]
@holly-g here is the URL for the LAX Flyaway feed https://www.flylax.com/-/media/flylax/flyaway/gtfs/google_transit.ashx Could you please make sure it ends up in agencies.yml? I already updated the feed in Airtable, and I can confirm that the Flyaway's ITP_ID is 165.

Thank you!
