### ISSUE TITLE
Pipelining strategy for ingesting / access to a range of data sources

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#511]
see [this slack thread](https://cal-itp.slack.com/archives/C02H6JUSS9L/p1634307911002600). Can we do the following?

* collect a list of data sources we might ingest
* specify how often they might get used?
* explore what they look like when used with `intake`?

Potential concerns:

* if it goes into bigquery, will we have too many data sources?
* how will we document the data?
* how processing heavy will things be? (and what should we do with processing heavy things?)
* what conventions are needed for data stored outside bigquery?

Related issues:

* cal-itp/data-analyses#162

**Comment by machow** [comment]
@evansiroky @hunterowens, I've set up a bucket and tested logging in via gcloud on jupyter hub. It looks like giving users access via gcloud works and is somewhat straightforward. (see #526).

For storage, what do you think of this?

## One-off analysis data

* stored in `gs://calitp-analytics-data/data-analyses/<analysis name>`
* `<analysis name>` should be the same as the folder used on https://github.com/cal-itp/data-analyses
* final analysis should access the data from that bucket
* we create a PR template for "publishing" with checkboxes for
  - all data is checked in to the bucket
  - kernel restarted / re-run, with no errors
  - an html or pdf version with no code inputs shown is committed alongside notebook (I can add an option for this to jupyterlab if it's not already easy to do)

## Common data

* Stored in `gs://calitp-analytics-data/shared/<some name TBD>`
* Uses intake to handle reading into notebook / cataloging
* I create a new issue to investigate intake / someone presents on it in the all-hands, etc..?
* Big and useful things
  - easy for analyst to see what data can be loaded
  - easy to add new data (e.g. doesn't require infra to redeploy a jupyterlab image)
  - handles a variety of formats (even if this requires installing dependencies / redeploying images)

**Comment by tiffanychu90** [comment]
I like this idea!

I may need a bit of pair programming to make sure I can upload / download files from the bucket. Specifically, folders when it's a shapefile, and if we choose to use geoparquet as a file format.
