### ISSUE TITLE
Put up quarterly dashboard metrics prototype

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#512]
## Breaking up work on metrics

* for each item [in this doc](https://docs.google.com/document/d/1FoWNYY1cxxuq3sQJWrFHyAC07SkdeySaVxD6ZhT-RP4/edit#heading=h.aoegc1pn3k33) create an issue using this [research request issue template]
  - copy the metric, and fill out the data source
  - if the data source does not exist, mark it blocked
  - name the issue: `metric: <some useful title or the question itself>`
  - if the metric is unclear, label it refinement
* prioritize the list of questions

## Working out ingest

* Create issue for an airflow ingest operator

## Misc

* How does Evan's feedback get worked into / apply to MSD dashboard specs?

## Prototyping w/ Metabase

* @e-lo flagged that stakeholders may need to see metrics in a way metabase is not well suited (e.g. low visual clutter, browsable from the web).
* Let's knock these issues down one-by-one in a metabase dashboard first as a prototype. This will give us a fast feedback loop to ensure we've chased down all sources / are doing the right calculations.
* If a metric doesn't match what the group expects, metabase makes it easy to see how exactly it was calculated.

**Comment by holly-g** [comment]
See https://github.com/cal-itp/data-infra/issues/1781
