### ISSUE TITLE
Make mermaid text in diagram more readable 

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/data-infra#522]
Currently, text in the mermaid diagrams in the documentation is really hard to read. It should be easily able to view or atleast give the option to zoom into the diagram.
![image](https://user-images.githubusercontent.com/32888103/137933820-32533e82-1128-4c78-bca1-866d8d541061.png)

**Comment by themightychris** [comment]
@machow @Nkdiaz so it looks like right now, you can click the chart to load it into the mermaid-live-viewer and then you can click the "View" button to get it open full screen, where you can zoom and pan freely and everything scales really nicely as vectors. I think that's going to be the best bet for now.

There are ways to override font sizes in mermaid, but then we need to be applying CSS classes to properly target them, and then different scopes might need to be different sizes, and then people will edit the chart and then need to update font sizes...trying to "design" mermaid gets out of hand pretty quickly and drifts away from the whole value prop of mermaid just being text in markdown. IMHO once you start thinking about optimizing font sizes/spacing/layout, the question to ask is: is this diagram complicated AND valuable enough that it should be custom designed? If so, make it in Figma or another design tool instead and then embed the SVG. Mermaid is for not designing.

What we might get a lot of utility out of though could be something like a floating button in the corner of all markdown renderings in the docs to open the SVG fullscreen in a tab. It would be cool if the plugin handling rendering mermaid in this docs system had a feature for that. Maybe it does, or maybe we could be successful just opening an issue requesting it? Failing that, we might implement the feature ourselves and try to upstream it through a PR, or I imagine the docs system has a way to let us embed arbitrary javascript and we could rig something pretty simple up with that.

**Comment by machow** [comment]
Going to close for now, since it's a lot of work, and the big value of mermaid is in quick diagrams
