### ISSUE TITLE
Set up GCS bucket for transit service increase research

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#526]
Could we get a GCS set up to check in files? Potentially some large files (like LEHD) could run into GitHub size issues

**Comment by machow** [comment]
@tiffanychu90, do you mind testing out this authentication process?

https://www.loom.com/share/6883b0bf9c8b4547a93d00bc6ba45b6d

I'm going to write-up a proposal for how we could store / access

* one-off datasets for reports
* common data

But want to make sure the access piece is worked out in the meantime!

**Comment by tiffanychu90** [comment]
Thanks @machow. Running `gcloud auth application-default login` worked and showed this. I was able to use pandas to read in the test csv:
```
Credentials saved to file: [/home/jovyan/.config/gcloud/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).

Quota project "cal-itp-data-infra" was added to ADC which can be used by Google client libraries for billing and quota. Note that some services may still bill the project owning the resource.
```

**Comment by machow** [comment]
Should be working now! cc @charlie-costanzo in case anyone has permissions issues. See https://docs.calitp.org/data-infra/warehouse/jupyterhub.html#uploading-data
