### ISSUE TITLE
Break out #data-infra Slack channel into two channels

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#529]
As of now, roughly 90% of the messages in the #data-infra Slack channel are from the automated Github notification feed for new issues. For the sake of maintaining a place that encourages conversation among team members,  I would suggest we break it out into two channels:
* #data-infra for conversation
* #data-infra-issues for Github notifications

**Comment by machow** [comment]
From stand-up: @evansiroky is a slack admin, so wields the power to rename #data-infra to #data-infra-issues!
