### ISSUE TITLE
Non-existent urls for gtfs-rt feeds

### ISSUE THREAD

**Issue by lottspot** [cal-itp/data-infra#535]
Several of the domains for gtfs-rt feeds in `agencies.yml` do not resolve. Each offending domain and the feeds which point to it (identified in the form `{itp_id}/{index}/{feed_name}`) are listed below.

**ridemvgo.net**
- `217/0/gtfs_rt_service_alerts_url`
- `217/0/gtfs_rt_trip_updates_url`

**presidiobus.net**
- `217/0/gtfs_rt_vehicle_positions_url`
- `257/0/gtfs_rt_service_alerts_url`
- `257/0/gtfs_rt_trip_updates_url`

The following domain shows a "No route to host" error:

**api.octa.net**
- `235/0/gtfs_rt_vehicle_positions_url`
- `235/0/gtfs_rt_trip_updates_url`
- `235/0/gtfs_rt_service_alerts_url`

**Comment by holly-g** [comment]
Research is needed on how to parse out the logs. Can stub this out for next sprint.

**Comment by machow** [comment]
related to https://github.com/cal-itp/data-infra/issues/868

**Comment by evansiroky** [comment]
This is resolved and related also to #536.
