### ISSUE TITLE
4xx response from gtfs-rt feed URLs

### ISSUE THREAD

**Issue by lottspot** [cal-itp/data-infra#536]
Several of the URLs for gtfs-rt feeds in agencies.yml return 4xx responses. Each offending URL and the feed which is associated with it (identified in the form `{itp_id}/{index}/{feed_name}`) is listed below.

**HTTP 404 Not Found**
- `4/0/gtfs_rt_trip_updates_url`:  `https://api.actransit.org/gtfsrt/tripupdates?token=[redacted]`
- `4/0/gtfs_rt_service_alerts_url`: `https://api.actransit.org/gtfsrt/alerts?token=[redacted]`
- `4/0/gtfs_rt_vehicle_positions_url`: `https://api.actransit.org/gtfsrt/vehicles?token=[redacted]`

**HTTP 401 Unauthorized**
- `98/0/gtfs_rt_trip_updates_url`:  `http://api.511.org/transit/tripupdates?api_key=[redacted]&agency=DE`
- `98/0/gtfs_rt_vehicle_positions_url`: `http://api.511.org/transit/vehiclepositions?api_key=[redacted]&agency=DE`

**Comment by machow** [comment]
@Nkdiaz if you wrap up emailing, let's have you look into how to pull logs to answer this question:

* from the logs, which feeds are failing to download?

**Comment by machow** [comment]
From pairing with @Nkdiaz -- we can see the errors in the UI

* what is a query we can write in the logger to get all the errors for the day?
* then, let's write a script that when run fetches all of the errors from the logger for a specified day

**Comment by Nkdiaz** [comment]
From today we can still verify errors from the following calitp ids:
4- AC Transit
98- Dumbarton Express
235-Orange County Transportation Authority
Here is the link to see it in the logs [https://console.cloud.google.com/logs/query;cursorTimestamp=2021-12-10T15:52:33.722471682Z;query=timestamp%3D%222021-12-10T15:52:33.685191481Z%22%0AinsertId%3D%22h4udchczimw32hdn%22?project=cal-itp-data-infra](url)

**Comment by Nkdiaz** [comment]
@machow This might be worth a longer conversation on what we are determining as an error within the log. Right now we are treating the http error with an Info tag rather than Error or Warning tag. I am sure there are other errors in the log we might be similarly missing. We are also counting some things as errors that I would assign different tags, such as each time there is a new connection.

**Comment by machow** [comment]
From pairing--looks like we can also export cloud logging straight to bigquery: https://cloud.google.com/logging/docs/export/bigquery

**Comment by machow** [comment]
We were able to create a test sink -> bigquery, so we can query the logs directly and transform.

To check: I didn't see any INFO severity level logs. It should print one log per attempted download. Let's double check that we can see them in the logger UI, and then figure out how / where we want to pull those in.

https://console.cloud.google.com/logs/router?project=cal-itp-data-infra

**Comment by evansiroky** [comment]
This is mostly resolved now due to the work in:

- #905
- #906
- #907

The URLs we have for AC Transit's URLs are what is noted as the proper endpoint in the [AC Transit API Documentation](http://api.actransit.org/transit/Help).
