### ISSUE TITLE
Screencast in docs showing how to pull and push to github from jupyterhub

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#547]
* Getting an authentication token
* Go through pulling data-analyses repo
* Go through pushing to the repo

**Comment by holly-g** [comment]
@charlie-costanzo, do you think we've sufficiently covered this in the [docs](https://docs.calitp.org/data-infra/analytics_tools/saving_code.html?highlight=push#pulling-and-pushing-changes )? 
should we close this?
