### ISSUE TITLE
Fares Validator

### ISSUE THREAD

**Issue by mcplanner-zz** [cal-itp/data-infra#55]
The quickest way for us to produce fares data (for small agencies at least) is to manually produce it in a spreadsheet. This is fast but error-prone, so having a basic rules-checker would be desirable. We should confirm if this is something MobilityData is planning to build, or if there are other existing tools we can use.

**Comment by mcplanner** [comment]
This may be irrelevant if we decide to deploy a fare data creation tool. Moving to "waiting" until that tool is selected.

**Comment by evansiroky** [comment]
There now exists a Fares v2 validator: https://github.com/TransitApp/gtfs-fares-v2-validator We should integrate this into our static feed pipeline.

**Comment by holly-g** [comment]
@chriscauley, putting this in your backlog!

**Comment by holly-g** [comment]
Notes from meeting with Evan today: we can icebox this. This is not a requirement for payments.

**Comment by evansiroky** [comment]
Closing as Fares v2 validation is part of the canonical validator.
