### ISSUE TITLE
Post airflow task failures to a slack channel

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#550]
Currently we email airflow task failures to Hunter and I. However, as DAGs grow / domains are added, it will be useful to have task success / failures out and convenient to access for everyone.

Chris C walked me through the process, and it seems fairly straightforward to set up. His advice was to not use the airflow provided tooling, since making the request to the slack API is straightforward (and airflow tools can get surprisingly weird).

**Comment by machow** [comment]
Checking on this, but AFAICT we can use the on_failure_callback in the task default should do it. 

This should enable messages:

*  use the requests with an environment variable for the slack token or URL we'll need for posting.
* set on_failure_callback to be our message posting function
  * need to add in default_args when calling create_dag here: https://github.com/cal-itp/data-infra/blob/main/airflow/dags/dags.py#L119

Relevant docs:

* [Dag class docs](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/dag/index.html?highlight=dag#airflow.models.dag.DAG)
* [Baseoperator docs](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/index.html?highlight=baseoperator#airflow.models.BaseOperator)

**Comment by holly-g** [comment]
See #data-infra-alerts
