### ISSUE TITLE
GTFS Guidelines: Presence of GTFS-RT feeds

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#566]
## Question

Does the provider publish all three versions of standard GTFS Realtime consistent with the GTFS Realtime Best Practices (Trip Updates, Vehicle Positions, and Alerts)?

See also #554.

## Metrics

* A provider is considered to have a complete set of associated GTFS-Realtime feeds if the existence of all three types of GTFS-Realtime feeds (Trip Updates, Vehicle Positions, Service Alerts) can be confirmed.

## Data sources

* Airtable via data warehouse?

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by machow** [comment]
Hey--looking at this in more detail on the airtable. It appears the calculation for this metric exists as `services.Realtime Status`.

[I've added a quick example analysis to this notebook](https://github.com/cal-itp/data-analyses/blob/main/airtable_explore/0_gtfs_rt_org_service.ipynb)

### Presence Service level GTFS RT feeds

Digging deeper, there are three rollup columns on the `services` table, based on `services data`:

* TripUpdates Status
* VehiclePostitions Status
* Alerts Status

It seems like this is sufficient to count the presence of GTFS RT feeds **per service**? Here is a count of services in the airtable marked as having complete GTFS RT feeds:

![image](https://user-images.githubusercontent.com/2574498/142494376-54e5ac98-bf10-47de-822a-49e377b478aa.png)


### Presence of provider level GTFS RT feeds 

AFAICT the provider level question just involves aggregating services grouped by provider organization.

Here's the number of services per organization

![image](https://user-images.githubusercontent.com/2574498/142494193-ca5f14ec-f2f0-446f-b136-7960f4e887b1.png)

And here is a count of the proportion of services with GTFS RT coverage within organizations

![image](https://user-images.githubusercontent.com/2574498/142494261-d6826276-4184-4235-8a80-85b3527a2c5e.png)

### Number of GTFS feeds  in agencies.yml

Note that this is just looking at the number of feeds with rt urls specified, and not those successfully downloading

![image](https://user-images.githubusercontent.com/2574498/142515253-257ec1aa-2426-441e-b207-bd47048492e0.png)

**Comment by evansiroky** [comment]
The latest assessment instructions say to check the GTFS Guidelines dashboard on metabase, so closing as complete for this iteration.
