### ISSUE TITLE
GTFS Guidelines: completeness of Trip Updates feed

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#569]
## Question

What percent of scheduled trips that are currently active have an associated record in the trip updates feed?

## Metrics

1. Calculate all trips that should be active at the current time
2. See what percent of these trips have a trip update record in the trip updates feed

## Data sources

* static GTFS
* trip updates feed

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by machow** [comment]
This question should be answerable through PR https://github.com/cal-itp/data-infra/pull/840, which would pull out all cardinality one fields from tripUpdates.

**Comment by evansiroky** [comment]
Closing as it is expected that #570 will provide information in this regard. Will reopen if further investigation is needed.
