### ISSUE TITLE
export statewide tables to data.ca.gov

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#57]
When we have a first crack at #31, we should export a statewide table of bus routes and bus stops and ... stop frequnecy? into the caltrans geoportal. 

Walter Yu gave been the data dictionary format to do this, so I'll start prepping that while @machow is working on the tables.

**Comment by hunterowens** [comment]
submitted the data dictionary to Walter Yu

**Comment by hunterowens** [comment]
update: they want to submit it directly to data.ca.gov, a CKAN portal. Should receive API keys from CDT.

**Comment by hunterowens** [comment]
Have received CKAN API keys, now blocked on Caltrans Portal admin creating the datasets. 

However, received sample code for uploading to CKAN, will take a look at PRing this week

**Comment by hunterowens** [comment]
Hunter to copy / paste GTFS documentation into form then good to go maybe?

**Comment by hunterowens** [comment]
Following information from Chad Baker:  

"""
Details you need to start doing uploads is attached and IDs provided below.  This entry is currently set as private in the CKAN system and can be made public once the data updates are working as expected.

 

Sam Hayashi @ CDT mentioned updating the data in chunks as there are limitations in size so once you have tested your script is working using test data, we can confirm on how to do the upload with the full dataset.

 

Resource ID:

agency = e8f9d49e-2bb6-400b-b01f-28bc2e0e7df2

routes = c6bbb637-988f-431c-8444-aef7277297f8

stop times = d31eef2f-e223-4ca4-a86b-170acc6b2590

stops = 8c876204-e12b-48a2-8299-10f6ae3d4f2b

trips = 0e4da89e-9330-43f8-8de9-305cb7d4918f
"""

@hunterowens has the API key

**Comment by hunterowens** [comment]
@machow @Nkdiaz can y'all take a look at the [CKAN upload API](https://docs.ckan.org/en/ckan-1.6/loading_data.html) and see if we can get something scheduled to automate this ?

**Comment by machow** [comment]
@hunterowens we can take a crack at it! Two quick checks...

* can you attach the data dictionary?
* is this the "latest" gtfs schedule data updated with some frequency? Or something else?

**Comment by hunterowens** [comment]
They are based off the "latest" we store in BQ, ideally we wanna update the data.ca.gov portal after we update the scrapes nightly. 

[DDP-6-cal-itp-gtfs-schedule-metadata_20210520.xlsx](https://github.com/cal-itp/data-infra/files/6658789/DDP-6-cal-itp-gtfs-schedule-metadata_20210520.xlsx)
[DDP-8-cal-itp-GTFS-schedule-data_20210520.xlsx](https://github.com/cal-itp/data-infra/files/6658790/DDP-8-cal-itp-GTFS-schedule-data_20210520.xlsx)

**Comment by hunterowens** [comment]
@machow any update on this?

**Comment by machow** [comment]
@Nkdiaz, do you mind looking into this? Hunter mentioned he can respond to questions / pair to go over it. I have to admit, I found it a bit difficult to follow the instructions on the portal (but that might just have been me?!). The tables on bigquery can be pulled using...

```python
from calitp.tables import tbl

# repeat for each table on gtfs_schedule
tbl.gtfs_schedule.trips() >> collect()
```

**Comment by machow** [comment]
Putting some notes from yesterday's meeting here (definitely correct where I get things wrong).

* data.ca.gov uses CKAN 1.6
* we need a simple example on how to load data (e.g. [these docs are difficult to understand](https://docs.ckan.org/en/ckan-1.6/loading_data.html#import-data-with-the-ckan-api))

**Comment by Nkdiaz** [comment]
curl -X POST  -H "Content-Type: multipart/form-data"  -H "Authorization: XXXXXXXX"  -F "id=e8f9d49e-2bb6-400b-b01f-28bc2e0e7df2" -F "upload=/PATH/results-20210727-131240.csv" https://data.ca.gov/api/3/action/resource_update

**Comment by hunterowens** [comment]
schematic of how to upload a CSV to the endpoint using requests

```
import requests

API_ENDPOINT   = "https://data.ca.gov/api/3/action/resource_update"
API_KEY = os.environ.get('some_key')

files = {'upload_file': open('file.csv','rb')}
headers= {'Content-Type': "multipart/form-data", 
                 "Authorization": 'API_KEY',
                 "id":"e8f9d49e-2bb6-400b-b01f-28bc2e0e7df2"
}

r = requests.post(API_ENDPOINT, files=files, headers=headers)
```
