### ISSUE TITLE
GTFS Guidelines: realtime feeds critical errors

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#570]
## Question

How many critical errors exist in the realtime feeds for a provider? 

See also #513.
 
 ## Stakeholder / End User
 
Data Quality team (@o-ram), part of Mobility Services Data (MSD)

## User story
As a member of the Data Quality team, I want to be able to identify how many [critical errors](https://dot.ca.gov/cal-itp/Critical-GTFS-Validation-Errors) exist in a transit provider's RT feed so I can assist the provider with communicating those findings to their vendor and/or support the process for getting their feed accepted by Google. 

Being able to identify RT critical errors will help providers feel empowered by the information they know they should be asking for from their vendors.

**Current workflow:** Olivia runs a a Docker image on occasion to validate GTFS-RT feeds, but the cadence is irregular (not frequent) and done only when she needs RT validation results for a specific reason. 
A snapshot in time (relatively recent) to reference is sufficient for the Data Quality team's use case. 
 

## Acceptance Criteria 

We know we can mark this ticket as done when:  

Given the existence of RT feeds for the transit provider, the Data Quality team can access the existing[ dashboard ](https://dashboards.calitp.org/dashboard/26-gtfs-guidelines-specific-date?feed_name=Unitrans%20(0)&relative_date=yesterday)to see a question created (e.g., titled `Realtime Validation Errors`) that displays validation errors flagged by [Mobility Data GTFS Realtime Validator](https://github.com/MobilityData/gtfs-realtime-validator), identified as critical by[ Cal-ITP](https://dot.ca.gov/cal-itp/Critical-GTFS-Validation-Errors), and acts as a recent snapshot in time.

The reliable production of the data used by the dashboards is required for the acceptance of this issue as being complete. A period of 10 consecutive business days of realtime validation errors being available in BigQuery for at least 2 days prior to each measured day will be considered the basis for completion. For this initial issue, it is acceptable for there being just one hour of daily validation data being analyzed, but it is strongly desired for all 24 hours of daily validation data being available to analyze.

## Metrics

Number of critical errors resulting from validating the GTFS-RT feeds categorized by feed type, error type and date.

## Data sources

* realtime feeds
* [Center for Urban Transportation Research (CUTR) GTFS Realtime Validator](https://github.com/CUTR-at-USF/gtfs-realtime-validator)
* [Cal-ITP's list of Critical GTFS Validation Errors](https://dot.ca.gov/cal-itp/critical-gtfs-validation-errors)

## Dependencies

This depends on the GTFS-RT validation pipeline being built out and running properly which is tracked here:

- [ ] dbt MVP #1009

**Comment by blakeflei** [comment]
@evansiroky We're taking a look at this and it appears there is already an experimental [dashboard](https://dashboards.calitp.org/dashboard/26-gtfs-guidelines-specific-date?feed_name=Unitrans%20(0)&relative_date=yesterday) card that meets the acceptance criteria of this ticket. Are we looking for something more or different?

**Comment by evansiroky** [comment]
That [first dashboard linked to](https://dashboards.calitp.org/dashboard/26) contains many production-ready questions, but also the "experimental" question of the GTFS-RT errors. Also, there is [a similar dashboard, but shown as a timeseries](https://dashboards.calitp.org/dashboard/27) that also contains at the very end the experimental question showing the GTFS-RT validation results.

These two questions in their respective dashboards are exactly what I believe the assessments team is looking for as an MVP. The only thing I'd note about the issue description is that the metrics description of `Number of critical errors resulting from validating the GTFS-RT feeds.` would be better written as `Number of critical errors resulting from validating the GTFS-RT feeds categorized by feed type, error type and date.`

**Comment by blakeflei** [comment]
Great - sounds like these criteria represent what we needed and are met! I'll mark this issue resolved.

**Comment by evansiroky** [comment]
I think it is premature to close this issue when there are still major stability issues with the airflow DAG task that is producing the data for the BigQuery dataset that these dashboards are pulling from. This task is marked as dependent on #1009 accordingly. So although the metabase dashboard has questions that are ready to answer this, the data is not there yet.

<img width="648" alt="Screen Shot 2022-04-04 at 9 52 38 AM" src="https://user-images.githubusercontent.com/3112493/161593901-ed3c93a8-c57c-439f-9b08-bb22ae02094f.png">

**Comment by blakeflei** [comment]
@evansiroky Could you please update the acceptance criteria of this ticket?

**Comment by evansiroky** [comment]
@blakeflei I added a paragraph to the acceptance criteria section.

**Comment by lauriemerrell** [comment]
For record keeping, the specific issue that is blocking at this point is #1180

**Comment by holly-g** [comment]
**Definition of Done** 

✅  User can see RT validation errors for service alerts, trip updates, and vehicle positions for transit providers on the [dashboard](https://dashboards.calitp.org/dashboard/26-gtfs-guidelines-specific-date?feed_name=Fairfield%20and%20Suisun%20Transit%20(1)&relative_date=past7days) for the past 7 days
✅ User acceptance testing
