### ISSUE TITLE
GTFS Guidelines: open license

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#575]
## Question

Does the provider publish their GTFS feed under a license that allows commercial use?

## Metrics

* Whether open license language exists

## Data sources

* Airtable data as entered from assessments.

## Depends on

- [ ] #979

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by holly-g** [comment]
Manual check exists in Airtable, will be moved over to warehouse in mid-Oct https://github.com/cal-itp/data-infra/issues/1773
