### ISSUE TITLE
GTFS Guidelines: technical contact in 2 locations

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#580]
## Question

Has the provider published technical contacts in two locations?

## Metrics

* Whether a specific contact has been published in 2 locations.

## Data sources

* Airtable data as entered from assessments.

## Depends on

- [ ] #979

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by holly-g** [comment]
Priority is to ingest the Airtable table.

**Comment by holly-g** [comment]
Manual check exists in Airtable, will be moved over to warehouse in mid-Oct https://github.com/cal-itp/data-infra/issues/1773
