### ISSUE TITLE
Infra offboarding Chris Cardillo, Ruth Miller

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#581]
Note: these are steps that should happen whenever a warehouse user leaves the project, but we can keep collaborators in as long as useful..!

- [ ] Remove from Teamwork 
- [ ] Remove Slack access
- [ ] Remove Sitecore access
- [ ]  Remove credentials from project IAM
- [ ] Remove from warehouse github team
- [ ] Check for custom collaborator access across project repos

**Comment by machow** [comment]
@hunterowens @evansiroky do you mind looking over the three offboarding pieces above and weighing in on whether anything else is needed?

**Comment by holly-g** [comment]
Additional pieces from Evan + Hunter: 

- Remove from Teamwork
- Remove Sitecore access
- Remove Slack access
