### ISSUE TITLE
Make title of docs "Data Services", explain major subsections of docs on home page

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#584]
Current subsections:

* Datasets (list of major data sources)
* Kubernetes (runs all services)
* Services (e.g. GTFS RT extractor, jupyterhub)
* Warehouse (e.g. adding a new table, table naming conventions, how to use metabase, metrics views)

Note that in addition, we likely need to address our main user segments on the homepage (e.g. where should an analyst go? Where should a team lead go?)

**Comment by machow** [comment]
Going to close since there was a major restructure of the docs (which included renaming). Let's loop back once some of the analytics sections are completed.

**Comment by charlie-costanzo** [comment]
Changed title of docs to 'Data Services Documentation' in PR #700
