### ISSUE TITLE
Set resource limits on jupyterlab helm chart config

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#592]
https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-resources.html?highlight=memory#set-user-memory-and-cpu-guarantees-limits

Let's set it to 5Gb for now? (cc @hunterowens what kind of memory usage will analysts need?)

Currently, the cluster has 12 Gb of memory, but it can always be upsized to meet need, etc..

TODO:

* @machow to investigate how much memory analysts need
* will try to implement the change with help from Chris C, since he's been prodding me to go through kubernetes stuff anyway
* let's also install https://github.com/jupyter-server/jupyter-resource-usage if it's easy to do along the way

**Comment by lottspot** [comment]
Now that we have an operation prometheus & grafana stack, we should complete #1284 in order to gain visibility into the insights we need to advance this task in an informed way.

**Comment by atvaccaro** [comment]
grabbing this to do alongside https://github.com/cal-itp/data-infra/issues/1323
