### ISSUE TITLE
Add a snippet for dimensional table joins in SQL snippets doc

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#593]
* Graph illustrating star schema using gtfs schedule daily feed files
* Dimensional tables create a <domain>_key column
* They are joined with fact tables via the `JOIN views.gtfs_schedule_dim_<domain> USING (<domain>_key)` syntax
* We also use calitp_itp_id, calitp_url_number as an internal feed tracking key

**Comment by atvaccaro** [comment]
I think we can close this @lauriemerrell 

We have documentation via the [dbt docs site](https://dbt-docs.calitp.org/#!/overview) and relationships tests
