### ISSUE TITLE
Create deduplicated versions of payments tables

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#597]
Related to #595 , where we'll mark duplication. That will allow us to analyze duplicates, while this will filter them out.

**Comment by mjumbewu** [comment]
@machow I think this is done for now. The following tables have `stg_cleaned_...` views available:
* device_transactions
* micropayment_adjustments
* micropayment_device_transactions
* micropayments
* product_data

These tables do not have cleaned versions available yet. The only table from this list that is a blocker for known work right now is `customer_funding_source`. The work to dedupe that should fall under #704. For the rest I created a separate issue #718 in the backlog to capture:
* authorisations
* customer_funding_source
* refunds
* settlements
