### ISSUE TITLE
calitp should let users configure max bytes at any time

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#604]
See https://github.com/cal-itp/data-infra/issues/594#issuecomment-952204878. When a user runs

```
from calitp.tables import tbl
```

It creates a sql alchemy engine that holds the max bytes settings. We need this to be recreated (or reconfigured via sqlalchemy whenever this property is reset). We can do this by making a given table property (e.g. `tbl.gtfs_schedule.agency`) an accessor that checks CALITP_BQ_MAX_BYTES in the environment.

edit: see this issue: https://github.com/cal-itp/data-infra/issues/500

Note that currently users must set the environment variable before importing:

```python
import os
os.environ["CALITP_BQ_MAX_BYTES"] = str(20_000_000_000)

from calitp.tables import tbl
```

**Comment by machow** [comment]
@Nkdiaz we can pair on this Weds

**Comment by machow** [comment]
Let's resolve this by adding docs on how to do it in the current setup

* import os, set new max bytes
* run something like `tbl._init()`

This doesn't seem to complicated, and we can always bump up the default max bytes in our jupyterhub deploy.

**Comment by charlie-costanzo** [comment]
@machow hmm what do you think about adding it after this section in Analytics Tools / Notebooks under a new header called something like 'Setting the Environment Variable'? Might move at some point, but do you think that makes sense for now?
