### ISSUE TITLE
Use intake for importing data in Jupyter Notebooks

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#608]
**Is your feature request related to a problem? Please describe.**

As analytics requests increase, there's a need to store outside data sources, as well as significant overlap in datasets. Along with establishing GCS buckets (#526), we should be able to catalog our canonical data sources somewhere and everyone imports the same file for their analyses.

**Describe the solution you'd like**

Use [intake](https://intake.readthedocs.io/en/latest/) to catalog our various data sources, determine canonical datasets for outside sources like Census, CA open data portal, etc.

**Describe alternatives you've considered**

**Additional context**
See data catalogs in City of LA repos [planning-entitlements](https://github.com/CityOfLosAngeles/planning-entitlements).

**Comment by Nkdiaz** [comment]
I was able to replicate the issues that @tiffanychu90 saw,
It gives the following error message:
CPLE_OpenFailedError: '/vsimem/470fe276e170472793034dc1c849a443' not recognized as a supported file format."

I first downloaded the test_shapefile_folder locally and verified that nothing was corrupted and it would load correctly into a pandas dataframe.  I then tried several tricks to try and read the ShapeFile Object
1- having the .shp directly mentioned in the args: urlpath
Had the same error message as before
2- tried to explicitly set the geopandas_kwards driver as as ESRI shapefile in sample_catalog.yml
3- attempted to alter fsspec
4- changed Fiona versions as it was previously supported, however the Fiona version is tied intimately with GDAL/OGR 1.8+ and did not accept only the shp or the parent folder
5- attempted to alter the catalog yml file with an uncompressed cache and a regex_filter for shp alone and shp, dbf, and shx file extensions needed to read the shape file 

All in all my suggestions are this and are ranked in least to greatest effort
1- do not allow users to upload non-zipped shapeFiles
2- allow users to upload shapeFile folders but then store them as a zip in the bucket
3- figure out a way to intercept the Fsspec library- have it respect the filename as it would in google cloud, download it to a local folder and read it as a normal gdframe.read_file()

I am leaning towards option 1 as we have already shown that users can successfully analyze zipped shape files

**Comment by machow** [comment]
Intake is now up on jupyterhub, and working with all the examples except for the shapefile one described above! I created a separate issue to track #674.
