### ISSUE TITLE
Update Metabase to the latest version

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#610]
**Is your feature request related to a problem? Please describe.**

The current version of Metabase is `v0.38.2` whereas the latest version is `v0.41.1`. The updated version has various interesting new items.

**Describe the solution you'd like**

For Metabase to be updated to the latest version.

**Describe alternatives you've considered**

The primary feature I'm interested in using is specifically the ability to [make custom expressions that check for records that are null](https://github.com/metabase/metabase/issues/12225) which seems to have been added in `v0.39`. For now, I can create 2 questions where one of them filters for null and the other doesn't, but that is not as helpful as having a custom expression that could combine the 2 which could make a percent value.

**Additional context**

It seems like a few other interesting items have been added along the way to Metabase, so it'd probably be best to update to the latest.

**Comment by lottspot** [comment]
This is scheduled to be performed this Wedneday morning (11/10) @ 04:30-05:30 PST

**Comment by evansiroky** [comment]
Looks great. Thanks!
