### ISSUE TITLE
Replace remaining hard-coded SQL examples in docs

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#613]
From @Nkdiaz in #612

> worth mentioning that I found some other areas in the documentation that didn't have official sql markdown but appear to mock a sql query. For example warehouse _04 sql_snippits. Might be worth further dicussion with @charlie-costanzo If those are meant to be actually executed

**Comment by Nkdiaz** [comment]
@charlie-costanzo It would be helpful if I could know which exact SQL examples should be replaced, or should I just expect all of it to be executed?

**Comment by machow** [comment]
I think the snippets are in: `warehouse/04_sql_snippets.md`

**Comment by machow** [comment]
For this snippet 
![image](https://user-images.githubusercontent.com/2574498/140177071-4f2fb429-f3f7-4bfd-b932-9557c43442f1.png)

It looks like the last piece should be

```
D.full_date BETWEEN (2021-06-01" AND "2021-06-07"
```

**Comment by machow** [comment]
Let's replace the examples on this page. we can keep them as they appear now (e.g. don't need to print out the result of the query; can do this with the `-o some_variable --quiet` flags (double check flag names)

**Comment by charlie-costanzo** [comment]
Great so it looks like this PR #722 has gotten the SQL scripts to execute - @Nkdiaz do we now just need to hide the results?

Also, @machow based on your comment above do think we should spin off an issue to replace the examples on this page?

**Comment by charlie-costanzo** [comment]
closing this out as @Nkdiaz satisfied this with PR #747
