### ISSUE TITLE
Bug: code errors in docs are not failing the docs build

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#618]
cc @Nkdiaz https://docs.calitp.org/data-infra/warehouse/07_tutorial.html#query-examples

![image](https://user-images.githubusercontent.com/2574498/139307054-1d09094b-f5a6-44a2-87b9-f4470cd2ef9d.png)

**Comment by Nkdiaz** [comment]
also fixed by @machow updating the requirements
