### ISSUE TITLE
Pushing doc build previews to netlify

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#623]
Currently we build the docs every time a change is made to `docs/**` using this action: https://github.com/cal-itp/data-infra/blob/main/.github/workflows/publish-docs.yml

@thekaveman, how hard would it be to push the docs to netlify in the action? :) It'd be a bit easier to stick with building the docs in gh actions for now, and we save the build artifact as part of the job, but being able to quickly open in the browser would be handy!

**Comment by thekaveman** [comment]
@machow let's sync on this when you're closer to working out the Actions workflow. I'm hoping we can use the Netlify site for more general purpose previews like this (love the idea!), and want to make sure the preview URLs we generate don't conflict with one another.

**Comment by thekaveman** [comment]
Closing - this was implemented in #761 and is currently working for docs PRs.
