### ISSUE TITLE
Create documentation focused on analytics

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#625]
**Is your feature request related to a problem? Please describe.**
JupyterBook makes it easy to spin up new books to compile documentation. We would like to build a new book called analytics-book to start writing and organizing documentation for analytics work. 

**Describe the solution you'd like**
A book called analytics-book to begin compiling documentation needs.

**Describe alternatives you've considered**
We've considered working on analytics documentation within the infrastructure book for now, but as it is easy to create new books we'll start with a separate book and revisit integrating them together as it progresses. This will also allow us to reconsider the organization of the current infrastructure documentation. 

**Additional context**
The problem statement/ needs assessment for this work will live in a separate spec document.

**Comment by machow** [comment]
Partially resolved by https://github.com/cal-itp/data-infra/pull/626, which stubs out analytics docs sections
