### ISSUE TITLE
Add Intake Documentation to Analytics JupyterBook

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#636]
**Is your feature request related to a problem? Please describe.**
Having recently implemented intakify as a solution for storing and accessing outside datasets, we want to store the documentation in a location that makes the most sense. For now, this will be in the analytics documentation in JupyterBook.

**Describe the solution you'd like**
Migrate the intakify documentation to the following location:

Location: [docs/analytics/07_storing_data](https://github.com/cal-itp/data-infra/blob/main/docs/analytics_tools/07_storing_data.md)

**Describe alternatives you've considered**
We explored the idea of adding it to infrastructure documentation, but it makes more sense to document it within analytics as this is something analysts should be familiar with and will likely use often.

**Comment by machow** [comment]
cc @tiffanychu90 -- @charlie-costanzo let's go over a bit how intake works when we pair

**Comment by machow** [comment]
See #608. Intake now working on our Jupyterhub so the last step is to document it.
