### ISSUE TITLE
Move gtfs_loader.gtfs_schedule_tables_load into gtfs_schedule_history2

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#653]
This task requires gtfs_schedule_history_load to have run across all time. This is a natural fit for gtfs_schedule_history2, since it also requires all past successes for that task. The one difference is that gtfs_schedule_tables_load can be `latest_only`, since it loads the most up-to-date gtfs schedule data for the day from the external tables (for convenience).

Setting latest_only: true in the yaml should work. You can check this by opening instance details.

**Comment by lauriemerrell** [comment]
This was made obsolete by #1157
