### ISSUE TITLE
Release October (and September) reports.calitp.org

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#657]
* generate reports
* push to development and sanity check
* deploy reports by merging to main
* let's handle the emailing of reports in a separate issue: #658

**Comment by machow** [comment]
@evansiroky development build up here: https://development-build--cal-itp-reports.netlify.app

Do you mind checking and letting me know once it looks good to merge?

**Comment by machow** [comment]
Note: I have not removed Amtrak and Tulare from the reports (#402), so we may need to do that before releasing....

**Comment by holly-g** [comment]
^Fixed by #781
