### ISSUE TITLE
Help default bash_profile in jupyterhub

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#659]
* research how to add a .bash_profile
* display git branch name

I'm going to push updates to the jupyterhub image, so can look into how these things are added a bit more..!

**Comment by machow** [comment]
@lottspot un-assigning so we are giving you issues that are ops / kubernetes lifts

**Comment by tiffanychu90** [comment]
https://github.com/ian-r-rose/citywide-jupyterhub/blob/master/image/custom.sh
