### ISSUE TITLE
[WIP] Document all bigquery datasets, tables, and columns -- so they are easy to find and understand

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#660]
Currently, we have a page of documentation that a broad data overview, and individual pages to document tables within a "domain" (e.g. payments).

| overview page | mst payments data page |
| -------- | ----- |
| ![image](https://user-images.githubusercontent.com/2574498/140400901-24a3b070-746a-4f91-9f8a-64d7c5209cea.png) | ![image](https://user-images.githubusercontent.com/2574498/140401021-9936b515-82bc-44fe-b803-1cf13d90a2ec.png) |

These pages have a lot of potential to document the following:

* how do I find the dataset I need? (overview page)
* how do I find the tables I need inside this dataset?
* how is this dataset maintained? (i.e. how could I make changes to it?)

However, as the number of tables grows, simply providing manual descriptions will become cumbersome and outdated quickly. 

## Goal

We automate the documenting of datasets, tables and columns within a specific section of each dataset subpage.

Note that this might include:

* documenting multiple "bigquery datasets"
* promoting or burying documentation for specific tables (e.g. staging tables)
* documenting specific tables in the `views` dataset, which holds consumer ready tables across domains.

## Proposal

* We provide individual dataset pages with roughly this structure
  - Datasets
    - dataset 1 (with dataset description, link to relevant DAGs?)
      - table x (with table and column descriptions)
      - table y
    - dataset 2
      - etc..
    - views
      - e.g. views.gtfs_schedule_dim_dates
  - Maintenance
    - DAGs overview
    - <sections specific to key modification / use paths >
    - Backfilling (e.g. if any tasks may need to be cleared in order to implement new changes)

## Key tasks (TODO)

* list out what we have done (e.g. field descriptions)
* list out what we need (e.g. dataset, table descriptions)
* e.g. mechanism for inserting into docs

**Comment by j-meelah** [comment]
dbt docs!
