### ISSUE TITLE
Create welcome /intro page for developer docs

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#662]
Once we merge #633 , developers will be their own chapter in the docs. If useful, let's add a intro page. So the final structure would be

* intro page
* kubernetes
* ci
* services

(note that we can move the order of the sections around as needed; can close out if a intro page is unneeded or redundant)

**Comment by holly-g** [comment]
Completed. See https://docs.calitp.org/data-infra/kubernetes/README.html
