### ISSUE TITLE
Read through service increase notebook for good warehouse analysis strategies

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#664]
* Michael to take first pass, then sync with Charlie (may have him read through before hand, or walk through the data, then go through by himself after)

https://github.com/cal-itp/data-analyses/blob/bus-pulse/bus_service_increase/generate_existing_service.ipynb

**Comment by holly-g** [comment]
Hi @charlie-costanzo, let me know if this should be closed out! Thanks.

**Comment by charlie-costanzo** [comment]
@holly-g yeah I just closed this out as it got outdated
