### ISSUE TITLE
Change jupyterhub url from hubtest.k8s.calitp.jarv.us to notebooks.calitp.org 

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#675]
want to change to jupyterhub.calitp.org (cc @hunterowens to confirm)

**Comment by themightychris** [comment]
The biggest barrier to this is just settling on a desired hostname and getting the official DNS record created. It would be great to knock this out so we can stop distributing the test URL sooner than later

**Comment by evansiroky** [comment]
@thekaveman, is this something you can help with?

**Comment by thekaveman** [comment]
@evansiroky yes once we have the desired hostname (assuming a subdomain of calitp.org), just let me know and I'll get the DNS rolling.

**Comment by blakeflei** [comment]
@thekaveman @evansiroky how about `jupyter.calitp.org`?

**Comment by evansiroky** [comment]
I don't have a strong opinion about the name, so if this sounds good to everyone else then it sounds good to me.

**Comment by thekaveman** [comment]
I also don't have a strong opinion. I will just point out that I personally have had a lot of trouble spelling the word `jupyter` in the past 😉

**Comment by themightychris** [comment]
well we did `dashboards.calitp.org` instead of `metabase.calitp.org` — so might we consider doing `notebooks.calitp.org` for this to hide the implementation detail from the consumers?

**Comment by charlie-costanzo** [comment]
> well we did `dashboards.calitp.org` instead of `metabase.calitp.org` — so might we consider doing `notebooks.calitp.org` for this to hide the hard-to-spell-phonetically implementation detail from the consumers? (sorry for the last minute thought :-)

I actually had this same thought after initially thinking we should go with `jupyter.calitp.org`, now I think we should set it to `notebooks.calitp.org` if it's not too late @thekaveman 

cc @blakeflei

**Comment by blakeflei** [comment]
Issuing a new CSR seems have resolved the certificate issuance
