### ISSUE TITLE
Pandas research: how to use str.contains to filter rows in an object Series

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#681]
A common analysis problem is a column that is mostly floats, and a couple accidental strings. However, pandas str methods are a bit unintuitive in that they return `NaN` for floats.

```python
import pandas as pd

ser = pd.Series([1.2, "abc", 3.4, None])

res = ser.str.contains("b")
res
# in pandas v 1.3.4  returns: NaN, True, NaN, None
```

This creates a serious problem for filtering, because you can't negate `NaN`:

```python
# TypeError: bad operand type for unary ~: 'float'
~res
```

As I recall, pandas fixed their new string dtype to make this easy

```python
~ser.astype("string").str.contains("b")
# True, False, True, <NA>

# Note that siuba will filter out any NA results, so this only returns the float rows,
# to include NAs you need to .fillna(False) or use | _.x.isna()
from siuba import filter

pd.DataFrame({'x': [1.2, "abc", 3.4, None]}) >> filter(~_.x.astype("string").str.contains("b"))
```

But let's look a bit deeper into the easiest way to do this, since it is very common in data wrangling.

**Comment by atvaccaro** [comment]
I think we can close, hasn't come up again
