### ISSUE TITLE
Epic: Add GTFS Realtime metrics to GTFS reports

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#682]
This epic is for implementing key metrics related to realtime data.

There are two big notes:

* we are in the process of moving reports to metabase, so we can plan to put them there.
* the time component of these metrics is undefined (e.g. what does it mean for a monthly report to say a feed is available?), so will need to be decided.

The metrics are spec'd in this [juniper reports document](https://docs.google.com/document/d/1-iXNdl4f2EbYayKg3e7jkTALAcNzht9yGQuyIOtPLc4/edit#).

## Screenshots of spec

| trip consistency graph | validator errors |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2574498/140820138-8e237661-3cc9-45ce-9fba-d63cac3490e9.png) | ![image](https://user-images.githubusercontent.com/2574498/140820022-bfb7f116-60b9-497e-8114-07dd3f89f0d0.png) |

## Update as of 2021-01-26

This is dependent on:

- [x] #221

**Comment by evansiroky** [comment]
Fixed in https://github.com/cal-itp/reports/pull/303
