### ISSUE TITLE
Where to best put static HTML maps?

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#686]
See https://cal-itp.slack.com/archives/C02KH3DGZL7/p1636393523022000

> What's the best approach for deploying static HTML maps? Interactive HTML maps?
Thus far, I have static choropleth maps made using folium , which wouldn't be put into Google Slides. Would enabling GitHub pages for the data-analyses repo do the trick? If interactive maps were added for the future, would GH pages still be the right home?

**Comment by atvaccaro** [comment]
I'm closing this, analysis.calitp.org is live
