### ISSUE TITLE
Create user stories for intro analytics tools, examples

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#690]
* Note: Michael can create one to flesh out warehouse docs, and has a rough epic up for dataset docs (https://github.com/cal-itp/data-infra/issues/660)
* Use user story template issue
* Aim for short-ish statements (break long statements into multiple short ones)
* Let's loop @holly-g in to review

**Comment by charlie-costanzo** [comment]
#719 and #725 complete the analytics tools and examples requirements, and @machow I put up a WIP epic for the warehouse assigned to you at #737. Want to close this out?
