### ISSUE TITLE
Implement freshness check table

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#696]
A freshness check is a process that often includes a table (e.g. with columns data source, date of last load), and a set of processes to kick off depending on the distance from today and last load dates.

It has 2 major benefits

* allow analysts to check how up-to-date a view is
* alert org, while allowing flexibility (e.g. alert after 2 days, or escalate in various ways)

Since this implementation will likely apply to all our data domains (e.g. gtfs schedule, payments, rt), we should take some time to tease out what it might look like. See https://docs.getdbt.com/reference/resource-properties/freshness for this concept in DBT :).

**Comment by holly-g** [comment]
Adding this to the dbt Adoption milestone 🎉
