### ISSUE TITLE
create golden-record-style "merged GTFS table"

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#70]
Building on #69, we should create a golden record/  merged GTFS table that has all of the foreigns into a main wide table that can be queried, summarized and aggegrated. 

the foreign keys can be found at https://developers.google.com/transit/gtfs/reference

**Comment by machow** [comment]
What grain are you thinking of for the table? One row per stop, including its trip and route info (w/ stop ids duplicated if stops can have multiple trips)? It seems like the three grain sizes (from smallest to largest) are...

* stops
* trips
* routes

(I'm still wrapping my head around the data, so could be totally off! putting this partridge table here, since I keep checking it)


![image](https://user-images.githubusercontent.com/2574498/115077619-5ca89080-9ecc-11eb-8ade-a77416cee709.png)

**Comment by machow** [comment]
Looking into joining agencies, routes, and trips ("agency_trips"). One thing I'm noticing is that some routes have NULL agency_ids.

From the GTFS spec, it looks like for routes.txt, agency_id is conditionally required (when there is only a single agency). It seems like a good opportunity for to transform in the implicit agency_id in this case! WDYT? I'm curious if there are other classic cases of this happening in the GTFS spec!

**Comment by machow** [comment]
Complicating this, some agencies don't specify an agency id, so we will need to make one for them (for example, the agency_name, or a number like 0, or -999 as a small cue we put the id in?)

**Comment by e-lo** [comment]
I think the defacto `agency_id` would be 0 or 1 (depending on indexing).  

Best practice is to add it and keep it stable even though it is only conditionally required.   That said, it could, in-fact, change.

Another thing to consider is that `agency_id` is supposed to represent a customer-facing "brand" not necessarily the agency operating or funding the service.

**Comment by e-lo** [comment]
> I'm surprised this is in the spec, since it is a big nuisance for cross-dataset analyses 😬

--> totally agree...but not what GTFS was designed for. Feel free to put in a PR to the spec to see if it passes a vote! ;-)

**Comment by machow** [comment]
@cvc5185 I have a kind of nuts query that creates on big history table. Do you mind putting it into gtfs_schedule_type2, and then querying the latest data from it (e.g. `calitp_extracted_at IS NULL`)?

This would involve creating two tasks

**gtfs_schedule_type2/route_trip_stops.sql**:

* depends on merge_updates
* creates joins of our type 2 tables. Here's a [post on how these joins work](https://sqlsunday.com/2014/11/30/joining-two-scd2-tables/).

query:

```SQL
WITH
trip_stop_times AS (
    SELECT
      * EXCEPT (calitp_extracted_at, calitp_deleted_at, calitp_hash)
      , GREATEST(ST.calitp_extracted_at, T.calitp_extracted_at) AS calitp_extracted_at
      , LEAST(ST.calitp_deleted_at, T.calitp_deleted_at) AS calitp_deleted_at
    FROM `cal-itp-data-infra.gtfs_schedule_type2.stop_times` ST
    JOIN `cal-itp-data-infra.gtfs_schedule_type2.trips` T 
        USING (calitp_itp_id, calitp_url_number, trip_id)
    WHERE
        ST.calitp_extracted_at < COALESCE(T.calitp_deleted_at, "2099-01-01")
        AND T.calitp_extracted_at < COALESCE(ST.calitp_deleted_at, "2099-01-01")
),
trip_stops AS (
  SELECT
    * EXCEPT(calitp_extracted_at, calitp_deleted_at, calitp_hash, continuous_pickup, continuous_drop_off)
    , continuous_pickup AS stop_time_continuous_pickup
    , continuous_drop_off AS stop_time_continuous_drop_off
    , GREATEST(S.calitp_extracted_at, TST.calitp_extracted_at) AS calitp_extracted_at
    , LEAST(S.calitp_deleted_at, TST.calitp_deleted_at) AS calitp_deleted_at
  FROM trip_stop_times TST
  JOIN `cal-itp-data-infra.gtfs_schedule_type2.stops` S
  USING (calitp_itp_id, calitp_url_number, stop_id)
  WHERE
      S.calitp_extracted_at < COALESCE(TST.calitp_deleted_at, "2099-01-01") 
      AND TST.calitp_extracted_at < COALESCE(S.calitp_deleted_at, "2099-01-01") 
),
route_trip_stops AS (
  SELECT
    * EXCEPT(calitp_extracted_at, calitp_deleted_at, calitp_hash, continuous_pickup, continuous_drop_off)
    , continuous_pickup AS route_continuous_pickup
    , continuous_drop_off AS route_continuous_drop_off
    , GREATEST(R.calitp_extracted_at, TST.calitp_extracted_at)
    , LEAST(R.calitp_deleted_at, TST.calitp_deleted_at)
  FROM trip_stops TST
  JOIN `cal-itp-data-infra.gtfs_schedule_type2.routes` R
  USING (calitp_itp_id, calitp_url_number, route_id)
  WHERE
      R.calitp_extracted_at < COALESCE(TST.calitp_deleted_at, "2099-01-01")
      AND TST.calitp_extracted_at < COALESCE(R.calitp_deleted_at, "2099-01-01")
)

SELECT * FROM route_trip_stops


```

**gtfs_views/gtfs_schedule_route_trip_stops_latest.sql**:

Queries above table to filter on `calitp_extracted_at is NULL`
