### ISSUE TITLE
User Story: shared utility functions for analysis

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#703]
## User stories

A user story is implemented as well as it is communicated.
If the context and the goals are made clear, it will be easier for everyone to implement it, test it, refer to it.

---

### Summary

A user story should typically have a summary structured this way:

For analysis, there's probably a set of steps in data cleaning or data visualization that we do repeatedly. We encounter them both within a research question and across research questions. Why reinvent the wheel?

I would want to document some of these shared utility functions to standardize and make it easier for analysts to do these steps. The utility functions would be importable across all directories in the `data-analyses` repo and can be called within a Jupyter notebook or Python script.

See 2 examples from City of LA work: [covid19-indicators](https://github.com/CityOfLosAngeles/covid19-indicators/tree/master/processing_utils) and [planning-entitlements](https://github.com/CityOfLosAngeles/planning-entitlements/tree/master/laplan)

Ex 1: exporting a geodataframe to geoparquet and save to GCS bucket. #698. Solution was to create a function that would write a geoparquet locally, upload to GCS bucket, then erase the local file. This is a repeated step that many analysts would come across using the JupyterHub + GCS, and the typical way to export doesn't work.
 
Ex 2: aggregating by geography (census tract, Caltrans district, zip code, etc). There's a `pandas` function that helps us aggregate and take the sum, count, count unique values, etc. Currently, to do a mix of these, you could merge your dataframes back together using `df.groupby().agg()` or get wonky column names using `df.pivot_table()`. A common function would wrap all this aggregation up and be paired with attaching `geometry` back, as the `geometry` column throws errors when you aggregate.

Other examples would be common charts or maps. We'll add more as we come across more use cases of generalizable functions!

### Acceptance Criteria

We can start with Tiffany / Eric's transit service research, and expand as more analyses are done by others.

Also, here are a few points that need to be addressed:

1. Need to test that `shared_utils` is importable across all directories, since analysts are making their own folders within `data-analyses` to store their work.
1. Would like the python files to be editable. This was in a previous `docker-compose.yml`: `pip install -e`...where should this go?

### Notes

Initial work here: https://github.com/cal-itp/data-analyses/tree/shared-utils

### Tester [Stakeholder]

1. @tiffanychu90 

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by tiffanychu90** [comment]
Tested this by running: `python setup.py install` in the terminal, and was able to access the utility functions within the `bus_service_increase` directory

**Comment by machow** [comment]
Hey--this seems great! RE

> Would like the python files to be editable. This was in a previous docker-compose.yml: pip install -e...where should this go?

I wonder if we should either create a new repo or restructure the existing data-analyses? It seems like now there are 3 pieces related to analyses...

* reports
* intake
* shared utils

This might make it easier for people to find things, and for us to add a docker-compose.yml, etc.. without the root directory being full of stuff like reports. WDYT? (cc @hunterowens )

In any event, would be pretty quick to drop in a docker-compose file, and even scaffolding for tests, CI with github actions of the shared utils :).

**Comment by tiffanychu90** [comment]
Not sure if we should break apart the reports, intake, and shared utils. 

Taking the `bus_service_increase` task as an example:
* Within notebooks, import `shared_utils`, similarly to `siuba`, and do some common tasks (export as geoparquet and upload to GCS)
* Within this directory, we have our own `catalog.yml` of data sources being used within notebooks and scripts. Other task sub-folders can have their own data catalog. There may be little or no overlap between those data catalogs. A file stored in GCS would be in its own `data-analyses/bus_service_increase`, but nothing prevents the `dla` data catalog to list a file from the `data-analyses/bus_service_increase` bucket. 
* Within each directory, users have the option to add their own `requirements.txt`, `conda-requirement.txt`, etc

**Comment by machow** [comment]
Hey--that's helpful to hear. I think that splitting can preserve what's happening within reports. The big upside is it could do two things:

* separate the **location** of shared_utils from reports (still importable from reports)
* separate the location of reports from a common intake catalog folder (e.g. shared resources across reports)

The structure

* reports (with report specific folders)
* shared_utils
* intake (or named data? for common data?)

Should help separate out all the different things you are doing (e.g. to make shared_utils work). What might be challenging right now for people is that there are all the files associated with packaging (e.g. setup.py) mixed in a folder with a lot of reports.

**Comment by tiffanychu90** [comment]
Ahh, I see the confusion.

* `catalogs` as a folder was there temporarily to showcase `intake`, but not intended to stay permanently. Once the docs are up for how to create a `catalog.yml`, and the `intake`, `intake-dcat`, etc packages are installed in environment, the `catalogs` folder can be removed. Each task sub-folder should have its own `catalog.yml` relevant to data sources used for their specific analysis. 

For me, my GCS file path has been `gs://calitp-analytics-data/data-analyses/bus_service_increase/`.
But, if I started working on a new task and needed a file previously downloaded for the `bus_service_increase` task, I can simply reference that `bus_service_increase` GCS file path in my new catalog (as opposed to creating second copy of the same dataset in the bucket). This preserves our canonical data sources. 

* `shared_utils` can live elsewhere in another repo. I'm just less familiar with how to get it to setup correctly and importable. I only care about it be importable for use, and for others to easily add functions they see being used over and over.

**Comment by machow** [comment]
Ah, okay--it sounds like people are liking having their reports at the root of the repo. How about this? We create prefix folders for common data catalogs, and for shared utils with `_`? E.g.

* `_shared_utils`. With everything for using shared utils inside this folder...
  - setup.py
  - a README.md
* `_data`
  - some `catalog.yml`

This way, they will appear at the top of the repo, and there won't be a lot of misc files floating around, but people can still see their reports at the front of the repo

**Comment by tiffanychu90** [comment]
Ref: [intakify work](https://github.com/cal-itp/data-analyses/tree/5320c3a24ee31afada20d1f89c7d15c6ea2508fd)

**Comment by tiffanychu90** [comment]
Initial work: https://github.com/cal-itp/data-infra/pull/717
