### ISSUE TITLE
Replace views.mst_ridership with views.payments_rides in payments dashboard

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#705]
* `mst_ridership` currently used in the payments metabase dashboard
* `payments_rides` should now have roughty the same number of rows (), but more columns (e.g. for product data)

Note: payments_rides records each ride (e.g. tap on + tap off are one row). So if it is important for the dashboard questions to count transactions, then we'll need to use a different table for those (TBD; payments.stg_cleaned_device_transactions? may want to move or forward it into views). cc @hunterowens

**Comment by mjumbewu** [comment]
There is a new dashboard in Metabase informed by `payments_rides` data: [Payments Metrics](https://metabase.k8s.calitp.jarv.us/dashboard/29-payments-metrics). At the appropriate time, this will replace the existing [Payments Performance Dashboard](https://metabase.k8s.calitp.jarv.us/dashboard/3-payments-performance-dashboard)
