### ISSUE TITLE
Previous and next links in the docs now stack

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#706]
![image](https://user-images.githubusercontent.com/2574498/141349241-dadc7c07-c8c9-48cc-b17b-ad093aa98ee4.png)

* likely due to sphinx update, or pydata sphinx theme update (would check their github issues, or jupyterbook for details).
* links are still clickable

cc @charlie-costanzo (who identified!)

**Comment by charlie-costanzo** [comment]
this appears to have resolved itself @machow...
<img width="856" alt="Screen Shot 2021-11-11 at 3 45 36 PM" src="https://user-images.githubusercontent.com/25835059/141366505-a1b16548-ab70-4838-a98d-36c00eb68a17.png">

**Comment by machow** [comment]
Incredible, thanks!
