### ISSUE TITLE
Add comments to custom merge sql for loading gtfs schedule type2 tables

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#712]
https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/merge_sql.py#L6

Note that there is an example that runs / tests this code in the sandbox (see tasks starting wit "merge"): https://github.com/cal-itp/data-infra/blob/main/airflow/dags/sandbox/merge_create_merge_target.sql

**Comment by lauriemerrell** [comment]
Should be rendered obsolete by #1259
