### ISSUE TITLE
Bug: ipyleaflet map not rendering in notebook

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#715]
**Describe the bug**

The ipyleaflet map isn't rendering in a notebook. Not sure what dependences to install.

**To Reproduce**
1. Go to [this notebook](https://github.com/cal-itp/data-analyses/blob/more-bus-pulse/bus_service_increase/ipyleaflet-error.ipynb)
1. Error is `Error displaying widget: model not found`

**Expected behavior**
The ipyleaflet map would render directly in the notebook.

**Additional context**

These are installed within the directory: 
* [conda requirements](https://github.com/cal-itp/data-analyses/blob/more-bus-pulse/bus_service_increase/conda-requirements.txt) 
* [requirements](https://github.com/cal-itp/data-analyses/blob/more-bus-pulse/bus_service_increase/requirements.txt) with `pip install`
* `jupyter labextension install @jupyter-widgets/jupyterlab-manager`
* `jupyter labextension install jupyter-leaflet`
* Also tried these, but it didn't work in the notebook: `jupyter nbextension install --py --symlink --sys-prefix ipyleaflet` and `jupyter nbextension enable --py --sys-prefix ipyleaflet`

**Comment by edasmalchi** [comment]
I get this error after first installing `ipyleaflet`, shutting down the notebook kernel, logging out of jupyterhub and logging back in seems to fix.

I wonder if this has something to do with the notebook extension -- perhaps there would be a way to have that preinstalled and not go through this every time?

**Comment by edasmalchi** [comment]
Has anyone got a chance to look into this?

I still run into this all the time, while logging out and back in seems to fix things it would be super helpful to not have to do that every time.

**Comment by tiffanychu90** [comment]
I think @machow wanted to solve it by adding more packages in the JupyterHub environment...so we're not doing our own `pip install` and debugging. Updated list of [requirements here.](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/setup.py)

**Comment by machow** [comment]
Hey--I'll try and put in these installs before Monday, and am working on who can pick up this kind of work going forward..!

**Comment by edasmalchi** [comment]
Looks good to me!
