### ISSUE TITLE
User Story: Introduction to Analytics Tools

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#719]
### Summary
* As a new analyst or non-analyst team member looking to use our analytics resources
* I want a series of progressive documents
* So that I can learn about the tools we use in the context of an end-to-end analysis.
### Acceptance Criteria
* I can learn more about which tools we use for which processes.
* I can browse the documents in an order that mirrors the stages of a typical analysis.
* I can easily see how the order informs my natural workflow.
* I can use this section to quickly access our tools.
#### Proposed section structure is 8 pages:
* Overview
* Tools Quick Links
* Querying with SQL
* Business Insights and Dashboards
* Notebooks
* Python Libraries
* Saving Code
* Storing New Data

### Research required:
* Research: End-to-end analysis walkthrough
* Research: Intakify Walkthrough (related 'Storing New Data')

### Pages as Issues

- [x] 1. #727
- [x] 2. #728
- [x] 3. #729
- [x] 4. #730
- [x] 5. #731
- [x] 6. #732
- [x] 7. #733
- [x] 8. #734 

### Tester [Stakeholder]

1.

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
5. - [x] External / 3rd Party dependencies identified

**Comment by tiffanychu90** [comment]
@charlie-costanzo: Should the "Quick links" page also include links to Google Cloud Storage and Google Big Query?

Those Google Big Query link also lives in the `data-analyses/README.md`, but might be useful here?

**Comment by charlie-costanzo** [comment]
great flag @tiffanychu90 - I definitely think we should add a link to Google Cloud Storage. 

We used to have a link to Big Query in there also but I removed it thinking 9/10 times we would just query SQL in the notebooks, and should nudge people to query SQL there. But I would be happy to add it back if you think it's good to have - what do you think?

**Comment by tiffanychu90** [comment]
@charlie-costanzo: Ahh, I usually use Big Query to quickly skim through the various tables to figure out which one it is that I want to use in the analysis. Might just be helpful to for someone to bookmark it in case they need the URL for something or when they onboard, but I agree, I also don't use it much.

**Comment by charlie-costanzo** [comment]
@tiffanychu90 I actually do the same thing.... I think it would be worthwhile to add the link back to the 'Technical Onboarding' section. I'm going to caputure that in an issue... #830
