### ISSUE TITLE
Investigate configuring range of behaviors with Jupyterhub deploy

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#720]
There are a wide range of enhancements requested:

* adding extensions - https://github.com/cal-itp/data-infra/issues/715
* adding custom files - https://github.com/cal-itp/data-infra/issues/659
* configuring hotkeys - https://github.com/cal-itp/data-infra/issues/679

**Comment by machow** [comment]
@lottspot going to un-assign based on our convo Monday, to make sure we're giving you ones that need your ops / kubernetes chops

**Comment by charlie-costanzo** [comment]
Resolved by calitp-py PRs 42, 44, 45
