### ISSUE TITLE
Docs page: Analytics Tools / Notebooks

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#731]
**Issue:** 
Much of this section is very complete. Besides the comments below, what is missing?

To-Do:
- [ ] **This section now needs content explaining querying SQL in the notebook as we've removed the section specific to BigQuery**
- [ ] Some more detailed introductory content to python notebooks for beginner users?

Notes:
‘Connecting to the Warehouse’
* Should we make Loom video here more concise?
  * Should we clarify use of ‘gcloud auth application-default login’?
* Should we add code for connecting to the project?
  * gcloud config set project cal-itp-data-infra
 * Should we add the code for test syncing to the warehouse?
  * Add folder ‘test’
  * gsutil rsync test gs://calitp-analytics-data 
* Should we add the code for 
  * from calitp.storage import get_fs
  * fs = get_fs()   
  * fs.open(‘gs://calitp-analytics-data/test.txt’).read()

‘Uploading Data’
* MOVE THIS SECTION TO # 8. STORING NEW DATA?
* ‘Uploading data from a notebook’
* ‘Uploading from google cloud storage’
* misc Need to review this Loom 

**_Misc:_**
* #500 
  * (assigned to Michael, watch still - add to notebook section and maybe warehouse)
* Add ‘What’s next?’ section with internal links out?
  * Using recommended Python libraries
  * Saving my code
  * Storing my data
  * Publishing my code

**Comment by tiffanychu90** [comment]
After today's lunch & learn, perhaps a section for storing `.env` or `_env`, and calling it in a notebook would be nice? Going to add that snippet.

**Comment by charlie-costanzo** [comment]
Thank you @tiffanychu90 !!

**Comment by holly-g** [comment]
Appears to be closed by #862
