### ISSUE TITLE
Docs page: Analytics Tools / Python Libraries 

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#732]
**Issue:** 

To-do:
- [x] Include all of the libraries in this section that we used in the warehouse querying tutorial

Add information for the following libraries:
- cal-itp
- mapping
- plotting (plotnine?)
- what else do we need for siuba?
- **what other libraries should we add and describe?**

**_Misc:_**
* Pandas research: how to use str.contains to filter rows in an object Series
* to_snakecase doc

**Comment by tiffanychu90** [comment]
> * plotting (plotnine?)

@charlie-costanzo: Should packages aside from Cal-ITP-specific packages be left off of this page and instead demonstrated in the `analytics_examples` section? Most of the common charting and mapping packages will soon come installed in JupyterHub, so it seems this section could explode to be extremely long if we open the floodgates and include `altair`, `matplotlib`/`seaborn`, `plotly`, and `bokeh`.

**Comment by charlie-costanzo** [comment]
@tiffanychu90 yes - totally! I think that makes a lot of sense.

I just captured this in issue #794
