### ISSUE TITLE
User Story - Introduction to contributing to the docs

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#739]
### Summary

1. **As a** user of the docs
2. **I want** information on how to modify or add content
3. **So that** I can contribute appropriately.

### Acceptance Criteria

1. I can find where to make edits or additions
2. I can find how to submit my changes
2. I can easily find references to how to write content
3. I can easily find references to how to markup content
3. I can access further resources with more detailed markup information
4. I can quickly get a grasp on our structure and format best practices
5. I can easily find conventions for adding sections
6. I can easily find conventions for naming sections
7. I can easily find conventions for adding pages

### Notes

- Modify [this section](https://data-infra-795--cal-itp-previews.netlify.app/contribute/submitting_changes.html#how-do-i-preview-my-documentation-change) to be related to netlify generation

add information on conventional commits:
* docs(area):
* ex docs(analytics-tools):

[MyST Syntax Cheat Sheet](https://jupyterbook.org/reference/cheatsheet.html)
[Documenting Code - Sphinx](https://www.jetbrains.com/pycharm/guide/tutorials/sphinx_sites/documentation/)

### Tester [Stakeholder]

1.

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by tiffanychu90** [comment]
Will add a couple sentences about pre-commit hooks. It's elsewhere in the docs, but highlight it again here

**Comment by charlie-costanzo** [comment]
Excellent - thank you for this @tiffanychu90!
