### ISSUE TITLE
Audit Metabase Permissions

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#740]
As a metabase administrator, I want to be able to have various groups and associated permissions that it is possible to assign various users to.

An asynchronous discussion can happen to figure out who needs access to what databases and collections.

**Comment by machow** [comment]
There are 2 levels of resource based access controls (RBAC) in the metabase right now. Does this do what you're looking for? If we list out the desired levels of access for collections and data sources, should be pretty straight forward to tweak!

https://docs.calitp.org/data-infra/analytics_tools/03_bi_dashboards.html#metabase-at-cal-itp

Right now there are admins, data consumers (read only on dashboards, can't see some rougher datasets), data workers

**Comment by machow** [comment]
Sorry--following up from our discussion in the payments meeting. I had set the payments dataset to be accessible from all users, and incorrectly assumed it had lower precedent than other settings. I've set the internal payments data to only be accessible to admins and payments teams

![image](https://user-images.githubusercontent.com/2574498/142460118-2f0b8ad4-7d33-4824-bd23-f92946ebc7bf.png)

**Comment by evansiroky** [comment]
This is resolved with the above-noted change.
