### ISSUE TITLE
Provision a new v2 version of composer

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#743]
* necessary for upgrading from v1 to v2
* once we have all content v2 compatible (#741), we can run the [upgrade script](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/composer/tools/composer_db_transfer.md) together
* we need to pause all dags before running the script

**Comment by lottspot** [comment]
The `calitp-airflow2-prod` environment has been provisioned. Please review to ensure all looks well. cc @machow

**Comment by machow** [comment]
thanks!
