### ISSUE TITLE
Start pushing airflow content into v2 bucket in push_to_gcloud gh action

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#746]
Let's create a second set of these lines while we upgrade, that also push to the newly provisioned v2 airflow (#743)

https://github.com/cal-itp/data-infra/blob/main/.github/workflows/push_to_gcloud.yml#L65-L70

Note that we'll need to ensure DAGs are not running before / after we do this. 

![image](https://user-images.githubusercontent.com/2574498/142269838-f7ec5218-a934-4d48-896d-f3c78ff96079.png)

**Comment by lottspot** [comment]
Closed by #784
