### ISSUE TITLE
Ensure users can consistently run voila from jupyterhub

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#748]
cc @natam1 , it sounds like periodically she gets "web server not found"

**Comment by hunterowens** [comment]
The answer to this is probably packing voila and the extension in the hub
docker image

**Comment by natam1** [comment]
Got the extension enabled using this code: 
`jupyter serverextension enable voila`
`jupyter server extension enable voila`

However, still get the following error when trying to run `voila notebook.ipynb` and `<url-of-my-server>/voila`:
`[Voila] WARNING | No web browser found: could not locate runnable browser.`

I am able to get a html when running the notebook from my local jupyter lab- continuing to do that for now

**Comment by machow** [comment]
Thanks--currently the hub is uses a docker image published via gh action on calitp-py:

https://github.com/cal-itp/calitp-py/blob/main/Dockerfile

Here is the line of config pointing to the image:

https://github.com/cal-itp/data-infra/blob/main/kubernetes/apps/charts/jupyterhub/values.yaml#L10-L11

**Comment by holly-g** [comment]
@natam1 verified that this issue has been resolved 🎉
