### ISSUE TITLE
Allow users to easily upload CSVs (or links to gcs data analyses data) into bigquery, so they can explore in metabase

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#749]
Pairing with @natam1 , loaded her DLA dataset into sandbox. Curious about whether a quick path to exploring in metabase is useful.

**Comment by natam1** [comment]
@holly-g thinking we can close this issue since now there is a process for uploading data into Metabase? @charlie-costanzo

**Comment by holly-g** [comment]
Yes, thanks @natam1 !
