### ISSUE TITLE
Payments: Research how to provide agency specific views and dashboards

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#751]
* Each agency sees a dashboard like [the metrics dashboard](https://dashboards.calitp.org/dashboard/29-payments-metrics), but only for their agency (but not others).
  - is this something we can easily do with metabase alone?
* Each agency can query a view of their data (but not others).
  - may need to create a new dataset, with agency specific views? Can we give access table by table? (I think so)

**Comment by mjumbewu** [comment]
Some thoughts on this:

The easiest way to create an agency-specific dashboard is probably to simply provide agency partners with a URL that auto-populates the `transit_provider` field on the the Payments Metrics board (e.g., add `?transit_provider=mst` parameter to the URL). This wouldn't disallow anyone from accessing other agencies' data (which could be a feature, not a bug), but it would provide a convenient endpoint where they partners wouldn't have to remember to choose the proper agency when they get to the dashboard. Also, if new charts are added to the dashboard, everyone would be able to take advantage of them.

**Comment by j-meelah** [comment]
This has been implemented
