### ISSUE TITLE
Remove old and unused tables from views dataset

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#758]
* when we change the name of a table, the old table sticks around
* this is an extreme hassle when using autocomplete with calitp-py and metabase, since you see a lot of old tables
* we can either periodically analyze the tables in views to see which have not been updated, or re-create the views dataset, since it is made to reconstruct everything daily.

**Comment by atvaccaro** [comment]
I think we can close this; #1026 already covers it
