### ISSUE TITLE
Allow users to access external tables from calitp.tables.tbl

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#759]
Should be resolved by upgrade python-sqlalchemy-bigquery to the latest v1.2.2 (or some version near there). See https://github.com/googleapis/python-bigquery-sqlalchemy/issues/332

**Comment by machow** [comment]
Note that this is where we search for table names: https://github.com/cal-itp/calitp-py/blob/main/calitp/tables.py#L48

**Comment by mjumbewu** [comment]
It looks like any version of sqlalchemy-bigquery from 1.2.1 or above [should work](https://github.com/googleapis/python-bigquery-sqlalchemy/blob/v1.2.1/sqlalchemy_bigquery/base.py#L979). Right now we're pinned to [pybigquery 0.10.2](https://github.com/cal-itp/calitp-py/blob/fde76be6bc3e3a66aced01ea1953d66bf2d3e380/requirements.txt#L55). The package [pybigquery is obsolete](https://pypi.org/project/pybigquery/) and we should switch to sqlalchemy-bigquery
* [ ] [in setup.py](https://github.com/cal-itp/calitp-py/blob/fde76be6bc3e3a66aced01ea1953d66bf2d3e380/setup.py#L22), 
* [ ] [in requirements.txt](https://github.com/cal-itp/calitp-py/blob/fde76be6bc3e3a66aced01ea1953d66bf2d3e380/requirements.txt#L55), and
* [ ] [in requirements-dev.txt](https://github.com/cal-itp/calitp-py/blob/51f13cd2a89a6b34003a68751022b1d252c5e802/requirements-dev.txt#L77)

We should just be able to use the latest available `sqlalchemy-bigquery==1.4.1`

**Comment by atvaccaro** [comment]
I've confirmed this works now `tbls.external_airtable.california_transit__gtfs_datasets()`
