### ISSUE TITLE
New Team Member - Amanda Ha

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#773]
**Name:**
Amanda Ha
**Role:**
Research Data Analyst II - Reports  to Hunter

**Google Workspace Email Address:**
tbd, probably amanda@calitp.org-  I'll update this when I create it 
**Github Username:**
will ask on 12/2
**Slack Username**
will setup on 12/2 
**Set-up:**
- [x] Google Cloud Console / BigQuery
- [x] Metabase
- [x] Github
- [x] Jupyter Lab
- [x] Technical Onboarding Call Scheduled
- [x] Added to Daily Stand-ups
- [x] Added to Slack: #data-analyses

**Comment by charlie-costanzo** [comment]
Excellent, thank you for this @hunterowens!

**Comment by hunterowens** [comment]
@charlie-costanzo Amanda should be joining slack today. Her gsuite is amanda@calitp.org

**Comment by charlie-costanzo** [comment]
thanks for the update @hunterowens!

**Comment by hunterowens** [comment]
Amanda's username is @amandaha8
