### ISSUE TITLE
Create calitp convenience functions for accessing data of the data analytics bucket

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#780]
Currently, the calitp library can be used to access data from any of our buckets:

```python
import pyarrow.parquet as pq

from calitp.storage import get_fs
fs = get_fs()

f = fs.open("gs://calitp-analytics-data/data-analyses/bus_service_increase/bus_stop_times_by_tract.parquet")
pq.read_table(f)
```

Since we have conventions around where analysis data should be stored (`"calitp-analytics-data/data-analyses/<analysis name>"`), it might be a good idea to make convenience functions in calitp for pulling / pushing files from these locations. This will let us remove some of these implementation details of where things live from notebooks.

(intake already does a good job of holding this data, so this would be for cases that don't fit well there?)

**Comment by atvaccaro** [comment]
@tiffanychu90 I think we can close this unless you still have shared_utils plans for this
