### ISSUE TITLE
Research sending emails via postmark for reports

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#782]
Currently, Jarvus has a postmark account set up for calitp. This allows us to automate emailing things like reports. (I can't remember where else this is being used, @themightychris can you list out where we use this?). Let's get familiar with postmark, so we can automate emailing / write email scripts.

* set up a script to send an email to yourself
* customize the body of the email

**Comment by holly-g** [comment]
From Hunter, via Slack thread: 

> We want the report to be sent using either @dot.ca.gov addres or @calitp.org, ideally the dot gov

**Comment by holly-g** [comment]
The approximate email template that was sent last time by Hunter (awaiting approval from Oliva + Erika to use same template/language in next batch of emails): 

> Hello!
Greetings from the Cal-ITP team. As part of our work with the GTFS feeds for agencies across the state, we prepare a monthly report with some basic statistics and validation results for your agencies' feed. You can view your report for [MM] at [[URL]]
If you have any questions, feel free to email hello@calitp.org.
Thanks,
The Cal-ITP Team
