### ISSUE TITLE
GTFS-RT: compress validation data by storing as parquet

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#786]
Note that from a quick test, there seems to be a 3 to 4x reduction when done on a single file. I suspect that if we batch validation files into a single parquet (or chunks of parquet e.g. by feed), or with a better defined schema?

```python
from pyarrow import json
import pyarrow.parquet as pq
from calitp.storage import get_fs
fs = get_fs()
f1 = fs.open("gs://calitp-py-ci/gtfs-rt-validator-api/test_output_full/2021-09-01T00:00:12__106__0__gtfs_rt_service_alerts_url")
f2 = fs.open("gs://calitp-py-ci/gtfs-rt-validator-api/test_output_full/2021-09-01T00:00:32__106__0__gtfs_rt_service_alerts_url")

# reads a single file
table = json.read_json(f1)
#pq.write_table(table)

# can concat two tables using pyarrow.concat_tables
```

Here's the SQL used to hold validation results as a reference schema:

<details>

```SQL
CREATE OR REPLACE EXTERNAL TABLE gtfs_rt.validation_service_alerts (
    errorMessage STRUCT<
      messageId INT64,
      gtfsRTFeedIterationModel STRING,
      validationRule STRUCT<
        errorId STRING,
        severity STRING,
        title STRING,
        errorDescription STRING,
        occurrenceSuffix STRING
      >,
      errorDetails STRING
    >,
    occurrenceList ARRAY<
      STRUCT<
        occurrenceId INT64,
        messageLogModel STRING,
        prefix STRING
      >
    >
)
OPTIONS (
    uris=["gs://calitp-py-ci/gtfs-rt-validator-api/test_output_full/*gtfs_rt_service_alerts_url"],
    format="JSON"
)
```

</details>

### TODO:

* compress data to parquet for a full day of validations, check memory savings
* save parquet file to cloud storage bucket, and ensure it can be loaded into bigquery (e.g. create an external table using SQL similar to above. Query the table to make sure it works).

**Comment by machow** [comment]
Note that while working on rollups, I'm seeing that the bulk of the results file is the full string descriptions of warnings and errors.

E.g. everything from here: https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/RULES.md#table-of-errors

If we load the rt rules as a dimension and drop them from the result data, this should make results outputs very small. E.g.

gtfs_rt.validation_dim_rt_rules table columns:

* rule_key: unique ID
* rule_id: e.g. E001 (error_id in the table linked above)
* rule_title
* rule_description
* rule_occurence_suffix (a message that gets appended to the end of the message about specific violations. E.g. 'old which is greater than the recommended age of 65 seconds', which appends to "you timestamp is X seconds")
* rule_severity: error or warning

gtfs rt result fact tables (very nicely parquet-able):

* rule_key
* date
* occurenceList (a STRUCT with occurenceId, messageLogModel, prefix)

**Comment by atvaccaro** [comment]
This will be closed with https://github.com/cal-itp/gtfs-rt-validator-api/pull/6
