### ISSUE TITLE
GTFS-RT: calculate the date of the last relevant gtfs schedule extract for validation

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#788]
The GTFS RT validator requires a gtfs schedule as part of its process. However, on the day we run validation, a schedule might not be available for a variety of reasons. It sounds like the last valid gtfs schedule per feed will be the most recent schedule (e.g. from `gtfs_schedule_history.calitp_feed_updates`) that does not have parse errors (e.g. `gtfs_schedule_history.feed_parse_result`).

Let's put a task in the gtfs_rt DAG that puts up a table.

The table should have one row per gtfs rt feed to be validated per day, `gtfs_rt.daily_validation_parameters` with these columns:

* calitp_itp_id, calitp_url_number
* date
* gtfs_schedule_date (NULL if no valid gtfs schedule; e.g. it hasn't been successfully extracted)

It might be a good idea to put this data into the gtfs-data bucket, and use an external table, since the validation uses a docker image that does not have calitp-py installed (for simplicity), but can pull from a bucket to read the parameters, and fetch all files needed for validation.

**Comment by atvaccaro** [comment]
I don't think this is strictly necessary for "current" validation but will be necessary if we want to backfill.

**Comment by holly-g** [comment]
No plans to backfill this

**Comment by atvaccaro** [comment]
we do this now
