### ISSUE TITLE
Create a script or notebook to send emails about reports.calitp.org

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#790]
@Nkdiaz is researching postmark for emails. Let's tee up this issue as one of the big outcomes for being able to send emails. We want to take in info about who to email for a provider's gtfs report, and send an email with a link to the report to them.

See this script I used to pull emails (note that the sheet of emails I pull might be out of date, may want to use the transitdatabase airtable): https://github.com/cal-itp/data-analyses/tree/main/gtfs_report_emails

Let's move it (or something similar) into the reports folder of https://github.com/cal-itp/reports. If you use the jupytext library, you can open .py files as notebooks. This might be a little easier to maintain that a ipynb.

cc @evansiroky 

## Steps

* copy over script
* test that you can send an email with postmark (e.g. to yourself)
* check on where we should pull data on emails from
* check on what the body of the email should be
* open PR with a working script (that you know is working because you used it to email yourself)

**Comment by machow** [comment]
@e-lo mentioned it would be useful to loop in @o-ram on content of the email :)

**Comment by holly-g** [comment]
[Link to email template](https://docs.google.com/document/d/1Hwq6B49vW8rQ1x3MnH4iRizsuOz9cfLTVNxdnLMGTSA/edit) from Erika + Olivia

**Comment by machow** [comment]
Looks like we only need to send emails to those supplied by @o-ram on the google sheet. [Relevant slack thread](https://cal-itp.slack.com/archives/C02JFS4LAMU/p1639084661036100?thread_ts=1639058404.032700&cid=C02JFS4LAMU). Posting screenshot since our slack deletes over time..

![image](https://user-images.githubusercontent.com/2574498/146247989-c97a6c46-877a-49c8-8582-9a78493e0756.png)

**Comment by machow** [comment]
See discussion on whether a separate script should be used to pre-process the sheet provided with email data:

https://github.com/cal-itp/reports/pull/55/files/dde337e60bea041f156ea487a653eaa3eb121e6e#r772002107
