### ISSUE TITLE
Metabase BigQuery Drivers are deprecated and need to be updated

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#798]
Within the Metabase admin screen, it is showing a message that says our current BigQuery Drivers are deprecated and need to be updated:

<img width="1080" alt="Screen Shot 2021-11-30 at 2 49 39 PM" src="https://user-images.githubusercontent.com/3112493/144140921-e1786b4a-5d9c-41fb-8c5c-3deaae3f63c0.png">

We should update these soon, probably.

**Comment by machow** [comment]
Updated today (thanks @evansiroky and @themightychris )

![image](https://user-images.githubusercontent.com/2574498/147009064-e024d00d-a62f-4df9-97b0-12b55613efe5.png)
