### ISSUE TITLE
Identify agencies missing from reports.calitp.org 

### ISSUE THREAD

**Issue by holly-g** [cal-itp/data-infra#800]
### Context 

Olivia reviewed the [reports](https://development-build--cal-itp-reports.netlify.app/) and flagged that there were some agencies (with feeds) missing from the reports site, such as B-line and Beach cities.
Michael explained that B-line was left off because they were missing`feed_info.txt` in their feed, and that was breaking report generation (see <https://github.com/cal-itp/reports/issues/26#issuecomment-883630244>).

What came out of this discovery: Michael opened a PR to fix a small bug <https://github.com/cal-itp/data-infra/pull/772)>; a question was created on Metabase [Which feeds are used to generate reports?](https://dashboards.calitp.org/collection/67-reports-calitp-org) to help Olivia see which reports should exist (and serve as a jumping off point for us to create more MB questions that will help Olivia to understand and debug report generation). 

### Task

Olivia has started going through the  list of agencies that have static data and tagging those who do not appear to be showing up on the reports site. (Working assumption: they may be agencies missing `feed_info_txt`)
She'll compile a spreadsheet to be shared with Holly and Michael as a guide.

### Reviewer [@holly-g ]  

cc @evansiroky // @machow

**Comment by o-ram** [comment]
Hello! Here is the [spreadsheet](https://docs.google.com/spreadsheets/d/1qVp6ejPRzovw45im6VepvQLEq5lWz16suju-xfnaBrw/edit#gid=0) I put together @holly-g @machow 

The first tab are all the agencies that are missing feed_info.txt, and therefore are not currently on the reports site despite having schedule feeds known to Cal-ITP.

The second tab is where I put agencies that I'm grouping as "other" for now. These are agencies who also have schedule GTFS data, but either don't make it public, or appear to have not yet been put in the .yml file. I will create a PR to add the few feeds that fall into that latter group into agencies.yml

**Comment by holly-g** [comment]
Thank you, @o-ram! This is wonderful. 

cc @evansiroky

**Comment by holly-g** [comment]
Linking #861 to this issue. I also added a column to the above spreadsheet to track the three agencies you added to `agencies.yml`. I will create a separate issue to track and contact the agencies you identified that have no `feed_info_txt`. Thanks!
