### ISSUE TITLE
Analyst Docs: Google Authentication Documentation

### ISSUE THREAD

**Issue by natam1** [cal-itp/data-infra#809]
When reviewing the analyst docs I noticed some sections containing information on how to connect to the data warehouse a few times (specifically in [notebooks.md](https://github.com/cal-itp/data-infra/blob/19235d809855e3ecd6dffaff43d1ba158d9a550e/docs/analytics_tools/notebooks.md?plain=1#L28) and in [storing_data.md](https://github.com/cal-itp/data-infra/blob/19235d809855e3ecd6dffaff43d1ba158d9a550e/docs/analytics_tools/storing_data.md?plain=1#L42))

Wondering if this section might be useful as a standalone (or just once) and then referenced and linked in the relevant sections? 

```python
# initial setup (in terminal) ----
curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-361.0.0-linux-x86_64.tar.gz
tar -zxvf google-cloud-sdk-361.0.0-linux-x86_64.tar.gz
./google-cloud-sdk/install.sh
./google-cloud-sdk/bin/gcloud init
# log in to project ----
gcloud auth login
gcloud auth application-default login

```

**Comment by charlie-costanzo** [comment]
Great catch @natam1, and thank you so much for capturing it in an issue! It looks great

**Comment by charlie-costanzo** [comment]
This was addressed by removing the content in /storing_data and clarifying /notebooks to focus more on important information like this. so this should be good to go!
