### ISSUE TITLE
Guideline Question: Publishing GTFSRT feeds that requires API key to data aggregators 

### ISSUE THREAD

**Issue by pjmaher7** [cal-itp/data-infra#812]
## Guideline Question

Some transit agencies that use a GTFSRT vendor that requires an API key are not meeting the current guideline: Point 2 on "Access to data" which states "Publish all GTFS and GTFS Realtime data feeds to both of the two larger global GTFS aggregators: transit.land and openmobilitydata.org."

These agencies typically work with a vendor that requires an API key (ie. Swiftly) to access their GTFSRT feeds. The GTFS workgroup would like to know: Can an agency publish functioning GTFSRT links that require an API on a data aggregator?

If not, should we request one of the following:
1. Ask Transit.land and Open Mobility Data to provide a method to access feeds that have an API key
2. Update guidelines to exempt feeds that require API keys from publishing to data aggregators

**Comment by hunterowens** [comment]
cc'ing @e-lo here (and I assume Olivia is already aware). 

I believe Transitland supports API keys by just calling them out in the URL - ie, [AC Transit](https://www.transit.land/feeds/f-actransit~rt)

**Comment by e-lo** [comment]
>  Transitland supports API keys by just calling them out in the URL - ie, AC Transit

**Comment by e-lo** [comment]
Open Mobility Data does as well ([see their AC Transit feed](https://openmobilitydata.org/p/ac-transit/577)) although currently their process is manual to add feeds and is....a complete mess....so I would give agencies any and all passes here until OMD cleans itself up.

**Comment by evansiroky** [comment]
There is now an entry in the guidelines and manual check in Airtable that notes whether or not the authentication method is acceptable, so I believe this issue can be closed.
