### ISSUE TITLE
GTFS RT Extractor should upload its agencies.yml to the gcs bucket upon restart

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#815]
Currently, everytime we push an update to agencies.yml, the GTFS RT extractor restarts with the updated file. Let's have it save to a bucket the contents of the file, so we can load / audit exact URLs it has available across time.

A common format in the pipeline is something like `gs://gtfs-data/rt-agencies/<datetime>_agencies.yml`

@lottspot assigned you, but also happy to pair on this / figure out the right way to go about things here

**Comment by machow** [comment]
Refining: we can load logs in bigquery, so the nice thing would be if we could detect each attempt to download a url. E.g. the itp id, url number, timestamp, and url. This will let us fully understand, what did we attempt to get and where did we attempt to get it from.

**Comment by evansiroky** [comment]
This issue is related to #888. Whatever work is done to resolve #888 should also consider how to address this issue in tandem since it is not desirable for the Archiver script to be restarted very often.

**Comment by holly-g** [comment]
Resolved by #999.
