### ISSUE TITLE
Reports: Add all static feed errors listed on Caltrans site

### ISSUE THREAD

**Issue by holly-g** [cal-itp/data-infra#818]
From Olivia's review of November reports:

> Validation notices that we include within data assessments (which are based on what Metabase says) are still not all appearing on the reports site. I looked at this Github[ issue](https://github.com/cal-itp/reports/issues/45), and I think the problem is that there are errors still missing from the list of “codes critical for reporting”. For assessments, we use [this page](https://dot.ca.gov/cal-itp/Critical-GTFS-Validation-Errors) on the Caltrans website to determine which validation notices to include or not. 

cc @machow

**Comment by machow** [comment]
Note that MSD gave us this sheet for critical rules, and it is currently ingested daily into the pipeline. See this extract + load task for it : https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/validation_stg_code_descriptions.py

**Comment by machow** [comment]
Counting our coding in reports, it looks like...

* we handle 12 notices
* there are 17 marked as critical on the sheet
* there are 52 marked as critical on the website
* some marked critical on the sheet are not marked critical on the website (e.g. UnknownFileNotice)

What is the correct set of critical errors? The website? Can we coordinate with someone to keep the sheet up to date? It seems we were passed incomplete information (or the intent changed).

**Comment by evansiroky** [comment]
The source-of-truth for the errors is those on the website. The sheet has been updated to match.
