### ISSUE TITLE
Fix gtfs schedule view task name to match its table name

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#820]
Note this task should be named gtfs_schedule_fact_daily_feed_stops (that is the name of the table it constructs)

https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/gtfs_schedule_fact_daily_stops.sql

**Comment by holly-g** [comment]
cc @lauriemerrell for visibility

**Comment by lauriemerrell** [comment]
@holly-g did you want me to address this? Looks relatively straightforward

**Comment by lauriemerrell** [comment]
I think that the preferred solution here would just be to wait for dbt transition and deprecate the task entirely. Unless we decide not to transition schedule to dbt, I would say this doesn't seem worth fixing.

**Comment by lauriemerrell** [comment]
This issue was rendered obsolete by #1369, closing
