### ISSUE TITLE
Research: GTFS-RT delay demo for Caltrans District 7 

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#826]
## Question

Caltrans D7 Director Tony Tavares and Planning Deputy Paul Marquez are interested in seeing results from our GTFS-RT delay analysis, specifically bottlenecks on the State Highway Network that could be developed into bus priority projects.

Meeting will likely occur first week of January.

## Metrics

* Calculations of delay from transit operating on the D7 State Highway Network
* Summary statistics, visualizations of bottlenecks

## Data sources

* GTFS-RT (data warehouse/GCS)
* State Highway Network (CA Geoportal)

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by holly-g** [comment]
Meeting is set up for January 6.
