### ISSUE TITLE
Enable table level descriptions in airflow view operators

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#828]
Currently, @mjumbewu and I have been following the convention that table descriptions go in a `description` field in a tasks yaml. calitp-py has the tooling to set these as table descriptions. Let's implement this across operators that allow column descriptions using `sql_patch_comments`, so people can pull all table documentation into bigquery.

This has 3 benefits:

* can pull full table documentation into docs
* can be seen from jupyterhub
* standardizes the convention of naming the description "description" :)

**Comment by machow** [comment]
@mjumbewu adding you to this, but let's hold off until after airflow v2 upgrade

**Comment by mjumbewu** [comment]
After discussing, seems like a good way to do this would be to:
* Create a function that digests the front matter from a task file and pulls out table information
* Use that function in Jupyter book code snippets to output table/task docs

The rendered task docs could include:
* Table name
* Task name/description
* Field names/descriptions
* Links to upstream tasks docs

**Comment by lauriemerrell** [comment]
Rendered obsolete by transition to dbt, will not do #1525
