### ISSUE TITLE
improve dataset documentation + developing on data pipelines

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#83]

**Comment by machow** [comment]
Breadcrumb: document running backfill commands. E.g.

```
gcloud beta composer environments run calitp-airflow-prod --location us-west2 backfill -- -s '2021-05-08' -e '2021-05-08' -x -y --rerun_failed_tasks gtfs_loader
```

**Comment by machow** [comment]
Breadcrumb: have Chris explain what holo is, and how it is used here (for generating docs).

https://github.com/JarvusInnovations/hologit

**Comment by machow** [comment]
Screencasts to record:

* using `debug.py` and importing / running a task from a dag
* creating a new view in `gtfs_views` DAG
* running queries in the bigquery web UI
  - checking how many bytes they processed
* basic siuba queries against warehouse

**Comment by machow** [comment]
Going to close, opened issue for documenting debug.py (https://github.com/cal-itp/data-infra/issues/699), and have epics for fleshing out tools like bigquery in the analytics docs
