### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#84]
juniper here we come!

**Comment by mcplanner** [comment]
@hunterowens, what's keeping this from getting closed?

**Comment by hunterowens** [comment]
AFAIK it was a back and forth between, you, me and @thekaveman on "public facing names" 

since we now have docs.calitp.org, etc, there's something to be said for names that are descriptive vs ones that you have to learn the various codenames, etc in terms of onboarding folks and being transparent.

**Comment by thekaveman** [comment]
Furthermore... isn't [Juniper the front-end User Interface](https://docs.google.com/document/d/1lyM9w3gdPsn4yog-8nlHEKoczwc30N-vnEsniQWr6Ho/edit) e.g. [reports](cal-itp/reports)? This repository is all the back-end stuff that makes the data and metrics available, right? I don't agree that this repo should be renamed to Juniper.

**Comment by mcplanner** [comment]
I put this into "Waiting" until we have a better sense of our suite of
tools and where this name will fit in among them.

**Comment by hunterowens** [comment]
SG.
