### ISSUE TITLE
Bug: fact daily feed files never has parse_error of true

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#849]
![image](https://user-images.githubusercontent.com/2574498/145467440-6e5cf882-616b-4354-9133-4a9c75588758.png)

I think this is related to #848, looking back at the airflow logs, when we implemented #693 I think we ended up skipping attempting to parse the feed that was failing before (due to a parse error). Once we address #848, let's double check that we have entries for this query:

```SQL
SELECT * FROM `cal-itp-data-infra.gtfs_schedule_history.calitp_feed_tables_parse_result`
WHERE parse_error_encountered
```

**Comment by evansiroky** [comment]
This appears to have been fixed by #872
