### ISSUE TITLE
Add Evan (+others) to failure emails

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#854]
**Is your feature request related to a problem? Please describe.**
currently, failure emails to @machow / me. This should probably be fixed globally so at least @evansiroky gets them. 
![image](https://user-images.githubusercontent.com/1735650/145619239-d7d6c294-7b45-42ee-8ea5-0a7b56978cbd.png)

**Describe the solution you'd like**
add evan to any airflow / pipeline failure email

**Comment by evansiroky** [comment]
I have yet to have a PR accepted in this DAG so I've been delaying adding my email to all the DAGs for as long as I can which is probably up until the moment I post this comment.

**Comment by machow** [comment]
Hey--we can add Evan to all the DAGs. I'd suggest at some point soon we implement posting failures to slack, so that people can subscribe to failures:

https://github.com/cal-itp/data-infra/issues/550#issuecomment-991190230

**Comment by machow** [comment]
Setting up time with @holly-g to implement #550 next week, which should satisfy this (and hopefully remove the need to add emails!).
