### ISSUE TITLE
Investigate logged severity levels in RT extractor service

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#858]
It appears that even though the logging module levels are set correctly, maybe cloud logger is not using them? We can likely work around with filters, but wanted to flag in case there's something obvious

Below is a log from a DEBUG event in the script, that is marked as INFO on cloud logger

![image](https://user-images.githubusercontent.com/2574498/145845303-5aaf2608-9a43-4405-84bf-41a4808ccb83.png)

**Comment by Nkdiaz** [comment]
Research Journey:
- verified that there was a discrepancy between debug and info within the logger. 
- Within the 'gtfs-rt-archiver1 script for the tick method we have it hardcoded as 'logger.debug' and for the url error it is hard coded to use `logger.info`
- looking at the logs for RT extractor service, all errors are listed as severity info. There are two main error messages using the following query 'resource.labels.namespace_name="gtfs-rt"', All 724 are listed as severity info, even with approximately 1/3 are Ticker messages. For the ticker messages the logged messages are as follows:
- severity: "INFO"
textPayload: "DEBUG:/gtfs-rt-archive.py:ticker: emit: ('tick', 6343, 1641416479)"
