### ISSUE TITLE
Increase CALITP_BQ_MAX_BYTES on warehouse to 15GB

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#876]
Recently, a query in `gtfs_views` required more than 10 GB to run. There are two things to note here:

* the limit of 10GB is arbitrary, but has an important job of signaling as queries grow bigger / preventing accidentally executing giant queries.
* the view that failed, [gtfs_schedule_data_feed_trip_stops_latest](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/gtfs_schedule_data_feed_trip_stops_latest.sql) is a wide table of feeds joined with routes all the way down to trip stops (e.g. trip stop times). Running in bigquery shows it takes 10.5GB to run. This makes sense, since it's a wide table with a lot of columns.
* bigquery charges $5 per TB of data processed, so 1GB is half a cent, so 10GB is 5 cents which is not too bad for a convenience table. An alternative would be to leave it as a fact table, and have users do the joins.

I'm going to up our MAX BYTES in the environment for now, but wanted to leave this up for awareness / discussion!

**Comment by machow** [comment]
Changed in composer's environment variable panel 
![image](https://user-images.githubusercontent.com/2574498/146786156-4bf636f4-9fe1-425a-86e6-f4ba34b904b0.png)

**Comment by evansiroky** [comment]
Thanks for writing up this issue. Since 10GB is $0.05, I went ahead and bumped the limit up to 50GB so that we aren't warned about something that costs a trivial amount of $$ to run.
