### ISSUE TITLE
Add dependency/security scanning

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-infra#88]
Over in [cal-itp/benefits](/cal-itp/benefits) I recently configured a few Python tools for improved security scanning:

* [pyup.io](https://pyup.io/) adds a check for commits with insecure dependencies, and will send PRs as soon as out-of-date dependencies are detected (similar to GitHub's own dependabot, but more configurable). Here's [an example PR](https://github.com/cal-itp/benefits/pull/53) (note the `pyup.io/safety-ci` check), and a screenshot of the nice dependency dashboard they give you:

![image](https://user-images.githubusercontent.com/1783439/117196402-4723d980-ad9b-11eb-8884-7c295cc65607.png)

* [bandit](https://github.com/PyCQA/bandit) is a tool from the folks that brought us Flake8, and comes with a pre-commit hook that scans for known code smells and security issues (like hardcoded passwords)

If the team is amenable, I would like to configure this repo with these tools. Any concerns or gotchas?

/cc @hunterowens @machow

**Comment by hunterowens** [comment]
SGTM! Can you setup a PR?

**Comment by thekaveman** [comment]
@hunterowens thoughts on whether the initial config should look for all dependency updates, or just security updates?
