### ISSUE TITLE
Prepare a bucket without sensitive data that can be accessed via requester pays

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#880]
**Is your feature request related to a problem? Please describe.**

A number of people outside of Cal-ITP have requested access to our data archives, mainly the GTFS and GTFS-RT data we archive.

**Describe the solution you'd like**

- [ ] There should be some kind of bucket that can be accessed on a requester-pays basis that contains non-sensitive data and at a minimum:

- the most recent `agencies.yml` file
- our archive of GTFS files that were downloaded
- our archive of GTFS-RT data files that were downloaded

- [ ] There should be some kind of script that runs nightly that copies all of the relevant data from our private bucket to the public bucket.

**Comment by machow** [comment]
@evansiroky can you say more on why a bucket without sensitive info is needed? It sounds like there are two issues:

* who pays for accessing a resource
* who has access to the resource (e.g. a folder w/in a bucket; a bucket)

I know that sometimes these things get mixed together on gcp, and it ends up being important to just bucket out specific things for specific purposes, so trying to get a feel on some of these dynamics. (Broadly speaking, this seems useful to throw someone at to research if needed).

**Comment by evansiroky** [comment]
> @evansiroky can you say more on why a bucket without sensitive info is needed? It sounds like there are two issues:

The audience of who has access to the resource could potentially be the general public. For example, we could choose to make our archive of GTFS and GTFS-RT data available to the public and document on a public website how one would go about making a request to obtain that data in a way that they would pay for the request so that we wouldn't incur any additional cloud costs.

**Comment by machow** [comment]
potentially related to: https://github.com/cal-itp/data-infra/issues/859

**Comment by holly-g** [comment]
For the research partner: Pick a week for Modesto Area Express (GTFS Schedule and RT)

**Comment by atvaccaro** [comment]
I've moved schedule and RT data for the day of 2022-02-06 to the new cal-itp-publish-requester-pays bucket for Modesto Area Express, ID 203 URL 0.

Doing this via gcsfs is kinda slow, it took a solid hour to move the RT files as-is. I will move over a week using data transfer, I think.

**Comment by evansiroky** [comment]
This is no longer needed, but if it is I will reopen.
