### ISSUE TITLE
gtfs-rt-archive service needs to be able to make requests with headers

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#882]
**Is your feature request related to a problem? Please describe.**

Some RT feeds require authorization via adding header information. Currently there does not appear to be a way to add header data into requests for RT feeds.

**Describe the solution you'd like**

- The agencies.yml file needs to be modified to be able to include any request headers and their values.
- The gtfs-rt-archive script needs to read in the new agencies.yml data and prepare a request with the appropriate headers.

**Comment by machow** [comment]
Hey--can you document the feeds you are seeing that require headers, and what they need to be successfully downloaded here? We can hand this off to the person implementing to validate it's working

**Comment by evansiroky** [comment]
All Swiftly feeds require a header. See the [Swiftly API Docs here](https://swiftly-inc.stoplight.io/docs/realtime-standalone/b3A6Mjg0MzYyMTk-gtfs-rt-trip-updates). We haven't yet added the feed URLs and keys to the transit database or to agencies.yml.

**Comment by machow** [comment]
Great--thanks. Where are we in the process of downloading swiftly feeds? Do we have swiftly API keys and urls? @holly-g can we lay out an issue / enhance this one to take this end-to-end, so we can make sure it's self-contained. Seems like we need...

* a list of feeds urls that will use the swiftly API / headers (or a pointer to a list)
* a working API key, url for verification (or key to test fetching the feed)
* to specify how to add to agencies.yml (e.g. could use a nested dictionary of `<header_type>: <header_value>` on the feeds entry)
* a written strategy for how we will verify it's working (e.g. check the bucket, etc..)

**Comment by chriscauley** [comment]
Just a heads up, I have a fix for this but I don't have the ability to assign it to myself (I think I need to be added on the project). PR inbound.

We'll still need all the things from @machow's comment above to verify that it's working. I can confirm that the headers are being added to the request, but it would be nice to verify with a live data source.

**Comment by lottspot** [comment]
It looks like this is merged and not yet deployed-- myself, Evan, and Chris C are meeting tomorrow to review deployment patterns so there should be an update after that discussion

**Comment by evansiroky** [comment]
This has been resolved.
