### ISSUE TITLE
The GTFS-RT-Archive script should be monitored to detect any periods of downtime

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#887]
**Is your feature request related to a problem? Please describe.**

Some kind of monitoring should exist to make sure the GTFS-RT-Archive script is always running.

**Describe the solution you'd like**

Some kind of health check of whether the script is running should always be running.

**Describe alternatives you've considered**

* Reporting health from the script itself
* Prometheus + Grafana
* @lottspot may have other ideas

**Comment by machow** [comment]
Hey--the service logs a tick every 20 seconds. Is this what you're looking for?

![image](https://user-images.githubusercontent.com/2574498/147505284-05251ae4-0168-4d04-8b03-2e4662af4c33.png)

Can also get from bigquery using:

```SQL
SELECT
  *
FROM `cal-itp-data-infra.gtfs_rt_logs.stdout`
WHERE
  DATE(timestamp) = "2021-12-27"
  AND textPayload LIKE "%tick%"
LIMIT 1000
```

If you're interested in digging in more into the logs, @Nkdiaz is a good person to connect with on how to search them / what's been exported into bigquery! (Note that logs by default only stay around for a limited number of days; so need to be loaded into bigquery, set to store forever, or a filtered version of them stored in a bucket).

**Comment by machow** [comment]
cc @themightychris

**Comment by lottspot** [comment]
@lauriemerrell has put together a wonderful metabase dashboard which helps us evaluate the reliability of this component and which she checks daily. This has already gone a long way to helping us improve in this area. While we will want to continue to evolve our monitoring, the basis of this task should be considered completed.
