### ISSUE TITLE
Avoid gtfs-rt-archive hiccups when uploading updates to agencies.yml

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#888]
**Is your feature request related to a problem? Please describe.**

It's possible that a hiccup could occur when restarting the gtfs-rt-archive service when updating the agencies.yml file that could result in missed collections of data.

**Describe the solution you'd like**

The gtfs-rt-archive script should not be restarted each time the agencies.yml is changed but should pull it as needed to avoid any hiccups.

**Comment by holly-g** [comment]
Resolved by #999.
