### ISSUE TITLE
New Team Member - Chris Cauley (Jarvus)

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#895]
Name: Chris Cauley
Role: Software Engineer
Reports to: @themightychris 

Google Workspace Email Address: chris.cauley@jarv.us
GitHub Username: @chriscauley
Slack Username: 

**Set-up:**
- [x] Technical Onboarding call scheduled

- [x] Added to tools:
  - [x] Github
    - [x] Organization: Cal-ITP
    - [x] Team: jarvus
    - [x] Team: warehouse-users
  - [x] JupyterHub
  - [x] Google Cloud Console
  - [x] Metabase
  - [x] Slack

- [x] Added to meetings:
  - [x] Daily Stand-ups
  - [x] Lunch n' Learn

- [x] Added to Slack channels:
  - [x] #data-analyses
  - [x] #data-office-hours
  - [x] #lunch-n-learn

**Comment by charlie-costanzo** [comment]
Hey @evansiroky @hunterowens - just tagging you in as we have another new team member joining, Chris Cauley! We just need to get Chris added to Github and Slack.

**Comment by charlie-costanzo** [comment]
hey @evansiroky I just wanted to see if you're able to get @chriscauley into the GitHub organization + teams at some point today
