### ISSUE TITLE
Come up with a way to mark URLs that are no longer functional

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#899]
What is the expected behavior? Thinking specifically...

* Should they have a report for a month where this url is marked null?
* Should their latest known data be included in our latest known data dataset (the gtfs_schedule dataset)?

Currently, I would say our data views reflect "latest known feed data", so their last downloaded feed / this url are what come up when you query the latest data. We could support mechanisms for (1) marking an entire feed as deleted, e.g. this gtfs schedule no longer exists / is relevant in any way, and (2) marking URLs that aren't supported , e.g. this data still exists and this was the url it came from, but there is no current url.

_Originally posted by @machow in https://github.com/cal-itp/data-infra/issues/494#issuecomment-946144413_

**Comment by machow** [comment]
See also these discussions about the structure of agencies.yml:

* https://github.com/cal-itp/data-infra/issues/146#issuecomment-856964043
* https://github.com/cal-itp/data-infra/issues/154

**Comment by lauriemerrell** [comment]
I believe that this need is met by the `deprecated_date` and related fields in GTFS datasets (available in the warehouse), recommend closing this ticket.
