### ISSUE TITLE
dump mobility gtfs-validator error code schemas as json or yaml

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#90]
Currently, the pipeline loads the json report from gtfs-validator, which includes about 100 code-specific fields. However, it has 2 limitations:

* when new fields are added by the validator, they will need to be added manually (a quick task)
* we can't say--for this code, these are the fields it uses (e.g. shapeDistTraveled, etc).

The second would be useful for analysis, since it will let us pull code-specific columns out of the very wide validation_notices table. Note that we pull this info from the reports themselves, but in the long run it'd be useful to have a way to generate it from the gtfs-validator repo.

**edit:** here's a quick script for pulling out fields based on the data

```python
import gcsfs
import json

fs = gcsfs.GCSFileSystem(project="cal-itp-data-infra")
reports = fs.glob("gs://gtfs-data-test/schedule/processed/*/validation_report.json")
reports_json = [json.load(fs.open(fname)) for fname in reports]

code_fields = defaultdict(lambda : set())
for report in reports_json:
    for notice in report["notices"]:
        for entry in notice["notices"]: code_fields[notice["code"]].update(entry.keys())
```

Note that one notice field, `suggestedExpirationDate` is a dictionary with subentries (of form `{"localDate": {"year": int, "month": int, "day": int}}`), which are not captured by the script (and maybe should be named in our flat table `suggestedExpirationDate_localDate_year`, etc..?).

**Comment by e-lo** [comment]
> The second would be useful for analysis, since it will let us pull code-specific columns out of the very wide validation_notices table. Note that we pull this info from the reports themselves, but in the long run it'd be useful to have a way to generate it from the gtfs-validator repo.

I agree that this should be an issue in https://github.com/MobilityData/gtfs-validator

**Comment by machow** [comment]
Thanks for the nudge--was going to focus on getting a table up the quick way before filing an issue, but tossed one up to stew in the meantime!

https://github.com/MobilityData/gtfs-validator/issues/899

**Comment by hunterowens** [comment]
@machow to close when #129

**Comment by machow** [comment]
Running in pipeline--will keep an eye on the mobilitydata issue, in case we can pull out the schema more easily  later on!
