### ISSUE TITLE
Fix high memory usage in validation_fact_notice_fields task view

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#900]
https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/validation_fact_notice_fields.py

This task pulls all the fields out corresponding to a code that the validator could throw. Recently this task failed, and looking at metric explorer, it appears to be maxing out memory (> 12 GB).

It looks like it's opening all validation reports into memory before looping over them. If we move the opening into the loop it should resolve. Note also that recently the GTFS validator added an option to dump its code schema, which is a simpler way to get this information (e.g. we couldn't do it before, but it was fast to infer it from the data).

**Comment by evansiroky** [comment]
Resolved with #901
