### ISSUE TITLE
Need a way to test out downloading all RT files in agencies.yml

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#908]
Currently, when we update links to RT feeds in agencies.yml, we need to do the following to evaluate the URLs:

* review a PR
* merge into main
* wait for the GTFS RT service to restart and pick it up

However, the simple act of downloading RT feeds from agencies.yml (or rather [agencies.filled.yml](https://github.com/cal-itp/data-infra/blob/main/.github/workflows/push_to_gcloud.yml#L39)) is pretty straightforward to implement in a few lines of python. 

It would be useful to have a way for users to test the links they are adding, or debug existing links (in addition to looking at logs).

## Proposal

* we add a workflow or job that can be initiated using github [workflow dispatch](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch)
  * by default the dispatch tries to download each URL in agencies.yml (after inserting API keys)
  * could also add an input to the dispatch to let people try only a specific agency, etc..
* we add a simple script in the `script` folder that takes the filled in agencies.yml and optional extra input as command line args, and attempts the downloads
  * it should be robust to failure, and report / summarize all failures at the end
* a natural place for this might be in push_to_gcloud.yml
  * let's be careful not to accidentally trigger other parts of `push_to_gcloud.yml`

**Comment by lottspot** [comment]
The existing collector could easily be run locally to perform URL validation; it already logs URL retrieval errors to stdout and has the capability to write data to /dev/null (which is actually the default location when none other is provided).

The collector could actually be wired up as-is to a docker-compose project in order to satisfy this need
