### ISSUE TITLE
Document how the the logs from the archiver service are automagically saved to Google Cloud

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#915]
The documentation about how the logs from the archiver service are automagically saved to Google Cloud and analyzeable within the logging dashboard seems like it could use a little more explanation. Was any extra configuration required to get this setup? The particular documentation in question is here:

https://github.com/cal-itp/data-infra/blob/38a2a6d4bbccdc7f8572255a0db26ee72003e494/docs/datasets_and_tables/gtfs_rt.md?plain=1#L50

However, that documentation might be able to live elsewhere.

_Originally posted by @evansiroky in https://github.com/cal-itp/data-infra/pull/879#discussion_r779250450_

**Comment by Nkdiaz** [comment]
@evansiroky I am meeting with @lottspot  to discuss further now the gtfs-rt-archive bucket is configured. I can write down my notes in this issue and update the documentation accordingly

**Comment by Nkdiaz** [comment]
Within the `gtfs-rt-archive. py` script, A logger channel is set up with the 'logging' facility for Python. Within this logger object, we define the log levels(info, warning, error, critical etc). The script loads the agencies.yml, instantiates the threads, and if the thread returns an error, then that error gets logged.
some of the errors we are currently logging and their associated error levels:
- missing feeds (Warning)
- missing itp_id (Warning)
- event dropped (Warning)
- Ticker (Debug)
- error fetching URL (Info)
Then the script writes to a GCPBucketWriter, via a post request. This data (the feed files and log files) go to a Kubernetes cluster where it is stored in the 'data-infra-apps'.  Google cloud automatically creates specific buckets called 'logging buckets' when the cluster is stood up, these are called `_Default` and `_Required`. Cloud Logging provides these two predefined sinks for each Cloud Project. All logs that are generated in a resource are automatically processed through those two sinks and then are stored either in the `_Required` or `_Default Buckets`.` _Required` has retention for 400 days and appears to have mostly audit log functionality for data compliance. We are mostly using `_Default` which has a retention of 30 days to log all of our cloud services. I created a log sink called "rt-extract-to-bigquery' that filters the logs within`_Default` for the namespace 'resource.labels.namespace_name="gtfs-rt"'. To reliably route logs, the log router stores the logs temporarily, which buffers against temporary disruptions on any sink. According to this documentation, the log logging frequency between Cloud Logging and Bigquery is 'near real-time' https://cloud.google.com/logging/docs/export/using_exported_logs#bigquery-frequency. 
Within The BigQuery table, the error messages are stored within the `stdout` table. The table names are generated automatically through the cloud router and cannot be renamed. The `stout` table is a partitioned table that does not have any limits on storage size currently. It might be worth a further conversation if we want to run a monthly pruning query on the timestamps to minimize storage size.

**Comment by Nkdiaz** [comment]
Within the `gtfs-rt-archive. py` script, A logger channel is set up with the 'logging' facility for Python. Within this logger object, we define the log levels(info, warning, error, critical, etc). The script loads the agencies.yml, instantiates the threads, and if the thread returns an error, then that error gets logged.
some of the errors we are currently logging and their associated error levels:
- missing feeds (Warning)
- missing itp_id (Warning)
- event dropped (Warning)
- ticker (Debug)
- error fetching URL (Info)
Then the script writes to a GCPBucketWriter, via a post request. This data (the feed files and log files) go to a Kubernetes cluster where it is stored in the 'data-infra-apps'.  Google cloud automatically creates specific buckets called 'logging buckets' when the cluster is stood up, these are called `_Default` and `_Required`. Cloud Logging provides these two predefined sinks for each Cloud Project. All logs that are generated in a resource are automatically processed through those two sinks and then are stored either in the `_Required` or `_Default Buckets`.` _Required` has retention for 400 days and appears to have mostly audit log functionality for data compliance. We are mostly using `_Default` which has a retention of 30 days to log all of our cloud services. _Default gets updated from the kubernetes cluster in hourly batches. I created a log sink called "rt-extract-to-bigquery' that filters the logs within`_Default` for the namespace 'resource.labels.namespace_name="gtfs-rt"'. To reliably route logs, the log router stores the logs temporarily, which buffers against temporary disruptions on any sink. According to this documentation, the log logging frequency between Cloud Logging and Bigquery is 'near real-time' . https://cloud.google.com/logging/docs/export/using_exported_logs#bigquery-frequency.
Within The BigQuery table, the error messages are stored within the `stdout` table. The table names are generated automatically through the cloud router and cannot be renamed. The `stout` table is a partitioned table that does not have any limits on storage size currently. It might be worth a further conversation if we want to run a monthly pruning query on the timestamps to minimize storage size

**Comment by evansiroky** [comment]
> Within the `gtfs-rt-archive. py` script, A logger channel is set up with the 'logging' facility for Python. Within this logger object, we define the log levels(info, warning, error, critical, etc). The script loads the agencies.yml, instantiates the threads, and if the thread returns an error, then that error gets logged. some of the errors we are currently logging and their associated error levels:
> 
> * missing feeds (Warning)
> * missing itp_id (Warning)
> * event dropped (Warning)
> * ticker (Debug)
> * error fetching URL (Info)
>   Then the script writes to a GCPBucketWriter, via a post request. This data (the feed files and log files) go to a Kubernetes cluster where it is stored in the 'data-infra-apps'.  Google cloud automatically creates specific buckets called 'logging buckets' when the cluster is stood up, these are called `_Default` and `_Required`. Cloud Logging provides these two predefined sinks for each Cloud Project. All logs that are generated in a resource are automatically processed through those two sinks and then are stored either in the `_Required` or `_Default Buckets`.` _Required` has retention for 400 days and appears to have mostly audit log functionality for data compliance. We are mostly using `_Default` which has a retention of 30 days to log all of our cloud services. _Default gets updated from the kubernetes cluster in hourly batches. I created a log sink called "rt-extract-to-bigquery' that filters the logs within`_Default` for the namespace 'resource.labels.namespace_name="gtfs-rt"'. To reliably route logs, the log router stores the logs temporarily, which buffers against temporary disruptions on any sink. According to this documentation, the log logging frequency between Cloud Logging and Bigquery is 'near real-time' . https://cloud.google.com/logging/docs/export/using_exported_logs#bigquery-frequency.
>   Within The BigQuery table, the error messages are stored within the `stdout` table. The table names are generated automatically through the cloud router and cannot be renamed. The `stout` table is a partitioned table that does not have any limits on storage size currently. It might be worth a further conversation if we want to run a monthly pruning query on the timestamps to minimize storage size

If this can be added to the documentation via a pull request that would probably be able to close out this issue.

**Comment by Nkdiaz** [comment]
will be closed by https://github.com/cal-itp/data-infra/pull/918
