### ISSUE TITLE
Pruning Query to clean up GTFS-RT-Logs

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/data-infra#916]
Currently, we are storing all of the GTFS-RT-Logs within a BigQuery table named 'gtfs-rt-logs'. This currently contains both the ticker notifications and the feed-URL errors and does not have a particular storage limit set. It might be worth discussing if we want to do a monthly or quarterly pruning query based on the timestamps to help cut down on storage. 

Note the GC bucket that we export this data from has a retention of 30 days.

Please see https://github.com/cal-itp/data-infra/issues/915 for background information/context

**Comment by atvaccaro** [comment]
v1 archiver ticket
