### ISSUE TITLE
Analytics Style Guide

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#922]
**Is your feature request related to a problem? Please describe.**

Implement an analytics / visualization style guide based on Cal-ITP's branded resources for slides / docs.

**Describe the solution you'd like**
Build a package part of `shared_utils` that will handle most of the styling for visualizations made within Jupyter Notebooks. Make it available for all the major charting packages: `altair`, `matplotlib`, `seaborn`, `plotnine`.

**Describe alternatives you've considered**

**Additional context**

**Comment by charlie-costanzo** [comment]
hey @tiffanychu90 - so I actually figured out how to update the jupyterhub image this past week and added `plotnine` as part of my testing process. I can add the rest of the packages the same way if you'd like, and talk about what else we'd like to have on there.

**Comment by tiffanychu90** [comment]
@charlie-costanzo: Sure, can you add the rest of the packages to be part of the image? Here's the [list](https://github.com/cal-itp/data-analyses/blob/4d00859d13c20bc933f24b9d889d4cdc46e00904/_shared_utils/setup.py)

**Comment by tiffanychu90** [comment]
restoring packages until image updated: https://github.com/cal-itp/data-analyses/commit/c0de1943ba03d658675bc3dab0aa296cffdd9756, https://github.com/cal-itp/data-analyses/commit/dc81d64432567931668b8aef416c40ab10e064be

**Comment by tiffanychu90** [comment]
@charlie-costanzo: Are you able to add the GitHub branch name in the terminal interface too? See #659

**Comment by charlie-costanzo** [comment]
ah nice thanks for flagging @tiffanychu90 I will take a look!

**Comment by tiffanychu90** [comment]
https://github.com/cal-itp/calitp-py/pull/33
