### ISSUE TITLE
Bug: Long Beach Transit (170) extracted at/deleted at fields empty in gtfs_schedule_fact_daily_trips

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#940]
**Describe the bug**
When filtering for Long Beach Transit (itp id 170), `calitp_extracted_at` and `calitp_deleted_at` are empty in gtfs_schedule_fact_daily_trips

**To Reproduce**
1. Open gtfs_schedule_fact_daily_trips in Metabase and filter for itp id 170, view blank columns for `calitp_extracted_at` and `calitp_deleted_at`
2. Or using siuba: `tbl.views.gtfs_schedule_fact_daily_trips() >> filter(_.calitp_itp_id == 170)`

**Expected behavior**
 `calitp_extracted_at` and `calitp_deleted_at` data present, which is helpful for analysts to run faster/smaller queries on a time period of interest.

**Additional context**
itp_ids 16, 48, 208, and 372 may have a similar issue.

**Comment by Nkdiaz** [comment]
Research Journey: 
Verified that `calitp_id ` 170 is missing from the `views.gtfs_schedule_fact_daily_trips`. The `calitp_extracted_at/deleted_At` columns are null for all rows. Using the feed key I looked at the `gtfs_schedule_fact_daily_feeds` and verified that for this test date of 2021-10-30 the extraction was success.  Looking at how the `extracted_at/deleted_at` column is populated in the `gtfs_schedule_fact_daily_trips`, it appears to be a subtable `daily_service_trips` where stg_daily_service_keyed is joined to views.gtfs_schedule_dim_trips where `calitp_id_extrated at is <= service date` and `calitp_deleted_at > service_date`. I verified that `calitp_extracted_at/deleted_at` are populated correctly in `gtfs_schedule_dim_trips`. Both tables have the data type of date and there are no leading/lagging white spaces I can discern from the JSON output.

**Comment by Nkdiaz** [comment]
After discussing at the standup, per the gtfs guidlines, agencies are only required to send either the calendar.txt or calendar_dates.txt [gtfs-guidelines] 'https://developers.google.com/transit/gtfs/reference#calendartxt'
