### ISSUE TITLE
Research: Are joins failing due to whitespace?

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#944]
Spun out of #914. We identified a feed that had corrupt data (`service_id` had leading whitespace in one file but not another), leading to a failed join and missing data in final views. We are wondering whether other joins are running into this same issue, so we would want to run some checks in BigQuery to see whether there are other joins where agencies are being dropped due to whitespace mismatches. 

cc @holly-g for prioritization. We basically aren't sure of impacts right now because we aren't sure whether other feeds/joins are affected, so this would be a research task to figure that out. @Nkdiaz had some ideas about how to approach this.

**Comment by lauriemerrell** [comment]
cc @Nkdiaz

**Comment by Nkdiaz** [comment]
closing this issue because it has been restructured to @lauriemerrell [ticket](https://github.com/cal-itp/data-infra/issues/946)
