### ISSUE TITLE
Trim whitespace in GTFS schedule data

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#946]
Spinning out from #914 after discussion in #gtfs-quality Slack channel. 

We decided we *should* trim whitespace from GTFS schedule data in our ingestion pipeline. 

Should be trimmed after validation is run to preserve whitespace validation notices (for posterity?)

At time of writing, not sure of best point in ingestion at which to do this.

**Comment by lauriemerrell** [comment]
This issue came up in my conversation with @mjumbewu this morning. 

We landed on the idea (which maybe came up yesterday too?) that the trimming probably needs to happen when the raw schedule files are copied over to `gtfs-data/schedule/processed` (it seems preferable to do the trimming in Python rather than trying to do it in SQL after they're loaded....) 

Looks like the thing to update would be: https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/utils.py#L7 
We're already loading into pandas to copy, seems like we can trim at that point? 

And then the main remaining question is actually backfilling this once this change is made.

cc @Nkdiaz @holly-g, not sure who wants to actually take this on

**Comment by lauriemerrell** [comment]
Discussed with @machow today. He pointed out that it might be preferable to do this trimming in `gtfs_views_staging` where the `gtfs_schedule_type2.<file>_clean` tables are created, rather than doing it in Python. That way:
* The totally raw data is still available and queryable in the `gtfs_schedule_history` external tables. 
* You don't have to re-run anything, the changes are picked up automatically. 

**Outstanding questions:**
* What fields exactly are we trimming -- are we only trimming ID fields to avoid the failing joins issue? Or are we trimming *all* fields? It seems like trimming *all* fields is actually fairly standard. But the real impact of not trimming seems to be the joins.
* Confirming which approach we want to take -- trim on file copy or trim on clean table load. 

**Side notes:**
* Michael said that CASTing dates has not failed in https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views_staging/calendar_clean.sql, indicating that leading/trailing spaces have not been present in the dates. So that would be a point in favor of just trimming IDs for now.
* We confirmed that all the raw data is still loaded as strings as of `gtfs_views_staging`, so trimming should be ok (one concern with trimming on the SQL side is that you can only trim string type data). 
* I think we need to let analysts know when we make this change (we probably should anyway but specifically:) because if we trim IDs before the `<record>_key` values are created, I think those values will change, so if they have any active notebooks where any of those key values are hard-coded they would need to change those.

**Comment by lauriemerrell** [comment]
One thing to confirm -- if we trim at clean table generation, should confirm that any joins with the validation_notices tables still work (do those reference the raw IDs? Maybe we need to trim those fields in the validation results tables too.)

**Comment by lauriemerrell** [comment]
A few additional things: 
* The (schedule) validator [explicitly](https://github.com/MobilityData/gtfs-validator/blob/master/core/src/main/java/org/mobilitydata/gtfsvalidator/notice/LeadingOrTrailingWhitespacesNotice.java) only emits a LeadingOrTrailingWhitespaces notice if the value in the feed is inside double quotes. (So '" 7"' will throw the error but ' 7' will not.)
* Do we want to add additional validation on our side that creates some kind of notification for cases where there is whitespace that's not getting caught by the existing validator? (i.e., that would have caught this SacRT issue?)

**Comment by lauriemerrell** [comment]
A bit more context from @mjumbewu, copied from Slack:

>  according to the [spec](https://datatracker.ietf.org/doc/html/rfc4180#page-2), §2.4, "Spaces are considered part of a field and should not be ignored." Looking further down at the grammar at the end of section 2, the only things that are not considered TEXTDATA in a non-quoted field are double quotes and commas.
> Python's default CSV parser keeps spaces, but allows you to [disable that behavior](https://docs.python.org/3/library/csv.html#csv.Dialect.skipinitialspace). Looks like Pandas also has a [skipinitialspace](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv) parameter on `read_csv` that defaults to `False`.
> SO, if we should be loading whatever raw data is in the CSVs into the warehouse, what that raw data actually is depends on our decision about `skipinitialspace`. (But this doesn't change the decision to trim legit whitespaces in SQL instead of Python).

And, per some other conversation in Slack, it seems important to clarify:
**Right now, our pipeline treats quoted and unquoted spaces  identically. So in our pipeline right now, of the following cases:
1.  `<space>7`
2.  `"<space>7"` 
3. `7`. 
1 & 2 are treated as identical, and both are treated differently than 3. However the GTFS validator only throws whitespace errors in *quoted* fields, so the validator would throw and error for 2 but not 1.**

So, I am updating my outstanding questions list from above: 

**Outstanding questions -- updated:**
1. What fields exactly are we trimming -- are we only trimming ID fields to avoid the failing joins issue? Or are we trimming all fields? It seems like trimming all fields is actually fairly standard. But the real impact of not trimming seems to be the joins.
2. Do we want to change `skipinitialspace` in `utils._keep_columns`? (Note that this only addresses leading spaces, not trailing ones. It also seems like this would affect both quoted and unquoted fields.)
3. Do we want to add trimming in `gtfs_views_staging`?

**Comment by machow** [comment]
Thanks for summarizing @lauriemerrell :). Just to add one thing, dovetailing off @mjumbewu's thoughts.

* If it seems like a legit loading issue (e.g. "we are parsing csvs wrong"), then I could see changing the pre-processing task. But in the case of even slight ambiguity I would say fixing belongs in SQL transformation, because whether it's an error is a business decision.
* In other words, the validator can change how it handles this, and guidelines could change. But it would be annoying to have to update the raw data load to reflect these business realities, when we have a staging layer for that.

**Comment by lauriemerrell** [comment]
Took more of a deep dive into this, a few more notes:
* My main question is how to trim efficiently in SQL -- we have to trim every string column and you can't just do a `TRIM(*)`
* The schemas for each external table are explicitly defined in `gtfs_schedule_history.<table>` 
* That schema is then referenced in `gtfs_loader` here: https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_loader/gtfs_schedule_history_load.py#L26
* So we have already defined the columns that we have by the time we get to `gtfs_views_staging`. If we enumerate each column in `gtfs_views_staging`, we have to manually keep that in sync with `gtfs_schedule_history`. 😕 But that might just be what we have to do... 
* I ran some quick checks to see what fields have leading/trailing whitespace, and it is a lot of them -- 34 distinct columns across 12 distinct tables had whitespace that would get trimmed (and that doesn't include `shapes` or `stop_times` because they were too big for me to load into my notebook for this ad hoc quick check). For example 201 unique `calitp_itp_id`s had leading or trailing whitespace in `stop_lat` and `stop_long`. So I do think that this is an argument for trimming all of it and not just IDs.
