### ISSUE TITLE
Docs: Support for analysts working with calitp_extracted_at / calitp_deleted_at

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#953]
Per conversation with @edasmalchi, it can be difficult for analysts to work with the `calitp_extracted_at` / `calitp_deleted_at` fields in the data warehouse. 

We should add some dedicated documentation about:
* How these fields are populated & how to interpret them 
* How to use these fields in some example queries to get the correct set of active information (potential example: what `trip_id` values should be considered "active" for some date in the past) 

Note: Currently sometimes these fields are blank (Eric submitted as separate ticket #940 -- outcomes of that may be relevant for documentation here).

**Comment by lauriemerrell** [comment]
Heads up @charlie-costanzo

**Comment by charlie-costanzo** [comment]
hey @lauriemerrell what would you say is missing from this resource - aside from the fact that it could be easier to find / in a more relevant place

[Docs / Warehouse / SQL Snippets](https://docs.calitp.org/data-infra/warehouse/sql_snippets.html)

**Comment by lauriemerrell** [comment]
@charlie-costanzo I am just closing this based on our convo... Seems like the documentation is there
