### ISSUE TITLE
Ingest Google Cloud Billing Data into Metabase as new source 

### ISSUE THREAD

**Issue by vykster** [cal-itp/data-infra#959]
**Is your feature request related to a problem? Please describe.**
Staff are limited in who can be granted access to view and/or receive billing notifications in Google Cloud console. Staff will be even more limited after the upcoming ownership migration. 

**Describe the solution you'd like**
Simple usage and billing data is available to be self-served in metabase

**Describe alternatives you've considered**
Adding individuals directly to google cloud console

**Additional context**
I don't have any preference for visualizations, would need to scope with staff who watch billing accounts/usage. 
Relevant Cloud help article: [Export Cloud Billing data to BigQuery](https://cloud.google.com/billing/docs/how-to/export-data-bigquery?_ga=2.44254052.-1169585143.1641321956)

**Comment by holly-g** [comment]
Tracking this ticket here in the `Data Services Backlog`, please let us know if the Data Services team can help!

**Comment by vykster** [comment]
Thanks @holly-g.

@angela-tran @machikoyasuda could one of you pick up this ticket? @thekaveman can give you some background.

**Comment by thekaveman** [comment]
Not a priority as we continue conversations about shifty GCP responsibility and ownership.
