### ISSUE TITLE
Differentiate between validator "errors" and "warnings" on reports.calitp.org

### ISSUE THREAD

**Issue by o-ram** [cal-itp/data-infra#963]
**Is your feature request related to a problem? Please describe.**
Since the December reports email went out, I've had a handful of agencies ask me why we are calling something an "error", but when they validate their feed themselves, it is a "warning". Each time I've looked into this in Metabase, the codes in question are indeed classified as warnings. This is causing some confusion for agencies.

**Describe the solution you'd like**
I'd like for the "validation errors" charts on the reports site to label codes as an "error" or a "warning". The table in the below screenshot could be called "Validation notices observed" instead, and then a "severity" column could be added to the table to convey error or warning. 
<img width="1297" alt="Screen Shot 2022-01-19 at 3 19 53 PM" src="https://user-images.githubusercontent.com/92001064/150234907-d30fc9a0-159c-4375-abf2-d47eb70d8447.png">

**Describe alternatives you've considered**
Only convey true errors on the site and filter out warnings altogether. Warnings may still be of interest to include on the site, which is why I have made it to the alternative option. I am open to doing this instead though.

**Comment by evansiroky** [comment]
@o-ram, both the reports website and metabase are including validation notices based on what is in the [Critical GTFS Validation Errors](https://dot.ca.gov/cal-itp/Critical-GTFS-Validation-Errors) list. The notice referred to in the screenshot in this issue is included in that list. Please advise on whether we need to filter out notices that are also warnings, but are included in the critical errors list.

**Comment by o-ram** [comment]
@evansiroky I'd like to either filter out the notices that are also warnings, or convey on the site that it's a warning. If we keep things as-is, then we should have an explanation to give agencies for why we are calling something an error even though the validator says it's a warning. To stick with the MST example, yes, that notice is on our critical validation errors list, but Metabase reported that this notice was just a warning in this instance. 

To show a different example, see the AC transit results from Metabase
<img width="701" alt="Screen Shot 2022-01-19 at 4 51 25 PM" src="https://user-images.githubusercontent.com/92001064/150246175-04980ca0-1ccb-4e44-9472-67a9737a03a4.png">

In this case, I would prefer that we either _only_ include the error in AC Transit's report, or we should label that the duplicate_route_name code is a warning, while the duplicate_fare_rule is an error.

Personally, I'd prefer we label warning vs error on the site like Metabase does, because I think the warnings are still important to convey if it's one of the notices on our list. I just don't want agencies to see our reports as inaccurate because of this discrepancy, as they will prioritize a validation error over a warning, so they consider the difference to be important.

Please let me know if I'm not making sense!

**Comment by Nkdiaz** [comment]
Wanted to clarifying some of the points that Evan raised. 
Calitp has a list of critical validation errors that are considered critical **by calitp**. Those are the data standards we are imposing regardless of the validator's severity for that code. So whether **the validator** says something is a warning or an error, it doesn't matter as much as **our** standards which say it's critical or not.  
There is still the option to add the warning vs. error column and label that as the validation severity from the validator to help illustrate that it is separate from us.

**Comment by o-ram** [comment]
The problem with that is we don't have adequate explanations at hand to give an agency for _why_ we are imposing something stronger than the validator. Why do we consider something a critical error when the validator calls it a warning? And it's causing tension with some agencies who want a reason, say we use the word critical far too often, and then choose to not work with us. So, we either need to distinguish between what the validator says or have thorough reasoning for why besides "these are our data standards". I personally would like to see us add the warning vs. error column. It doesn't mean we won't ask/advocate for these to be fixed, but it makes agency interactions easier to say we know it's a warning by validator standards, but here's why you should still fix it/why Cal-ITP cares about it.

**Comment by Nkdiaz** [comment]
currently implemented in march reports, once march reports are approved by @o-ram, the branch will be merged into main and we can close this ticket. Worth mentioning that I will not be updating previous months to have the severity table, it will just be march moving forward
