### ISSUE TITLE
Bug: get interactive widgets rendering properly

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#965]
**Describe the bug**

The `ipywidget` won't update interactively in the notebook, but logs show updated print statements. 

**To Reproduce**

This PR is tracking this issue: https://github.com/cal-itp/data-analyses/pull/54

**Expected behavior**
The dropdown updates and the print statements update accordingly, either within the notebook or within Voila locally.

**Additional context**

**Comment by tiffanychu90** [comment]
@charlie-costanzo: this is a good issue for analytics tooling quality-of-life improvement

**Comment by edasmalchi** [comment]
I might have figured this out, see comment on PR: https://github.com/cal-itp/data-analyses/pull/54#issuecomment-1016978638
