### ISSUE TITLE
GTFS(rt) Data: SDMTS

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#966]
Update `agencies.yml` in order to....

Add the following gtfs datasets:
[SD MTS now has gtfs-rt](https://www.sdmts.com/business-center-developers/real-time-data)

Update the following gtfs datsets:

```san-diego-metropolitan-transit-system:
  agency_name: San Diego Metropolitan Transit System
  feeds:
    - gtfs_schedule_url: https://www.sdmts.com/google_transit_files/google_transit.zip
      gtfs_rt_vehicle_positions_url: null
      gtfs_rt_service_alerts_url: null
      gtfs_rt_trip_updates_url: null
  itp_id: 278

```
## Checklist

- [ ] Manually made sure any new feeds have `itp_id`s that are not duplicative
- [ ] Mannually confirmed URIs are valid (to be automated in future per #908)
- [ ] Made sure the Airtable database has consistent information

**Comment by hunterowens** [comment]
FYI @evansiroky I've put in a request for the API key and will do the PR when ready

**Comment by evansiroky** [comment]
> FYI @evansiroky I've put in a request for the API key and will do the PR when ready

Looks like both you and me have made a request for an API key. Here is the note about my request: https://github.com/cal-itp/data-infra/pull/968#issuecomment-1018176393
