### ISSUE TITLE
New Team Member - Andrew Vaccaro (Jarvus)

### ISSUE THREAD

**Issue by holly-g** [cal-itp/data-infra#971]
Name: Andrew Vaccaro
Role: Data Tools Lead Engineer
Reports to: @themightychris 

Google Workspace Email Address: andrew.v@jarv.us
GitHub Username: @atvaccaro
Slack Username:

Starts full-time on Feb 7

**Set-up:**
- [x] Technical Onboarding call scheduled

- [x] Added to tools:
  - [x] Github
    - [x] Organization: Cal-ITP
    - [x] Team: jarvus
    - [x] Team: warehouse-users
  - [x] JupyterLab
  - [x] Google Cloud Console
  - [x] Metabase
  - [x] Slack

- [x] Added to meetings:
  - [x] Daily Stand-ups
  - [x] Lunch n' Learn
  - [x] Data Team All-Hands

- [x] Added to Slack channels:
  - [x] #data-analyses
  - [x] #data-infra
  - [x] #data-office-hours
  - [x] #lunch-n-learn

**Comment by charlie-costanzo** [comment]
Hey @evansiroky and @hunterowens! I just wanted to flag that Andrew will need to be added to the GitHub organization and Slack soon

**Comment by evansiroky** [comment]
> Hey @evansiroky and @hunterowens! I just wanted to flag that Andrew will need to be added to the GitHub organization and Slack soon

I just took care of the GitHub org and Slack invites.

**Comment by charlie-costanzo** [comment]
thank you @evansiroky!

**Comment by holly-g** [comment]
Pre-onboarding, complete 🎉
