### ISSUE TITLE
Airtable view:  California Transit

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#973]
California Transit table from #774 

Update -- breaking into multiple PRs / subtasks:
- [x] #990 imports raw data to internal tables in warehouse (`airtable` dataset; initially imported data is **not** user-friendly but is technically accessible)
- [x] Confirm subsequent approach -- prioritization of table joins to support and normalization schema
- [x] Create at least a few initial views with enough normalization to support analysis

**Comment by lauriemerrell** [comment]
Per conversation with @evansiroky -- 
* Will start by focusing on some of the "core" tables in the California Transit base:
   * Organizations
   * Services
   * GTFS service data
   * GTFS datasets 
* Will start by just running the Airtable operator and seeing how the "raw" outputs look in Metabase to scope out how much processing is needed. Specifically, wondering how much unpacking we'll need to do for many-to-one relationships. 
* Per #983, will be using a new Airtable dataset in BQ for this data, and will prefix each table with its base of origin.

**Comment by lauriemerrell** [comment]
Notes: 
* A bunch of the raw column names contain characters (`#` or `=` specifically) that BigQuery does not allow, and that our current `to_snakecase` function does not strip out. I am addressing them manually using the `rename_fields` parameter for now, wanted to note since it's a bit of a gotcha -- the # signs in particular are interpreted as comments in YAMLs so have to escape with double quotes. 
* Before loading to the final warehouse location, do we want to strip out the foreign key columns from the current schemas and move those to mapping tables or something? (For example, drop the `mobility_services_managed` list-type column from `organizations` and instead create an `organization_service` mapping table that captures those relationships.)
  * [BQ docs](https://cloud.google.com/bigquery/docs/nested-repeated) say *not* to do this, but this data is not particularly huge and I wonder if having those kind of explicit mapping tables would be useful to people who will be consuming the data? Need to see what the nested/repeated columns look like in Metabase. 
* Some columns are metrics that are being calculated in Airtable (for example, number of complete RT feeds). Do we want to drop those columns and instead calculate them in BigQuery? (I assume that might be a future direction/longer term question, not sure what the long term vision is for the relationship between Airtable and the warehouse.)

**Comment by evansiroky** [comment]
See my feedback inline:

> * A bunch of the raw column names contain characters (`#` or `=` specifically) that BigQuery does not allow, and that our current `to_snakecase` function does not strip out. I am addressing them manually using the `rename_fields` parameter for now, wanted to note since it's a bit of a gotcha -- the # signs in particular are interpreted as comments in YAMLs so have to escape with double quotes.

This sounds good for now. Perhaps it would be useful to have the AirtableOperator log a warning and remove those problematic characters from the column name in the future. The next time we hit this problem or if it seems to be frequently causing DAG tasks to fail, lets create an issue and address then.

> * Before loading to the final warehouse location, do we want to strip out the foreign key columns from the current schemas and move those to mapping tables or something? (For example, drop the `mobility_services_managed` list-type column from `organizations` and instead create an `organization_service` mapping table that captures those relationships.)
>   * [BQ docs](https://cloud.google.com/bigquery/docs/nested-repeated) say _not_ to do this, but this data is not particularly huge and I wonder if having those kind of explicit mapping tables would be useful to people who will be consuming the data? Need to see what the nested/repeated columns look like in Metabase.

Let's keep everything in raw form for now and check later if it needs to be removed or refactored. We may only want to do this for a few columns at a time as needed.

> * Some columns are metrics that are being calculated in Airtable (for example, number of complete RT feeds). Do we want to drop those columns and instead calculate them in BigQuery? (I assume that might be a future direction/longer term question, not sure what the long term vision is for the relationship between Airtable and the warehouse.)

Let's keep everything in raw form for now and check later if it needs to be removed or refactored. Any analysis done should be subject to code review and the use of these special columns should be verified to be the expected information. I added a few columns myself to organizations and services I believe, so if they become confusing, they can either be removed from airtable entirely, prefix-renamed "DO_NOT_USE_column_name" or the AirtableOperator can be modified to have a whitelist of blacklist of columns.

**Comment by lauriemerrell** [comment]
@evansiroky -- right now the Airtable operator by default writes to the `gtfs-data` GCS bucket. (So for example right now the operator's sandbox outputs are going in `gtfs-data/sandbox`.) The operator does not currently allow you to provide a different bucket as an argument, it just reads from a config file via the `calitp.save_to_gcs` function.

Is that ok? For this batch I'd have them write to `gtfs-data/airtable/california-transit`. If you want to have an Airtable-specific bucket, I can modify the operator to take that as an argument.

**Comment by lauriemerrell** [comment]
My understanding from the responses above is that for the initial implementation, we're planning to have one DAG task per table that writes the Airtable data to GCS and simultaneously to a warehouse dataset that is accessible via Metabase, i.e., it sounds like we're **not** thinking of having separate `load` and `view` DAGs at this stage? 

If so, there is a challenge in suppressing columns that we don't want to expose in Metabase (for example `API key` in the GTFS dataset table.) I see a few options:

1. Download the full raw data to GCS (including the API key column) and load only a subset of columns into the warehouse

2. Download the full raw data into GCS and into an internal table in the warehouse (not to be exposed in Metabase) and then subset the columns in a subsequent SQL operator that puts the data in the Metabase-accessible BQ dataset

3. Add functionality to the Airtable operator that lets you skip columns entirely (either via an explicit whitelist or blacklist), and then use that to not save the API key data to GCS at all and we don't have to have two-stage loading for this table. 

Options 1 and 2 would require us to have separate `load` and `view` DAGs for at least any tables with columns we want to suppress in Metabase. Option 3 would let us stick with this more streamlined initial implementation with only one DAG task per table.

However I think this raises a potentially important point -- right now, if someone adds a new column in Airtable, including potentially sensitive data, it would be picked up by default and passed through to Metabase. I wonder if that's an argument for adding an explicit whitelist of columns to make sure that we only expose columns that we want to expose?

**Comment by lauriemerrell** [comment]
Status update:
* Initial, totally naive implementation of this is complete in #990 -- the totally raw data is accessible in the `staging` environment now. 
   * I *did* end up making separate `load` and `views` DAGs, because I think the data does need some transformation to be usable. 
   * We are continuing to use the existing `views` BQ dataset because Metabase doesn't let you join data across datasets and we want to be able to join the Airtable data with other datasets for analysis. 
* Per feedback from @evansiroky, this initial implementation is not sufficient even as an MVP because the way that the linked-record relationships load into the warehouse are totally user-unfriendly. At least some transformation is needed to make this data usable.

Second bullet means that the complexity of this task has increased significantly, because now I will need to actually make explicit mapping tables to capture the different relationships. The implementation is no longer basically content-agnostic and requires actually digging into the schema. 

I am working on a few examples and then will check in to get feedback. A few of the things that we will need to confirm:
* Are there some relationships that are definitely one-to-one? (If so can skip separate mapping tables for these and just treat them as normal foreign keys. It seems like Airtable implicitly structures all linked-record relationships as lists, even if none have more than one link; I'm not sure which are *actually* one-to-one.) 
* How to handle the naming for the mapping tables -- linked records in Airtable have one column in each table, sometimes those columns have semantic titles, sometimes they don't, need a consistent naming scheme.

**Comment by lauriemerrell** [comment]
Synced again with @evansiroky. Decided to go ahead and merge #990 minus views and continue building views with more feedback.

**Comment by lauriemerrell** [comment]
@evansiroky can we close this for now and create future tickets when specific additional Airtable data is needed? See #1063 for first batch

(cc @holly-g)

**Comment by evansiroky** [comment]
Yeah, sounds like a good idea.
