### ISSUE TITLE
Installing pybigquery by putting "vendored" copy into data bucket

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#98]
Currently, we need to use an updated version of https://github.com/googleapis/python-bigquery-sqlalchemy, with fixes that have not been released to pypi. However, AFAIK google composer does not allow installing libraries straight from github (see [this doc](https://cloud.google.com/composer/docs/how-to/using/installing-python-dependencies)).

tl;dr - if we copy pybigquery into our data folder, and set our PYTHONPATH, we can include its version w/ unreleased fixes into the pipeline. (I tested this in order to bring the pipeline up to date).

Composer gives us three options:

* install from pypi
* install from private (pypi) repo
* install by putting it in the plugins folder

There are two airflow behaviors we need to work with:

* airflow does custom importing of the plugins folder (so it can reload it often for DAG reloading)
* airflow scheduler does not reload external libraries often (this happens in our [update_gcloud_requirements workflow](https://github.com/cal-itp/data-infra/blob/main/.github/workflows/update_gcloud_requirements.yml); or when workers are spawned)

I would lobby for a very dumb, but effective solution:

* we add a "vendored" version of pybigquery to our `data/` folder, by copying in its source folder (it's MIT license).
* we customize the composer environments PYTHONPATH (currently unset) to include that folder.
* we raise an issue on pybigquery gently asking / encouraging a release 

There may be a reasonable way for us to quickly set up a private repo, or even use a github source as private pypi repo, but I'm not sure there would be much pay-off.

**Comment by hunterowens** [comment]
Vendor: https://macwright.com/2021/03/11/vendor-by-default.html

**Comment by hunterowens** [comment]
I think we can close based on new pybigquery version?
