### ISSUE TITLE
Add new airtable BigQuery dataset as new database to metabase

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#983]
Once there is a new BigQuery dataset with data from airtable (upon completion of #973), a new database should be added to metabase that allows the consumption of data from this dataset.

**Comment by lauriemerrell** [comment]
@evansiroky I had just been thinking I'd add the Airtable data to the existing `views` dataset (with `airtable` prefixes on the individual tables) so that it would show in Metabase automatically -- should I not do that?

**Comment by evansiroky** [comment]
@lauriemerrell, the `views` dataset closely correlates with the views DAGs, as do other datasets in the pipeline. Please do create a new dataset. In fact, it might also make sense to create new datasets for each of the airtable bases as described in https://github.com/cal-itp/data-infra/issues/774.

**Comment by lauriemerrell** [comment]
Ok, I can do that -- I had just been thinking that I'd make an `airtable_views` DAG like there is for the other types of data and feed that into the `views` dataset. But if we want to keep it separate that's fine.
