### ISSUE TITLE
Static GTFS validation reporting for GRaaS

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#997]
**Is your feature request related to a problem? Please describe.**
GRaaS is unable to produce reliable GTFS-rt for transit agencies when there are issues in their static GTFS, or when they are missing certain field we rely on. These can be preexisting issues when we begin working with an agency, or issues that emerge during routine maintenance of their their feed.

Here are the specific static GTFS needs that we have:
1. There be no “dangling references”: if a shape, stop, calendar or other item is referenced in one file, it needs to exist. For example, every route_id in trips.txt must map to a route in routes.txt.
2. Each trip in trips.txt must have a trip_headsign, or the corresponding route must have a route_short_name or route_long_name

**Describe the solution you'd like**
For a fixed list of agencies, send a message (email or slack) to the GRaaS team (Scott, Kay, Ali, Lauren) when the above static GTFS needs fail to be met. Daily checks would be great, and we wouldn't say no to more frequent checks.

**Describe alternatives you've considered**
1. Initially we would manually check static feeds when onboarding an agency, and then when our programs failed we would debug the underlying (often static GTFS) issue. An example of a program that would fail due to bad GTFS is [GraphicReport](https://github.com/cal-itp/graas/blob/main/gtfu/src/main/java/gtfu/GraphicReport.java).
2. We did a very initial pass at integrating gtfs-validator, creating [GTFSValidator.java](https://github.com/cal-itp/graas/blob/main/gtfu/src/main/java/gtfu/tools/GTFSValidator.java). We started running this as a part of the agency onboarding process, but it didn't catch all "dangling reference" issues. We admittedly didn't go too deep down the rabbit hole of why it wasn't catching all issues or engaging with MobilityData about it.
3. We created [this job](https://github.com/cal-itp/graas/blob/main/gtfu/src/test/java/gtfu/test/LoadAgencyDataTest.java) to run nightly, which runs some of our GTFS-loading functions, throwing an error when dangling references occur. It is successfully flagging dangling references (routes & shapes), but we haven't built it out to catch everything yet. **We could continue relying on this approach, but it would be an elegant solution to have a shared system across Cal-ITP rather than this homegrown GRaaS-specific tool.**

**Comment by e-lo** [comment]
> We did a very initial pass at integrating gtfs-validator, creating GTFSValidator.java. We started running this as a part of the agency onboarding process, but it didn't catch all "dangling reference" issues

Oomph. That's not good. Could you reference an example feed that does this and what it fails to catch so we can bring up with the GTFS Validator team?

**Comment by e-lo** [comment]
> Each trip in trips.txt must have a trip_headsign, or the corresponding route must have a route_short_name or route_long_name

It is [technically compliant with the spec, but not best practices to just have `route_id` and not the names or headsigns](https://gtfs.mobilitydata.org/spec/gtfs-schedule#h.elenes7l8gmy).  

#1001 Should fix this and add the best practices to the validator.

**Comment by e-lo** [comment]
>  It would be an elegant solution to have a shared system across Cal-ITP rather than this homegrown GRaaS-specific tool.

Ideally you could take on implementing some of the Best Practices rules into the canonical validator and submitting PRs. Then you could rely on the existing Cal-ITP Airflow stack to flag non-validating feeds.

**Comment by themightychris** [comment]
Could this potentially be accomplished by hardcoding the GRaaS agency list into questions within a Metabase dashboard and setting up [Dashboard subscriptions](https://www.metabase.com/docs/latest/users-guide/dashboard-subscriptions.html) ?

**Comment by owades** [comment]
> > We did a very initial pass at integrating gtfs-validator, creating GTFSValidator.java. We started running this as a part of the agency onboarding process, but it didn't catch all "dangling reference" issues
> 
> Oomph. That's not good. Could you reference an example feed that does this and what it fails to catch so we can bring up with the GTFS Validator team?

I spent some time today trying to reproduce this issue, and so far GTFS-Validator **does** produce a foreign_key_violation error in the cases I described. I'll keep you posted if I find an exception.

**Comment by evansiroky** [comment]
Let's go ahead and proceed with investigating whether creating a GRaaS-specific metabase dashboard with nightly emails is something that will work for the GRaaS team.

**Comment by lauriemerrell** [comment]
I was tapped in to potentially work on this if we do want to make a dashboard -- @owades can you confirm if this is still needed, based on this?
>  so far GTFS-Validator does produce a foreign_key_violation error in the cases I described. I'll keep you posted if I find an exception.
If these issues **are** all being caught in the validator, is a dashboard still needed?

**Comment by owades** [comment]
@lauriemerrell I don't have an opinion on whether we get our own dashboard or not - we just need a daily check, that sends an email listing any errors.

**Comment by lauriemerrell** [comment]
@owades @evansiroky [Here is a draft dashboard](https://dashboards.calitp.org/dashboard/45-graas-static-gtfs-requirements-based-on-gtfs-guidelines-specific-date?feed_name=Unitrans%20(0)&feed_name=Tulare%20County%20Regional%20Transit%20Agency%20(0)&feed_name=Santa%20Ynez%20Valley%20Transit%20(0)&feed_name=Desert%20Roadrunner%20(0)&feed_name=Glendora%20Transportation%20Division%20(0)&feed_name=Glenn%20County%20Transit%20(0)&feed_name=County%20Express%20(0)&relative_date=yesterday).

Outstanding issues / notes:
* Right now, the `trip_headsign` one will populate regardless of the feed filter (I was having trouble joining it to the feeds to facilitate filtering on that). I can keep working on that next week but I think violations of this should be rare across the board, not sure how worried we are about false positives (violations that aren't in the monitored feeds.) 
* These are looking only at currently-active feeds (`calitp_deleted_at = 2099-01-01`) -- we may want to review the logic for that? 
* I set it to filter on the [list of feeds](https://storage.googleapis.com/graas-resources/test/live-agencies.txt) that Scott sent me by default -- default filter not hard to change.
* I believe this can be set up to email if any of the cards is not empty.

**Comment by lauriemerrell** [comment]
@owades are we comfortable closing this issue for now? 

I did fix the filtering, so now all three checks are filtering correctly for `feed name` based on the filter at the top. I also removed the date filter so now it just looks for the currently active feed for these 7 agencies. (I thought that might help avoid any weirdness with time zones like #1064.)

I haven't received any emails from it, but I think that's because none of these issues have been present (?)

**Comment by owades** [comment]
Thanks for checking in - is there a way we can run a test? One option would be to add an agency to the list that you know has bad static GTFS, to see if the email fires/how it looks.

**Comment by lauriemerrell** [comment]
Yup, good call @owades. I have added Amtrak to the filter, which is missing `calendar_dates`, and manually triggered the email. Then I added San Luis Obispo which has a dangling reference and triggered again to show how it would look with two active cards. I received both emails successfully on my end. 

Let me know what you think? The text of the dashboard boxes can be changed, and we can change which columns are included in the cards. We can also change a setting on whether that CSV is attached. I don't think we can change the appearance like color or the graphic with the empty box. :P 

I also wanted to ask about the [more comprehensive document](https://docs.google.com/document/d/1miFP29LIVHSh7spwjhSxZ-kKAtxopBcT9ucgj2aJJmA/edit#heading=h.9x8pukxpx5mc) that @evansiroky put together about RT requirements -- do you want to add *all* the requirements to this dashboard? I had been working off the more specific GRaaS doc and the requirements explicitly listed in this ticket. 

Right now this dashboard does not cover:
- Critical validation errors
- `FeedExpirationNotice` (although it *does* only filter on currently active feeds.... I could add a card that just confirms that all the agencies listed *have* a currently active feed?)

And there are some that I'm not sure the dashboard can cover:
- Existence of feed / permalink... I think the closest we can get is checking that it has an active feed based on the URL that we have on file (Perhaps we could add a check based on information from the Assessments Airtable or similar once that's in the warehouse, but I'm not sure what coverage we have on that data? And I believe it would only change when an assessment is actually performed)
- GTFS alignment with reality / Grading Scheme -- again perhaps we can pull from Assessments Airtable data (not yet available in warehouse) if needed, but would not be updated unless an assessment was performed

**Comment by owades** [comment]
Thanks @lauriemerrell! These look great.

The current dashboard seems really useful useful, and covering every item in the [more comprehensive doc](https://docs.google.com/document/d/1miFP29LIVHSh7spwjhSxZ-kKAtxopBcT9ucgj2aJJmA/edit#heading=h.9x8pukxpx5mc) would be more useful (Evan did some helpful work expanding on the requirements).

I think the decision of how in-depth to go would be up to @evansiroky, since I would just say "yes" to more detail until the end of time 😃

**Comment by evansiroky** [comment]
See my responses about what else we could go ahead and add.

> Right now this dashboard does not cover:
> 
> * Critical validation errors

Let's go ahead and do this, but it'd be helpful for the GRaaS team to come up with a list of "Critical GRaaS Validation Errors" so that we aren't including non-critical errors for the GRaaS use case in these emails. We could create another Google sheet or tab within [this sheet](https://docs.google.com/spreadsheets/d/1GDDaDlsBPCYn3dtYPSABnce9ns3ekJ8Jzfgyy56lZz4/edit#gid=0) and then load that into BigQuery to allow some filtering of validation notices so that the GRaaS team doesn't get alerted for non-relevant items. 

> * `FeedExpirationNotice` (although it _does_ only filter on currently active feeds.... I could add a card that just confirms that all the agencies listed _have_ a currently active feed?)

If there is a way to add a question like that then that would be great.

> And there are some that I'm not sure the dashboard can cover:
> 
> * Existence of feed / permalink... I think the closest we can get is checking that it has an active feed based on the URL that we have on file (Perhaps we could add a check based on information from the Assessments Airtable or similar once that's in the warehouse, but I'm not sure what coverage we have on that data? And I believe it would only change when an assessment is actually performed)

The GTFS Guidelines Dashboard has something really similar that gets what was found in agencies.yml.

> * GTFS alignment with reality / Grading Scheme -- again perhaps we can pull from Assessments Airtable data (not yet available in warehouse) if needed, but would not be updated unless an assessment was performed

The Grading Scheme assessments aren't even done anyways yet. This can wait.


So given all that, perhaps we can proceed with the first 3 items and then close out this issue as good enough for the first attempt.

**Comment by lauriemerrell** [comment]
Thanks @evansiroky, I'll get to work on these as soon as I can (likely early next week). @owades -- a list of the GRaaS-specific validations (as Evan describes) would definitely be helpful.

**Comment by evansiroky** [comment]
Doing one card per error seems like it'd be a lot of work given how many validation errors that may be worth checking for. Perhaps something that can help get the GRaaS team going is to use the critical validation errors as a starting point. If the GRaaS team notices a pattern of certain errors showing up that are not relevant to them, then they can begin to make a sublist as needed. Or we could just go ahead and create a copy of the critical validation errors into a new sheet called GRaaS-critical validation errors or something and let the GRaaS team curate that list.

**Comment by evansiroky** [comment]
It is true that showing all validation errors duplicates the specifically called-out items from the GRaaS team. It could be an opportunity to streamline the dashboard, but it could also leave out some important details. I'm curious to hear what level of debugging detail the GRaaS team (cc @owades) desires. Perhaps it's good enough to note the validation errors and then the GRaaS team can pass those on to the agency to ask them to fix.

**Comment by owades** [comment]
Thank you! Let's actually stick with the whole list for now, I think they all are helpful for us to see. Can we turn off the emails for these errors?

I don't mind the duplication - it's helpful to highlight the most critical ones to us, while also giving us an exhaustive list.

**Comment by lauriemerrell** [comment]
I don't think you can turn off the emails for one card, unfortunately. The Metabase setting only suppresses emails if all cards are empty. 

Here's one proposed solution:
* I left the [original dashboard](https://dashboards.calitp.org/dashboard/45-graas-static-gtfs-requirements) as it was (checking for required files, dangling refs, and trip signage) -- this one will only email if violations are found
* I moved the validation errors to [a separate dashboard](https://dashboards.calitp.org/dashboard/55-graas-static-gtfs-critical-validation-errors) which is linked in the first dashboard but which will not send emails. So you can easily check these validation errors if you want but it will not generate emails.

Let me know if that doesn't seem like a good solution. If this is ok, then perhaps we can close this ticket for now.

**Comment by lauriemerrell** [comment]
Unless we want to add any more dedicated checks to the "primary" (email generating) dashboard right now, which I can also do. For example I did not add a dedicated check for feed expiration notice yet because that was included in the general critical validations list. Let me know if we want to add anything like that to the primary dashboard.

**Comment by owades** [comment]
Thank you @lauriemerrell! Separating to another dashboard is a great solution. I appreciate you taking care of us with this work!
